import characterquests
from characterutil import *

def charquest_z_98_legion_intro(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"98: Legion Invasion",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,40519,"The Legion Returns","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,43926,"The Legion Returns","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,42782,"To Be Prepared","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,44281,"To Be Prepared","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,42740,"The Battle for Broken Shore","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,43806,"The Battle for Broken Shore","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,40518,"The Battle for Broken Shore","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,44543,"The Battle for Broken Shore","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,40517,"The Fallen Lion","alliance")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,39691,"The Call of War","alliance","classicon_demonhunter","race_nightelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,40522,"Fate of the Horde","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,40976,"Audience with the Warchief","horde")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,44471,"Second Sight","alliance","classicon_demonhunter","race_nightelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,40760,"Emissary","horde")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,40982,"Second Sight","horde","classicon_demonhunter","race_bloodelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,40593,"Demons Among Us","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,40607,"Demons Among Us","horde")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,40983,"Demons Among Them","horde","classicon_demonhunter","race_bloodelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,44120,"Illidari Allies","alliance")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,44473,"A Weapon of the Alliance","alliance","classicon_demonhunter","race_nightelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,40605,"Keep Your Friends Close","horde")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,41002,"A Weapon of the Horde","horde","classicon_demonhunter","race_bloodelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,40661,"Protect the Home Front","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,44092,"Protect the Home Front","horde")
	characterquests.charquestheader(count,"98: Legion Invasion: Teleportation",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,40717,"Calling of the Council","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,40718,"Calling of the Council","horde")
	characterquests.charquestprint(count,datatree,openfile,42970,"The Diamond King")
	characterquests.charquestprint(count,datatree,openfile,40755,"Hiding in the Stacks")
	characterquests.charquestprint(count,datatree,openfile,44182,"City Under Siege")
	characterquests.charquestprint(count,datatree,openfile,44421,"Anomalous Anomalies")
	characterquests.charquestprint(count,datatree,openfile,44500,"Author! Author!")
	characterquests.charquestprint(count,datatree,openfile,44184,"In the Blink of an Eye")

def charquest_z_100_azsuna(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"100-110: Azsuna: Behind Legion Lines",openfile)
	characterquests.charquestprint(count,datatree,openfile,39718,"Paradise Lost")
	characterquests.charquestprint(count,datatree,openfile,41220,"Down to Azsuna")
	characterquests.charquestprint(count,datatree,openfile,38834,"Into the Fray")
	characterquests.charquestprint(count,datatree,openfile,37658,"Reignite the Wards")
	characterquests.charquestprint(count,datatree,openfile,37653,"Demon Souls")
	characterquests.charquestprint(count,datatree,openfile,37660,"The Scythe of Souls")
	characterquests.charquestprint(count,datatree,openfile,44140,"From Within")
	characterquests.charquestprint(count,datatree,openfile,37656,"Fel Machinations")
	characterquests.charquestprint(count,datatree,openfile,37450,"Saving Stellagosa")
	characterquests.charquestprint(count,datatree,openfile,37449,"Dark Revelations")
	characterquests.charquestheader(count,"100-110: Azsuna: Defending Azurewing Repose",openfile)
	characterquests.charquestprint(count,datatree,openfile,38443,"Journey to the Repose")
	characterquests.charquestprint(count,datatree,openfile,37853,"The Death of the Eldest")
	characterquests.charquestprint(count,datatree,openfile,37991,"Agapanthus")
	characterquests.charquestprint(count,datatree,openfile,42271,"Their Dying Breaths")
	characterquests.charquestprint(count,datatree,openfile,37855,"The Last of the Last")
	characterquests.charquestprint(count,datatree,openfile,37859,"The Consumed")
	characterquests.charquestprint(count,datatree,openfile,37856,"The Withered")
	characterquests.charquestprint(count,datatree,openfile,37858,"Stellagosa")
	characterquests.charquestprint(count,datatree,openfile,37957,"Runas the Shamed")
	characterquests.charquestprint(count,datatree,openfile,37857,"Runas Knows the Way")
	characterquests.charquestprint(count,datatree,openfile,37960,"Leyline Abuse")
	characterquests.charquestprint(count,datatree,openfile,37959,"The Hunger Returns")
	characterquests.charquestprint(count,datatree,openfile,37861,"The Nightborne Prince")
	characterquests.charquestprint(count,datatree,openfile,37860,"You Scratch My Back...")
	characterquests.charquestprint(count,datatree,openfile,37862,"Still Alive")
	characterquests.charquestprint(count,datatree,openfile,38015,"On the Brink")
	characterquests.charquestprint(count,datatree,openfile,38014,"Feasting on the Dragon")
	characterquests.charquestprint(count,datatree,openfile,42567,"Cursed to Wither")
	characterquests.charquestprint(count,datatree,openfile,42756,"Hunger's End")
	characterquests.charquestheader(count,"100-110: Azsuna: Azsuna versus Azshara",openfile)
	characterquests.charquestprint(count,datatree,openfile,37690,"Those Who Remember")
	characterquests.charquestprint(count,datatree,openfile,37256,"They Came From the Sea")
	characterquests.charquestprint(count,datatree,openfile,37733,"Prince Farondis")
	characterquests.charquestprint(count,datatree,openfile,37257,"Our Very Bones")
	characterquests.charquestprint(count,datatree,openfile,37492,"A Rather Long Walk")
	characterquests.charquestprint(count,datatree,openfile,37728,"Presentation is Everything")
	characterquests.charquestprint(count,datatree,openfile,37727,"The Magister of Mixology")
	characterquests.charquestprint(count,datatree,openfile,37497,"Trailing the Tidestone")
	characterquests.charquestprint(count,datatree,openfile,37486,"Nar'thalas Still Suffers")
	characterquests.charquestprint(count,datatree,openfile,42692,"Children of Nar'thalas")
	characterquests.charquestprint(count,datatree,openfile,42693,"You Never Know Until You Scry")
	characterquests.charquestprint(count,datatree,openfile,42694,"Back from the Dead")
	characterquests.charquestprint(count,datatree,openfile,37467,"The Walk of Shame")
	characterquests.charquestprint(count,datatree,openfile,37468,"Into the Academy")
	characterquests.charquestprint(count,datatree,openfile,37736,"Dressing With Class")
	characterquests.charquestprint(count,datatree,openfile,37678,"Hit the Books")
	characterquests.charquestprint(count,datatree,openfile,37518,"The Haunted Halls")
	characterquests.charquestprint(count,datatree,openfile,42370,"Wanding 101")
	characterquests.charquestprint(count,datatree,openfile,42371,"Study Hall: Combat Research")
	characterquests.charquestprint(count,datatree,openfile,37729,"Pop Quiz: Advanced Rune Drawing")
	characterquests.charquestprint(count,datatree,openfile,37730,"The Headmistress' Keys")
	characterquests.charquestprint(count,datatree,openfile,37469,"The Tidestone: Shattered")
	characterquests.charquestprint(count,datatree,openfile,37530,"Save Yourself")
	characterquests.charquestprint(count,datatree,openfile,37470,"The Head of the Snake")
	characterquests.charquestheader(count,"100-110: Azsuna: Eye of Azshara",openfile)
	characterquests.charquestprint(count,datatree,openfile,38286,"Eye of Azshara: Wrath of Azshara")
	characterquests.charquestprint(count,datatree,openfile,42213,"Eye of Azshara: The Tidestone of Golganneth")
	characterquests.charquestheader(count,"100-110: Azsuna: Against the Giants",openfile)
	characterquests.charquestprint(count,datatree,openfile,38407,"Bottled Up")
	characterquests.charquestprint(count,datatree,openfile,37496,"Infiltrating Shipwreck Arena")
	characterquests.charquestprint(count,datatree,openfile,37507,"Boss Whalebelly's in Charge")
	characterquests.charquestprint(count,datatree,openfile,37542,"No Time for Tryouts")
	characterquests.charquestprint(count,datatree,openfile,37528,"Let Sleeping Giants Lie")
	characterquests.charquestprint(count,datatree,openfile,37510,"Sternfathom's Champion")
	characterquests.charquestprint(count,datatree,openfile,37536,"Morale Booster")
	characterquests.charquestprint(count,datatree,openfile,37538,"Round 1, Fight!")
	characterquests.charquestprint(count,datatree,openfile,37565,"The Right Weapon for the Job")
	characterquests.charquestprint(count,datatree,openfile,37566,"The Prince is Going Down")
	characterquests.charquestheader(count,"100-110: Azsuna: Mak'rana and the Fate of the Queen's Reprisal",openfile)
	characterquests.charquestprint(count,datatree,openfile,38857,"A Favor for Mr. Shackle")
	characterquests.charquestprint(count,datatree,openfile,37654,"Maritime Law")
	characterquests.charquestprint(count,datatree,openfile,37659,"The Captain's Foot Locker")
	characterquests.charquestprint(count,datatree,openfile,42268,"Shipwrecked Sailors")
	characterquests.charquestprint(count,datatree,openfile,42244,"Fate of the Queen's Reprisal")
	characterquests.charquestheader(count,"100-110: Azsuna: Daglop",openfile)
	characterquests.charquestprint(count,datatree,openfile,42238,"Missing Demon")
	characterquests.charquestprint(count,datatree,openfile,38460,"Let's Make A Deal")
	characterquests.charquestprint(count,datatree,openfile,38232,"Minion! Kill Them!")
	characterquests.charquestprint(count,datatree,openfile,38237,"This IS In My Contract.")
	characterquests.charquestheader(count,"100-110: Azsuna: PVP",openfile)
	characterquests.charquestprint(count,datatree,openfile,43942,"Timeworn Artifact")
	characterquests.charquestheader(count,"100-110: Azsuna: Bonus Objectives",openfile)
	characterquests.charquestprint(count,datatree,openfile,36811,"Retake Faronaar")
	characterquests.charquestprint(count,datatree,openfile,37466,"The Broken Academy")
	characterquests.charquestprint(count,datatree,openfile,37963,"Those Beyond Redemption")
	characterquests.charquestprint(count,datatree,openfile,37779,"Tip the Scales")
	characterquests.charquestprint(count,datatree,openfile,37965,"A Tainted Vintage")
	characterquests.charquestprint(count,datatree,openfile,37495,"Plunder the Cove")

def charquest_z_100_valsharah(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"100-110: Val'sharah: Intro",openfile)
	characterquests.charquestprint(count,datatree,openfile,39731,"The Tranquil Forest")
	characterquests.charquestprint(count,datatree,openfile,39861,"Tying Up Loose Ends")
	characterquests.charquestprint(count,datatree,openfile,38305,"Cenarius, Keeper of the Grove")
	characterquests.charquestprint(count,datatree,openfile,38384,"Nature's Call")
	characterquests.charquestheader(count,"100-110: Val'sharah: Archdruid of Lore",openfile)
	characterquests.charquestprint(count,datatree,openfile,38381,"Archdruid of Lore")
	characterquests.charquestprint(count,datatree,openfile,38235,"Solid as a Rock")
	characterquests.charquestprint(count,datatree,openfile,38225,"Death to the Witchmother")
	characterquests.charquestprint(count,datatree,openfile,38322,"Return to the Grove")
	characterquests.charquestheader(count,"100-110: Val'sharah: Archdruid of the Claw",openfile)
	characterquests.charquestprint(count,datatree,openfile,38142,"Archdruid of the Claw")
	characterquests.charquestheader(count,"100-110: Val'sharah: Archdruid of the Claw: Furlbolgs",openfile)
	characterquests.charquestprint(count,datatree,openfile,38455,"Frenzied Furbolgs")
	characterquests.charquestprint(count,datatree,openfile,38922,"Littlefur")
	characterquests.charquestprint(count,datatree,openfile,38246,"Totemic Call")
	characterquests.charquestprint(count,datatree,openfile,38146,"The Chieftain's Beads")
	characterquests.charquestheader(count,"100-110: Val'sharah: Archdruid of the Claw: Awakening the Archdruid",openfile)
	characterquests.charquestprint(count,datatree,openfile,38143,"Awakening the Archdruid")
	characterquests.charquestprint(count,datatree,openfile,38145,"Out of the Dream")
	characterquests.charquestprint(count,datatree,openfile,38144,"The Demons Below")
	characterquests.charquestprint(count,datatree,openfile,38147,"Entangled Dreams")
	characterquests.charquestprint(count,datatree,openfile,38148,"Return to the Grove")
	characterquests.charquestheader(count,"100-110: Val'sharah: Archdruid of the Vale",openfile)
	characterquests.charquestprint(count,datatree,openfile,38382,"Archdruid of the Vale")
	characterquests.charquestprint(count,datatree,openfile,39383,"Dishonored")
	characterquests.charquestprint(count,datatree,openfile,39384,"The Corruptor")
	characterquests.charquestprint(count,datatree,openfile,40573,"The Nightmare Lord")
	characterquests.charquestprint(count,datatree,openfile,38323,"Return to the Grove")
	characterquests.charquestheader(count,"100-110: Val'sharah: Into the Nightmare",openfile)
	characterquests.charquestprint(count,datatree,openfile,38377,"The Emerald Queen")
	characterquests.charquestprint(count,datatree,openfile,38641,"The Temple of Elune")
	characterquests.charquestprint(count,datatree,openfile,38662,"Tears for Fears")
	characterquests.charquestprint(count,datatree,openfile,38655,"Root Cause")
	characterquests.charquestprint(count,datatree,openfile,38656,"Mark of the Demon")
	characterquests.charquestprint(count,datatree,openfile,38663,"The Die is Cast")
	characterquests.charquestprint(count,datatree,openfile,38595,"Malfurion's Fury")
	characterquests.charquestprint(count,datatree,openfile,38582,"To Old Friends")
	characterquests.charquestprint(count,datatree,openfile,38753,"The Demon's Trail")
	characterquests.charquestheader(count,"100-110: Val'sharah: All Nightmare Long",openfile)
	characterquests.charquestprint(count,datatree,openfile,41054,"Love Lost")
	characterquests.charquestprint(count,datatree,openfile,41890,"Dark Side of the Moon")
	characterquests.charquestprint(count,datatree,openfile,38671,"Lost in Retreat")
	characterquests.charquestprint(count,datatree,openfile,41707,"Wormtalon Wreckage")
	characterquests.charquestprint(count,datatree,openfile,43576,"Regroup at the Refuge")
	characterquests.charquestprint(count,datatree,openfile,38675,"Heart of the Nightmare")
	characterquests.charquestprint(count,datatree,openfile,38684,"Reading the Leaves")
	characterquests.charquestprint(count,datatree,openfile,41749,"Given to Corruption")
	characterquests.charquestprint(count,datatree,openfile,43702,"Softening the Target")
	characterquests.charquestprint(count,datatree,openfile,41763,"Close Enough to Touch")
	characterquests.charquestprint(count,datatree,openfile,38743,"The Fate of Val'sharah")
	characterquests.charquestprint(count,datatree,openfile,40890,"The Tears of Elune")
	characterquests.charquestheader(count,"100-110: Val'sharah: Darkheart Thicket",openfile)
	characterquests.charquestprint(count,datatree,openfile,40567,"Darkheart Thicket: Enter the Nightmare")
	characterquests.charquestheader(count,"100-110: Val'sharah: Bradensbrook",openfile)
	characterquests.charquestprint(count,datatree,openfile,38643,"A Village in Peril")
	characterquests.charquestprint(count,datatree,openfile,38645,"Children of the Night")
	characterquests.charquestprint(count,datatree,openfile,38644,"The Farmsteads")
	characterquests.charquestprint(count,datatree,openfile,39117,"Shriek No More")
	characterquests.charquestprint(count,datatree,openfile,38646,"A Sight For Sore Eyes")
	characterquests.charquestprint(count,datatree,openfile,38647,"For the Corn!")
	characterquests.charquestprint(count,datatree,openfile,38691,"Jarod's Mission")
	characterquests.charquestheader(count,"100-110: Val'sharah: Black Rook Hold",openfile)
	characterquests.charquestprint(count,datatree,openfile,38718,"Kur'talos Ravencrest")
	characterquests.charquestprint(count,datatree,openfile,38714,"Maiev's Trail")
	characterquests.charquestprint(count,datatree,openfile,38715,"The Rook's Guard")
	characterquests.charquestprint(count,datatree,openfile,38717,"Black Rook Prison")
	characterquests.charquestprint(count,datatree,openfile,38724,"Brotherly Love")
	characterquests.charquestprint(count,datatree,openfile,38719,"Illidari Freedom")
	characterquests.charquestprint(count,datatree,openfile,38721,"Lieutenant of the Tower")
	characterquests.charquestheader(count,"100-110: Val'sharah: Bonus Areas",openfile)
	characterquests.charquestprint(count,datatree,openfile,38716,"Black Rook Hold")
	characterquests.charquestprint(count,datatree,openfile,39029,"Defend The Temple")
	characterquests.charquestprint(count,datatree,openfile,38842,"Faerie Fracas")
	characterquests.charquestprint(count,datatree,openfile,43241,"Flow of the Nightmare")
	characterquests.charquestprint(count,datatree,openfile,39393,"Moonclaw Vale")
	characterquests.charquestprint(count,datatree,openfile,38748,"Ruins of Shala'nir")
	characterquests.charquestprint(count,datatree,openfile,38372,"Wretched Sisters")
	characterquests.charquestheader(count,"100-110: Val'sharah: Saylanna Riverbreeze",openfile)
	characterquests.charquestprint(count,datatree,openfile,40220,"Thorny Dancing")
	characterquests.charquestprint(count,datatree,openfile,38862,"Thieving Thistleleaf")
	characterquests.charquestprint(count,datatree,openfile,40221,"Spread Your Lunarwings and Fly")
	characterquests.charquestheader(count,"100-110: Val'sharah: Grizzleweald",openfile)
	characterquests.charquestprint(count,datatree,openfile,42857,"Moist Around the Hedges")
	characterquests.charquestheader(count,"100-110: Val'sharah: Lightsong",openfile)
	characterquests.charquestprint(count,datatree,openfile,42747,"Where the Wildkin Are")
	characterquests.charquestprint(count,datatree,openfile,42748,"Emerald Sisters")
	characterquests.charquestprint(count,datatree,openfile,42750,"Dreamcatcher")
	characterquests.charquestprint(count,datatree,openfile,42786,"Grotesque Remains")
	characterquests.charquestprint(count,datatree,openfile,42751,"Moon Reaver")
	characterquests.charquestheader(count,"100-110: Val'sharah: Single Quests",openfile)
	characterquests.charquestprint(count,datatree,openfile,39354,"Wisp in the Willows")
	characterquests.charquestprint(count,datatree,openfile,38889,"Adopting the Adorable")

def charquest_z_100_highmountain(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"100-110: Highmountain: Thunder Totem",openfile)
	characterquests.charquestprint(count,datatree,openfile,39733,"The Lone Mountain")
	characterquests.charquestprint(count,datatree,openfile,38907,"Keepers of the Hammer")
	characterquests.charquestprint(count,datatree,openfile,38911,"The Rivermane Tribe")
	characterquests.charquestprint(count,datatree,openfile,39491,"Ormgul the Pestilent")
	characterquests.charquestprint(count,datatree,openfile,39272,"Poisoned Crops")
	characterquests.charquestprint(count,datatree,openfile,39490,"Infestation")
	characterquests.charquestprint(count,datatree,openfile,39496,"The Flow of the River")
	characterquests.charquestprint(count,datatree,openfile,39316,"Trapped Tauren")
	characterquests.charquestprint(count,datatree,openfile,39277,"Spray and Prey")
	characterquests.charquestprint(count,datatree,openfile,39614,"Fish Out of Water")
	characterquests.charquestprint(count,datatree,openfile,39572,"Moozy's Adventure")
	characterquests.charquestprint(count,datatree,openfile,39323,"Moozy's Sojourn")
	characterquests.charquestprint(count,datatree,openfile,42590,"Moozy's Reunion")
	characterquests.charquestprint(count,datatree,openfile,39661,"Lifespring Cavern")
	characterquests.charquestprint(count,datatree,openfile,39488,"Balance of Elements")
	characterquests.charquestprint(count,datatree,openfile,39489,"Invading Spelunkers")
	characterquests.charquestprint(count,datatree,openfile,39487,"Crystal Fury")
	characterquests.charquestprint(count,datatree,openfile,39498,"High Water")
	characterquests.charquestprint(count,datatree,openfile,42104,"The Underking Comes")
	characterquests.charquestheader(count,"100-110: Highmountain: Riverbend",openfile)
	characterquests.charquestprint(count,datatree,openfile,39025,"Grasp of the Underking")
	characterquests.charquestprint(count,datatree,openfile,39026,"The Drogbar")
	characterquests.charquestprint(count,datatree,openfile,39043,"Bitestone Enclave")
	characterquests.charquestprint(count,datatree,openfile,39027,"Dargrul and the Hammer")
	characterquests.charquestprint(count,datatree,openfile,38909,"Get to High Ground")
	characterquests.charquestheader(count,"100-110: Highmountain: The Skyhorn Tribe",openfile)
	characterquests.charquestprint(count,datatree,openfile,38913,"The Skyhorn Tribe")
	characterquests.charquestprint(count,datatree,openfile,39318,"Nursing the Wounds")
	characterquests.charquestprint(count,datatree,openfile,38910,"Rocs vs Eagles")
	characterquests.charquestprint(count,datatree,openfile,39321,"The Three")
	characterquests.charquestprint(count,datatree,openfile,39429,"Assaulting the Haglands")
	characterquests.charquestprint(count,datatree,openfile,39322,"The Witchqueen")
	characterquests.charquestprint(count,datatree,openfile,39387,"The Skies of Highmountain")
	characterquests.charquestprint(count,datatree,openfile,39419,"Hex-a-Gone")
	characterquests.charquestheader(count,"100-110: Highmountain: The Bloodtotem Tribe",openfile)
	characterquests.charquestprint(count,datatree,openfile,38912,"The Bloodtotem Tribe")
	characterquests.charquestprint(count,datatree,openfile,39372,"Witch of the Wood")
	characterquests.charquestprint(count,datatree,openfile,39373,"Hags of a Feather")
	characterquests.charquestprint(count,datatree,openfile,39873,"I Have a Bad Feeling About This")
	characterquests.charquestprint(count,datatree,openfile,39374,"An Audience with Torok")
	characterquests.charquestprint(count,datatree,openfile,39455,"Cave of the Blood Trial")
	characterquests.charquestprint(count,datatree,openfile,39860,"Rite of Blood")
	characterquests.charquestprint(count,datatree,openfile,39381,"Rock Troll in a Hard Place")
	characterquests.charquestprint(count,datatree,openfile,39391,"Pet Rocks")
	characterquests.charquestprint(count,datatree,openfile,39425,"Stonedark Crystal")
	characterquests.charquestprint(count,datatree,openfile,39588,"They Will Pay With Blood")
	characterquests.charquestprint(count,datatree,openfile,39426,"Blood Debt")
	characterquests.charquestprint(count,datatree,openfile,40229,"Step into the Dark")
	characterquests.charquestprint(count,datatree,openfile,39456,"Unexpected Allies")
	characterquests.charquestheader(count,"100-110: Highmountain: Huln's War",openfile)
	characterquests.charquestprint(count,datatree,openfile,40515,"A Walk With the Spirits")
	characterquests.charquestprint(count,datatree,openfile,40167,"The Story of Huln")
	characterquests.charquestprint(count,datatree,openfile,40520,"To See the Past")
	characterquests.charquestprint(count,datatree,openfile,39983,"Huln's War - The Arrival")
	characterquests.charquestprint(count,datatree,openfile,40112,"Huln's War - Malorne's Favored")
	characterquests.charquestprint(count,datatree,openfile,39988,"Huln's War - Stormrage")
	characterquests.charquestprint(count,datatree,openfile,39990,"Huln's War - Reinforcements")
	characterquests.charquestprint(count,datatree,openfile,40388,"Huln's War - Shadowsong")
	characterquests.charquestprint(count,datatree,openfile,39992,"Huln's War - The Nathrezim")
	characterquests.charquestheader(count,"100-110: Highmountain: Secrets of Highmountain",openfile)
	characterquests.charquestprint(count,datatree,openfile,38916,"Secrets of Highmountain")
	characterquests.charquestprint(count,datatree,openfile,39575,"The Path of Huln")
	characterquests.charquestprint(count,datatree,openfile,40219,"In Defiance of Deathwing")
	characterquests.charquestprint(count,datatree,openfile,39578,"Titanic Showdown")
	characterquests.charquestprint(count,datatree,openfile,39577,"An Ancient Secret")
	characterquests.charquestprint(count,datatree,openfile,39579,"The Backdoor")
	characterquests.charquestprint(count,datatree,openfile,39580,"The High Chieftain")
	characterquests.charquestheader(count,"100-110: Highmountain: Battle of Snowblind Mesa",openfile)
	characterquests.charquestprint(count,datatree,openfile,38915,"Battle of Snowblind Mesa")
	characterquests.charquestprint(count,datatree,openfile,39776,"Battle Worms")
	characterquests.charquestprint(count,datatree,openfile,39777,"Buy Us Time")
	characterquests.charquestprint(count,datatree,openfile,39862,"The Siegebrul")
	characterquests.charquestprint(count,datatree,openfile,42088,"Evacuate Snowmane")
	characterquests.charquestprint(count,datatree,openfile,42512,"Highmountain Stands")
	characterquests.charquestprint(count,datatree,openfile,40594,"Justice Rains from Above")
	characterquests.charquestprint(count,datatree,openfile,39780,"The Underking")
	characterquests.charquestheader(count,"100-110: Highmountain: Neltharion's Lair",openfile)
	characterquests.charquestprint(count,datatree,openfile,39781,"Neltharion's Lair")
	characterquests.charquestprint(count,datatree,openfile,42454,"Eye of Azshara: The Hammer of Khaz'goroth")
	characterquests.charquestheader(count,"100-110: Highmountain: Stonedark Cavern",openfile)
	characterquests.charquestprint(count,datatree,openfile,39440,"You Lift, Brul?")
	characterquests.charquestprint(count,datatree,openfile,39439,"Stonedark Relics")
	characterquests.charquestprint(count,datatree,openfile,39437,"Deep in the Cavern")
	characterquests.charquestprint(count,datatree,openfile,39438,"Guhruhlruhlruh")
	characterquests.charquestheader(count,"100-110: Highmountain: Rockcrawler Chasm",openfile)
	characterquests.charquestprint(count,datatree,openfile,40070,"Eagle Egg Recovery")
	characterquests.charquestprint(count,datatree,openfile,39305,"Empty Nest")
	characterquests.charquestprint(count,datatree,openfile,40069,"Fledgling Worm Guts")
	characterquests.charquestprint(count,datatree,openfile,42425,"Going Down, Going Up")
	characterquests.charquestprint(count,datatree,openfile,40071,"Tamer Takedown")
	characterquests.charquestheader(count,"100-110: Highmountain: Hemet Nesingwary",openfile)
	characterquests.charquestprint(count,datatree,openfile,40217,"An Offering of Ammo")
	characterquests.charquestprint(count,datatree,openfile,39417,"Rating Razik")
	characterquests.charquestprint(count,datatree,openfile,40170,"Amateur Hour")
	characterquests.charquestprint(count,datatree,openfile,39859,"Note-Eating Goats")
	characterquests.charquestprint(count,datatree,openfile,40216,"A Hunter at Heart")
	characterquests.charquestprint(count,datatree,openfile,40228,"Scout It Out")
	characterquests.charquestprint(count,datatree,openfile,39392,"Bear Huntin'")
	characterquests.charquestprint(count,datatree,openfile,39123,"Lion Stalkin'")
	characterquests.charquestprint(count,datatree,openfile,39124,"Moose Shootin'")
	characterquests.charquestprint(count,datatree,openfile,39178,"Moose on the Loose'")
	characterquests.charquestprint(count,datatree,openfile,39867,"I'm Not Lion!")
	characterquests.charquestprint(count,datatree,openfile,40244,"That Guy in the Costume")
	characterquests.charquestheader(count,"100-110: Highmountain: Shipwreck Cove",openfile)
	characterquests.charquestprint(count,datatree,openfile,40049,"Slime Time")
	characterquests.charquestprint(count,datatree,openfile,40047,"I'll Huff, I'll Puff...")
	characterquests.charquestprint(count,datatree,openfile,40045,"Nature vs. Nurture")
	characterquests.charquestprint(count,datatree,openfile,40102,"Murlocs: The Next Generation")
	characterquests.charquestprint(count,datatree,openfile,40230,"Oh, the Clawdacity!")
	characterquests.charquestheader(count,"100-110: Highmountain: Candle King",openfile)
	characterquests.charquestprint(count,datatree,openfile,39768,"Candle to the Grave")
	characterquests.charquestprint(count,datatree,openfile,39765,"Wax On, Wax Off")
	characterquests.charquestprint(count,datatree,openfile,39769,"The Gates of Wax")
	characterquests.charquestprint(count,datatree,openfile,40339,"Candle of Command")
	characterquests.charquestprint(count,datatree,openfile,40345,"Burn the Candle at Both Ends")
	characterquests.charquestprint(count,datatree,openfile,39772,"Can't Hold a Candle To You")
	characterquests.charquestheader(count,"100-110: Highmountain: Aviana",openfile)
	characterquests.charquestprint(count,datatree,openfile,41094,"Hatchlings of the Talon")
	characterquests.charquestheader(count,"100-110: Highmountain: Thunder Totem Misc.",openfile)
	characterquests.charquestprint(count,datatree,openfile,42622,"Ceremonial Drums")
	characterquests.charquestprint(count,datatree,openfile,42596,"Mountainstrider Round-Up")
	characterquests.charquestprint(count,datatree,openfile,39133,"No Time to Talk")
	characterquests.charquestprint(count,datatree,openfile,39134,"Wrathshard")
	characterquests.charquestheader(count,"100-110: Highmountain: Bonus Objectives",openfile)
	characterquests.charquestprint(count,datatree,openfile,39274,"Defend the Riverlands")
	characterquests.charquestprint(count,datatree,openfile,39576,"Echoes of Deathwing")
	characterquests.charquestprint(count,datatree,openfile,40050,"Shipwreck Cove")
	characterquests.charquestprint(count,datatree,openfile,39317,"Siege of Crawliac")
	characterquests.charquestprint(count,datatree,openfile,40316,"The Screeching Crag")
	characterquests.charquestprint(count,datatree,openfile,42373,"Vengeance for the Stonedark")
	characterquests.charquestprint(count,datatree,openfile,39371,"Witches of the Sky")
	characterquests.charquestprint(count,datatree,openfile,39123,"Lion Stalkin'")

def charquest_z_100_stormheim(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"100-110: Stormheim: Intro: Alliance","alliance",openfile)
	characterquests.charquestprint(count,datatree,openfile,39735,"Stormheim")
	characterquests.charquestprint(count,datatree,openfile,38035,"A Royal Summons")
	characterquests.charquestprint(count,datatree,openfile,38206,"Making the Rounds")
	characterquests.charquestprint(count,datatree,openfile,39800,"Greymane's Gambit")
	characterquests.charquestprint(count,datatree,openfile,38052,"Boarded!")
	characterquests.charquestprint(count,datatree,openfile,38036,"Supplies From the Skies")
	characterquests.charquestprint(count,datatree,openfile,38053,"Assault and Battery")
	characterquests.charquestprint(count,datatree,openfile,38558,"See Ya Later, Oscillator")
	characterquests.charquestprint(count,datatree,openfile,38058,"Lightning Rod")
	characterquests.charquestprint(count,datatree,openfile,38057,"The Lost Legion")
	characterquests.charquestprint(count,datatree,openfile,38059,"Pins and Needles")
	characterquests.charquestprint(count,datatree,openfile,38060,"Signal Boost")
	characterquests.charquestprint(count,datatree,openfile,39775,"Stormforged Grapple Launcher")
	characterquests.charquestheaderfaction(count,"100-110: Stormheim: Intro: Horde","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,39864,"Stormheim")
	characterquests.charquestprint(count,datatree,openfile,38307,"The Warchief Beckons")
	characterquests.charquestprint(count,datatree,openfile,39698,"Making the Rounds")
	characterquests.charquestprint(count,datatree,openfile,39801,"The Splintered Fleet")
	characterquests.charquestprint(count,datatree,openfile,38332,"The Ranger Lord")
	characterquests.charquestprint(count,datatree,openfile,38358,"Pump it Up")
	characterquests.charquestprint(count,datatree,openfile,38357,"Side Effects May Include Mild Undeath")
	characterquests.charquestprint(count,datatree,openfile,38360,"The Windrunner's Fate")
	characterquests.charquestprint(count,datatree,openfile,38361,"Wrath of the Blightcaller")
	characterquests.charquestprint(count,datatree,openfile,38362,"A Grim Trophy")
	characterquests.charquestprint(count,datatree,openfile,38308,"Eyes in the Overlook")
	characterquests.charquestprint(count,datatree,openfile,38317,"Masters of Disguise")
	characterquests.charquestprint(count,datatree,openfile,39775,"Stormforged Grapple Launcher")
	characterquests.charquestheader(count,"100-110: Stormheim: Ancient Trials: The Blessing of the Watchers",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,38210,"The Ancient Trials","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38459,"The Ancient Trials","horde")
	characterquests.charquestprint(count,datatree,openfile,38331,"Havi's Test")
	characterquests.charquestprint(count,datatree,openfile,39590,"Ahead of the Game")
	characterquests.charquestprint(count,datatree,openfile,39595,"Blood and Gold")
	characterquests.charquestprint(count,datatree,openfile,39591,"A Trial of Valor")
	characterquests.charquestprint(count,datatree,openfile,39592,"A Trial of Will")
	characterquests.charquestprint(count,datatree,openfile,39593,"The Shattered Watcher")
	characterquests.charquestprint(count,datatree,openfile,39594,"A Trial of Might")
	characterquests.charquestprint(count,datatree,openfile,39597,"The Blessing of the Watchers")
	characterquests.charquestheader(count,"100-110: Stormheim: Ancient Trials: Where Dragons Rule",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,38473,"Will of the Thorignir","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38611,"Will of the Thorignir","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38312,"A Grapple a Day","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38612,"A Grapple a Day","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38318,"No Wings Required","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38613,"No Wings Required","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38405,"To Weather the Storm","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38614,"To Weather the Storm","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38616,"Built to Scale","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38337,"Built to Scale","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38410,"Impalement Insurance","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38615,"Impalement Insurance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38342,"Another Way","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38617,"Another Way","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,38412,"Above the Winter Moonlight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38618,"Above the Winter Moonlight","horde")
	characterquests.charquestprint(count,datatree,openfile,38414,"Heart of a Dragon")
	characterquests.charquestprint(count,datatree,openfile,38413,"Wings of Liberty")
	characterquests.charquestprint(count,datatree,openfile,40568,"Fury of the Storm")
	characterquests.charquestprint(count,datatree,openfile,39652,"Where Dragons Rule")
	characterquests.charquestprint(count,datatree,openfile,38624,"Cry Thunder!")
	characterquests.charquestheader(count,"100-110: Stormheim: Ancient Trials: The Final Judgement",openfile)
	characterquests.charquestprint(count,datatree,openfile,39803,"The Trials Continue")
	characterquests.charquestprint(count,datatree,openfile,39804,"Speaking of Bones")
	characterquests.charquestprint(count,datatree,openfile,39796,"To Haustvald")
	characterquests.charquestprint(count,datatree,openfile,38778,"Turn the Keys")
	characterquests.charquestprint(count,datatree,openfile,39788,"The Runewood's Revenge")
	characterquests.charquestprint(count,datatree,openfile,38810,"The Dreaming Fungus")
	characterquests.charquestprint(count,datatree,openfile,38808,"Bjornharta")
	characterquests.charquestprint(count,datatree,openfile,38811,"Judgment Day")
	characterquests.charquestprint(count,datatree,openfile,39791,"Lay Them to Rest")
	characterquests.charquestprint(count,datatree,openfile,38817,"Regal Remains")
	characterquests.charquestprint(count,datatree,openfile,38816,"Breaking the Bonespeakers")
	characterquests.charquestprint(count,datatree,openfile,38823,"The Runes that Bind")
	characterquests.charquestprint(count,datatree,openfile,38815,"Waking the Shieldmaiden")
	characterquests.charquestprint(count,datatree,openfile,38818,"The Final Judgment")
	characterquests.charquestheader(count,"100-110: Stormheim: Ancient Trials: Victory is Eternal (Helheim)",openfile)
	characterquests.charquestprint(count,datatree,openfile,39837,"An Unworthy Task")
	characterquests.charquestprint(count,datatree,openfile,38339,"A Little Kelp From My Foes")
	characterquests.charquestprint(count,datatree,openfile,38324,"Accessories of the Cursed")
	characterquests.charquestprint(count,datatree,openfile,38347,"Stealth by Seaweed")
	characterquests.charquestprint(count,datatree,openfile,39848,"A Desperate Bargain")
	characterquests.charquestprint(count,datatree,openfile,39857,"The Eternal Nemesis")
	characterquests.charquestprint(count,datatree,openfile,39849,"To Light the Way")
	characterquests.charquestprint(count,datatree,openfile,39850,"Sundered")
	characterquests.charquestprint(count,datatree,openfile,39851,"Allies in Death")
	characterquests.charquestprint(count,datatree,openfile,39853,"Victory is Eternal")
	characterquests.charquestprint(count,datatree,openfile,39855,"Paid in Lifeblood")
	characterquests.charquestheader(count,"100-110: Stormheim: The Aegis of Agrammar",openfile)
	characterquests.charquestprint(count,datatree,openfile,40078,"A Heavy Burden")
	characterquests.charquestprint(count,datatree,openfile,40001,"Knocking on Valor's Door")
	characterquests.charquestprint(count,datatree,openfile,40002,"A Familiar Fate")
	characterquests.charquestprint(count,datatree,openfile,40003,"Stem the Tide")
	characterquests.charquestprint(count,datatree,openfile,40004,"Break the Spine")
	characterquests.charquestprint(count,datatree,openfile,40005,"Stormheim's Salvation")
	characterquests.charquestheader(count,"100-110: Stormheim: Halls of Valor",openfile)
	characterquests.charquestprint(count,datatree,openfile,40072,"Halls of Valor: Securing the Aegis")
	characterquests.charquestprint(count,datatree,openfile,43349,"The Aegis of Aggramar")
	characterquests.charquestheader(count,"100-110: Stormheim: Skold-Ashil (Alliance)",openfile)
	characterquests.charquestprint(count,datatree,openfile,39059,"To Catch a Banshee")
	characterquests.charquestprint(count,datatree,openfile,39060,"Combustible Contagion")
	characterquests.charquestprint(count,datatree,openfile,39061,"Whispers from the Dark")
	characterquests.charquestprint(count,datatree,openfile,39472,"Cut Out the Heart")
	characterquests.charquestprint(count,datatree,openfile,39062,"To Skold-Ashil")
	characterquests.charquestprint(count,datatree,openfile,39063,"Shielded Secrets")
	characterquests.charquestprint(count,datatree,openfile,39092,"Becoming the Ascendant")
	characterquests.charquestprint(count,datatree,openfile,39122,"Ending the New Beginning")
	characterquests.charquestheader(count,"100-110: Stormheim: Skold-Ashil (Horde)",openfile)
	characterquests.charquestprint(count,datatree,openfile,38872,"The Dark Lady's Bidding")
	characterquests.charquestprint(count,datatree,openfile,38873,"Clear the Deck!")
	characterquests.charquestprint(count,datatree,openfile,39153,"Dreadwake's Dilemma")
	characterquests.charquestprint(count,datatree,openfile,39385,"A Gift for Greymane")
	characterquests.charquestprint(count,datatree,openfile,39154,"To Skold-Ashil")
	characterquests.charquestprint(count,datatree,openfile,38878,"Shielded Secrets")
	characterquests.charquestprint(count,datatree,openfile,39405,"Stories of Battle")
	characterquests.charquestprint(count,datatree,openfile,39155,"Becoming the Ascendant")
	characterquests.charquestprint(count,datatree,openfile,38882,"A New Life for Undeath")
	characterquests.charquestheader(count,"100-110: Stormheim: Sixtrigger Brothers",openfile)
	characterquests.charquestprint(count,datatree,openfile,39789,"Eating Into Our Business")
	characterquests.charquestprint(count,datatree,openfile,39793,"Only the Finest")
	characterquests.charquestprint(count,datatree,openfile,39787,"Rigging the Wager")
	characterquests.charquestprint(count,datatree,openfile,39786,"A Stone Cold Gamble")
	characterquests.charquestprint(count,datatree,openfile,39792,"A Stack of Racks")
	characterquests.charquestprint(count,datatree,openfile,42483,"Put It All on Red")
	characterquests.charquestprint(count,datatree,openfile,43331,"Time to Collect")
	characterquests.charquestheader(count,"100-110: Stormheim: Bonus Objectives",openfile)
	characterquests.charquestprint(count,datatree,openfile,38442,"A Worthy Challenger")
	characterquests.charquestprint(count,datatree,openfile,38343,"Raze Hel")
	characterquests.charquestprint(count,datatree,openfile,38939,"Assault on Skold-Ashil")
	characterquests.charquestprint(count,datatree,openfile,38374,"Assault the Drekirjar")
	characterquests.charquestprint(count,datatree,openfile,39998,"Drive Back the Tideskorn")
	characterquests.charquestprint(count,datatree,openfile,40111,"Rout the Bilgefin Invaders")
	characterquests.charquestprint(count,datatree,openfile,42431,"The Brood of Nithogg")

def charquest_z_110_suramar(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: Nightfall",openfile)
	characterquests.charquestprint(count,datatree,openfile,39985,"Khadgar's Discovery")
	characterquests.charquestprint(count,datatree,openfile,44555,"Khadgar's Discovery")
	characterquests.charquestprint(count,datatree,openfile,39986,"Magic Message")
	characterquests.charquestprint(count,datatree,openfile,39987,"Trail of Echoes")
	characterquests.charquestprint(count,datatree,openfile,40008,"The Only Way Out is Through")
	characterquests.charquestprint(count,datatree,openfile,40123,"The Nightborne Pact")
	characterquests.charquestprint(count,datatree,openfile,40009,"Arcane Thirst")
	characterquests.charquestprint(count,datatree,openfile,42229,"Shal'Aran")
	characterquests.charquestprint(count,datatree,openfile,44672,"Ancient Mana")
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: Arcanist Kel'danath",openfile)
	characterquests.charquestprint(count,datatree,openfile,40012,"An Old Ally")
	characterquests.charquestprint(count,datatree,openfile,41149,"A Re-Warding Effort")
	characterquests.charquestprint(count,datatree,openfile,40326,"Scattered Memories")
	characterquests.charquestprint(count,datatree,openfile,41702,"Written in Stone")
	characterquests.charquestprint(count,datatree,openfile,41704,"Subject 16")
	characterquests.charquestprint(count,datatree,openfile,41760,"Kel'danath's Legacy")
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: Chief Telemancer Oculeth",openfile)
	characterquests.charquestprint(count,datatree,openfile,40011,"Oculeth's Workshop")
	characterquests.charquestprint(count,datatree,openfile,40747,"The Delicate Art of Telemancy")
	characterquests.charquestprint(count,datatree,openfile,40748,"Network Security")
	characterquests.charquestprint(count,datatree,openfile,40830,"Close Enough")
	characterquests.charquestprint(count,datatree,openfile,44691,"Hungry Work")
	characterquests.charquestprint(count,datatree,openfile,40956,"Survey Says...")
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: Feeding Shal'Aran",openfile)
	characterquests.charquestprint(count,datatree,openfile,40010,"Tapping the Leylines")
	characterquests.charquestprint(count,datatree,openfile,41028,"Power Grid")
	characterquests.charquestprint(count,datatree,openfile,41138,"Feeding Shal'Aran")
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: Masquerade",openfile)
	characterquests.charquestprint(count,datatree,openfile,41762,"Sympathizers Among the Shal'dorei")
	characterquests.charquestprint(count,datatree,openfile,41834,"The Masks We Wear")
	characterquests.charquestprint(count,datatree,openfile,41989,"Blood of My Blood")
	characterquests.charquestprint(count,datatree,openfile,42079,"Masquerade")
	characterquests.charquestprint(count,datatree,openfile,42147,"First Contact")
	characterquests.charquestheader(count,"110: Suramar: Nightfallen But Not Forgotten: The Light Below",openfile)
	characterquests.charquestprint(count,datatree,openfile,40324,"Arcane Communion")
	characterquests.charquestprint(count,datatree,openfile,40325,"Scenes from a Memory")
	characterquests.charquestprint(count,datatree,openfile,42224,"Cloaked in Moonshade")
	characterquests.charquestprint(count,datatree,openfile,42225,"Breaking the Seal")
	characterquests.charquestprint(count,datatree,openfile,42226,"Moonshade Holdout")
	characterquests.charquestprint(count,datatree,openfile,42227,"Into the Crevasse")
	characterquests.charquestprint(count,datatree,openfile,42228,"The Hidden City")
	characterquests.charquestprint(count,datatree,openfile,42230,"The Valewalker's Burden")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: The Waning Crescent",openfile)
	characterquests.charquestprint(count,datatree,openfile,41877,"Lady Lunastre")
	characterquests.charquestprint(count,datatree,openfile,40746,"One of the People")
	characterquests.charquestprint(count,datatree,openfile,41148,"Dispensing Compassion")
	characterquests.charquestprint(count,datatree,openfile,40947,"Special Delivery")
	characterquests.charquestprint(count,datatree,openfile,41878,"The Gondolier")
	characterquests.charquestprint(count,datatree,openfile,40727,"All Along the Waterways")
	characterquests.charquestprint(count,datatree,openfile,40730,"Redistribution")
	characterquests.charquestprint(count,datatree,openfile,40745,"Shift Change")
	characterquests.charquestprint(count,datatree,openfile,42722,"Friends in Cages")
	characterquests.charquestprint(count,datatree,openfile,42486,"Little One Lost")
	characterquests.charquestprint(count,datatree,openfile,42487,"Friends On the Outside")
	characterquests.charquestprint(count,datatree,openfile,44051,"Wasted Potential")
	characterquests.charquestprint(count,datatree,openfile,42488,"Thalyssra's Abode")
	characterquests.charquestprint(count,datatree,openfile,42489,"Thalyssra's Drawers")
	characterquests.charquestprint(count,datatree,openfile,44636,"Building an Army")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Blood and Wine",openfile)
	characterquests.charquestprint(count,datatree,openfile,44561,"Seed of Hope")
	characterquests.charquestprint(count,datatree,openfile,42828,"Moths to a Flame")
	characterquests.charquestprint(count,datatree,openfile,42829,"Make an Entrance")
	characterquests.charquestprint(count,datatree,openfile,42832,"The Fruit of Our Efforts")
	characterquests.charquestprint(count,datatree,openfile,42833,"How It's Made: Arcwine")
	characterquests.charquestprint(count,datatree,openfile,42834,"Intense Concentration")
	characterquests.charquestprint(count,datatree,openfile,42835,"The Old Fashioned Way")
	characterquests.charquestprint(count,datatree,openfile,42836,"Silkwing Sabotage")
	characterquests.charquestprint(count,datatree,openfile,42837,"Balance to Spare")
	characterquests.charquestprint(count,datatree,openfile,42838,"Reversal")
	characterquests.charquestprint(count,datatree,openfile,44084,"Vengeance for Margaux")
	characterquests.charquestprint(count,datatree,openfile,42839,"Seek the Unsavory")
	characterquests.charquestprint(count,datatree,openfile,43969,"Hired Help")
	characterquests.charquestprint(count,datatree,openfile,42840,"If Words Don't Work...")
	characterquests.charquestprint(count,datatree,openfile,42841,"A Big Score")
	characterquests.charquestprint(count,datatree,openfile,43352,"Asset Security")
	characterquests.charquestprint(count,datatree,openfile,42792,"Make Your Mark")
	characterquests.charquestprint(count,datatree,openfile,44052,"And They Will Tremble")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Statecraft",openfile)
	characterquests.charquestprint(count,datatree,openfile,43309,"The Perfect Opportunity")
	characterquests.charquestprint(count,datatree,openfile,43310,"Either With Us")
	characterquests.charquestprint(count,datatree,openfile,43312,"Thinly Veiled Threats")
	characterquests.charquestprint(count,datatree,openfile,44040,"Vote of Confidence")
	characterquests.charquestprint(count,datatree,openfile,43311,"Or Against Us")
	characterquests.charquestprint(count,datatree,openfile,43315,"Death Becomes Him")
	characterquests.charquestprint(count,datatree,openfile,43313,"Rumor Has It")
	characterquests.charquestprint(count,datatree,openfile,43317,"In the Bag")
	characterquests.charquestprint(count,datatree,openfile,43318,"Ly'leth's Champion")
	characterquests.charquestprint(count,datatree,openfile,44053,"Friends With Benefits")
	characterquests.charquestprint(count,datatree,openfile,42490,"The Arcway: Opening the Arcway")
	characterquests.charquestprint(count,datatree,openfile,42491,"The Arcway: Long Buried Knowledge")
	characterquests.charquestprint(count,datatree,openfile,43314,"Court of Stars: Beware the Fury of a Patient Elf")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: A Growing Crisis",openfile)
	characterquests.charquestprint(count,datatree,openfile,44562,"Growing Strong")
	characterquests.charquestprint(count,datatree,openfile,44152,"A Growing Crisis")
	characterquests.charquestprint(count,datatree,openfile,43360,"The Shardmaidens")
	characterquests.charquestprint(count,datatree,openfile,43361,"Fragments of Disaster")
	characterquests.charquestprint(count,datatree,openfile,44156,"Another Arcan'dor Closes...")
	characterquests.charquestprint(count,datatree,openfile,40125,"Branch of the Arcan'dor")
	characterquests.charquestprint(count,datatree,openfile,43362,"The Emerald Nightmare: The Stuff of Dreams")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: A Change of Seasons",openfile)
	characterquests.charquestprint(count,datatree,openfile,43502,"A Change of Seasons")
	characterquests.charquestprint(count,datatree,openfile,43562,"Giving It All We've Got")
	characterquests.charquestprint(count,datatree,openfile,43563,"Ephemeral Manastorm Projector")
	characterquests.charquestprint(count,datatree,openfile,43564,"Flow Control")
	characterquests.charquestprint(count,datatree,openfile,43565,"Bring Home the Beacon")
	characterquests.charquestprint(count,datatree,openfile,43567,"All In")
	characterquests.charquestprint(count,datatree,openfile,43568,"Arcan'dor, Gift of the Ancient Magi")
	characterquests.charquestprint(count,datatree,openfile,43569,"Arluin's Request")
	characterquests.charquestprint(count,datatree,openfile,44563,"Redemption for the Fallen")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Leylines",openfile)
	characterquests.charquestprint(count,datatree,openfile,43587,"Leyline Feed: Elor'shan")
	characterquests.charquestprint(count,datatree,openfile,43588,"Leyline Feed: Kel'balor")
	characterquests.charquestprint(count,datatree,openfile,43590,"Leyline Feed: Ley Station Moonfall")
	characterquests.charquestprint(count,datatree,openfile,43591,"Leyline Feed: Ley Station Aethenar")
	characterquests.charquestprint(count,datatree,openfile,43592,"Leyline Feed: Falanaar Arcway")
	characterquests.charquestprint(count,datatree,openfile,43593,"Leyline Feed: Falanaar Depths")
	characterquests.charquestprint(count,datatree,openfile,43594,"Leyline Feed: Halls of the Eclipse")
	characterquests.charquestprint(count,datatree,openfile,44492,"Leyline Apprentice")
	characterquests.charquestprint(count,datatree,openfile,44493,"Leyline Proficiency")
	characterquests.charquestprint(count,datatree,openfile,44495,"Leyline Master")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Teleporters",openfile)
	characterquests.charquestprint(count,datatree,openfile,43808,"Moon Guard Teleporter Online!")
	characterquests.charquestprint(count,datatree,openfile,43809,"Tel'anor Teleporter Online!")
	characterquests.charquestprint(count,datatree,openfile,43811,"Lunastre Estate Teleporter Online!")
	characterquests.charquestprint(count,datatree,openfile,43813,"Sanctum of Order Teleporter Online!")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Breaking the Lightbreaker",openfile)
	characterquests.charquestprint(count,datatree,openfile,40297,"Lyana Darksorrow")
	characterquests.charquestprintclass(count,datatree,openfile,44489,"Lyana Darksorrow","classicon_demonhunter")
	characterquests.charquestprint(count,datatree,openfile,40307,"Glaive Circumstances")
	characterquests.charquestprint(count,datatree,openfile,40898,"Fresh Meat")
	characterquests.charquestprint(count,datatree,openfile,40901,"Grimwing the Devourer")
	characterquests.charquestprintclass(count,datatree,openfile,44490,"Grimwing the Devourer","classicon_demonhunter")
	characterquests.charquestprint(count,datatree,openfile,40328,"A Fate Worse Than Dying")
	characterquests.charquestprint(count,datatree,openfile,40929,"Symbols of Power")
	characterquests.charquestprint(count,datatree,openfile,41097,"Shard of Vorgos")
	characterquests.charquestprint(count,datatree,openfile,41098,"Shard of Kozak")
	characterquests.charquestprint(count,datatree,openfile,40412,"Azoran Must Die")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Moon Guard Stronghold",openfile)
	characterquests.charquestprint(count,datatree,openfile,40883,"Fate of the Guard")
	characterquests.charquestprint(count,datatree,openfile,40949,"Not Their Last Stand")
	characterquests.charquestprint(count,datatree,openfile,41030,"Sigil Reclamation")
	characterquests.charquestprint(count,datatree,openfile,40963,"Take Them in Claw")
	characterquests.charquestprint(count,datatree,openfile,40968,"Recovering Stolen Power")
	characterquests.charquestprint(count,datatree,openfile,41109,"Waiting for Revenge")
	characterquests.charquestprint(count,datatree,openfile,41108,"Rain Death Upon Them")
	characterquests.charquestprint(count,datatree,openfile,40964,"The Rift Between")
	characterquests.charquestprint(count,datatree,openfile,40967,"Precious Little Left")
	characterquests.charquestprint(count,datatree,openfile,41032,"Stop the Spell Seekers")
	characterquests.charquestprint(count,datatree,openfile,40965,"Lay Waste, Lay Mines")
	characterquests.charquestprint(count,datatree,openfile,40969,"Starweaver's Fate")
	characterquests.charquestprint(count,datatree,openfile,40970,"The Orchestrator of Our Demise")
	characterquests.charquestprint(count,datatree,openfile,40971,"Overwhelming Distraction")
	characterquests.charquestprint(count,datatree,openfile,40972,"Last Stand of the Moon Guard")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Tidying Tel'anor",openfile)
	characterquests.charquestprint(count,datatree,openfile,40266,"The Lost Advisor")
	characterquests.charquestprint(count,datatree,openfile,40744,"An Ancient Recipe")
	characterquests.charquestprint(count,datatree,openfile,40227,"Bad Intentions")
	characterquests.charquestprint(count,datatree,openfile,40300,"Tools of the Trade")
	characterquests.charquestprint(count,datatree,openfile,40306,"The Last Chapter")
	characterquests.charquestprint(count,datatree,openfile,40578,"Paying Respects")
	characterquests.charquestprint(count,datatree,openfile,40315,"End of the Line")
	characterquests.charquestprint(count,datatree,openfile,40319,"The Final Ingredient")
	characterquests.charquestprint(count,datatree,openfile,40321,"Feathersong's Redemption")
	characterquests.charquestprint(count,datatree,openfile,40308,"Fragments of Memory")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Eminent Grow-main",openfile)
	characterquests.charquestprint(count,datatree,openfile,41452,"Feline Frantic")
	characterquests.charquestprint(count,datatree,openfile,41453,"Homeward Bounding")
	characterquests.charquestprint(count,datatree,openfile,41462,"Trouble Has Huge Feet")
	characterquests.charquestprint(count,datatree,openfile,41197,"You've Got to Be Kitten Me Right Meow")
	characterquests.charquestprint(count,datatree,openfile,41463,"Missing Along the Way")
	characterquests.charquestprint(count,datatree,openfile,41464,"Not Here, Not Now, Not Ever")
	characterquests.charquestprint(count,datatree,openfile,41467,"The Only Choice We Can Make")
	characterquests.charquestprint(count,datatree,openfile,41473,"Redhoof the Ancient")
	characterquests.charquestprint(count,datatree,openfile,41474,"Fertilizing the Future")
	characterquests.charquestprint(count,datatree,openfile,41475,"Prongs and Fangs")
	characterquests.charquestprint(count,datatree,openfile,41478,"The Final Blessing")
	characterquests.charquestprint(count,datatree,openfile,41479,"Natural Adversaries")
	characterquests.charquestprint(count,datatree,openfile,41485,"Moonwhisper Rescue")
	characterquests.charquestprint(count,datatree,openfile,41480,"Managazer")
	characterquests.charquestprint(count,datatree,openfile,41469,"Return to Irongrove Retreat")
	characterquests.charquestprint(count,datatree,openfile,41494,"Eminent Grow-main")
	characterquests.charquestprint(count,datatree,openfile,42223,"Scouting the Crimson Thicket")
	characterquests.charquestprint(count,datatree,openfile,40617,"Turn Around, Nighteyes")
	characterquests.charquestprint(count,datatree,openfile,41230,"Trapping Evolved")
	characterquests.charquestprint(count,datatree,openfile,41215,"They Become The Hunted")
	characterquests.charquestprint(count,datatree,openfile,41231,"Apex Predator")
	characterquests.charquestprint(count,datatree,openfile,43582,"Shalassic Park")
	characterquests.charquestheader(count,"110: Suramar: Good Suramaritan: Jandvik's Jarl",openfile)
	characterquests.charquestprint(count,datatree,openfile,40907,"Removing Obstacles")
	characterquests.charquestprint(count,datatree,openfile,40908,"Jarl Come Back Now")
	characterquests.charquestprint(count,datatree,openfile,40332,"Beach Bonfire")
	characterquests.charquestprint(count,datatree,openfile,40320,"Band of Blood Brothers")
	characterquests.charquestprint(count,datatree,openfile,40331,"Bite of the Sashj'tar")
	characterquests.charquestprint(count,datatree,openfile,40334,"Fisherman's Tonic")
	characterquests.charquestprint(count,datatree,openfile,41034,"Testing the Waters")
	characterquests.charquestprint(count,datatree,openfile,40927,"Jandvik's Last Hope")
	characterquests.charquestprint(count,datatree,openfile,41426,"Against Their Will")
	characterquests.charquestprint(count,datatree,openfile,41709,"Breaking Down the Big Guns")
	characterquests.charquestprint(count,datatree,openfile,41410,"Dry Powder")
	characterquests.charquestprint(count,datatree,openfile,41409,"Timing Is Everything")
	characterquests.charquestprint(count,datatree,openfile,41606,"Finding Brytag")
	characterquests.charquestprint(count,datatree,openfile,40364,"Bubble Trouble")
	characterquests.charquestprint(count,datatree,openfile,41618,"The Seawarden")
	characterquests.charquestprint(count,datatree,openfile,41425,"Sunken Foes")
	characterquests.charquestprint(count,datatree,openfile,41001,"Shatter the Sashj'tar")
	characterquests.charquestprint(count,datatree,openfile,41499,"Squid Out of Water")
	characterquests.charquestprint(count,datatree,openfile,40336,"Turning the Tidemistress")
	characterquests.charquestprint(count,datatree,openfile,41137,"Fall of the King")
	characterquests.charquestheader(count,"110: Suramar: Lespin Silverleaf",openfile)
	characterquests.charquestprint(count,datatree,openfile,41123,"An Artisan's Mark")
	characterquests.charquestprint(count,datatree,openfile,41307,"All That Glitters")
	characterquests.charquestprint(count,datatree,openfile,41466,"Estate Jewelry: Haute Claw-ture")
	characterquests.charquestprint(count,datatree,openfile,41320,"Pry It From Their Cold, Feral Claws")
	characterquests.charquestprint(count,datatree,openfile,41465,"Estate Jewelry: A Braggart's Brooch")
	characterquests.charquestprint(count,datatree,openfile,41146,"Elegant Design")
	characterquests.charquestprint(count,datatree,openfile,41915,"The Master's Legacy")
	characterquests.charquestheader(count,"110: Suramar: Kyrtos",openfile)
	characterquests.charquestprint(count,datatree,openfile,40694,"One Small Step for Magic")
	characterquests.charquestprint(count,datatree,openfile,40625,"A Different Source")
	characterquests.charquestprint(count,datatree,openfile,40657,"The Road to Fel")
	characterquests.charquestprint(count,datatree,openfile,40683,"Discovery Requires Experimentation")
	characterquests.charquestprint(count,datatree,openfile,40919,"Fel Bent for Leather")
	characterquests.charquestprint(count,datatree,openfile,40713,"The Black Tome")
	characterquests.charquestprint(count,datatree,openfile,40642,"Power! Get The Power!")
	characterquests.charquestprint(count,datatree,openfile,42366,"The Bigger They Are, The Harder They Fel")
	characterquests.charquestheader(count,"110: Suramar: Iadreth",openfile)
	characterquests.charquestprint(count,datatree,openfile,40401,"A Way Back In")
	characterquests.charquestprint(count,datatree,openfile,40469,"Final Preparations")
	characterquests.charquestprint(count,datatree,openfile,40424,"A Desperate Journey")
	characterquests.charquestprint(count,datatree,openfile,40470,"Quality of Life")
	characterquests.charquestheader(count,"110: Suramar: Absolon",openfile)
	characterquests.charquestprint(count,datatree,openfile,40796,"Lingering on the Edge")
	characterquests.charquestprint(count,datatree,openfile,40798,"Cling to Hope")
	characterquests.charquestheader(count,"110: Suramar: Morhun Rivertamer",openfile)
	characterquests.charquestprint(count,datatree,openfile,40368,"Turtle Powered")
	characterquests.charquestprint(count,datatree,openfile,40348,"Something in the Water")
	characterquests.charquestprint(count,datatree,openfile,40370,"Purge the Unclean")
	characterquests.charquestheader(count,"110: Suramar: Shal'aran Banking Chest",openfile)
	characterquests.charquestprint(count,datatree,openfile,44176,"The Conveniences of Home")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part One: Lockdown",openfile)
	characterquests.charquestprint(count,datatree,openfile,45260,"One Day at a Time")
	characterquests.charquestprint(count,datatree,openfile,38649,"Silence in the City")
	characterquests.charquestprint(count,datatree,openfile,38695,"Crackdown")
	characterquests.charquestprint(count,datatree,openfile,38692,"Answering Aggression")
	characterquests.charquestprint(count,datatree,openfile,38720,"No Reason to Stay")
	characterquests.charquestprint(count,datatree,openfile,38694,"Regroup")
	characterquests.charquestprint(count,datatree,openfile,42889,"The Way Back Home")
	characterquests.charquestprint(count,datatree,openfile,44955,"Visitor in Shal'Aran")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Two: Missing Persons",openfile)
	characterquests.charquestprint(count,datatree,openfile,45261,"Continuing the Cure")
	characterquests.charquestprint(count,datatree,openfile,44722,"Disillusioned Defector")
	characterquests.charquestprint(count,datatree,openfile,44724,"Missing Persons")
	characterquests.charquestprint(count,datatree,openfile,44723,"More Like Me")
	characterquests.charquestprint(count,datatree,openfile,44725,"Hostage Situation")
	characterquests.charquestprint(count,datatree,openfile,44726,"In the Business of Souls")
	characterquests.charquestprint(count,datatree,openfile,44727,"Smuggled!")
	characterquests.charquestprint(count,datatree,openfile,44814,"Waning Refuge")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Three: Waxing Crescent",openfile)
	characterquests.charquestprint(count,datatree,openfile,45262,"A Message from Ly'leth")
	characterquests.charquestprint(count,datatree,openfile,44742,"Tavernkeeper's Fate")
	characterquests.charquestprint(count,datatree,openfile,44752,"Essence Triangulation")
	characterquests.charquestprint(count,datatree,openfile,44753,"On Public Display")
	characterquests.charquestprint(count,datatree,openfile,44754,"Waxing Crescent")
	characterquests.charquestprint(count,datatree,openfile,44756,"Sign of the Dusk Lily")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Four: An Elven Problem",openfile)
	characterquests.charquestprint(count,datatree,openfile,45316,"Stabilizing Suramar")
	characterquests.charquestprint(count,datatree,openfile,45263,"Eating Before the Meeting")
	characterquests.charquestprint(count,datatree,openfile,40391,"Take Me To Your Leader")
	characterquests.charquestprintfaction(count,datatree,openfile,43810,"Down to Business","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,43812,"Down to Business","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,44831,"Taking a Promenade","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,41607,"Taking a Promenade","horde")
	characterquests.charquestprint(count,datatree,openfile,41916,"A Better Future")
	characterquests.charquestprint(count,datatree,openfile,44834,"Nullified")
	characterquests.charquestprint(count,datatree,openfile,44843,"Crystal Clearing")
	characterquests.charquestprint(count,datatree,openfile,44844,"Powering Down the Portal")
	characterquests.charquestprint(count,datatree,openfile,44842,"Shield, Meet Spell")
	characterquests.charquestprint(count,datatree,openfile,44845,"Break an Arm")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Five: Crafting War",openfile)
	characterquests.charquestprint(count,datatree,openfile,45265,"Feeding the Rebellion")
	characterquests.charquestprintfaction(count,datatree,openfile,44743,"Tyrande's Command","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,44859,"Liadrin's Command","horde")
	characterquests.charquestprint(count,datatree,openfile,44870,"Mouths to Feed")
	characterquests.charquestprint(count,datatree,openfile,44873,"Oculeth Ex Machina")
	characterquests.charquestprintfaction(count,datatree,openfile,44858,"Trolling Them","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,44860,"Trolling Them","horde")
	characterquests.charquestprint(count,datatree,openfile,44928,"Something's Not Quite Right...")
	characterquests.charquestprintfaction(count,datatree,openfile,44861,"Arming the Rebels","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,44862,"Arming the Rebels","horde")
	characterquests.charquestprint(count,datatree,openfile,44827,"Citizens' Army")
	characterquests.charquestprint(count,datatree,openfile,44829,"We Need Weapons")
	characterquests.charquestprint(count,datatree,openfile,44830,"Learning From the Dead")
	characterquests.charquestprint(count,datatree,openfile,44790,"Trial by Demonfire")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Six: March on Suramar",openfile)
	characterquests.charquestprint(count,datatree,openfile,45266,"A United Front")
	characterquests.charquestprint(count,datatree,openfile,44739,"Ready for Battle")
	characterquests.charquestprint(count,datatree,openfile,44738,"Full Might of the Elves")
	characterquests.charquestprint(count,datatree,openfile,44740,"Staging Point")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Seven: Elisande's Retort",openfile)
	characterquests.charquestprint(count,datatree,openfile,45317,"Fighting on All Fronts")
	characterquests.charquestprint(count,datatree,openfile,45267,"Before the Siege")
	characterquests.charquestprint(count,datatree,openfile,44736,"Gates of the Nighthold")
	characterquests.charquestprint(count,datatree,openfile,44822,"Temporal Investigations")
	characterquests.charquestprint(count,datatree,openfile,45209,"Those Scrying Eyes")
	characterquests.charquestprint(count,datatree,openfile,44832,"Scouting the Breach")
	characterquests.charquestprint(count,datatree,openfile,44833,"The Seal's Power")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Eight: As Strong as Our Will",openfile)
	characterquests.charquestprint(count,datatree,openfile,45268,"The Advisor and the Arcanist")
	characterquests.charquestprint(count,datatree,openfile,44918,"A Message From Our Enemies")
	characterquests.charquestprint(count,datatree,openfile,44919,"A Challenge From Our Enemies")
	characterquests.charquestprint(count,datatree,openfile,45063,"The Felsoul Experiments")
	characterquests.charquestprint(count,datatree,openfile,45067,"Telemantic Expanse")
	characterquests.charquestprint(count,datatree,openfile,45062,"Resisting Arrest")
	characterquests.charquestprint(count,datatree,openfile,45065,"Survey the City")
	characterquests.charquestprint(count,datatree,openfile,45066,"Experimental Instability")
	characterquests.charquestprint(count,datatree,openfile,45064,"Felborne No More")
	characterquests.charquestheader(count,"110: Suramar: Insurrection: Part Nine: Breaking the Nighthold",openfile)
	characterquests.charquestprint(count,datatree,openfile,45269,"A Taste of Freedom")
	characterquests.charquestprint(count,datatree,openfile,44964,"I'll Just Leave This Here")
	characterquests.charquestprint(count,datatree,openfile,44719,"Breaching the Sanctum")
	characterquests.charquestprint(count,datatree,openfile,45417,"The Nighthold: Lord of the Shadow Council")
	characterquests.charquestprint(count,datatree,openfile,45372,"Fate of the Nightborne")

def charquest_z_110_legion_fall(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"110: Broken Shore: Armies of Legionfall",openfile)
	characterquests.charquestprint(count,datatree,openfile,46730,"Armies of Legionfall")
	characterquests.charquestprint(count,datatree,openfile,46734,"Assault on Broken Shore")
	characterquests.charquestprint(count,datatree,openfile,46286,"Legionfall Supplies")
	characterquests.charquestprint(count,datatree,openfile,46832,"Aalgen Point")
	characterquests.charquestprint(count,datatree,openfile,46845,"Vengeance Point")
	characterquests.charquestprint(count,datatree,openfile,46245,"Begin Construction")
	characterquests.charquestprint(count,datatree,openfile,46244,"Cathedral of Eternal Night: Altar of the Aegis")
	characterquests.charquestprint(count,datatree,openfile,46247,"Defending Broken Isles")
	characterquests.charquestprint(count,datatree,openfile,47137,"Champions of Legionfall")
	characterquests.charquestprint(count,datatree,openfile,46251,"Shard Times")
	characterquests.charquestprint(count,datatree,openfile,47139,"Mark of the Sentinax")
	characterquests.charquestprint(count,datatree,openfile,46248,"Self-Fulfilling Prophecy")
	characterquests.charquestprint(count,datatree,openfile,46252,"Intolerable Infestation")
	characterquests.charquestprint(count,datatree,openfile,46769,"Relieved of Their Valuables")
	characterquests.charquestprint(count,datatree,openfile,46250,"Take Out the Head...")
	characterquests.charquestprint(count,datatree,openfile,46249,"Championing Our Cause")
	characterquests.charquestprint(count,datatree,openfile,46246,"Strike Them Down")
	characterquests.charquestheader(count,"Broken Shore: Dungeon/Raid Quests",openfile)
	characterquests.charquestprint(count,datatree,openfile,46253,"Pillars of Creation")
	characterquests.charquestprint(count,datatree,openfile,46805,"The Deceiver's Downfall")

def charquest_z_110_Argus(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"110: Argus: The Assault Begins",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,47221,"The Hand of Fate","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,47835,"The Hand of Fate","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,47222,"Two If By Sea","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,47867,"Two If By Sea","horde")
	characterquests.charquestprint(count,datatree,openfile,47223,"Light's Exodus")
	characterquests.charquestprint(count,datatree,openfile,47224,"The Vindicaar")
	characterquests.charquestprint(count,datatree,openfile,48440,"Into the Night")
	characterquests.charquestprint(count,datatree,openfile,46938,"Alone in the Abyss")
	characterquests.charquestprint(count,datatree,openfile,47589,"Righteous Fury")
	characterquests.charquestprint(count,datatree,openfile,46297,"Overwhelming Power")
	characterquests.charquestprint(count,datatree,openfile,48483,"A Stranger's Plea")
	characterquests.charquestprint(count,datatree,openfile,47627,"Vengeance")
	characterquests.charquestprint(count,datatree,openfile,47641,"Sign of Resistance")
	characterquests.charquestprint(count,datatree,openfile,46732,"The Prophet's Gambit")
	characterquests.charquestprint(count,datatree,openfile,46816,"Rendezvous")
	characterquests.charquestprint(count,datatree,openfile,46839,"From Darkness")
	characterquests.charquestprint(count,datatree,openfile,46840,"Prisoners No More")
	characterquests.charquestprint(count,datatree,openfile,46841,"Threat Reduction")
	characterquests.charquestprint(count,datatree,openfile,46842,"A Strike at the Heart")
	characterquests.charquestprint(count,datatree,openfile,46843,"Return to the Vindicaar")
	characterquests.charquestprint(count,datatree,openfile,48500,"A Moment of Respite")
	characterquests.charquestprint(count,datatree,openfile,47431,"Gathering Light")
	characterquests.charquestprint(count,datatree,openfile,46213,"Crystals Not Included")
	characterquests.charquestprint(count,datatree,openfile,40238,"A Grim Equation")
	characterquests.charquestprint(count,datatree,openfile,47541,"The Best Prevention")
	characterquests.charquestprint(count,datatree,openfile,47508,"Fire at Will")
	characterquests.charquestprint(count,datatree,openfile,47771,"Locating the Longshot")
	characterquests.charquestprint(count,datatree,openfile,47526,"Bringing the Big Guns")
	characterquests.charquestprint(count,datatree,openfile,47754,"Lightly Roasted")
	characterquests.charquestprint(count,datatree,openfile,47653,"Light's Return")
	characterquests.charquestprint(count,datatree,openfile,47743,"The Child of Light and Shadow")
	characterquests.charquestprint(count,datatree,openfile,49143,"Essence of the Light Mother")
	characterquests.charquestprint(count,datatree,openfile,47287,"The Vindicaar Matrix Core")
	characterquests.charquestprint(count,datatree,openfile,48559,"An Offering of Light")
	characterquests.charquestprint(count,datatree,openfile,48199,"The Burning Heart")
	characterquests.charquestprint(count,datatree,openfile,48200,"Securing a Foothold")
	characterquests.charquestprint(count,datatree,openfile,48201,"Reinforce Light's Purchase")
	characterquests.charquestprint(count,datatree,openfile,48202,"Reinforce the Veiled Den")
	characterquests.charquestprint(count,datatree,openfile,47473,"Sizing Up The Opposition")
	characterquests.charquestheader(count,"110: Argus: Dark Awakenings",openfile)
	characterquests.charquestprint(count,datatree,openfile,47889,"The Speaker Calls")
	characterquests.charquestprint(count,datatree,openfile,47890,"Visions of Torment")
	characterquests.charquestprint(count,datatree,openfile,47891,"Dire News")
	characterquests.charquestprint(count,datatree,openfile,47892,"Storming the Citadel")
	characterquests.charquestprint(count,datatree,openfile,47986,"Scars of the Past")
	characterquests.charquestprint(count,datatree,openfile,47987,"Preventive Measures")
	characterquests.charquestprint(count,datatree,openfile,47988,"Chaos Theory")
	characterquests.charquestprint(count,datatree,openfile,47991,"Dark Machinations")
	characterquests.charquestprint(count,datatree,openfile,47990,"A Touch of Fel")
	characterquests.charquestprint(count,datatree,openfile,47989,"Heralds of Apocalypse")
	characterquests.charquestprint(count,datatree,openfile,47992,"Dawn of Justice")
	characterquests.charquestprint(count,datatree,openfile,47993,"Lord of the Spire")
	characterquests.charquestprint(count,datatree,openfile,47994,"Forming a Bond")
	characterquests.charquestprint(count,datatree,openfile,48081,"A Floating Ruin")
	characterquests.charquestprint(count,datatree,openfile,46815,"Mac'Aree, Jewel of Argus")
	characterquests.charquestprint(count,datatree,openfile,46818,"Defenseless and Afraid")
	characterquests.charquestprint(count,datatree,openfile,46834,"Khazaduum, First of His Name")
	characterquests.charquestprint(count,datatree,openfile,47066,"Consecrating Ground")
	characterquests.charquestprint(count,datatree,openfile,46941,"The Path Forward")
	characterquests.charquestprint(count,datatree,openfile,47686,"Not-So-Humble Beginnings")
	characterquests.charquestprint(count,datatree,openfile,47882,"Conservation of Magic")
	characterquests.charquestprint(count,datatree,openfile,47688,"Invasive Species")
	characterquests.charquestprint(count,datatree,openfile,47883,"The Longest Vigil")
	characterquests.charquestprint(count,datatree,openfile,47689,"Gatekeeper's Challenge: Tenacity")
	characterquests.charquestprint(count,datatree,openfile,47685,"Gatekeeper's Challenge: Cunning")
	characterquests.charquestprint(count,datatree,openfile,47687,"Gatekeeper's Challenge: Mastery")
	characterquests.charquestprint(count,datatree,openfile,47690,"The Defiler's Legacy")
	characterquests.charquestprint(count,datatree,openfile,48107,"The Sigil of Awakening")
	characterquests.charquestheader(count,"110: Argus: War of Light and Shadow",openfile)
	characterquests.charquestprint(count,datatree,openfile,48461,"Where They Least Expect It")
	characterquests.charquestprint(count,datatree,openfile,48344,"We Have a Problem")
	characterquests.charquestprint(count,datatree,openfile,47691,"A Non-Prophet Organization")
	characterquests.charquestprint(count,datatree,openfile,47854,"Wrath of the Hight Exarch")
	characterquests.charquestprint(count,datatree,openfile,47995,"Overt Ops")
	characterquests.charquestprint(count,datatree,openfile,47853,"Flanking Maneuvers")
	characterquests.charquestprint(count,datatree,openfile,48345,"Talgath's Forces")
	characterquests.charquestprint(count,datatree,openfile,47855,"What Might Have Been")
	characterquests.charquestprint(count,datatree,openfile,47856,"Across the Universe")
	characterquests.charquestprint(count,datatree,openfile,47416,"Shadow of the Triumvirate")
	characterquests.charquestprint(count,datatree,openfile,47238,"The Seat of the Triumvirate")
	characterquests.charquestprint(count,datatree,openfile,40761,"Whispers from Oronaar")
	characterquests.charquestprint(count,datatree,openfile,47101,"Arkhaan's Prayers")
	characterquests.charquestprint(count,datatree,openfile,47180,"The Pulsing Madness")
	characterquests.charquestprint(count,datatree,openfile,47100,"Arkhaan's Pain")
	characterquests.charquestprint(count,datatree,openfile,47183,"Arkhaan's Plan")
	characterquests.charquestprint(count,datatree,openfile,47184,"Arkhaan's Peril")
	characterquests.charquestprint(count,datatree,openfile,47203,"Throwing Shade")
	characterquests.charquestprint(count,datatree,openfile,47217,"Sources of Darkness")
	characterquests.charquestprint(count,datatree,openfile,47218,"The Shadowguard Incursion")
	characterquests.charquestprint(count,datatree,openfile,47219,"A Vessel Made Ready")
	characterquests.charquestprint(count,datatree,openfile,47220,"A Beacon in the Dark")
	characterquests.charquestprint(count,datatree,openfile,48560,"An Offering of Shadow")
	characterquests.charquestprint(count,datatree,openfile,47654,"Seat of the Triumvirate: The Crest of Knowledge")
	characterquests.charquestheader(count,"110: Argus: Side Chain: Class Hall",openfile)
	characterquests.charquestprint(count,datatree,openfile,48460,"The Wranglers")
	characterquests.charquestprint(count,datatree,openfile,47967,"An Argus Roper")
	characterquests.charquestprint(count,datatree,openfile,48455,"Duskcloak Problem")
	characterquests.charquestprint(count,datatree,openfile,48453,"Strike Back")
	characterquests.charquestprint(count,datatree,openfile,48544,"Woah, Nelly!")
	characterquests.charquestprint(count,datatree,openfile,48441,"Remnants of Darkfall Ridge")
	characterquests.charquestprint(count,datatree,openfile,48442,"Nath'raxas Hold: Preparations")
	characterquests.charquestprint(count,datatree,openfile,48443,"Nath'raxas Hold: Rescue Mission")
	characterquests.charquestprint(count,datatree,openfile,48445,"The Ruins of Oronaar")
	characterquests.charquestprint(count,datatree,openfile,48446,"Relics of the Ancient Eredar")
	characterquests.charquestprint(count,datatree,openfile,48654,"Beneath Oronaar")
	characterquests.charquestprint(count,datatree,openfile,48447,"Shadowguard Dispersion")
	characterquests.charquestprint(count,datatree,openfile,48911,"Void Inoculation")
	characterquests.charquestprint(count,datatree,openfile,48448,"Hindering the Legion War Machine")
	characterquests.charquestprint(count,datatree,openfile,48600,"Take the Edge Off")
	characterquests.charquestprint(count,datatree,openfile,48912,"Supplying the Antoran Campaign")
	characterquests.charquestprint(count,datatree,openfile,48601,"Felfire Shattering")
	characterquests.charquestheader(count,"110: Argus: Side Chain: Invasion Points",openfile)
	characterquests.charquestprint(count,datatree,openfile,48461,"Where They Least Expect It")
	characterquests.charquestprint(count,datatree,openfile,48513,"Invasion Point Offensive")
	characterquests.charquestprint(count,datatree,openfile,48605,"Commander's Downfall")
	characterquests.charquestheader(count,"110: Argus: Side Chain: The Fel Heart of Argus",openfile)
	characterquests.charquestprint(count,datatree,openfile,47102,"The Mysterious Missive")
	characterquests.charquestprint(count,datatree,openfile,47554,"Intercepting the Legion's Plans")
	characterquests.charquestprint(count,datatree,openfile,47104,"Imprisoned Inquisitor")
	characterquests.charquestprint(count,datatree,openfile,47134,"Foiling the Legion's Jailbreak")
	characterquests.charquestprint(count,datatree,openfile,47182,"Long Overdue")

def charquest_chromie(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"Chromie",openfile)
	characterquests.charquestprint(count,datatree,openfile,48021,"Chromie")
	characterquests.charquestprint(count,datatree,openfile,47543,"The Day That Chromie Dies")
	characterquests.charquestprint(count,datatree,openfile,47545,"Rewind")
	characterquests.charquestprint(count,datatree,openfile,47550,"The Many Advantages of Being a Time Dragon")
	characterquests.charquestprint(count,datatree,openfile,47557,"Smoldering Chronoshard")
	characterquests.charquestprint(count,datatree,openfile,47558,"Fel-Touched Chronoshard")
	characterquests.charquestprint(count,datatree,openfile,47559,"Gleaming Chronoshard")
	characterquests.charquestprint(count,datatree,openfile,47560,"Frozen Chronoshard")
	characterquests.charquestprint(count,datatree,openfile,47642,"Soul Crystal")
	characterquests.charquestprint(count,datatree,openfile,47643,"The Ancients' Wisdom")
	characterquests.charquestprint(count,datatree,openfile,47644,"Demonic Corestone")
	characterquests.charquestprint(count,datatree,openfile,47645,"Voidcallers' Scroll")
	characterquests.charquestprint(count,datatree,openfile,47807,"Worried About My Friends")
	characterquests.charquestprint(count,datatree,openfile,47904,"Preserve the True Future")
	characterquests.charquestprint(count,datatree,openfile,47906,"The Deaths of Chromie")

def charquest_artifact_improvingonhistory(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"Improving on History",openfile)
	characterquests.charquestprint(count,datatree,openfile,43496,"The Power Within")
	characterquests.charquestprint(count,datatree,openfile,40668,"Eye of Azshara: The Heart of Zin-Azshari (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,43517,"Darkheart Thicket: Fallen Power (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,43514,"Vainglorious Past")
	characterquests.charquestprint(count,datatree,openfile,43518,"Tempering Darkness")
	characterquests.charquestprint(count,datatree,openfile,43519,"Lucid Strength ")
	characterquests.charquestprint(count,datatree,openfile,43520,"The Emerald Nightmare: In Nightmares")
	characterquests.charquestprint(count,datatree,openfile,43521,"Essence of Power")
	characterquests.charquestprint(count,datatree,openfile,43522,"Essential Consumption")
	characterquests.charquestprint(count,datatree,openfile,43527,"Saving the Guard")
	characterquests.charquestprint(count,datatree,openfile,43523,"Repaid Debt")
	characterquests.charquestprint(count,datatree,openfile,40673,"Lost Knowledge")
	characterquests.charquestprint(count,datatree,openfile,43525,"Vault of the Wardens: Borrowing Without Asking (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,40675,"The Arcway: Rite of the Captain (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,43524,"Court of Stars: Literary Perfection (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,40678,"Twisted Power")
	characterquests.charquestprint(count,datatree,openfile,43526,"A True Test")
	characterquests.charquestprint(count,datatree,openfile,40603,"Seeking the Valkyra")
	characterquests.charquestprint(count,datatree,openfile,40608,"The Mark")
	characterquests.charquestprint(count,datatree,openfile,40613,"Maw of Souls: Retrieving the Svalnguard (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,40614,"A Feast Fit for Odyn")
	characterquests.charquestprint(count,datatree,openfile,40672,"Neltharion's Lair: Presentation is Key (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,40615,"Halls of Valor: Odyn's Blessing (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,43528,"Planning the Assault")
	characterquests.charquestprint(count,datatree,openfile,43898,"Preparing to Move")
	characterquests.charquestprint(count,datatree,openfile,43531,"Into the Nighthold")
	characterquests.charquestprint(count,datatree,openfile,43530,"The Nighthold: Delusions of Grandeur")
	characterquests.charquestprint(count,datatree,openfile,43532,"The Nighthold: Darkness Calls")
	characterquests.charquestprint(count,datatree,openfile,43533,"Balance of Power")

def charquest_empoweredartifacts(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"Empowering Artifacts",openfile)
	characterquests.charquestprint(count,datatree,openfile,46744,"Greater Power for Greater Threats")
	characterquests.charquestprint(count,datatree,openfile,46765,"The Broken Shore: Investigating the Legion")
	characterquests.charquestprint(count,datatree,openfile,47000,"The Council's Call")
	characterquests.charquestprint(count,datatree,openfile,44782,"Away From Prying Eyes")
	characterquests.charquestprint(count,datatree,openfile,44821,"In Dire Need")
	characterquests.charquestheader(count,"DPS: Archmage Xylem<div>Survival Hunter, Subtlety Rogue, Havoc Demon Hunter, Frost Death Knight, Arms Warrior</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47046,"Frost: The Thieving Apprentice","classicon_deathknight")
	characterquests.charquestprintclass(count,datatree,openfile,47043,"Havoc: The Thieving Apprentice","classicon_demonhunter")
	characterquests.charquestprintclass(count,datatree,openfile,47047,"Survival: The Thieving Apprentice","classicon_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,47048,"Subtlety: The Thieving Apprentice","classicon_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,44914,"Arms: The Thieving Apprentice","classicon_warrior")
	characterquests.charquestprint(count,datatree,openfile,44915,"Professionally Good Looking")
	characterquests.charquestprint(count,datatree,openfile,44920,"Order of Incantations")
	characterquests.charquestprint(count,datatree,openfile,44924,"The Archmage Accosted")
	characterquests.charquestprint(count,datatree,openfile,46177,"A Portal Away")
	characterquests.charquestprint(count,datatree,openfile,45865,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,44925,"Closing the Eye")
	characterquests.charquestprint(count,datatree,openfile,45570,"In Safer Hands")
	characterquests.charquestprint(count,datatree,openfile,45908,"Xylem's Gift")
	characterquests.charquestheader(count,"DPS: Fate of the Tideskorn<div>Arcane Mage, Assassination Rogue, Retribution Paladin, Enhancement Shaman, Demonology Warlock</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,45482,"Arcane: Fate of the Tideskorn","classicon_mage")
	characterquests.charquestprintclass(count,datatree,openfile,47052,"Retribution: Fate of the Tideskorn","classicon_paladin")
	characterquests.charquestprintclass(count,datatree,openfile,47051,"Assassination: Fate of the Tideskorn","classicon_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,47050,"Enhancement: Fate of the Tideskorn","classicon_shaman")
	characterquests.charquestprintclass(count,datatree,openfile,47049,"Demonology: Fate of the Tideskorn","classicon_warlock")
	characterquests.charquestprint(count,datatree,openfile,45486,"The Reluctant Queen")
	characterquests.charquestprint(count,datatree,openfile,45522,"To Silence the Bonespeakers")
	characterquests.charquestprint(count,datatree,openfile,45523,"To Tame the Drekirjar")
	characterquests.charquestprint(count,datatree,openfile,45524,"The Forgotten Heir")
	characterquests.charquestprint(count,datatree,openfile,45525,"Unanswered Questions")
	characterquests.charquestprint(count,datatree,openfile,46340,"The Gates Are Closed")
	characterquests.charquestprint(count,datatree,openfile,45862,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,45526,"The God-Queen's Fury")
	characterquests.charquestprint(count,datatree,openfile,45527,"Eyir's Forgiveness")
	characterquests.charquestprint(count,datatree,openfile,45904,"The God-Queen's Gift")
	characterquests.charquestheader(count,"DPS: Folly of Levia Laurence<div>Feral Druid, Outlaw Rogue, Unholy Death Knight, Fury Warrior, Fire Mage, Elemental Shaman</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47057,"Unholy: The Folly of Levia Laurence","classicon_deathknight")
	characterquests.charquestprintclass(count,datatree,openfile,47059,"Feral: The Folly of Levia Laurence","classicon_druid")
	characterquests.charquestprintclass(count,datatree,openfile,47055,"Fire: The Folly of Levia Laurence","classicon_mage")
	characterquests.charquestprintclass(count,datatree,openfile,47058,"Outlaw: The Folly of Levia Laurence","classicon_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,45123,"Elemental: The Folly of Levia Laurence","classicon_shaman")
	characterquests.charquestprintclass(count,datatree,openfile,47056,"Fury: The Folly of Levia Laurence","classicon_warrior")
	characterquests.charquestprint(count,datatree,openfile,45916,"The Acolyte Imperiled")
	characterquests.charquestprint(count,datatree,openfile,45917,"Following the Scent")
	characterquests.charquestprint(count,datatree,openfile,45125,"Dabbling in the Demonic")
	characterquests.charquestprint(count,datatree,openfile,45126,"Unlikely Seduction")
	characterquests.charquestprint(count,datatree,openfile,45127,"Fel-Crossed Lovers")
	characterquests.charquestprint(count,datatree,openfile,45861,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,46065,"An Impossible Foe")
	characterquests.charquestprint(count,datatree,openfile,45902,"The Imp Mother's Gift")
	characterquests.charquestheader(count,"DPS: Rumbling Near Feltotem<div>Discipline Priest, Windwalker Monk, Beast Mastery Hunter, Destruction Warlock</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47018,"Beast Mastery: Rumblings Near Feltotem","classicon_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,47019,"Windwalker: Rumblings Near Feltotem","classicon_monk")
	characterquests.charquestprintclass(count,datatree,openfile,47020,"Discipline: Rumblings Near Feltotem","classicon_priest")
	characterquests.charquestprintclass(count,datatree,openfile,45560,"Destruction: Rumblings Near Feltotem","classicon_warlock")
	characterquests.charquestprint(count,datatree,openfile,45564,"The Burning Birds")
	characterquests.charquestprint(count,datatree,openfile,45726,"The Tainted Marsh")
	characterquests.charquestprint(count,datatree,openfile,45575,"Village of the Corruptors")
	characterquests.charquestprint(count,datatree,openfile,45587,"The Feltotem Menace")
	characterquests.charquestprint(count,datatree,openfile,45796,"Destroying the Nest")
	characterquests.charquestprint(count,datatree,openfile,45841,"A Triumphant Report")
	characterquests.charquestprint(count,datatree,openfile,45842,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,45627,"Feltotem's Fall")
	characterquests.charquestprint(count,datatree,openfile,45909,"Navarrogg's Gift")
	characterquests.charquestheader(count,"DPS: Twisted Twin<div>Shadow Priest, Affliction Warlock, Marksmanship Hunter, Balance Druid, Frost Mage</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47037,"Balance: The Twisted Twin","classicon_druid")
	characterquests.charquestprintclass(count,datatree,openfile,47039,"Marksmanship: The Twisted Twin","classicon_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,45182,"Frost: The Twisted Twin","classicon_mage")
	characterquests.charquestprintclass(count,datatree,openfile,47042,"Shadow: The Twisted Twin","classicon_priest")
	characterquests.charquestprintclass(count,datatree,openfile,47041,"Affliction: The Twisted Twin","classicon_warlock")
	characterquests.charquestprint(count,datatree,openfile,45185,"Message from the Shadows")
	characterquests.charquestprint(count,datatree,openfile,45187,"Secrets in the Underbelly")
	characterquests.charquestprint(count,datatree,openfile,45188,"The Wisdom of the Council")
	characterquests.charquestprint(count,datatree,openfile,45190,"Where it's Thinnest")
	characterquests.charquestprint(count,datatree,openfile,45192,"Runes of Rending")
	characterquests.charquestprint(count,datatree,openfile,45193,"One Step Behind")
	characterquests.charquestprint(count,datatree,openfile,45866,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,46127,"Thwarting the Twins")
	characterquests.charquestprint(count,datatree,openfile,45910,"Raest's Gift")
	characterquests.charquestheader(count,"Healing: Bradensbrook Investigation<div>Holy Priest, Holy Paladin, Mistweaver Monk, Restoration Druid, Restoration Shaman</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47004,"Restoration: The Bradensbrook Investigation","classicon_druid")
	characterquests.charquestprintclass(count,datatree,openfile,47005,"Mistweaver: The Bradensbrook Investigation","classicon_monk")
	characterquests.charquestprintclass(count,datatree,openfile,47006,"Holy: The Bradensbrook Investigation","classicon_paladin")
	characterquests.charquestprintclass(count,datatree,openfile,46078,"Holy: The Bradensbrook Investigation","classicon_priest")
	characterquests.charquestprintclass(count,datatree,openfile,47003,"Restoration: The Bradensbrook Investigation","classicon_shaman")
	characterquests.charquestprint(count,datatree,openfile,46079,"Aid on the Front Lines")
	characterquests.charquestprint(count,datatree,openfile,46080,"Quieting the Spirits")
	characterquests.charquestprint(count,datatree,openfile,46082,"Shadowsong's Return")
	characterquests.charquestprint(count,datatree,openfile,46106,"Cutting off the Heads")
	characterquests.charquestprint(count,datatree,openfile,46107,"Source of the Corruption")
	characterquests.charquestprint(count,datatree,openfile,46200,"The Matter Resolved... For Now...")
	characterquests.charquestprint(count,datatree,openfile,45864,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,46035,"End of the Risen Threat")
	characterquests.charquestprint(count,datatree,openfile,45906,"Jarod's Gift")
	characterquests.charquestheader(count,"Tank: Aid of the Illidari<div>Blood Death Knight, Vengeance Demon Hunter, Guardian Druid, Brewmaster Monk, Protection Paladin, Protection Warrior</div>",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,47025,"Blood: Aid of the Illidari","classicon_deathknight")
	characterquests.charquestprintclass(count,datatree,openfile,46314,"Vengeance: Seeking Kor'vas","classicon_demonhunter")
	characterquests.charquestprintclass(count,datatree,openfile,47023,"Guardian: Aid of the Illidari","classicon_druid")
	characterquests.charquestprintclass(count,datatree,openfile,47024,"Brewmaster: Aid of the Illidari","classicon_monk")
	characterquests.charquestprintclass(count,datatree,openfile,47022,"Protection: Aid of the Illidari","classicon_paladin")
	characterquests.charquestprintclass(count,datatree,openfile,45412,"Protection: Aid of the Illidari","classicon_warrior")
	characterquests.charquestprint(count,datatree,openfile,45413,"Gathering Information")
	characterquests.charquestprint(count,datatree,openfile,45414,"Confirming Suspicions")
	characterquests.charquestprint(count,datatree,openfile,45415,"Between Worlds")
	characterquests.charquestprint(count,datatree,openfile,45843,"Dark Omens")
	characterquests.charquestprint(count,datatree,openfile,45863,"A Gift From the Six")
	characterquests.charquestprint(count,datatree,openfile,45416,"The Highlord's Return")
	characterquests.charquestprint(count,datatree,openfile,45905,"Krull's Gift")
