import characterquests
from characterutil import *

def z_58_80_Hellfire_Peninsula(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,28705,"Warchief's Command: Outland!")
	characterquests.charquestprint(count,datatree,openfile,9407,"Through the Dark Portal")
	characterquests.charquestprint(count,datatree,openfile,10120,"Arrival in Outland")
	characterquests.charquestprint(count,datatree,openfile,10289,"Journey to Thrallmar")
	characterquests.charquestprint(count,datatree,openfile,10291,"Report to Nazgrel")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Thrallmar","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10121,"Eradicate the Burning Legion")
	characterquests.charquestprint(count,datatree,openfile,10123,"Felspark Ravine")
	characterquests.charquestprint(count,datatree,openfile,10124,"Forward Base: Reaver's Fall")
	characterquests.charquestprint(count,datatree,openfile,10208,"Disrupt Their Reinforcements")
	characterquests.charquestprint(count,datatree,openfile,10129,"Mission: Gateways Murketh and Shaadraz")
	characterquests.charquestprint(count,datatree,openfile,10162,"Mission: The Abyssal Shelf")
	characterquests.charquestprint(count,datatree,openfile,10388,"Return to Thrallmar")
	characterquests.charquestprint(count,datatree,openfile,10086,"I Work... For the Horde!")
	characterquests.charquestprint(count,datatree,openfile,10087,"Burn It Up... For the Horde!")
	characterquests.charquestheaderfaction(count,"58: Hellfire Peninsula: Thrallmar PvP","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10110,"Hellfire Fortifications")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Mag'har","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,9400,"The Assassin")
	characterquests.charquestprint(count,datatree,openfile,9401,"A Strange Weapon")
	characterquests.charquestprint(count,datatree,openfile,9405,"The Warchief's Mandate")
	characterquests.charquestprint(count,datatree,openfile,9410,"A Spirit Guide")
	characterquests.charquestprint(count,datatree,openfile,9406,"The Mag'har")
	characterquests.charquestprint(count,datatree,openfile,9442,"A Debilitating Sickness (Obsolete)")
	characterquests.charquestprint(count,datatree,openfile,9447,"Administering the Salve (Obsolete)")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Fel Orc Blood","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10450,"Bonechewer Blood")
	characterquests.charquestprint(count,datatree,openfile,10449,"Apothecary Zelana")
	characterquests.charquestprint(count,datatree,openfile,10242,"Spinebreaker Post")
	characterquests.charquestprint(count,datatree,openfile,10538,"Boiling Blood")
	characterquests.charquestprint(count,datatree,openfile,10835,"Apothecary Antonivich")
	characterquests.charquestprint(count,datatree,openfile,10864,"A Burden of Souls")
	characterquests.charquestprint(count,datatree,openfile,10838,"The Demoniac Scryer")
	characterquests.charquestprint(count,datatree,openfile,10875,"Report to Nazgrel")
	characterquests.charquestprint(count,datatree,openfile,10876,"The Foot of the Citadel")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Forge Camp: Mageddon","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10390,"Forge Camp: Mageddon")
	characterquests.charquestprint(count,datatree,openfile,10391,"Cannons of Rage")
	characterquests.charquestprint(count,datatree,openfile,10392,"Doorway to the Abyss")
	characterquests.charquestprint(count,datatree,openfile,10389,"The Agony and the Darkness")
	characterquests.charquestprint(count,datatree,openfile,10136,"Cruel's Intentions")
	characterquests.charquestprint(count,datatree,openfile,10393,"Vile Plans")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Spinebreaker Post: Honor the Fallen","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10220,"Make Them Listen")
	characterquests.charquestprint(count,datatree,openfile,10229,"Decipher the Tome")
	characterquests.charquestprint(count,datatree,openfile,10230,"The Battle Horn")
	characterquests.charquestprint(count,datatree,openfile,10250,"Bloody Vengeance")
	characterquests.charquestprint(count,datatree,openfile,10258,"Honor the Fallen")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Spinebreaker Post: Ogath the Mad","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10278,"The Warp Rifts")
	characterquests.charquestprint(count,datatree,openfile,10294,"Void Ridge")
	characterquests.charquestprint(count,datatree,openfile,10295,"From the Abyss")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Spinebreaker Post: Zeth'gor","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10792,"Zeth'Gor Must Burn!")
	characterquests.charquestprint(count,datatree,openfile,10809,"Wanted: Worg Master Kruush")
	characterquests.charquestprint(count,datatree,openfile,10813,"The Eyes of Grillok")
	characterquests.charquestprint(count,datatree,openfile,10834,"Grillok \"Darkeye\"")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Zeppelin","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,9345,"Preparing the Salve")
	characterquests.charquestprint(count,datatree,openfile,10213,"Investigate the Crash")
	characterquests.charquestprint(count,datatree,openfile,10161,"In Case of Emergency...")
	characterquests.charquestprint(count,datatree,openfile,9351,"Voidwalkers Gone Wild")
	characterquests.charquestprint(count,datatree,openfile,9349,"Ravager Egg Roundup")
	characterquests.charquestprint(count,datatree,openfile,9361,"Helboar, the Other White Meat")
	characterquests.charquestprint(count,datatree,openfile,9356,"Smooth as Butter")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Falcon Watch","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,9375,"The Road to Falcon Watch")
	characterquests.charquestprint(count,datatree,openfile,9498,"Falcon Watch")
	characterquests.charquestprint(count,datatree,openfile,9499,"Falcon Watch")
	characterquests.charquestprint(count,datatree,openfile,9340,"The Great Fissure")
	characterquests.charquestprint(count,datatree,openfile,9391,"Marking the Path")
	characterquests.charquestprint(count,datatree,openfile,9376,"A Pilgrim's Plight")
	characterquests.charquestprint(count,datatree,openfile,9381,"Trueflight Arrows")
	characterquests.charquestprint(count,datatree,openfile,9466,"Wanted: Blacktalon the Savage")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Falcon Watch: Arelion's Mistress","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,9374,"Arelion's Journal")
	characterquests.charquestprint(count,datatree,openfile,10286,"Arelion's Secret")
	characterquests.charquestprint(count,datatree,openfile,10287,"The Mistress Revealed")
	characterquests.charquestprint(count,datatree,openfile,9483,"Life's Finer Pleasures")
	characterquests.charquestprint(count,datatree,openfile,9472,"Arelion's Mistress")
	characterquests.charquestheader(count,"58-80: Hellfire Peninsula: Falcon Watch: Miscellaneous",openfile)
	characterquests.charquestprint(count,datatree,openfile,9397,"Birds of a Feather")
	characterquests.charquestprint(count,datatree,openfile,9366,"In Need of Felblood")
	characterquests.charquestprint(count,datatree,openfile,9370,"The Cleansing Must Be Stopped")
	characterquests.charquestprint(count,datatree,openfile,9387,"Source of the Corruption")
	characterquests.charquestprint(count,datatree,openfile,9396,"Magic of the Arakkoa")
	characterquests.charquestheaderfaction(count,"58-80: Hellfire Peninsula: Cenarion Post","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10442,"Helping the Cenarion Post")
	characterquests.charquestprint(count,datatree,openfile,9373,"Missing Missive")
	characterquests.charquestprint(count,datatree,openfile,9372,"Demonic Contamination")
	characterquests.charquestprint(count,datatree,openfile,10255,"Testing the Antidote")
	characterquests.charquestprint(count,datatree,openfile,10159,"Keep Thornfang Hill Clear!")
	characterquests.charquestprint(count,datatree,openfile,10132,"Colossal Menace")
	characterquests.charquestprint(count,datatree,openfile,10134,"Crimson Crystal Clue")
	characterquests.charquestprint(count,datatree,openfile,10349,"The Earthbinder")
	characterquests.charquestprint(count,datatree,openfile,10351,"Natural Remedies")
	characterquests.charquestprint(count,datatree,openfile,9912,"The Cenarion Expedition")
	characterquests.charquestheader(count,"58-80: Hellfire Peninsula: Neutral quest chains",openfile)
	characterquests.charquestheader(count,"58-80: Hellfire Peninsula: Outland Sucks!",openfile)
	characterquests.charquestprint(count,datatree,openfile,10236,"Outland Sucks!")
	characterquests.charquestprint(count,datatree,openfile,10238,"How to Serve Goblins")
	characterquests.charquestprint(count,datatree,openfile,10629,"Shizz Work")
	characterquests.charquestprint(count,datatree,openfile,10630,"Beneath Thrallmar")
	characterquests.charquestheader(count,"58-80: Hellfire Peninsula: Dreghood",openfile)
	characterquests.charquestprint(count,datatree,openfile,10403,"Naladu")
	characterquests.charquestprint(count,datatree,openfile,10367,"A Traitor Among Us")
	characterquests.charquestprint(count,datatree,openfile,10368,"The Dreghood Elders")
	characterquests.charquestprint(count,datatree,openfile,10369,"Arzeth's Demise")
	characterquests.charquestheader(count,"58-80: Hellfire Peninsula: Miscellaneous",openfile)
	characterquests.charquestprint(count,datatree,openfile,9418,"Avruu's Orb")

def z_60_80_Zangarmarsh(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"60-80: Zangarmarsh: Cenarion Refuge",openfile)
	characterquests.charquestprint(count,datatree,openfile,9912,"The Cenarion Expedition")
	characterquests.charquestprint(count,datatree,openfile,39180,"Warchief's Command: Zangarmarsh")
	characterquests.charquestprint(count,datatree,openfile,9895,"The Dying Balance")
	characterquests.charquestprint(count,datatree,openfile,9747,"The Umbrafen Tribe")
	characterquests.charquestprint(count,datatree,openfile,9788,"A Damp, Dark Place")
	characterquests.charquestprint(count,datatree,openfile,10096,"Saving the Sporeloks")
	characterquests.charquestprint(count,datatree,openfile,9894,"Safeguarding the Watchers")
	characterquests.charquestprint(count,datatree,openfile,9716,"Disturbance at Umbrafen Lake")
	characterquests.charquestprint(count,datatree,openfile,9718,"As the Crow Flies")
	characterquests.charquestprint(count,datatree,openfile,9720,"Balance Must Be Preserved")
	characterquests.charquestprint(count,datatree,openfile,9731,"Drain Schematics")
	characterquests.charquestprint(count,datatree,openfile,9724,"Warning the Cenarion Circle")
	characterquests.charquestprint(count,datatree,openfile,9732,"Return to the Marsh")
	characterquests.charquestprint(count,datatree,openfile,9876,"Failed Incursion (Obsolete)")
	characterquests.charquestprint(count,datatree,openfile,9817,"Leader of the Bloodscale")
	characterquests.charquestprint(count,datatree,openfile,9802,"Plants of Zangarmarsh")
	characterquests.charquestprint(count,datatree,openfile,9697,"Watcher Leesa'oh")
	characterquests.charquestprint(count,datatree,openfile,9957,"What's Wrong at Cenarion Thicket?")
	characterquests.charquestprint(count,datatree,openfile,9785,"Blessings of the Ancients")
	characterquests.charquestprint(count,datatree,openfile,9730,"Leader of the Darkcrest")
	characterquests.charquestprint(count,datatree,openfile,9778,"Warden Hamoot")
	characterquests.charquestprint(count,datatree,openfile,9728,"A Warm Welcome")
	characterquests.charquestheader(count,"60-80: Zangarmarsh: Cenarion Watchpost",openfile)
	characterquests.charquestprint(count,datatree,openfile,9701,"Observing the Sporelings")
	characterquests.charquestprint(count,datatree,openfile,9702,"A Question of Gluttony")
	characterquests.charquestprint(count,datatree,openfile,9708,"Familiar Fungi")
	characterquests.charquestprint(count,datatree,openfile,9709,"Stealing Back the Mushrooms")
	characterquests.charquestheader(count,"60-80: Zangarmarsh: Sporeggar",openfile)
	characterquests.charquestprint(count,datatree,openfile,9806,"Fertile Spores")
	characterquests.charquestprint(count,datatree,openfile,9808,"Glowcap Mushrooms")
	characterquests.charquestprint(count,datatree,openfile,9726,"Now That We're Friends...")
	characterquests.charquestprint(count,datatree,openfile,9729,"Fhwoor Smash!")
	characterquests.charquestprint(count,datatree,openfile,9739,"The Sporelings' Plight")
	characterquests.charquestprint(count,datatree,openfile,9743,"Natural Enemies")
	characterquests.charquestprint(count,datatree,openfile,9919,"Sporeggar")
	characterquests.charquestprint(count,datatree,openfile,9911,"The Count of the Marshes")
	characterquests.charquestheaderfaction(count,"60-80: Zangarmarsh: Swamprat Post","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,9899,"A Job Undone")
	characterquests.charquestprint(count,datatree,openfile,9773,"No More Mushrooms!")
	characterquests.charquestprint(count,datatree,openfile,9770,"Menacing Marshfangs")
	characterquests.charquestprint(count,datatree,openfile,9898,"Nothin' Says Lovin' Like a Big Stinger")
	characterquests.charquestprint(count,datatree,openfile,9796,"News from Zangarmarsh")
	characterquests.charquestprint(count,datatree,openfile,9775,"Report to Shadow Hunter Denjai")
	characterquests.charquestprint(count,datatree,openfile,9769,"There's No Explanation for Fashion")
	characterquests.charquestprint(count,datatree,openfile,9774,"Thick Hydra Scales")
	characterquests.charquestprint(count,datatree,openfile,9771,"Searching for Scout Jyoba")
	characterquests.charquestprint(count,datatree,openfile,9772,"Jyoba's Report")
	characterquests.charquestheaderfaction(count,"60-80: Zangarmarsh: Zabra'jin","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10105,"News for Rakoria")
	characterquests.charquestprint(count,datatree,openfile,9846,"Spirits of the Feralfen")
	characterquests.charquestprint(count,datatree,openfile,9847,"A Spirit Ally?")
	characterquests.charquestprint(count,datatree,openfile,9845,"Angling to Beat the Competition")
	characterquests.charquestprint(count,datatree,openfile,9904,"Pursuing Terrorclaw")
	characterquests.charquestprint(count,datatree,openfile,9903,"The Biggest of Them All")
	characterquests.charquestprint(count,datatree,openfile,9814,"Burstcap Mushrooms, Mon!")
	characterquests.charquestprint(count,datatree,openfile,9816,"Have You Ever Seen One of These?")
	characterquests.charquestprint(count,datatree,openfile,9797,"Reinforcements for Garadar")
	characterquests.charquestprint(count,datatree,openfile,9795,"The Ogre Threat")
	characterquests.charquestprint(count,datatree,openfile,9841,"Stinging the Stingers")
	characterquests.charquestprint(count,datatree,openfile,9842,"The Sharpest Blades")
	characterquests.charquestprint(count,datatree,openfile,9820,"WANTED: Boss Grog'ak")
	characterquests.charquestprint(count,datatree,openfile,9822,"Impending Attack")
	characterquests.charquestprint(count,datatree,openfile,9823,"Us or Them")
	characterquests.charquestprint(count,datatree,openfile,10117,"Wanted: Chieftain Mummaki")
	characterquests.charquestprint(count,datatree,openfile,10118,"Message to the Daggerfen")
	characterquests.charquestprint(count,datatree,openfile,9828,"Withered Basidium")
	characterquests.charquestheader(count,"60-80: Zangarmarsh: Umbrafen Village",openfile)
	characterquests.charquestprint(count,datatree,openfile,9752,"Escape from Umbrafen")

def z_62_80_Terokkar_Forest(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"62-80: Terrokar Forest",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,39188,"Hero's Call: Terokkar Forest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,39182,"Warchief's Command: Terokkar Forest","horde")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Shattrath",openfile)
	characterquests.charquestprint(count,datatree,openfile,10210,"A'dal")
	characterquests.charquestprint(count,datatree,openfile,10211,"City of Light")
	characterquests.charquestprint(count,datatree,openfile,10037,"Rather Be Fishin'")
	characterquests.charquestprint(count,datatree,openfile,10917,"The Outcast's Plight")
	characterquests.charquestprint(count,datatree,openfile,10180,"Can't Stay Away")
	characterquests.charquestprint(count,datatree,openfile,10847,"The Eyes of Skettis")
	characterquests.charquestprint(count,datatree,openfile,10849,"Seek Out Kirrik")
	characterquests.charquestprint(count,datatree,openfile,10839,"Veil Skith: Darkstone of Terokk")
	characterquests.charquestprint(count,datatree,openfile,10848,"Veil Rhaze: Unliving Evil")
	characterquests.charquestprint(count,datatree,openfile,10861,"Veil Lithic: Preemptive Strike")
	characterquests.charquestprint(count,datatree,openfile,10874,"Veil Shalas: Signal Fires")
	characterquests.charquestprint(count,datatree,openfile,10889,"Return to Shattrath")
	characterquests.charquestprint(count,datatree,openfile,10879,"The Skettis Offensive")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Cenarian Thicket",openfile)
	characterquests.charquestprint(count,datatree,openfile,9957,"What's Wrong at Cenarion Thicket?")
	characterquests.charquestprintfaction(count,datatree,openfile,9960,"What's Wrong at Cenarion Thicket?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9961,"What's Wrong at Cenarion Thicket?","alliance")
	characterquests.charquestprint(count,datatree,openfile,9968,"Strange Energy")
	characterquests.charquestprint(count,datatree,openfile,9971,"Clues in the Thicket")
	characterquests.charquestprint(count,datatree,openfile,9978,"By Any Means Necessary")
	characterquests.charquestprint(count,datatree,openfile,9979,"Wind Trader Lathrai")
	characterquests.charquestprint(count,datatree,openfile,10112,"A Personal Favor")
	characterquests.charquestprint(count,datatree,openfile,9990,"Investigate Tuurem")
	characterquests.charquestprint(count,datatree,openfile,9951,"It's Watching You!")
	characterquests.charquestprintfaction(count,datatree,openfile,9994,"What Are These Things?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9995,"What Are These Things?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10444,"Report to the Allerian Post","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10448,"Report to Stonebreaker Camp","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9996,"Attack on Firewing Point","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9997,"Attack on Firewing Point","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10446,"The Final Code","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10447,"The Final Code","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10005,"Letting Earthbinder Tavgren Know","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10006,"Letting Earthbinder Tavgren Know","horde")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Firewing Point",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,10051,"Escape from Firewing Point!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10052,"Escape from Firewing Point!","horde")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Bonechewer Ruins",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,10012,"Fel Orc Plans","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10013,"An Unseen Hand","horde")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Refugee Caravan",openfile)
	characterquests.charquestprint(count,datatree,openfile,10842,"Vengeful Souls")
	characterquests.charquestprint(count,datatree,openfile,10908,"Speak with Rilak the Redeemed")
	characterquests.charquestprintfaction(count,datatree,openfile,10863,"Secrets of the Arakkoa","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10862,"Surrender to the Horde","horde")
	characterquests.charquestprint(count,datatree,openfile,10896,"The Infested Protectors")
	characterquests.charquestprint(count,datatree,openfile,10878,"Before Darkness Falls")
	characterquests.charquestprint(count,datatree,openfile,10852,"Missing Friends")
	characterquests.charquestprint(count,datatree,openfile,10840,"The Tomb of Lights")
	characterquests.charquestprint(count,datatree,openfile,10030,"Recover the Bones")
	characterquests.charquestprint(count,datatree,openfile,10031,"Helping the Lost Find Their Way")
	characterquests.charquestprint(count,datatree,openfile,10880,"Cabal Orders")
	characterquests.charquestprint(count,datatree,openfile,10881,"The Shadow Tomb")
	characterquests.charquestprint(count,datatree,openfile,10887,"Escaping the Tomb")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Sha'tari Base Camp",openfile)
	characterquests.charquestprint(count,datatree,openfile,10922,"Digging Through Bones")
	characterquests.charquestprint(count,datatree,openfile,10929,"Fumping")
	characterquests.charquestprint(count,datatree,openfile,10930,"The Big Bone Worm")
	characterquests.charquestprint(count,datatree,openfile,10877,"The Dread Relic")
	characterquests.charquestprint(count,datatree,openfile,10923,"Evil Draws Near")
	characterquests.charquestprint(count,datatree,openfile,10913,"An Improper Burial")
	characterquests.charquestprint(count,datatree,openfile,10914,"A Hero Is Needed")
	characterquests.charquestprint(count,datatree,openfile,10915,"The Fallen Exarch")
	characterquests.charquestprint(count,datatree,openfile,10873,"Taken in the Night")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Netherweb Ridge",openfile)
	characterquests.charquestprint(count,datatree,openfile,10898,"Skywing")
	characterquests.charquestprint(count,datatree,openfile,10920,"For the Fallen")
	characterquests.charquestprint(count,datatree,openfile,10921,"Terokkarantula")
	characterquests.charquestprint(count,datatree,openfile,10926,"Return to Sha'tari Base Camp")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Auchindoun",openfile)
	characterquests.charquestprint(count,datatree,openfile,10227,"I See Dead Draenei")
	characterquests.charquestprint(count,datatree,openfile,10228,"Ezekiel")
	characterquests.charquestprint(count,datatree,openfile,10231,"What Book? I Don't See Any Book.")
	characterquests.charquestprint(count,datatree,openfile,10251,"The Master's Grand Design?")
	characterquests.charquestprint(count,datatree,openfile,10252,"Vision of the Dead")
	characterquests.charquestprint(count,datatree,openfile,10253,"Levixus the Soul Caller")
	characterquests.charquestprint(count,datatree,openfile,29595,"Everything Will Be Alright")
	characterquests.charquestprint(count,datatree,openfile,29596,"The End of the Exarch")
	characterquests.charquestheaderfaction(count,"62-80: Terrokar Forest: Stonebreaker Hold","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,10105,"News for Rakoria")
	characterquests.charquestprint(count,datatree,openfile,9993,"Olemba Seed Oil")
	characterquests.charquestprint(count,datatree,openfile,10201,"And Now, the Moment of Truth")
	characterquests.charquestprint(count,datatree,openfile,9987,"Stymying the Arakkoa")
	characterquests.charquestprint(count,datatree,openfile,10000,"An Unwelcome Presence")
	characterquests.charquestprint(count,datatree,openfile,10003,"The Firewing Liaison")
	characterquests.charquestprint(count,datatree,openfile,10008,"What Happens in Terokkar Stays in Terokkar")
	characterquests.charquestprint(count,datatree,openfile,10027,"Magical Disturbances")
	characterquests.charquestprint(count,datatree,openfile,10039,"Speak with Scout Neftis")
	characterquests.charquestprint(count,datatree,openfile,10041,"Who Are They?")
	characterquests.charquestprint(count,datatree,openfile,10043,"Kill the Shadow Council!")
	characterquests.charquestprint(count,datatree,openfile,10018,"Vestments of the Wolf Spirit")
	characterquests.charquestprint(count,datatree,openfile,10023,"Patriarch Ironjaw")
	characterquests.charquestprint(count,datatree,openfile,10791,"Welcoming the Wolf Spirit")
	characterquests.charquestprint(count,datatree,openfile,10034,"Wanted: Bonelashers Dead!")
	characterquests.charquestprint(count,datatree,openfile,10036,"Torgos!")
	characterquests.charquestprint(count,datatree,openfile,10868,"Arakkoa War Path")
	characterquests.charquestheaderfaction(count,"62-80: Terrokar Forest: Allerian Hold","alliance",openfile)
	characterquests.charquestprint(count,datatree,openfile,9992,"Olemba Seeds")
	characterquests.charquestprint(count,datatree,openfile,10028,"Vessels of Power")
	characterquests.charquestprint(count,datatree,openfile,10026,"Magical Disturbances")
	characterquests.charquestprint(count,datatree,openfile,10038,"Speak with Private Weeks")
	characterquests.charquestprint(count,datatree,openfile,10040,"Who Are They?")
	characterquests.charquestprint(count,datatree,openfile,10042,"Kill the Shadow Council!")
	characterquests.charquestprint(count,datatree,openfile,9998,"Unruly Neighbors")
	characterquests.charquestprint(count,datatree,openfile,10007,"Thinning the Ranks")
	characterquests.charquestprint(count,datatree,openfile,9986,"Stymying the Arakkoa")
	characterquests.charquestprint(count,datatree,openfile,10016,"Timber Worg Tails")
	characterquests.charquestprint(count,datatree,openfile,10022,"The Elusive Ironjaw")
	characterquests.charquestprint(count,datatree,openfile,10002,"The Firewing Liaison")
	characterquests.charquestprint(count,datatree,openfile,10869,"Thin the Flock")
	characterquests.charquestprint(count,datatree,openfile,10033,"Wanted: Bonelashers Dead!")
	characterquests.charquestprint(count,datatree,openfile,10035,"Torgos!")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Skettis",openfile)
	characterquests.charquestprint(count,datatree,openfile,11096,"Threat from Above")
	characterquests.charquestprint(count,datatree,openfile,11098,"To Skettis!")
	characterquests.charquestprint(count,datatree,openfile,11093,"Hungry Nether Rays")
	characterquests.charquestprint(count,datatree,openfile,11004,"World of Shadows")
	characterquests.charquestprint(count,datatree,openfile,11005,"Secrets of the Talonpriests")
	characterquests.charquestprint(count,datatree,openfile,11021,"Ishaal's Almanac")
	characterquests.charquestprint(count,datatree,openfile,11024,"An Ally in Lower City")
	characterquests.charquestprint(count,datatree,openfile,11028,"Countdown to Doom")
	characterquests.charquestprint(count,datatree,openfile,11056,"Hazzik's Bargain")
	characterquests.charquestprint(count,datatree,openfile,11029,"A Shabby Disguise")
	characterquests.charquestprint(count,datatree,openfile,11073,"Terokk's Downfall")
	characterquests.charquestheader(count,"62-80: Terrokar Forest: Rep",openfile)
	characterquests.charquestprint(count,datatree,openfile,10551,"Allegiance to the Aldor")
	characterquests.charquestprint(count,datatree,openfile,10554,"Ishanah")
	characterquests.charquestprint(count,datatree,openfile,10021,"Restoring the Light")
	characterquests.charquestprint(count,datatree,openfile,10017,"Strained Supplies")
	characterquests.charquestprint(count,datatree,openfile,10325,"Marks of Kil'jaeden")
	characterquests.charquestprint(count,datatree,openfile,10020,"A Cure for Zahlia")
	characterquests.charquestprint(count,datatree,openfile,10552,"Allegiance to the Scryers")
	characterquests.charquestprint(count,datatree,openfile,10412,"Firewing Signets")
	characterquests.charquestprint(count,datatree,openfile,10553,"Voren'thal the Seer")

def z_64_80_Nagrand(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"64-80: Nagrand: Breadcrumbs",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,39189,"Warchief's Command: Nagrand","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39197,"Hero's Call: Nagrand","alliance")
	characterquests.charquestheaderfaction(count,"64-80: Nagrand: Garadar","horde",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9888,"The Impotent Leader","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9889,"Don't Kill the Fat One","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9890,"Success!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9891,"Because Kilrath is a Coward","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9906,"Message in a Battle","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9907,"An Audacious Advance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10107,"Diplomatic Measures","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9910,"Standards and Practices","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9916,"Bleeding Hollow Supply Crates","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9935,"Wanted: Giselda the Crone","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9939,"Wanted: Zorbo the Advisor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9937,"Wanted: Durn the Hungerer","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9863,"Vile Idolatry","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9944,"Missing Mag\'hari Procession","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9945,"War on the Warmaul","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9946,"Cho\'war the Pillager","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9864,"The Missing War Party","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9865,"Once Were Warriors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9866,"He Will Walk The Earth...","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10479,"Proving Your Strength","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9867,"Murkblood Leaders...","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9872,"Murkblood Invaders","horde")
	characterquests.charquestheaderfaction(count,"64-80: Nagrand: Garadar: Finale","horde",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,10044,"A Visit With the Greatmother","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10045,"Material Components","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10081,"To Meet Mother Kashur","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10082,"The Agitated Ancestors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10085,"A Visit With The Ancestors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10101,"When Spirits Speak","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10102,"A Secret Revealed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10167,"Auchindoun...","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10168,"What the Soul Sees","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10170,"Return to the Greatmother","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10171,"The Inconsolable Chieftain","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10172,"There Is No Hope","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10175,"Thrall, Son of Durotan (Obsolete) ","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,10212,"Hero of the Mag\'har","horde")
	characterquests.charquestheader(count,"64-80: Nagrand: Throne of the Elements",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9869,"The Throne of the Elements","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9870,"The Throne of the Elements","horde")
	characterquests.charquestprint(count,datatree,openfile,9861,"The Howling Wind")
	characterquests.charquestprint(count,datatree,openfile,9862,"Murkblood Corrupters")
	characterquests.charquestprint(count,datatree,openfile,9800,"A Rare Bean")
	characterquests.charquestprint(count,datatree,openfile,9804,"Agitated Spirits of Skysong")
	characterquests.charquestprint(count,datatree,openfile,9805,"Blessing of Incineratus")
	characterquests.charquestprint(count,datatree,openfile,9810,"The Spirit Polluted")
	characterquests.charquestprint(count,datatree,openfile,9815,"Muck Diving")
	characterquests.charquestprint(count,datatree,openfile,9818,"The Underneath")
	characterquests.charquestprint(count,datatree,openfile,9819,"The Tortured Earth")
	characterquests.charquestprint(count,datatree,openfile,9821,"Eating Damnation")
	characterquests.charquestprint(count,datatree,openfile,9849,"Shattering the Veil")
	characterquests.charquestprint(count,datatree,openfile,9853,"Gurok the Usurper")
	characterquests.charquestprint(count,datatree,openfile,9852,"The Ultimate Bloodsport")
	characterquests.charquestheader(count,"64-80: Nagrand: Mag'hari Procession",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9948,"Finding the Survivors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,9879,"The Totem of Kar\'dash","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9868,"The Totem of Kar\'dash","horde")
	characterquests.charquestheader(count,"64-80: Nagrand: Nesingwary Safari",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,10113,"The Nesingwary Safari","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10114,"The Nesingwary Safari","horde")
	characterquests.charquestprint(count,datatree,openfile,9897,"I'm Saved!")
	characterquests.charquestprint(count,datatree,openfile,9857,"Talbuk Mastery")
	characterquests.charquestprint(count,datatree,openfile,9858,"Talbuk Mastery")
	characterquests.charquestprint(count,datatree,openfile,9859,"Talbuk Mastery")
	characterquests.charquestprint(count,datatree,openfile,9854,"Windroc Mastery")
	characterquests.charquestprint(count,datatree,openfile,9855,"Windroc Mastery")
	characterquests.charquestprint(count,datatree,openfile,9856,"Windroc Mastery")
	characterquests.charquestprint(count,datatree,openfile,9850,"Clefthoof Mastery")
	characterquests.charquestprint(count,datatree,openfile,9851,"Clefthoof Mastery")
	characterquests.charquestprint(count,datatree,openfile,9789,"Clefthoof Mastery")
	characterquests.charquestprint(count,datatree,openfile,9852,"The Ultimate Bloodsport")
	characterquests.charquestheader(count,"64-80: Nagrand: Burning Blade Ruins",openfile)
	characterquests.charquestprint(count,datatree,openfile,9928,"Armaments for Deception")
	characterquests.charquestprint(count,datatree,openfile,9927,"Ruthless Cunning")
	characterquests.charquestprint(count,datatree,openfile,9932,"Body of Evidence")
	characterquests.charquestprint(count,datatree,openfile,9931,"Returning the Favor")
	characterquests.charquestprintfaction(count,datatree,openfile,9933,"Message to Telaar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9934,"Message to Garadar","horde")
	characterquests.charquestheaderfaction(count,"64-80: Nagrand: Telaar","alliance",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9917,"Do My Eyes Deceive Me","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9918,"Not On My Watch!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9920,"Mo\'mor the Breaker","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9921,"The Ruins of Burning Blade","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9922,"The Twin Clefts of Nagrand","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10108,"Diplomatic Measures","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9936,"Wanted: Giselda the Crone","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9940,"Wanted: Zorbo the Advisor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9938,"Wanted: Durn the Hungerer","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9871,"Murkblood Invaders","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10476,"Fierce Enemies","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9923,"HELP!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9924,"Corki's Gone Missing Again!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9954,"Corki's Ransom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9955,"Cho'war the Pillager","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9956,"The Ravaged Caravan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9874,"Stopping the Spread","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9878,"Solving the Problem","alliance")
	characterquests.charquestheader(count,"64-80: Nagrand: Ring of Blood",openfile)
	characterquests.charquestprint(count,datatree,openfile,9962,"The Ring of Blood: Brokentoe")
	characterquests.charquestprint(count,datatree,openfile,9967,"The Ring of Blood: The Blue Brothers")
	characterquests.charquestprint(count,datatree,openfile,9970,"The Ring of Blood: Rokdar the Sundered Lord")
	characterquests.charquestprint(count,datatree,openfile,9972,"The Ring of Blood: Skra\'gath")
	characterquests.charquestprint(count,datatree,openfile,9973,"The Ring of Blood: The Warmaul Champion")
	characterquests.charquestprint(count,datatree,openfile,9977,"The Ring of Blood: The Final Challenge")
	characterquests.charquestheader(count,"64-80: Nagrand: Aeris Landing",openfile)
	characterquests.charquestprint(count,datatree,openfile,9913,"The Consortium Needs You!")
	characterquests.charquestprint(count,datatree,openfile,9914,"A Head Full of Ivory")
	characterquests.charquestprint(count,datatree,openfile,9925,"Matters of Security")
	characterquests.charquestprint(count,datatree,openfile,9900,"Gava\'xi")
	characterquests.charquestprint(count,datatree,openfile,9882,"Stealing from Thieves")
	characterquests.charquestprint(count,datatree,openfile,9893,"Obsidian Warbeads")
	characterquests.charquestheader(count,"64-80: Nagrand: Miscellaneous",openfile)
	characterquests.charquestprint(count,datatree,openfile,10111,"Bring Me The Egg!")
	characterquests.charquestprint(count,datatree,openfile,10109,"I Must Have Them!")
	characterquests.charquestprint(count,datatree,openfile,13799,"Where Are My Keys?")
	characterquests.charquestprint(count,datatree,openfile,13800,"Get My Keys!")
	characterquests.charquestheader(count,"64-80: Nagrand: Altruis the Sufferer",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9983,"He Called Himself Altruis...","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9982,"He Called Himself Altruis...","horde")
	characterquests.charquestprint(count,datatree,openfile,9991,"Survey the Land")
	characterquests.charquestprint(count,datatree,openfile,9999,"Buying Time")
	characterquests.charquestprint(count,datatree,openfile,10001,"The Master Planner")
	characterquests.charquestprint(count,datatree,openfile,10004,"Patience and Understanding")
	characterquests.charquestprint(count,datatree,openfile,10009,"Crackin' Some Skulls")
	characterquests.charquestprint(count,datatree,openfile,10010,"It's Just That Easy?")
	characterquests.charquestprint(count,datatree,openfile,10011,"Forge Camp: Annihilated")

def z_65_80_Blades_Edge_Mountains(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"65-80: Blades Edge Mountain",openfile)
	characterquests.charquestprint(count,datatree,openfile,10984,"Speak with the Ogre")
	characterquests.charquestprint(count,datatree,openfile,10983,"Mog'dorg the Wizened")
	characterquests.charquestprint(count,datatree,openfile,10989,"Mog'dorg the Wizened")
	characterquests.charquestprint(count,datatree,openfile,10615,"Ruuan Weald")
	characterquests.charquestprint(count,datatree,openfile,10618,"The Softest Wings")
	characterquests.charquestprint(count,datatree,openfile,10565,"The Stones of Vekh'nir")
	characterquests.charquestprint(count,datatree,openfile,10566,"Trial and Error")
	characterquests.charquestprint(count,datatree,openfile,10567,"Creating the Pendant")
	characterquests.charquestprint(count,datatree,openfile,10617,"Silkwing Cocoons")
	characterquests.charquestprint(count,datatree,openfile,10584,"Picking Up Some Power Converters")
	characterquests.charquestprint(count,datatree,openfile,10657,"Ride the Lightning")
	characterquests.charquestprint(count,datatree,openfile,10674,"Trapping the Light Fantastic")
	characterquests.charquestprint(count,datatree,openfile,10682,"A Time for Negotiation...")
	characterquests.charquestprint(count,datatree,openfile,10713,"...and a Time for Action")
	characterquests.charquestprint(count,datatree,openfile,10717,"Poaching from Poachers")
	characterquests.charquestprint(count,datatree,openfile,10719,"Did You Get The Note?")
	characterquests.charquestprint(count,datatree,openfile,10753,"Culling the Wild")
	characterquests.charquestprint(count,datatree,openfile,10770,"Little Embers")
	characterquests.charquestprint(count,datatree,openfile,10771,"From the Ashes")
	characterquests.charquestprint(count,datatree,openfile,10846,"Understanding the Mok'Nathal")
	characterquests.charquestprint(count,datatree,openfile,10851,"The Totems of My Enemy")
	characterquests.charquestprint(count,datatree,openfile,10853,"Spirit Calling")
	characterquests.charquestprint(count,datatree,openfile,10860,"Mok'Nathal Treats")
	characterquests.charquestprint(count,datatree,openfile,11036,"Out of This World Produce!")
	characterquests.charquestprint(count,datatree,openfile,11040,"Parts for the Rocket-Chief")
	characterquests.charquestprint(count,datatree,openfile,11043,"Building a Better Gryphon")
	characterquests.charquestprint(count,datatree,openfile,11047,"The Apprentice's Request")
	characterquests.charquestprint(count,datatree,openfile,10675,"Show Them Gnome Mercy!")
	characterquests.charquestprint(count,datatree,openfile,10810,"Damaged Mask")
	characterquests.charquestprint(count,datatree,openfile,10812,"Mystery Mask")
	characterquests.charquestprint(count,datatree,openfile,10819,"Felsworn Gas Mask")
	characterquests.charquestprint(count,datatree,openfile,10820,"Deceive thy Enemy")
	characterquests.charquestprint(count,datatree,openfile,10821,"You're Fired!")
	characterquests.charquestprint(count,datatree,openfile,10843,"Since Time Forgotten...")
	characterquests.charquestprint(count,datatree,openfile,10845,"Slay the Brood Mother")
	characterquests.charquestprint(count,datatree,openfile,10974,"Stasis Chambers of Bash'ir")
	characterquests.charquestprint(count,datatree,openfile,10976,"The Mark of the Nexus-King")
	characterquests.charquestprint(count,datatree,openfile,10982,"The Eye of Haramad")
	characterquests.charquestprint(count,datatree,openfile,10995,"Grulloc Has Two Skulls")
	characterquests.charquestprint(count,datatree,openfile,10996,"Maggoc's Treasure Chest")
	characterquests.charquestprint(count,datatree,openfile,10998,"Grim(oire) Business")
	characterquests.charquestprint(count,datatree,openfile,11000,"Into the Soulgrinder")
	characterquests.charquestprint(count,datatree,openfile,11009,"Ogre Heaven")
	characterquests.charquestprint(count,datatree,openfile,11010,"Bombing Run")
	characterquests.charquestprint(count,datatree,openfile,11025,"The Crystals")
	characterquests.charquestprint(count,datatree,openfile,11026,"Banish the Demons")
	characterquests.charquestprint(count,datatree,openfile,11030,"Our Boy Wants To Be A Skyguard Ranger")
	characterquests.charquestprint(count,datatree,openfile,11057,"The Trouble Below")
	characterquests.charquestprint(count,datatree,openfile,11058,"An Apexis Relic")
	characterquests.charquestprint(count,datatree,openfile,11059,"Guardian of the Monument")
	characterquests.charquestprint(count,datatree,openfile,11061,"A Father's Duty")
	characterquests.charquestprint(count,datatree,openfile,11062,"The Skyguard Outpost")
	characterquests.charquestprint(count,datatree,openfile,11065,"Wrangle Some Aether Rays!")
	characterquests.charquestprint(count,datatree,openfile,11078,"To Rule The Skies")
	characterquests.charquestprint(count,datatree,openfile,11079,"A Fel Whip For Gahk")
	characterquests.charquestprint(count,datatree,openfile,11091,"A Special Thank You")
	characterquests.charquestprint(count,datatree,openfile,11102,"Bombing Run")
	characterquests.charquestprint(count,datatree,openfile,11119,"Assault on Bash'ir Landing!")

def z_67_80_Netherstorm(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"67-80: Netherstorm",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,11042,"A Mystifying Vision","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,11037,"A Strange Vision","horde")
	characterquests.charquestprint(count,datatree,openfile,11039,"Report to Spymaster Thalodien")
	characterquests.charquestprint(count,datatree,openfile,11038,"Assist Exarch Orelis")
	characterquests.charquestprint(count,datatree,openfile,39201,"Warchief's Command: Netherstorm")
	characterquests.charquestprint(count,datatree,openfile,39202,"Hero's Call: Netherstorm")
	characterquests.charquestprint(count,datatree,openfile,10173,"The Archmage's Staff")
	characterquests.charquestprint(count,datatree,openfile,10174,"Curse of the Violet Tower")
	characterquests.charquestprint(count,datatree,openfile,10176,"Ar'kelos the Guardian")
	characterquests.charquestprint(count,datatree,openfile,10182,"Battle-Mage Dathric")
	characterquests.charquestprint(count,datatree,openfile,10183,"Off To Area 52")
	characterquests.charquestprint(count,datatree,openfile,10184,"Malevolent Remnants")
	characterquests.charquestprint(count,datatree,openfile,10185,"A Fate Worse Than Death")
	characterquests.charquestprint(count,datatree,openfile,10186,"You're Hired!")
	characterquests.charquestprint(count,datatree,openfile,10189,"Manaforge B'naar")
	characterquests.charquestprint(count,datatree,openfile,10190,"Recharging the Batteries")
	characterquests.charquestprint(count,datatree,openfile,10191,"Mark V is Alive!")
	characterquests.charquestprint(count,datatree,openfile,10193,"High Value Targets")
	characterquests.charquestprint(count,datatree,openfile,10194,"Stealth Flight")
	characterquests.charquestprint(count,datatree,openfile,10197,"A Convincing Disguise")
	characterquests.charquestprint(count,datatree,openfile,10198,"Information Gathering")
	characterquests.charquestprint(count,datatree,openfile,10199,"That Little Extra Kick")
	characterquests.charquestprint(count,datatree,openfile,10200,"Return to Thalodien")
	characterquests.charquestprint(count,datatree,openfile,10204,"Bloodgem Crystals")
	characterquests.charquestprint(count,datatree,openfile,10206,"Pick Your Part")
	characterquests.charquestprint(count,datatree,openfile,10221,"Dr. Boom!")
	characterquests.charquestprint(count,datatree,openfile,10224,"Essence for the Engines")
	characterquests.charquestprint(count,datatree,openfile,10225,"Report to Engineering")
	characterquests.charquestprint(count,datatree,openfile,10226,"Elemental Power Extraction")
	characterquests.charquestprint(count,datatree,openfile,10241,"Distraction at Manaforge B'naar")
	characterquests.charquestprint(count,datatree,openfile,10243,"Naaru Technology")
	characterquests.charquestprint(count,datatree,openfile,10245,"B'naar Console Transcription")
	characterquests.charquestprint(count,datatree,openfile,10246,"Attack on Manaforge Coruu")
	characterquests.charquestprint(count,datatree,openfile,10261,"Wanted: Annihilator Servo!")
	characterquests.charquestprint(count,datatree,openfile,10262,"A Heap of Ethereals")
	characterquests.charquestprint(count,datatree,openfile,10299,"Shutting Down Manaforge B'naar")
	characterquests.charquestprint(count,datatree,openfile,10309,"It's a Fel Reaver, But with Heart")
	characterquests.charquestprint(count,datatree,openfile,10313,"Measuring Warp Energies")
	characterquests.charquestprint(count,datatree,openfile,10329,"Shutting Down Manaforge B'naar")
	characterquests.charquestprint(count,datatree,openfile,10342,"Securing the Shaleskin Shale")
	characterquests.charquestprint(count,datatree,openfile,10417,"Run a Diagnostic!")
	characterquests.charquestprint(count,datatree,openfile,10418,"Deal With the Saboteurs")
	characterquests.charquestprint(count,datatree,openfile,10701,"Breaking Down Netherock")
	characterquests.charquestprint(count,datatree,openfile,10188,"The Sigil of Krasus")
	characterquests.charquestprint(count,datatree,openfile,10192,"Krasus's Compendium")
	characterquests.charquestprint(count,datatree,openfile,10203,"Invaluable Asset Zapping")
	characterquests.charquestprint(count,datatree,openfile,10205,"Warp-Raider Nesaad")
	characterquests.charquestprint(count,datatree,openfile,10209,"Summoner Kanthin's Prize")
	characterquests.charquestprint(count,datatree,openfile,10222,"The Sunfury Garrison")
	characterquests.charquestprint(count,datatree,openfile,10232,"In A Scrap With The Legion")
	characterquests.charquestprint(count,datatree,openfile,10234,"One Demon's Trash...")
	characterquests.charquestprint(count,datatree,openfile,10235,"Declawing Doomclaw")
	characterquests.charquestprint(count,datatree,openfile,10237,"Warn Area 52!")
	characterquests.charquestprint(count,datatree,openfile,10239,"Potential Energy Source")
	characterquests.charquestprint(count,datatree,openfile,10240,"Building a Perimeter")
	characterquests.charquestprint(count,datatree,openfile,10247,"Doctor Vomisa, Ph.T.")
	characterquests.charquestprint(count,datatree,openfile,10248,"You, Robot")
	characterquests.charquestprint(count,datatree,openfile,10249,"Back to the Chief!")
	characterquests.charquestprint(count,datatree,openfile,10256,"Finding the Keymaster")
	characterquests.charquestprint(count,datatree,openfile,10265,"Consortium Crystal Collection")
	characterquests.charquestprint(count,datatree,openfile,10266,"Request for Assistance")
	characterquests.charquestprint(count,datatree,openfile,10267,"Rightful Repossession")
	characterquests.charquestprint(count,datatree,openfile,10268,"An Audience with the Prince")
	characterquests.charquestprint(count,datatree,openfile,10269,"Triangulation Point One")
	characterquests.charquestprint(count,datatree,openfile,10293,"Hitting the Motherlode")
	characterquests.charquestprint(count,datatree,openfile,10300,"Rebuilding the Staff")
	characterquests.charquestprint(count,datatree,openfile,10301,"Unlocking the Compendium")
	characterquests.charquestprint(count,datatree,openfile,10305,"Abjurist Belmara")
	characterquests.charquestprint(count,datatree,openfile,10307,"Cohlien Frostweaver")
	characterquests.charquestprint(count,datatree,openfile,10312,"The Annals of Kirin'Var")
	characterquests.charquestprint(count,datatree,openfile,10314,"A Lingering Suspicion")
	characterquests.charquestprint(count,datatree,openfile,10316,"Searching for Evidence")
	characterquests.charquestprint(count,datatree,openfile,10319,"Capturing the Phylactery")
	characterquests.charquestprint(count,datatree,openfile,10320,"Destroy Naberius!")
	characterquests.charquestprint(count,datatree,openfile,10321,"Shutting Down Manaforge Coruu")
	characterquests.charquestprint(count,datatree,openfile,10330,"Shutting Down Manaforge Coruu")
	characterquests.charquestprint(count,datatree,openfile,10331,"Indispensable Tools")
	characterquests.charquestprint(count,datatree,openfile,10332,"Master Smith Rhonsus")
	characterquests.charquestprint(count,datatree,openfile,10333,"Help Mama Wheeler")
	characterquests.charquestprint(count,datatree,openfile,10334,"Needs More Cowbell")
	characterquests.charquestprint(count,datatree,openfile,10337,"When the Cows Come Home")
	characterquests.charquestprint(count,datatree,openfile,10343,"The Unending Invasion")
	characterquests.charquestprint(count,datatree,openfile,10348,"New Opportunities")
	characterquests.charquestprint(count,datatree,openfile,10423,"To the Stormspire")
	characterquests.charquestprint(count,datatree,openfile,10424,"Diagnosis: Critical")
	characterquests.charquestprint(count,datatree,openfile,10426,"Flora of the Eco-Domes")
	characterquests.charquestprint(count,datatree,openfile,10427,"Creatures of the Eco-Domes")
	characterquests.charquestprint(count,datatree,openfile,10429,"When Nature Goes Too Far")
	characterquests.charquestprint(count,datatree,openfile,10430,"Testing the Prototype")
	characterquests.charquestprint(count,datatree,openfile,10433,"Keeping Up Appearances")
	characterquests.charquestprint(count,datatree,openfile,10434,"The Dynamic Duo")
	characterquests.charquestprint(count,datatree,openfile,10435,"Retrieving the Goods")
	characterquests.charquestprint(count,datatree,openfile,10436,"All Clear!")
	characterquests.charquestprint(count,datatree,openfile,10440,"Success!")
	characterquests.charquestprint(count,datatree,openfile,10652,"Behind Enemy Lines")
	characterquests.charquestprint(count,datatree,openfile,10855,"Fel Reavers, No Thanks!")
	characterquests.charquestprint(count,datatree,openfile,10856,"The Best Defense")
	characterquests.charquestprint(count,datatree,openfile,10857,"Teleport This!")
	characterquests.charquestprint(count,datatree,openfile,10924,"Bloody Imp-ossible!")
	characterquests.charquestprint(count,datatree,openfile,10257,"Capturing the Keystone")
	characterquests.charquestprint(count,datatree,openfile,10270,"A Not-So-Modest Proposal")
	characterquests.charquestprint(count,datatree,openfile,10271,"Getting Down to Business")
	characterquests.charquestprint(count,datatree,openfile,10272,"A Promising Start")
	characterquests.charquestprint(count,datatree,openfile,10273,"Troublesome Distractions")
	characterquests.charquestprint(count,datatree,openfile,10274,"Securing the Celestial Ridge")
	characterquests.charquestprint(count,datatree,openfile,10275,"Triangulation Point Two")
	characterquests.charquestprint(count,datatree,openfile,10276,"Full Triangle")
	characterquests.charquestprint(count,datatree,openfile,10281,"Formal Introductions")
	characterquests.charquestprint(count,datatree,openfile,10290,"In Search of Farahlite")
	characterquests.charquestprint(count,datatree,openfile,10335,"Surveying the Ruins")
	characterquests.charquestprint(count,datatree,openfile,10336,"The Minions of Culuthas")
	characterquests.charquestprint(count,datatree,openfile,10339,"The Ethereum")
	characterquests.charquestprint(count,datatree,openfile,10345,"The Flesh Lies...")
	characterquests.charquestprint(count,datatree,openfile,10353,"Arconus the Insatiable")
	characterquests.charquestprint(count,datatree,openfile,10384,"Ethereum Data")
	characterquests.charquestprint(count,datatree,openfile,10385,"Potential for Brain Damage = High")
	characterquests.charquestprint(count,datatree,openfile,10405,"S-A-B-O-T-A-G-E")
	characterquests.charquestprint(count,datatree,openfile,10406,"Delivering the Message")
	characterquests.charquestprint(count,datatree,openfile,10408,"Nexus-King Salhadaar")
	characterquests.charquestprint(count,datatree,openfile,10411,"Electro-Shock Goodness!")
	characterquests.charquestprint(count,datatree,openfile,10422,"Captain Tyralius")
	characterquests.charquestprint(count,datatree,openfile,10437,"Recipe for Destruction")
	characterquests.charquestprint(count,datatree,openfile,10438,"On Nethery Wings")
	characterquests.charquestprint(count,datatree,openfile,10439,"Dimensius the All-Devouring")
	characterquests.charquestprint(count,datatree,openfile,10969,"Seek Out Ameer")
	characterquests.charquestprint(count,datatree,openfile,10970,"A Mission of Mercy")
	characterquests.charquestprint(count,datatree,openfile,10971,"Ethereum Secrets")
	characterquests.charquestprint(count,datatree,openfile,10973,"A Thousand Worlds")

def z_67_80_Shadowmoon_Valley(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"67: Shadowmoon Valley",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,11044,"Visions of Destruction","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,11048,"Kroghan\'s Report","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,11045,"Zorus the Judicator","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,11046,"Chief Apothecary Hildagard","horde")
	characterquests.charquestheader(count,"70: Shadowmoon Valley/Nagrand: Altruis the Sufferer",openfile)
	characterquests.charquestprint(count,datatree,openfile,10640,"Altruis (Aldor)")
	characterquests.charquestprint(count,datatree,openfile,10689,"Altruis (Scryers)")
	characterquests.charquestprint(count,datatree,openfile,10641,"Against the Legion")
	characterquests.charquestprint(count,datatree,openfile,10668,"Against the Illidari")
	characterquests.charquestprint(count,datatree,openfile,10669,"Against All Odds")
	characterquests.charquestprint(count,datatree,openfile,10646,"Illidan's Pupil")
	characterquests.charquestprint(count,datatree,openfile,10649,"The Book of Fel Names")
	characterquests.charquestprint(count,datatree,openfile,10650,"Return to the Aldor")
	characterquests.charquestprint(count,datatree,openfile,10691,"Return to the Scryers")
	characterquests.charquestprint(count,datatree,openfile,10651,"Varedis Must Be Stopped (Aldor)")
	characterquests.charquestprint(count,datatree,openfile,10692,"Varedis Must Be Stopped (Scryers)")
	characterquests.charquestheader(count,"67-80: Shadowmoon Valley (Unsorted)",openfile)
	characterquests.charquestprint(count,datatree,openfile,10562,"Besieged!")
	characterquests.charquestprint(count,datatree,openfile,10563,"To Legion Hold")
	characterquests.charquestprint(count,datatree,openfile,10564,"Blast the Infernals!")
	characterquests.charquestprint(count,datatree,openfile,10572,"Setting Up the Bomb")
	characterquests.charquestprint(count,datatree,openfile,10582,"Minions of the Shadow Council")
	characterquests.charquestprint(count,datatree,openfile,10595,"Besieged!")
	characterquests.charquestprint(count,datatree,openfile,10596,"To Legion Hold")
	characterquests.charquestprint(count,datatree,openfile,10597,"Setting Up the Bomb")
	characterquests.charquestprint(count,datatree,openfile,10598,"Blast the Infernals!")
	characterquests.charquestprint(count,datatree,openfile,10599,"The Deathforge")
	characterquests.charquestprint(count,datatree,openfile,10600,"Minions of the Shadow Council")
	characterquests.charquestprint(count,datatree,openfile,10624,"A Haunted History")
	characterquests.charquestprint(count,datatree,openfile,10625,"Spectrecles")
	characterquests.charquestprint(count,datatree,openfile,10660,"What Strange Creatures...")
	characterquests.charquestprint(count,datatree,openfile,10672,"Frankly, It Makes No Sense...")
	characterquests.charquestprint(count,datatree,openfile,10702,"A Grunt's Work...")
	characterquests.charquestprint(count,datatree,openfile,10759,"Find the Deserter")
	characterquests.charquestprint(count,datatree,openfile,10760,"The Sketh'lon Wreckage")
	characterquests.charquestprint(count,datatree,openfile,10761,"Find the Deserter")
	characterquests.charquestprint(count,datatree,openfile,10777,"Asghar's Totem")
	characterquests.charquestprint(count,datatree,openfile,10451,"Escape from Coilskar Cistern")
	characterquests.charquestprint(count,datatree,openfile,10633,"Teron Gorefiend - Lore and Legend")
	characterquests.charquestprint(count,datatree,openfile,10804,"Kindness")
	characterquests.charquestprint(count,datatree,openfile,10811,"Seek Out Neltharaku")
	characterquests.charquestprint(count,datatree,openfile,10814,"Neltharaku's Tale")
	characterquests.charquestprint(count,datatree,openfile,10824,"Sunfury Signets")
	characterquests.charquestprint(count,datatree,openfile,10836,"Infiltrating Dragonmaw Fortress")
	characterquests.charquestprint(count,datatree,openfile,10837,"To Netherwing Ledge!")
	characterquests.charquestprint(count,datatree,openfile,10854,"The Force of Neltharaku")
	characterquests.charquestprint(count,datatree,openfile,10858,"Karynaku")
	characterquests.charquestprint(count,datatree,openfile,10866,"Zuluhed the Whacked")
	characterquests.charquestprint(count,datatree,openfile,10870,"Ally of the Netherwing")
	characterquests.charquestprint(count,datatree,openfile,10871,"Ally of the Netherwing")
	characterquests.charquestprint(count,datatree,openfile,10872,"Zuluhed the Whacked")
	characterquests.charquestprint(count,datatree,openfile,11012,"Blood Oath of the Netherwing")
	characterquests.charquestprint(count,datatree,openfile,11013,"In Service of the Illidari")
	characterquests.charquestprint(count,datatree,openfile,11014,"Enter the Taskmaster")
	characterquests.charquestprint(count,datatree,openfile,11019,"Your Friend On The Inside")
	characterquests.charquestprint(count,datatree,openfile,11041,"A Job Unfinished...")
	characterquests.charquestprint(count,datatree,openfile,11049,"The Great Netherwing Egg Hunt")
	characterquests.charquestprint(count,datatree,openfile,11053,"Rise, Overseer!")
	characterquests.charquestprint(count,datatree,openfile,11054,"Overseeing and You: Making the Right Choices")
	characterquests.charquestprint(count,datatree,openfile,11063,"Earning Your Wings...")
	characterquests.charquestprint(count,datatree,openfile,11064,"Dragonmaw Race: The Ballad of Oldie McOld")
	characterquests.charquestprint(count,datatree,openfile,11067,"Dragonmaw Race: Trope the Filth-Belcher")
	characterquests.charquestprint(count,datatree,openfile,11068,"Dragonmaw Race: Corlok the Vet")
	characterquests.charquestprint(count,datatree,openfile,11069,"Dragonmaw Race: Wing Commander Ichman")
	characterquests.charquestprint(count,datatree,openfile,11070,"Dragonmaw Race: Wing Commander Mulverick")
	characterquests.charquestprint(count,datatree,openfile,11071,"Dragonmaw Race: Captain Skyshatter")
	characterquests.charquestprint(count,datatree,openfile,11075,"The Netherwing Mines")
	characterquests.charquestprint(count,datatree,openfile,11081,"The Great Murkblood Revolt")
	characterquests.charquestprint(count,datatree,openfile,11082,"Seeker of Truth")
	characterquests.charquestprint(count,datatree,openfile,11083,"Crazed and Confused")
	characterquests.charquestprint(count,datatree,openfile,11084,"Stand Tall, Captain!")
	characterquests.charquestprint(count,datatree,openfile,11089,"The Soul Cannon of Reth'hedron")
	characterquests.charquestprint(count,datatree,openfile,11090,"Subdue the Subduer")
	characterquests.charquestprint(count,datatree,openfile,11092,"Hail, Commander!")
	characterquests.charquestprint(count,datatree,openfile,11094,"Kill Them All!")
	characterquests.charquestprint(count,datatree,openfile,11095,"Commander Hobb")
	characterquests.charquestprint(count,datatree,openfile,11099,"Kill Them All!")
	characterquests.charquestprint(count,datatree,openfile,11100,"Commander Arcus")
	characterquests.charquestprint(count,datatree,openfile,11107,"Bow to the Highlord")
	characterquests.charquestprint(count,datatree,openfile,11108,"Lord Illidan Stormrage")

def z_70_Isle_Of_Queldanas(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"70: Isle of Quel'Danas",openfile)
	characterquests.charquestprint(count,datatree,openfile,11554,"A Friend in the Frontlines")
	characterquests.charquestprint(count,datatree,openfile,11555,"Honored by Your Allies")
	characterquests.charquestprint(count,datatree,openfile,11556,"Revered in the Field of Battle")
	characterquests.charquestprint(count,datatree,openfile,11557,"Exalted Among All Combatants")
	characterquests.charquestprint(count,datatree,openfile,11549,"A Magnanimous Benefactor")
