import characterquests
from characterutil import *

def dungeons(count,datatree,openfile):
	characterquests.charquestheader(count,"Ragefire Chasm",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,30969,"A New Enemy","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,30983,"The Dark","horde","class_shaman")
	characterquests.charquestprintfaction(count,datatree,openfile,30984,"No Orc Left Behind","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30995,"No Man Left Behind","alliance")
	characterquests.charquestprintfactionclass(count,datatree,openfile,30996,"The Dark","alliance","class_shaman")
	characterquests.charquestprintfaction(count,datatree,openfile,30998,"A New Enemy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31034,"Enemies Below","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31036,"Enemies Below","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31037,"Enemies Below","horde")
	characterquests.charquestheader(count,"The Deadmines",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27756,"The Foreman","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27758,"The Carpenter","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27781,"The Machination","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27785,"The Admiral","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27790,"The Defias Kingpin","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27842,"Only the Beginning","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27844,"Traitors!!!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27847,"Not Quite There","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27848,"Good Intentions...Poor Execution","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27850,"The Defias Kingpin","horde")
	characterquests.charquestheader(count,"Wailing Caverns",openfile)
	characterquests.charquestprint(count,datatree,openfile,26870,"Cleansing the Caverns")
	characterquests.charquestprint(count,datatree,openfile,26872,"Deviate Hides")
	characterquests.charquestprint(count,datatree,openfile,26873,"Preemptive Methods")
	characterquests.charquestprintfaction(count,datatree,openfile,26878,"Disciples of Naralex","horde")
	characterquests.charquestheader(count,"Shadowfang Keep",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27917,"Sniffing Them Out","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27920,"Armored to the Teeth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27921,"Fighting Tooth and Claw","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27968,"Fury of the Pack","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27974,"This Land is Our Land","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27988,"Plague...Plague Everywhere!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27996,"Orders Are For the Living","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27998,"Sweet, Merciless Revenge","horde")
	characterquests.charquestheader(count,"The Stockade",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27733,"The Good Ol' Switcheroo","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27737,"By Fire Be Saved!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27739,"The Gnoll King","alliance")
	characterquests.charquestheader(count,"Blackfathom Deeps",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,26897,"Blackfathom Deeps","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34672,"The Rise of Aku'mai","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34673,"The Rise of Aku'mai","horde")
	characterquests.charquestheader(count,"Gnomeregan",openfile)
	characterquests.charquestprint(count,datatree,openfile,2945,"Grime-Encrusted Ring")
	characterquests.charquestprintfaction(count,datatree,openfile,2947,"Return of the Ring","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2949,"Return of the Ring","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26939,"The G-Team","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26941,"The G-Team","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26942,"The G-Team","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26943,"Home Sweet Gnome","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26944,"Exploring Gnomeregan","alliance")
	characterquests.charquestheader(count,"26: Scarlet Halls",openfile)
	characterquests.charquestprint(count,datatree,openfile,31490,"Rank and File")
	characterquests.charquestprint(count,datatree,openfile,31493,"Just for Safekeeping, Of Course")
	characterquests.charquestheader(count,"90: Scarlet Halls",openfile)
	characterquests.charquestprint(count,datatree,openfile,31495,"Rank and File")
	characterquests.charquestprint(count,datatree,openfile,31497,"Just for Safekeeping, Of Course")
	characterquests.charquestheader(count,"26: Scarlet Monastery",openfile)
	characterquests.charquestprint(count,datatree,openfile,31513,"Blades of the Anointed")
	characterquests.charquestprint(count,datatree,openfile,31514,"Unto Dust Thou Shalt Return")
	characterquests.charquestheader(count,"90: Scarlet Monastery",openfile)
	characterquests.charquestprint(count,datatree,openfile,31515,"Blades of the Anointed")
	characterquests.charquestprint(count,datatree,openfile,31516,"Unto Dust Thou Shalt Return")
	characterquests.charquestheader(count,"Razorfen Kraul",openfile)
	characterquests.charquestprint(count,datatree,openfile,26901,"Going, Going, Guano!")
	characterquests.charquestprint(count,datatree,openfile,26905,"Agamaggan's Charge")
	characterquests.charquestprint(count,datatree,openfile,26906,"Agamaggan")
	characterquests.charquestprint(count,datatree,openfile,26907,"Take Them Down!")
	characterquests.charquestprint(count,datatree,openfile,26908,"Feeling Thorny")
	characterquests.charquestheader(count,"Maraudon",openfile)
	characterquests.charquestprint(count,datatree,openfile,27697,"Corruption in Maraudon")
	characterquests.charquestprint(count,datatree,openfile,27698,"Servants of Theradras")
	characterquests.charquestprint(count,datatree,openfile,27692,"Princess Theradras")
	characterquests.charquestheader(count,"Uldaman",openfile)
	characterquests.charquestprint(count,datatree,openfile,2278,"The Platinum Discs")
	characterquests.charquestprint(count,datatree,openfile,2280,"The Platinum Discs")
	characterquests.charquestprintfaction(count,datatree,openfile,27672,"The Chamber of Khaz'mul","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27673,"It's What's Inside That Counts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27676,"Behind Closed Doors","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27677,"Archaedas, The Ancient Stone Watcher","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27679,"The Chamber of Khaz'mul","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27680,"Archaedas, The Ancient Stone Watcher","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27681,"Behind Closed Doors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27682,"We Require More Minerals","horde")
	characterquests.charquestheader(count,"Dire Maul",openfile)
	characterquests.charquestprint(count,datatree,openfile,27103,"Shards of the Felvine")
	characterquests.charquestprint(count,datatree,openfile,27104,"Alzzin the Wildshaper")
	characterquests.charquestprint(count,datatree,openfile,27105,"An Unwelcome Guest")
	characterquests.charquestprint(count,datatree,openfile,27107,"Pusillin The Thief")
	characterquests.charquestprint(count,datatree,openfile,27108,"Lethtendris's Web")
	characterquests.charquestprint(count,datatree,openfile,27109,"The Warped Defender")
	characterquests.charquestprint(count,datatree,openfile,27110,"The Madness Within")
	characterquests.charquestprint(count,datatree,openfile,27111,"The Treasure of the Shen'dralar")
	characterquests.charquestprint(count,datatree,openfile,27112,"The Cursed Remains")
	characterquests.charquestprint(count,datatree,openfile,27113,"The Shen'dralar Ancient")
	characterquests.charquestprint(count,datatree,openfile,27114,"The Gordok Taste Test")
	characterquests.charquestprint(count,datatree,openfile,27118,"A Broken Trap")
	characterquests.charquestprint(count,datatree,openfile,27119,"The Gordok Ogre Suit")
	characterquests.charquestprint(count,datatree,openfile,27120,"The Gordok Ogre Suit")
	characterquests.charquestprint(count,datatree,openfile,27124,"Unfinished Gordok Business")
	characterquests.charquestprintfaction(count,datatree,openfile,27125,"King of the Gordok","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27128,"King of the Gordok","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27129,"Saving Warpwood","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27130,"Saving Warpwood","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27131,"The Highborne","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27132,"The Highborne","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27133,"Eyes in the Sky","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27134,"Ogre in the Field","horde")
	characterquests.charquestheader(count,"40: Scholomance",openfile)
	characterquests.charquestprint(count,datatree,openfile,28756,"Aberrations of Bone")
	characterquests.charquestprint(count,datatree,openfile,31440,"The Four Tomes")
	characterquests.charquestprint(count,datatree,openfile,31447,"An End to the Suffering")
	characterquests.charquestheader(count,"40: Scholomance",openfile)
	characterquests.charquestprint(count,datatree,openfile,31442,"The Four Tomes")
	characterquests.charquestprint(count,datatree,openfile,31448,"An End to the Suffering")
	characterquests.charquestheader(count,"Razorfen Downs",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27063,"Looming Threat","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27062,"Looming Threat","horde")
	characterquests.charquestprint(count,datatree,openfile,33513,"Blackthorn's Lieutenants")
	characterquests.charquestprint(count,datatree,openfile,33514,"The Ritual")
	characterquests.charquestheader(count,"Stratholme",openfile)
	characterquests.charquestprint(count,datatree,openfile,27185,"Cutting the Competition")
	characterquests.charquestprint(count,datatree,openfile,27192,"The Great Fras Siabi")
	characterquests.charquestprint(count,datatree,openfile,27208,"The Dreadlord Balnazzar")
	characterquests.charquestprint(count,datatree,openfile,27223,"Retribution")
	characterquests.charquestprint(count,datatree,openfile,27227,"Lord Aurius Rivendare")
	characterquests.charquestprint(count,datatree,openfile,27228,"Man Against Abomination")
	characterquests.charquestprint(count,datatree,openfile,27230,"Weapons for War")
	characterquests.charquestprint(count,datatree,openfile,27305,"Of Love and Family")
	characterquests.charquestprint(count,datatree,openfile,27352,"Liquid Gold")
	characterquests.charquestprint(count,datatree,openfile,27359,"Argent Reinforcements")
	characterquests.charquestprint(count,datatree,openfile,27422,"A City Under Siege")
	characterquests.charquestprint(count,datatree,openfile,28755,"Annals of the Silver Hand")
	characterquests.charquestheader(count,"Zul'Farrak",openfile)
	characterquests.charquestprint(count,datatree,openfile,25556,"Into Zul'Farrak")
	characterquests.charquestprint(count,datatree,openfile,27068,"Chief Ukorz Sandscalp")
	characterquests.charquestprint(count,datatree,openfile,27070,"A Fool's Errand")
	characterquests.charquestprint(count,datatree,openfile,27071,"Wrath of the Sandfury")
	characterquests.charquestprint(count,datatree,openfile,27076,"Breaking and Entering")
	characterquests.charquestheader(count,"Blackrock Depths",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28068,"Adventurers Wanted: Blackrock Depths","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28069,"Adventurers Wanted: Blackrock Depths","horde")
	characterquests.charquestprint(count,datatree,openfile,4083,"The Spectral Chalice")
	characterquests.charquestprint(count,datatree,openfile,7604,"A Binding Contract")
	characterquests.charquestprintfaction(count,datatree,openfile,27565,"Into the Prison","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27567,"Twilight?! No!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27568,"Infiltrating Shadowforge City","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27569,"Dark Iron Tacticians","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27571,"The Grim Guzzler","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27573,"The Dark Iron Pact","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27578,"Morgan's Fruition","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27579,"Into the Prison","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27581,"Twilight?! No!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27582,"Infiltrating Shadowforge City","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27585,"The 109th Division","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27589,"The Grim Guzzler","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27591,"The Dark Iron Pact","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27593,"Rebirth of the K.E.F.","horde")
	characterquests.charquestprint(count,datatree,openfile,27596,"The Heart of the Mountain")
	characterquests.charquestprint(count,datatree,openfile,27603,"The Sealed Gate")
	characterquests.charquestheader(count,"Blackrock Depths: Class Specific",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,28343,"The Breath of Cenarius","class_druid")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28394,"The Golem Lord's Creations","alliance","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28461,"The Golem Lord's Creations","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28398,"The Pyromancer's Grimoire","alliance","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28458,"The Pyromancer's Grimoire","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28405,"Weapons of Darkness","alliance","class_paladin")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28466,"Weapons of Darkness","horde","class_paladin")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28473,"Weapons of Darkness","horde","class_paladin")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28328,"Twilight Scheming","alliance","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28474,"Twilight Scheming","horde","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28475,"Twilight Scheming","horde","class_priest")
	characterquests.charquestprintfaction(count,datatree,openfile,28476,"Twilight Scheming","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28477,"Twilight Scheming","horde","class_priest")
	characterquests.charquestprintfaction(count,datatree,openfile,28478,"Twilight Scheming","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28406,"The Dark Iron Army","alliance","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28463,"The Dark Iron Army","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28401,"Slaves of the Firelord","alliance","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28465,"Slaves of the Firelord","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28399,"Stones of Binding","alliance","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28459,"Stones of Binding","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28393,"A Dangerous Alliance","alliance","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28457,"A Dangerous Alliance","horde","class_warrior")
	characterquests.charquestheader(count,"Sunken Temple",openfile)
	characterquests.charquestprint(count,datatree,openfile,27604,"Jammal'an the Prophet")
	characterquests.charquestprint(count,datatree,openfile,27605,"Eranikus")
	characterquests.charquestprint(count,datatree,openfile,27633,"The Blood God Hakkar")
	characterquests.charquestprint(count,datatree,openfile,27915,"The Heart of the Temple")
	characterquests.charquestheader(count,"Blackrock Spire",openfile)
	characterquests.charquestprint(count,datatree,openfile,27440,"Trolls, Ogres, and Orcs, Oh My!")
	characterquests.charquestprint(count,datatree,openfile,27469,"Friends on The Other Side")
	characterquests.charquestprint(count,datatree,openfile,27470,"A Potential Ally")
	characterquests.charquestprintfaction(count,datatree,openfile,27471,"Blackrock Anomaly","alliance")
	characterquests.charquestheader(count,"Hellfire Ramparts",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29528,"War on the Ramparts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29527,"War on the Ramparts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29529,"Demons in the Citadel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29530,"Demons in the Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29543,"Invading the Citadel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29542,"Invading the Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29594,"Hitting Them Where It Hurts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29593,"Hitting Them Where It Hurts","horde")
	characterquests.charquestheader(count,"The Blood Furnace",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29535,"Make Them Bleed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29538,"Make Them Bleed","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29536,"Heart of Rage","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29539,"Heart of Rage","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29537,"Mind the Gap","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29540,"The Breaker","alliance")
	characterquests.charquestheader(count,"The Slave Pens",openfile)
	characterquests.charquestprint(count,datatree,openfile,29563,"Lost in Action")
	characterquests.charquestprint(count,datatree,openfile,29564,"A Brother Betrayed")
	characterquests.charquestprint(count,datatree,openfile,29565,"The Heart of the Matter")
	characterquests.charquestprint(count,datatree,openfile,29566,"Checking Up")
	characterquests.charquestheader(count,"The Underbog",openfile)
	characterquests.charquestprint(count,datatree,openfile,29567,"Stalk the Stalker")
	characterquests.charquestprint(count,datatree,openfile,29568,"A Necessary Evil")
	characterquests.charquestprint(count,datatree,openfile,29570,"Rescuing the Expedition")
	characterquests.charquestprint(count,datatree,openfile,29571,"Defending the Wilds")
	characterquests.charquestprint(count,datatree,openfile,29691,"Bring Me A Shrubbery!")
	characterquests.charquestprint(count,datatree,openfile,29692,"Bring Me Another Shrubbery!")
	characterquests.charquestheader(count,"Mana-Tombs",openfile)
	characterquests.charquestprint(count,datatree,openfile,10977,"Stasis Chambers of the Mana-Tombs")
	characterquests.charquestprint(count,datatree,openfile,10981,"Nexus-Prince Shaffar's Personal Chamber")
	characterquests.charquestprint(count,datatree,openfile,29573,"Safety is Job One")
	characterquests.charquestprint(count,datatree,openfile,29574,"Intriguing Specimens")
	characterquests.charquestprint(count,datatree,openfile,29575,"Undercutting the Competition")
	characterquests.charquestprintfaction(count,datatree,openfile,29583,"Eckert the Mad","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29582,"Grek's Crazy Night","horde")
	characterquests.charquestheader(count,"Auchenai Crypts",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,10167,"Auchindoun...","horde")
	characterquests.charquestprint(count,datatree,openfile,10253,"Levixus the Soul Caller")
	characterquests.charquestprint(count,datatree,openfile,29590,"The Dead Watcher")
	characterquests.charquestprint(count,datatree,openfile,29591,"Raging Spirits")
	characterquests.charquestheader(count,"Sethekk Halls",openfile)
	characterquests.charquestprint(count,datatree,openfile,10180,"Can't Stay Away")
	characterquests.charquestprint(count,datatree,openfile,29605,"Brother Against Brother")
	characterquests.charquestprint(count,datatree,openfile,29606,"Terokk's Legacy")
	characterquests.charquestprint(count,datatree,openfile,29607,"Eyes of Desire")
	characterquests.charquestheader(count,"The Steamvault",openfile)
	characterquests.charquestprint(count,datatree,openfile,29613,"A Proper Fate")
	characterquests.charquestprint(count,datatree,openfile,29614,"Containment is Key")
	characterquests.charquestprint(count,datatree,openfile,29615,"Windcaller Claw and the Water Thief")
	characterquests.charquestprint(count,datatree,openfile,29616,"Storming the Steamvault")
	characterquests.charquestheader(count,"The Shattered Halls",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29649,"How to Save a Life","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29654,"Turning the Tide","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29656,"O'mrogg's Warcloth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29652,"One Last Favor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29689,"Advancing the Campaign","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29688,"Advancing the Campaign","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29650,"Fel Ember","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29651,"Honor the Dying","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29653,"The Will of the Warchief","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29655,"A Very Special Cloth","horde")
	characterquests.charquestheader(count,"Shadow Labyrinth",openfile)
	characterquests.charquestprint(count,datatree,openfile,29640,"Find Spy To'gun")
	characterquests.charquestprint(count,datatree,openfile,29641,"The Soul Devices")
	characterquests.charquestprint(count,datatree,openfile,29642,"Trouble at Auchindoun")
	characterquests.charquestprint(count,datatree,openfile,29643,"The Codex of Blood")
	characterquests.charquestprint(count,datatree,openfile,29644,"Into the Heart of the Labyrinth")
	characterquests.charquestprint(count,datatree,openfile,29645,"Ambassador Hellmaw")
	characterquests.charquestheader(count,"Caverns of Time",openfile)
	characterquests.charquestprint(count,datatree,openfile,10277,"The Caverns of Time")
	characterquests.charquestprint(count,datatree,openfile,10279,"To The Master's Lair")
	characterquests.charquestprint(count,datatree,openfile,12513,"Nice Hat...")
	characterquests.charquestprint(count,datatree,openfile,29134,"A Wrinkle in Time")
	characterquests.charquestprint(count,datatree,openfile,29193,"On a Wing and a Prayer")
	characterquests.charquestprint(count,datatree,openfile,29598,"Taretha's Diversion")
	characterquests.charquestprint(count,datatree,openfile,29599,"Escape from Durnholde")
	characterquests.charquestprint(count,datatree,openfile,10282,"Old Hillsbrad")
	characterquests.charquestheader(count,"The Mechanar",openfile)
	characterquests.charquestprint(count,datatree,openfile,29657,"With Great Power, Comes Great Responsibility")
	characterquests.charquestprint(count,datatree,openfile,29658,"The Calculator")
	characterquests.charquestprint(count,datatree,openfile,29659,"Lost Treasure")
	characterquests.charquestheader(count,"The Botanica",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29660,"Saving the Botanica","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29667,"Culling the Herd","horde")
	characterquests.charquestprint(count,datatree,openfile,29669,"A Most Somber Task")
	characterquests.charquestheader(count,"The Arcatraz",openfile)
	characterquests.charquestprint(count,datatree,openfile,10704,"How to Break Into the Arcatraz")
	characterquests.charquestprint(count,datatree,openfile,10705,"Seer Udalo")
	characterquests.charquestprint(count,datatree,openfile,29674,"Unbound Darkness")
	characterquests.charquestprint(count,datatree,openfile,29675,"Hey There Dalliah")
	characterquests.charquestprint(count,datatree,openfile,29681,"Maximum Security Breakout")
	characterquests.charquestheader(count,"The Black Morass",openfile)
	characterquests.charquestprint(count,datatree,openfile,10296,"The Black Morass")
	characterquests.charquestprint(count,datatree,openfile,10297,"The Opening of the Dark Portal")
	characterquests.charquestheader(count,"Magisters' Terrace",openfile)
	characterquests.charquestprint(count,datatree,openfile,11490,"The Scryer's Scryer")
	characterquests.charquestprint(count,datatree,openfile,29682,"Magisters' Terrace")
	characterquests.charquestprint(count,datatree,openfile,29684,"Severed Communications")
	characterquests.charquestprint(count,datatree,openfile,29685,"Hard to Kill")
	characterquests.charquestprint(count,datatree,openfile,29686,"A Radical Notion")
	characterquests.charquestprint(count,datatree,openfile,29687,"Twisted Associations")
	characterquests.charquestheader(count,"Utgarde Keep",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29763,"Stealing Their Thunder","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29803,"Ears of the Lich King","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29764,"Disarmament","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,13206,"Disarmament","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,11262,"Ingvar Must Die!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,11272,"A Score to Settle","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30112,"A Score to Settle","horde")
	characterquests.charquestheader(count,"The Nexus",openfile)
	characterquests.charquestprint(count,datatree,openfile,11905,"Postponing the Inevitable")
	characterquests.charquestprint(count,datatree,openfile,11911,"Quickening")
	characterquests.charquestprint(count,datatree,openfile,11973,"Prisoner of War")
	characterquests.charquestprintfaction(count,datatree,openfile,13094,"Have They No Shame?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,13095,"Have They No Shame?","horde")
	characterquests.charquestprint(count,datatree,openfile,29225,"Actionable Intelligence")
	characterquests.charquestprint(count,datatree,openfile,29820,"Into the Nexus")
	characterquests.charquestheader(count,"Azjol-Nerub",openfile)
	characterquests.charquestprint(count,datatree,openfile,29807,"Death to the Traitor King")
	characterquests.charquestprint(count,datatree,openfile,29808,"Don't Forget the Eggs!")
	characterquests.charquestprint(count,datatree,openfile,29811,"The Gatewatcher's Talisman")
	characterquests.charquestheader(count,"Ahn'kahet: The Old Kingdom",openfile)
	characterquests.charquestprint(count,datatree,openfile,13187,"The Faceless Ones")
	characterquests.charquestprint(count,datatree,openfile,29825,"Pupil No More")
	characterquests.charquestprint(count,datatree,openfile,29826,"Reclaiming Ahn'Kahet")
	characterquests.charquestheader(count,"Drak'Tharon Keep",openfile)
	characterquests.charquestprint(count,datatree,openfile,12037,"Search and Rescue")
	characterquests.charquestprint(count,datatree,openfile,12238,"Cleansing Drak'Tharon")
	characterquests.charquestprint(count,datatree,openfile,13129,"Head Games")
	characterquests.charquestprint(count,datatree,openfile,29828,"What the Scourge Dred")
	characterquests.charquestprint(count,datatree,openfile,30120,"Cleansing Drak'Tharon")
	characterquests.charquestheader(count,"The Violet Hold",openfile)
	characterquests.charquestprint(count,datatree,openfile,29829,"Discretion is Key")
	characterquests.charquestprint(count,datatree,openfile,29830,"Containment")
	characterquests.charquestheader(count,"Gundrak",openfile)
	characterquests.charquestprint(count,datatree,openfile,29833,"Unfinished Business")
	characterquests.charquestprint(count,datatree,openfile,29834,"Gal'darah Must Pay")
	characterquests.charquestprint(count,datatree,openfile,29835,"Gal'darah Must Pay")
	characterquests.charquestprint(count,datatree,openfile,29836,"Just Checkin'")
	characterquests.charquestprint(count,datatree,openfile,29838,"One of a Kind")
	characterquests.charquestprint(count,datatree,openfile,29839,"One of a Kind")
	characterquests.charquestprint(count,datatree,openfile,29840,"For Posterity")
	characterquests.charquestprint(count,datatree,openfile,29844,"For Posterity")
	characterquests.charquestheader(count,"Halls of Stone",openfile)
	characterquests.charquestprint(count,datatree,openfile,13207,"Halls of Stone")
	characterquests.charquestprint(count,datatree,openfile,29848,"The Forlorn Watcher")
	characterquests.charquestprint(count,datatree,openfile,29850,"Corrupt Constructs")
	characterquests.charquestheader(count,"The Oculus",openfile)
	characterquests.charquestprint(count,datatree,openfile,13124,"The Struggle Persists")
	characterquests.charquestprint(count,datatree,openfile,13126,"A Unified Front")
	characterquests.charquestprint(count,datatree,openfile,13127,"Mage-Lord Urom")
	characterquests.charquestprint(count,datatree,openfile,13128,"A Wing and a Prayer")
	characterquests.charquestheader(count,"Halls of Lightning",openfile)
	characterquests.charquestprint(count,datatree,openfile,29860,"Diametrically Opposed")
	characterquests.charquestprint(count,datatree,openfile,29861,"Whatever it Takes!")
	characterquests.charquestprint(count,datatree,openfile,29862,"Clearing the Way")
	characterquests.charquestprint(count,datatree,openfile,29863,"Stormherald Eljrrin")
	characterquests.charquestheader(count,"Utgarde Pinnacle",openfile)
	characterquests.charquestprint(count,datatree,openfile,13131,"Junk in My Trunk")
	characterquests.charquestprint(count,datatree,openfile,13132,"Vengeance Be Mine!")
	characterquests.charquestprint(count,datatree,openfile,29864,"Working at the Source")
	characterquests.charquestheader(count,"The Culling of Stratholme",openfile)
	characterquests.charquestprint(count,datatree,openfile,13149,"Dispelling Illusions")
	characterquests.charquestprint(count,datatree,openfile,13151,"A Royal Escort")
	characterquests.charquestheader(count,"Trial of the Champion",openfile)
	characterquests.charquestprint(count,datatree,openfile,29851,"Champion of the Tournament")
	characterquests.charquestheader(count,"The Forge of Souls",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,24499,"Echoes of Tortured Souls","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24506,"Inside the Frozen Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24510,"Inside the Frozen Citadel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24511,"Echoes of Tortured Souls","horde")
	characterquests.charquestheader(count,"Pit of Saron",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,24683,"The Pit of Saron","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24682,"The Pit of Saron","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24498,"The Path to the Citadel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24507,"The Path to the Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24710,"Deliverance from the Pit","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24712,"Deliverance from the Pit","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24461,"Reforging The Sword","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24559,"Reforging The Sword","horde")
	characterquests.charquestheader(count,"Halls of Reflection",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,24480,"The Halls Of Reflection","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24561,"The Halls Of Reflection","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24711,"Frostmourne","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24713,"Frostmourne","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24500,"Wrath of the Lich King","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24802,"Wrath of the Lich King","horde")
	characterquests.charquestheader(count,"Throne of the Tides",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28834,"Rescue the Earthspeaker!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28833,"Rescue the Earthspeaker!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28836,"Sins of the Sea Witch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28843,"Sins of the Sea Witch","horde")
	characterquests.charquestheader(count,"Blackrock Caverns",openfile)
	characterquests.charquestprint(count,datatree,openfile,28732,"This Can Only Mean One Thing...")
	characterquests.charquestprint(count,datatree,openfile,28735,"To the Chamber of Incineration!")
	characterquests.charquestprint(count,datatree,openfile,28737,"What Is This Place?")
	characterquests.charquestprint(count,datatree,openfile,28738,"The Twilight Forge")
	characterquests.charquestprint(count,datatree,openfile,28740,"Do My Eyes Deceive Me?")
	characterquests.charquestprint(count,datatree,openfile,28741,"Ascendant Lord Obsidius")
	characterquests.charquestheader(count,"The Stonecore",openfile)
	characterquests.charquestprint(count,datatree,openfile,28814,"Followers and Leaders")
	characterquests.charquestprint(count,datatree,openfile,28815,"Twilight Documents")
	characterquests.charquestprint(count,datatree,openfile,28824,"Wayward Child")
	characterquests.charquestprint(count,datatree,openfile,28866,"Into the Stonecore")
	characterquests.charquestheader(count,"The Vortex Pinnacle",openfile)
	characterquests.charquestprint(count,datatree,openfile,28760,"Vengeance for Orsis")
	characterquests.charquestprint(count,datatree,openfile,28779,"A Long Way from Home")
	characterquests.charquestprint(count,datatree,openfile,28845,"The Vortex Pinnacle")
	characterquests.charquestheader(count,"Lost City of the Tol'vir",openfile)
	characterquests.charquestprint(count,datatree,openfile,28781,"Targets of Opportunity")
	characterquests.charquestprint(count,datatree,openfile,28783,"The Source of Their Power")
	characterquests.charquestprint(count,datatree,openfile,28870,"Return to the Lost City")
	characterquests.charquestheader(count,"Grim Batol",openfile)
	characterquests.charquestprint(count,datatree,openfile,28852,"Soften them Up")
	characterquests.charquestprint(count,datatree,openfile,28853,"Kill the Courier")
	characterquests.charquestprint(count,datatree,openfile,28854,"Closing a Dark Chapter")
	characterquests.charquestheader(count,"Halls of Origination",openfile)
	characterquests.charquestprint(count,datatree,openfile,28654,"The Heart of the Matter")
	characterquests.charquestprint(count,datatree,openfile,28746,"Penetrating Their Defenses")
	characterquests.charquestprint(count,datatree,openfile,28753,"Doing it the Hard Way")
	characterquests.charquestheader(count,"End Time",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,30095,"The End Time","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30094,"The End Time","horde")
	characterquests.charquestprint(count,datatree,openfile,30096,"Murozond")
	characterquests.charquestprint(count,datatree,openfile,30097,"Archival Purposes")
	characterquests.charquestheader(count,"Well of Eternity",openfile)
	characterquests.charquestprint(count,datatree,openfile,30098,"The Well of Eternity")
	characterquests.charquestprint(count,datatree,openfile,30099,"In Unending Numbers")
	characterquests.charquestprint(count,datatree,openfile,30100,"The Vainglorious")
	characterquests.charquestprint(count,datatree,openfile,30101,"The Path to the Dragon Soul")
	characterquests.charquestprint(count,datatree,openfile,30104,"Documenting the Timeways")
	characterquests.charquestheader(count,"Hour of Twilight",openfile)
	characterquests.charquestprint(count,datatree,openfile,30102,"The Hour of Twilight")
	characterquests.charquestprint(count,datatree,openfile,30103,"To Wyrmrest!")
	characterquests.charquestprint(count,datatree,openfile,30105,"The Twilight Prophet")
	characterquests.charquestheader(count,"Temple of the Jade Serpent",openfile)
	characterquests.charquestprint(count,datatree,openfile,31355,"Restoring Jade's Purity")
	characterquests.charquestprint(count,datatree,openfile,31356,"Deep Doubts, Deep Wisdom")
	characterquests.charquestheader(count,"Stormstout Brewery",openfile)
	characterquests.charquestprint(count,datatree,openfile,30085,"Into the Brewery")
	characterquests.charquestprint(count,datatree,openfile,31324,"Family Secrets")
	characterquests.charquestprint(count,datatree,openfile,31327,"Trouble Brewing")
	characterquests.charquestheader(count,"Mogu'shan Palace",openfile)
	characterquests.charquestprint(count,datatree,openfile,31357,"Relics of the Four Kings")
	characterquests.charquestprint(count,datatree,openfile,31360,"A New Lesson for the Master")
	characterquests.charquestheader(count,"Shado-Pan Monastery",openfile)
	characterquests.charquestprint(count,datatree,openfile,30757,"Lord of the Shado-Pan")
	characterquests.charquestprint(count,datatree,openfile,31030,"Into the Monastery")
	characterquests.charquestprint(count,datatree,openfile,31342,"The Path to Respect Lies in Violence")
	characterquests.charquestheader(count,"Gate of the Setting Sun",openfile)
	characterquests.charquestprint(count,datatree,openfile,31363,"Lighting the Way")
	characterquests.charquestprint(count,datatree,openfile,31364,"That's a Big Bug!")
	characterquests.charquestheader(count,"Siege of Niuzao Temple",openfile)
	characterquests.charquestprint(count,datatree,openfile,31365,"Somewhere Inside")
	characterquests.charquestprint(count,datatree,openfile,31366,"Take Down the Wing Leader")

def raid_60_aq10(count,datatree,openfile):
	characterquests.charquestheader(count,"Ruins of Ahn\'Qiraj",openfile)
	characterquests.charquestheader(count,"Druid",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8692,"Cloak of Unending Life","class_druid")
	characterquests.charquestprintclass(count,datatree,openfile,8708,"Mace of Unending Life","class_druid")
	characterquests.charquestprintclass(count,datatree,openfile,8700,"Band of Unending Life","class_druid")
	characterquests.charquestheader(count,"Hunter",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8696,"Cloak of the Unseen Path","class_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,8712,"Scythe of the Unseen Path","class_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,8704,"Signet of the Unseen Path","class_hunter")
	characterquests.charquestheader(count,"Mage",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8691,"Drape of Vaulted Secrets","class_mage")
	characterquests.charquestprintclass(count,datatree,openfile,8707,"Blade of Vaulted Secrets","class_mage")
	characterquests.charquestprintclass(count,datatree,openfile,8699,"Band of Vaulted Secrets","class_mage")
	characterquests.charquestheader(count,"Paladin",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8695,"Cape of Eternal Justice","class_paladin")
	characterquests.charquestprintclass(count,datatree,openfile,8711,"Blade of Eternal Justice","class_paladin")
	characterquests.charquestprintclass(count,datatree,openfile,8703,"Ring of Eternal Justice","class_paladin")
	characterquests.charquestheader(count,"Priest",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8689,"Shroud of Infinite Wisdom","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,8705,"Gavel of Infinite Wisdom","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,8697,"Ring of Infinite Wisdom","class_priest")
	characterquests.charquestheader(count,"Rogue",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8693,"Cloak of Veiled Shadows","class_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,8709,"Dagger of Veiled Shadows","class_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,8701,"Band of Veiled Shadows","class_rogue")
	characterquests.charquestheader(count,"Shaman",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8690,"Cloak of the Gathering Storm","class_shaman")
	characterquests.charquestprintclass(count,datatree,openfile,8706,"Hammer of the Gathering Storm","class_shaman")
	characterquests.charquestprintclass(count,datatree,openfile,8698,"Ring of the Gathering Storm","class_shaman")
	characterquests.charquestheader(count,"Warlock",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8694,"Shroud of Unspoken Names","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,8710,"Kris of Unspoken Names","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,8702,"Ring of Unspoken Names","class_warlock")
	characterquests.charquestheader(count,"Warrior",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,8557,"Drape of Unyielding Strength","class_warrior")
	characterquests.charquestprintclass(count,datatree,openfile,8558,"Sickle of Unyielding Strength","class_warrior")
	characterquests.charquestprintclass(count,datatree,openfile,8556,"Signet of Unyielding Strength","class_warrior")

def raid_100_brf(count,datatree,openfile):
	characterquests.charquestheader(count,"Blackrock Foundry",openfile)
	characterquests.charquestprint(count,datatree,openfile,37029,"Sigil of the Black Hand (Normal)")
	characterquests.charquestprint(count,datatree,openfile,37030,"Sigil of the Black Hand (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,37031,"Sigil of the Black Hand (Mythic)")

def raid_100_hfc(count,datatree,openfile):
	characterquests.charquestheader(count,"Hellfire Citadel",openfile)
	characterquests.charquestprint(count,datatree,openfile,39499,"Well of Souls (Normal)")
	characterquests.charquestprint(count,datatree,openfile,39500,"Well of Souls (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,39501,"Well of Souls (Mythic)")
	characterquests.charquestprint(count,datatree,openfile,39502,"The Fel Spire (Normal)")
	characterquests.charquestprint(count,datatree,openfile,39504,"The Fel Spire (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,39505,"The Fel Spire (Mythic)")

def raid_110_en(count,datatree,openfile):
	characterquests.charquestheader(count,"Emerald Nightmare",openfile)
	characterquests.charquestprint(count,datatree,openfile,44283,"The Emerald Nightmare: Piercing the Veil (Normal)")
	characterquests.charquestprint(count,datatree,openfile,44284,"The Emerald Nightmare: Piercing the Veil (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,44285,"The Emerald Nightmare: Piercing the Veil (Mythic)")

def raid_110_nh(count,datatree,openfile):
	characterquests.charquestheader(count,"Nighthold",openfile)
	characterquests.charquestprint(count,datatree,openfile,45381,"Talisman of the Shal'dorei (Normal)")
	characterquests.charquestprint(count,datatree,openfile,45382,"Talisman of the Shal'dorei (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,45383,"Talisman of the Shal'dorei (Mythic)")

def raid_110_tos(count,datatree,openfile):
	characterquests.charquestheader(count,"Tomb of Sargeras",openfile)
	characterquests.charquestprint(count,datatree,openfile,47725,"Aegwynn's Path (Normal)")
	characterquests.charquestprint(count,datatree,openfile,47726,"Aegwynn's Path (Heroic)")
	characterquests.charquestprint(count,datatree,openfile,47727,"Aegwynn's Path (Mythic)")

def class_quests(count,datatree,openfile):
	characterquests.charquestheader(count,"Class Quests",openfile)
	characterquests.charquestheader(count,"Druid",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27273,"An Invitation from Moonglade","alliance","class_druid")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27283,"A Journey to Moonglade","horde","class_druid")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27356,"The Circle's Future","alliance","class_druid")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27404,"The Circle's Future","horde","class_druid")
	characterquests.charquestheader(count,"Hunter",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27266,"Wulf Calls","alliance","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27278,"Grimshot's Call","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27344,"A Well-Earned Reward","alliance","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27395,"A Marksman's Weapon","horde","class_hunter")
	characterquests.charquestheader(count,"Mage",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27271,"Journey to the Wizard's Sanctum","alliance","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27277,"An Audience with Ureda","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27354,"Mastering the Arcane","alliance","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27400,"Mastering the Arcane","horde","class_mage")
	characterquests.charquestheader(count,"Paladin",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27265,"Lord Grayson Shadowbreaker","alliance","class_paladin")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27343,"The Hand of the Light","alliance","class_paladin")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,27298,"Seek Out Master Pyreanor","horde","class_paladin","race_bloodelf_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,27434,"The Adept's Path","horde","class_paladin","race_bloodelf_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,27403,"A True Sunwalker","horde","class_paladin","race_tauren_female")
	characterquests.charquestheader(count,"Priest",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27268,"Make Haste to the Cathedral","alliance","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27269,"The Temple of the Moon","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27274,"The Chief Surgeon","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27331,"The Seer's Call","horde","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27332,"Seek the Shadow-Walker","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27334,"Dark Cleric Cecille","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27335,"Journey to Orgrimmar","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27361,"Favored of the Light","alliance","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27362,"Favored of Elune","alliance","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27363,"A Budding Young Surgeon","alliance","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27435,"A Seer's Staff","horde","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27436,"The Shadow-Walker's Task","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27437,"The Dark Cleric's Bidding","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27439,"Staff of the Light","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,27441,"A Seer's Staff","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28164,"Seek Brother Silverhallow","horde","class_priest")
	characterquests.charquestheader(count,"Rogue",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27267,"Make Contact with SI:7","alliance","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27279,"The Shattered Hand","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27351,"A Royal Reward","alliance","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27396,"Blade of the Shattered Hand","horde","class_rogue")
	characterquests.charquestheader(count,"Shaman",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27270,"An Audience with the Farseer","alliance","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27280,"The Earthbreaker Calls","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27353,"Blessings of the Elements","alliance","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27397,"Terga's Task","horde","class_shaman")
	characterquests.charquestheader(count,"Warlock",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27272,"Demisette Sends Word","alliance","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27282,"Kranosh's Behest","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27355,"A Boon for the Powerful","alliance","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27402,"Token of Power","horde","class_warlock")
	characterquests.charquestheader(count,"Legion Class Mount: Warlock",openfile)
	characterquests.charquestprint(count,datatree,openfile,46237,"Bloodbringer's Missive")
	characterquests.charquestprint(count,datatree,openfile,46238,"If You Build It")
	characterquests.charquestprint(count,datatree,openfile,46239,"Fel to the Core")
	characterquests.charquestprint(count,datatree,openfile,46240,"Give Me Fuel, Give Me Fire")
	characterquests.charquestprint(count,datatree,openfile,46241,"The Minions of Hel'nurath")
	characterquests.charquestprint(count,datatree,openfile,46242,"The Dreadlord's Calling")
	characterquests.charquestprint(count,datatree,openfile,46243,"The Wrathsteed of Xoroth")
	characterquests.charquestheader(count,"Warrior",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,27225,"A Summons from Ander Germaine","alliance","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27337,"A Fitting Weapon","alliance","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27281,"Grezz Ragefist","horde","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,27365,"A Fitting Weapon","horde","class_warrior")

def warlock_green_fire(count,datatree,openfile):
	characterquests.charquestheader(count,"Warlock: Green Fire",openfile)
	characterquests.charquestprintclass(count,datatree,openfile,32295,"An Unusual Tome","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32307,"Reader for the Dead Tongue","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,32310,"A Tale of Six Masters","alliance","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,32309,"A Tale of Six Masters","horde","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32317,"Seeking the Soulstones","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32324,"Seek the Signal","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32325,"Infiltrating the Black Temple","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32340,"Plunder the Black Temple","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,32358,"The Soulcore","class_warlock")
