import characterquests
from characterutil import *

def sz_01_10_Wandering_Isle(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"01-10: Wandering Isle",openfile)

def z_80_90_Jade_Forest(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"80-90: Jade Forest",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29552,"Critical Condition","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29553,"The Missing Admiral","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29555,"The White Pawn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29556,"Hozen Aren't Your Friends, Hozen Are Your Enemies","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29558,"The Path of War","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29559,"Freeing Our Brothers","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29560,"Ancient Power","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29562,"Jailbreak","alliance")
	characterquests.charquestprint(count,datatree,openfile,29576,"An Air of Worry")
	characterquests.charquestprint(count,datatree,openfile,29578,"Defiance")
	characterquests.charquestprint(count,datatree,openfile,29579,"Rally the Survivors")
	characterquests.charquestprint(count,datatree,openfile,29580,"Orchard-Supplied Hardware")
	characterquests.charquestprint(count,datatree,openfile,29585,"Spitfire")
	characterquests.charquestprint(count,datatree,openfile,29586,"The Splintered Path")
	characterquests.charquestprint(count,datatree,openfile,29587,"Unbound")
	characterquests.charquestprint(count,datatree,openfile,29617,"Tian Monastery")
	characterquests.charquestprint(count,datatree,openfile,29618,"The High Elder")
	characterquests.charquestprint(count,datatree,openfile,29619,"A Courteous Guest")
	characterquests.charquestprint(count,datatree,openfile,29620,"The Great Banquet")
	characterquests.charquestprint(count,datatree,openfile,29622,"Your Training Starts Now")
	characterquests.charquestprint(count,datatree,openfile,29623,"Perfection")
	characterquests.charquestprint(count,datatree,openfile,29624,"Attention")
	characterquests.charquestprint(count,datatree,openfile,29626,"Groundskeeper Wu")
	characterquests.charquestprint(count,datatree,openfile,29627,"A Proper Weapon")
	characterquests.charquestprint(count,datatree,openfile,29628,"A Strong Back")
	characterquests.charquestprint(count,datatree,openfile,29629,"A Steady Hand")
	characterquests.charquestprint(count,datatree,openfile,29630,"And a Heavy Fist")
	characterquests.charquestprint(count,datatree,openfile,29631,"Burning Bright")
	characterquests.charquestprint(count,datatree,openfile,29632,"Becoming Battle-Ready")
	characterquests.charquestprint(count,datatree,openfile,29633,"Zhi-Zhi, the Dextrous")
	characterquests.charquestprint(count,datatree,openfile,29634,"Husshun, the Wizened")
	characterquests.charquestprint(count,datatree,openfile,29635,"Xiao, the Eater")
	characterquests.charquestprint(count,datatree,openfile,29636,"A Test of Endurance")
	characterquests.charquestprint(count,datatree,openfile,29637,"The Rumpus")
	characterquests.charquestprint(count,datatree,openfile,29639,"Flying Colors")
	characterquests.charquestprint(count,datatree,openfile,29646,"Flying Colors")
	characterquests.charquestprint(count,datatree,openfile,29647,"Flying Colors")
	characterquests.charquestprint(count,datatree,openfile,29670,"Maul Gormal")
	characterquests.charquestprintfaction(count,datatree,openfile,29694,"Regroup!","horde")
	characterquests.charquestprint(count,datatree,openfile,29716,"The Double Hozen Dare")
	characterquests.charquestprint(count,datatree,openfile,29717,"Down Kitty!")
	characterquests.charquestprint(count,datatree,openfile,29723,"The Jade Witch")
	characterquests.charquestprintfaction(count,datatree,openfile,29725,"SI:7 Report: Fire From the Sky","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29726,"SI:7 Report: Hostile Natives","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29727,"SI:7 Report: Take No Prisoners","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29730,"Scouting Report: Hostile Natives","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29731,"Scouting Report: On the Right Track","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29733,"SI:7 Report: Lost in the Woods","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29743,"Monstrosity","horde")
	characterquests.charquestprint(count,datatree,openfile,29745,"The Sprites' Plight")
	characterquests.charquestprint(count,datatree,openfile,29747,"Break the Cycle")
	characterquests.charquestprint(count,datatree,openfile,29748,"Simulacrumble")
	characterquests.charquestprint(count,datatree,openfile,29749,"An Urgent Plea")
	characterquests.charquestprint(count,datatree,openfile,29750,"Vessels of the Spirit")
	characterquests.charquestprint(count,datatree,openfile,29751,"Ritual Artifacts")
	characterquests.charquestprint(count,datatree,openfile,29752,"The Wayward Dead")
	characterquests.charquestprint(count,datatree,openfile,29753,"Back to Nature")
	characterquests.charquestprint(count,datatree,openfile,29754,"To Bridge Earth and Sky")
	characterquests.charquestprint(count,datatree,openfile,29755,"Pei-Back")
	characterquests.charquestprint(count,datatree,openfile,29756,"A Humble Offering")
	characterquests.charquestprintfaction(count,datatree,openfile,29759,"Kung Din","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29762,"Family Heirlooms","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29765,"Cryin' My Eyes Out","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29804,"Seein' Red","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29815,"Forensic Science","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29821,"Missed Me By... That Much!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29822,"Lay of the Land","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29823,"Scouting Report: The Friend of My Enemy","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29824,"Scouting Report: Like Jinyu in a Barrel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29827,"Acid Rain","horde")
	characterquests.charquestprint(count,datatree,openfile,29865,"The Silkwood Road")
	characterquests.charquestprint(count,datatree,openfile,29866,"The Threads that Stick")
	characterquests.charquestprintfaction(count,datatree,openfile,29879,"Swallowed Whole","horde")
	characterquests.charquestprint(count,datatree,openfile,29881,"The Perfect Color")
	characterquests.charquestprint(count,datatree,openfile,29882,"Quill of Stingers")
	characterquests.charquestprintfaction(count,datatree,openfile,29883,"The Pearlfin Situation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29885,"Road Rations","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29887,"The Elder's Instruments","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29888,"Seek Out the Lorewalker","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29889,"Borrowed Brew","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29890,"Finding Your Center","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29891,"Potency","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29892,"Body","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29893,"Hue","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29894,"Spirits of the Water","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29898,"Sacred Waters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29899,"Rest in Peace","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29900,"An Ancient Legend","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29901,"Anduin's Decision","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29903,"A Perfect Match","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29904,"Bigger Fish to Fry","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29905,"Let Them Burn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29906,"Carp Diem","alliance")
	characterquests.charquestprint(count,datatree,openfile,29920,"Getting Permission")
	characterquests.charquestprintfaction(count,datatree,openfile,29922,"In Search of Wisdom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29924,"Kill Kher Shan","horde")
	characterquests.charquestprint(count,datatree,openfile,29925,"All We Can Spare")
	characterquests.charquestprint(count,datatree,openfile,29926,"Calamity Jade")
	characterquests.charquestprint(count,datatree,openfile,29927,"Mann's Man")
	characterquests.charquestprint(count,datatree,openfile,29928,"I Have No Jade And I Must Scream")
	characterquests.charquestprint(count,datatree,openfile,29929,"Trapped!")
	characterquests.charquestprint(count,datatree,openfile,29930,"What's Mined Is Yours")
	characterquests.charquestprint(count,datatree,openfile,29931,"The Serpent's Heart")
	characterquests.charquestprint(count,datatree,openfile,29932,"The Temple of the Jade Serpent")
	characterquests.charquestprintfaction(count,datatree,openfile,29933,"The Bees' Knees","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29935,"Orders are Orders","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29936,"Instant Messaging","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29937,"Furious Fowl","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29939,"Boom Bait","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29941,"Beyond the Horizon","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29942,"Silly Wikket, Slickies are for Hozen","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29943,"Guerrillas in our Midst","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29966,"Burning Down the House","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29967,"Boom Goes the Doonamite!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29968,"Green-ish Energy","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29971,"The Scouts Return","horde")
	characterquests.charquestprint(count,datatree,openfile,29993,"Find the Boy")
	characterquests.charquestprint(count,datatree,openfile,29995,"Shrine of the Dawn")
	characterquests.charquestprint(count,datatree,openfile,29997,"The Scryer's Dilemma")
	characterquests.charquestprint(count,datatree,openfile,29998,"The Librarian's Quandary")
	characterquests.charquestprint(count,datatree,openfile,29999,"The Rider's Bind")
	characterquests.charquestprint(count,datatree,openfile,30000,"The Jade Serpent")
	characterquests.charquestprint(count,datatree,openfile,30001,"Moth-Ridden")
	characterquests.charquestprint(count,datatree,openfile,30002,"Pages of History")
	characterquests.charquestprint(count,datatree,openfile,30004,"Everything In Its Place")
	characterquests.charquestprint(count,datatree,openfile,30005,"Lighting Up the Sky")
	characterquests.charquestprint(count,datatree,openfile,30006,"The Darkness Around Us")
	characterquests.charquestprint(count,datatree,openfile,30011,"A New Vision")
	characterquests.charquestprintfaction(count,datatree,openfile,30015,"Dawn's Blossom","horde")
	characterquests.charquestprint(count,datatree,openfile,30063,"Behind the Masks")
	characterquests.charquestprint(count,datatree,openfile,30064,"Saving the Sutras")
	characterquests.charquestprint(count,datatree,openfile,30065,"Arrows of Fortune")
	characterquests.charquestprint(count,datatree,openfile,30066,"Hidden Power")
	characterquests.charquestprint(count,datatree,openfile,30067,"The Shadow of Doubt")
	characterquests.charquestprint(count,datatree,openfile,30068,"Flames of the Void")
	characterquests.charquestprintfaction(count,datatree,openfile,30069,"No Plan Survives Contact with the Enemy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30070,"The Fall of Ga'trul","alliance")
	characterquests.charquestprint(count,datatree,openfile,30134,"Wild Things")
	characterquests.charquestprint(count,datatree,openfile,30135,"Beating the Odds")
	characterquests.charquestprint(count,datatree,openfile,30136,"Empty Nests")
	characterquests.charquestprint(count,datatree,openfile,30137,"Egg Collection")
	characterquests.charquestprint(count,datatree,openfile,30138,"Choosing the One")
	characterquests.charquestprint(count,datatree,openfile,30139,"The Rider's Journey")
	characterquests.charquestprint(count,datatree,openfile,30140,"The Rider's Journey")
	characterquests.charquestprint(count,datatree,openfile,30141,"The Rider's Journey")
	characterquests.charquestprint(count,datatree,openfile,30142,"It's A...")
	characterquests.charquestprint(count,datatree,openfile,30143,"They Grow Like Weeds")
	characterquests.charquestprint(count,datatree,openfile,30144,"Flight Training: Ring Round-Up")
	characterquests.charquestprint(count,datatree,openfile,30145,"Flight Training: Full Speed Ahead")
	characterquests.charquestprint(count,datatree,openfile,30146,"Snack Time")
	characterquests.charquestprint(count,datatree,openfile,30147,"Fragments of the Past")
	characterquests.charquestprint(count,datatree,openfile,30148,"Just a Flesh Wound")
	characterquests.charquestprint(count,datatree,openfile,30149,"A Feast for the Senses")
	characterquests.charquestprint(count,datatree,openfile,30150,"Sweet as Honey")
	characterquests.charquestprint(count,datatree,openfile,30151,"Catch!")
	characterquests.charquestprint(count,datatree,openfile,30152,"The Sky Race")
	characterquests.charquestprint(count,datatree,openfile,30154,"The Easiest Way To A Serpent's Heart")
	characterquests.charquestprint(count,datatree,openfile,30155,"Restoring the Balance")
	characterquests.charquestprint(count,datatree,openfile,30156,"Feeding Time")
	characterquests.charquestprint(count,datatree,openfile,30157,"Emptier Nests")
	characterquests.charquestprint(count,datatree,openfile,30158,"Disarming the Enemy")
	characterquests.charquestprint(count,datatree,openfile,30159,"Preservation")
	characterquests.charquestprint(count,datatree,openfile,30187,"Flight Training: In Due Course")
	characterquests.charquestprint(count,datatree,openfile,30188,"Riding the Skies")
	characterquests.charquestprintfaction(count,datatree,openfile,30466,"Sufficient Motivation","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30484,"Gauging Our Progress","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30485,"Last Piece of the Puzzle","horde")
	characterquests.charquestprint(count,datatree,openfile,30495,"Love's Labor")
	characterquests.charquestprintfaction(count,datatree,openfile,30498,"Get Back Here!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30499,"Get Back Here!","horde")
	characterquests.charquestprint(count,datatree,openfile,30500,"Residual Fallout")
	characterquests.charquestprint(count,datatree,openfile,30502,"Jaded Heart")
	characterquests.charquestprintfaction(count,datatree,openfile,30504,"Emergency Response","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30565,"An Unexpected Advantage","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30568,"Helping the Cause","alliance")
	characterquests.charquestprint(count,datatree,openfile,30648,"Moving On")
	characterquests.charquestprintfaction(count,datatree,openfile,31112,"They're So Thorny!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31121,"Stay a While, and Listen","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31130,"A Visit with Lorewalker Cho","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31132,"A Mile in My Shoes","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31134,"If These Stones Could Speak","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31152,"Peering Into the Past","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31167,"Family Tree","horde")
	characterquests.charquestprint(count,datatree,openfile,31194,"Slitherscale Suppression")
	characterquests.charquestprint(count,datatree,openfile,31230,"Welcome to Dawn's Blossom")
	characterquests.charquestprintfaction(count,datatree,openfile,31239,"What's in a Name Name?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31241,"Wicked Wikkets","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31261,"Captain Jack's Dead","horde")
	characterquests.charquestprint(count,datatree,openfile,31303,"The Seal is Broken")
	characterquests.charquestprint(count,datatree,openfile,31307,"FLAG - Jade Infused Blade")
	characterquests.charquestprintfaction(count,datatree,openfile,31319,"Emergency Response","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31362,"Last Piece of the Puzzle","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31373,"The Order of the Cloud Serpent","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31375,"The Order of the Cloud Serpent","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31732,"Unleash Hell","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31733,"Touching Ground","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31734,"Welcome Wagons","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31735,"The Right Tool For The Job","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31736,"Envoy of the Alliance","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31737,"The Cost of War","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31738,"Pillaging Peons","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31739,"Priorities!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31740,"Koukou's Rampage","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31741,"Twinspire Keep","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31742,"Fractured Forces","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31743,"Smoke Before Fire","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31744,"Unfair Trade","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31745,"Onward and Inward","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31765,"Paint it Red!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31766,"Touching Ground","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31767,"Finish Them!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31768,"Fire Is Always the Answer","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31769,"The Final Blow!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31770,"You're Either With Us Or...","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31771,"Face to Face With Consequence","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31772,"Priorities!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31773,"Prowler Problems","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31774,"Seeking Zin'jun","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31775,"Assault on the Airstrip","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31776,"Strongarm Tactics","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31777,"Choppertunity","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31778,"Unreliable Allies","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31779,"The Darkness Within","horde")
	characterquests.charquestprint(count,datatree,openfile,31784,"Onyx To Goodness")
	characterquests.charquestprint(count,datatree,openfile,31810,"Riding the Skies")
	characterquests.charquestprint(count,datatree,openfile,31811,"Riding the Skies")
	characterquests.charquestprintfaction(count,datatree,openfile,31978,"Priorities!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31999,"Nazgrim's Command","horde")
	characterquests.charquestprint(count,datatree,openfile,33250,"A Time-Lost Treasure")
	characterquests.charquestprintfaction(count,datatree,openfile,49538,"Warchief's Command: Jade Forest!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,49556,"Hero's Call: Jade Forest!","alliance")

def z_81_90_Valley_of_the_Four_Winds(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"81-90: Valley of the Four Winds",openfile)
	characterquests.charquestprint(count,datatree,openfile,29577,"Ashyo's Vision")
	characterquests.charquestprint(count,datatree,openfile,29581,"The Golden Dream")
	characterquests.charquestprint(count,datatree,openfile,29600,"Snap Judgment")
	characterquests.charquestprint(count,datatree,openfile,29757,"Bottletoads")
	characterquests.charquestprint(count,datatree,openfile,29758,"Guess Whose Back")
	characterquests.charquestprint(count,datatree,openfile,29871,"Clever Ashyo")
	characterquests.charquestprint(count,datatree,openfile,29872,"Lin Tenderpaw")
	characterquests.charquestprint(count,datatree,openfile,29877,"A Poor Grasp of the Basics")
	characterquests.charquestprint(count,datatree,openfile,29907,"Chen and Li Li")
	characterquests.charquestprint(count,datatree,openfile,29908,"A Seemingly Endless Nuisance")
	characterquests.charquestprint(count,datatree,openfile,29909,"Low Turnip Turnout")
	characterquests.charquestprint(count,datatree,openfile,29910,"Rampaging Rodents")
	characterquests.charquestprint(count,datatree,openfile,29911,"Practically Perfect Produce")
	characterquests.charquestprint(count,datatree,openfile,29912,"The Fabulous Miss Fanny")
	characterquests.charquestprint(count,datatree,openfile,29913,"The Meat They'll Eat")
	characterquests.charquestprint(count,datatree,openfile,29914,"Back to the Sty")
	characterquests.charquestprint(count,datatree,openfile,29915,"A Neighbor's Duty")
	characterquests.charquestprint(count,datatree,openfile,29916,"Piercing Talons and Slavering Jaws")
	characterquests.charquestprint(count,datatree,openfile,29917,"Lupello")
	characterquests.charquestprint(count,datatree,openfile,29918,"A Lesson in Bravery")
	characterquests.charquestprint(count,datatree,openfile,29919,"Great Minds Drink Alike")
	characterquests.charquestprint(count,datatree,openfile,29940,"Taking a Crop")
	characterquests.charquestprint(count,datatree,openfile,29944,"Leaders Among Breeders")
	characterquests.charquestprint(count,datatree,openfile,29945,"Yellow and Red Make Orange")
	characterquests.charquestprint(count,datatree,openfile,29946,"The Warren-Mother")
	characterquests.charquestprint(count,datatree,openfile,29947,"Crouching Carrot, Hidden Turnip")
	characterquests.charquestprint(count,datatree,openfile,29948,"Thieves to the Core")
	characterquests.charquestprint(count,datatree,openfile,29949,"Legacy")
	characterquests.charquestprint(count,datatree,openfile,29950,"Li Li's Day Off")
	characterquests.charquestprint(count,datatree,openfile,29951,"Muddy Water")
	characterquests.charquestprint(count,datatree,openfile,29952,"Broken Dreams")
	characterquests.charquestprint(count,datatree,openfile,29981,"Stemming the Swarm")
	characterquests.charquestprint(count,datatree,openfile,29982,"Evacuation Orders")
	characterquests.charquestprint(count,datatree,openfile,29983,"The Hidden Master")
	characterquests.charquestprint(count,datatree,openfile,29984,"Unyielding Fists: Trial of Bamboo")
	characterquests.charquestprint(count,datatree,openfile,29985,"They Will Be Mist")
	characterquests.charquestprint(count,datatree,openfile,29986,"Fog Wards")
	characterquests.charquestprint(count,datatree,openfile,29987,"Unyielding Fists: Trial of Wood")
	characterquests.charquestprint(count,datatree,openfile,29988,"A Taste For Eggs")
	characterquests.charquestprint(count,datatree,openfile,29989,"Unyielding Fists: Trial of Stone")
	characterquests.charquestprint(count,datatree,openfile,29990,"Training and Discipline")
	characterquests.charquestprint(count,datatree,openfile,29992,"Tenderpaw By Name, Tender Paw By Reputation")
	characterquests.charquestprint(count,datatree,openfile,30028,"Grain Recovery")
	characterquests.charquestprint(count,datatree,openfile,30029,"Wee Little Shenanigans")
	characterquests.charquestprint(count,datatree,openfile,30030,"Out of Sprite")
	characterquests.charquestprint(count,datatree,openfile,30031,"Taste Test")
	characterquests.charquestprint(count,datatree,openfile,30032,"The Quest for Better Barley")
	characterquests.charquestprint(count,datatree,openfile,30046,"Chen's Resolution")
	characterquests.charquestprint(count,datatree,openfile,30047,"The Chen Taste Test")
	characterquests.charquestprint(count,datatree,openfile,30048,"Li Li and the Grain")
	characterquests.charquestprint(count,datatree,openfile,30049,"Doesn't Hold Water")
	characterquests.charquestprint(count,datatree,openfile,30050,"Gardener Fran and the Watering Can")
	characterquests.charquestprint(count,datatree,openfile,30051,"The Great Water Hunt")
	characterquests.charquestprint(count,datatree,openfile,30052,"Weed War")
	characterquests.charquestprint(count,datatree,openfile,30053,"Hop Hunting")
	characterquests.charquestprint(count,datatree,openfile,30054,"Enough is Ookin' Enough")
	characterquests.charquestprint(count,datatree,openfile,30055,"Stormstout's Hops")
	characterquests.charquestprint(count,datatree,openfile,30056,"The Farmer's Daughter")
	characterquests.charquestprint(count,datatree,openfile,30057,"Seeing Orange")
	characterquests.charquestprint(count,datatree,openfile,30058,"Mothallus!")
	characterquests.charquestprint(count,datatree,openfile,30059,"The Moth Rebellion")
	characterquests.charquestprint(count,datatree,openfile,30072,"Where Silk Comes From")
	characterquests.charquestprint(count,datatree,openfile,30073,"The Emperor")
	characterquests.charquestprint(count,datatree,openfile,30074,"Knocking on the Door")
	characterquests.charquestprint(count,datatree,openfile,30075,"Clear the Way")
	characterquests.charquestprint(count,datatree,openfile,30076,"The Fanciest Water")
	characterquests.charquestprint(count,datatree,openfile,30077,"Barrels, Man")
	characterquests.charquestprint(count,datatree,openfile,30078,"Cleaning House")
	characterquests.charquestprint(count,datatree,openfile,30086,"The Search for the Hidden Master")
	characterquests.charquestprint(count,datatree,openfile,30117,"Stoneplow Thirsts")
	characterquests.charquestprint(count,datatree,openfile,30172,"Barreling Along")
	characterquests.charquestprint(count,datatree,openfile,30181,"Mushan Mastery")
	characterquests.charquestprint(count,datatree,openfile,30182,"Fox Mastery")
	characterquests.charquestprint(count,datatree,openfile,30183,"Stalker Mastery")
	characterquests.charquestprint(count,datatree,openfile,30184,"Mushan Mastery: Darkhide")
	characterquests.charquestprint(count,datatree,openfile,30185,"Tortoise Mastery")
	characterquests.charquestprint(count,datatree,openfile,30186,"Parental Mastery")
	characterquests.charquestprintfaction(count,datatree,openfile,30241,"Warn Stoneplow","horde")
	characterquests.charquestprint(count,datatree,openfile,30252,"A Helping Hand")
	characterquests.charquestprint(count,datatree,openfile,30254,"Learn and Grow II: Tilling and Planting")
	characterquests.charquestprint(count,datatree,openfile,30255,"Learn and Grow III: Tending Crops")
	characterquests.charquestprint(count,datatree,openfile,30256,"Learn and Grow IV: Harvesting")
	characterquests.charquestprint(count,datatree,openfile,30257,"Learn and Grow V: Halfhill Market")
	characterquests.charquestprint(count,datatree,openfile,30258,"Mung-Mung's Vote I: A Hozen's Problem")
	characterquests.charquestprint(count,datatree,openfile,30259,"Mung-Mung's Vote II: Rotten to the Core")
	characterquests.charquestprint(count,datatree,openfile,30260,"Growing the Farm I: The Weeds")
	characterquests.charquestprint(count,datatree,openfile,30267,"Watery Woes")
	characterquests.charquestprint(count,datatree,openfile,30275,"A Crocolisk Tale")
	characterquests.charquestprint(count,datatree,openfile,30325,"Where It Counts")
	characterquests.charquestprint(count,datatree,openfile,30326,"The Kunzen Legend-Chief")
	characterquests.charquestprint(count,datatree,openfile,30334,"Stealing is Bad... Re-Stealing is OK")
	characterquests.charquestprintfaction(count,datatree,openfile,30360,"Warn Stoneplow","alliance")
	characterquests.charquestprint(count,datatree,openfile,30376,"Hope Springs Eternal")
	characterquests.charquestprint(count,datatree,openfile,30516,"Growing the Farm I: A Little Problem")
	characterquests.charquestprint(count,datatree,openfile,30517,"Farmer Fung's Vote I: Yak Attack")
	characterquests.charquestprint(count,datatree,openfile,30518,"Farmer Fung's Vote II: On the Loose")
	characterquests.charquestprint(count,datatree,openfile,30519,"Nana's Vote I: Nana's Secret Recipe")
	characterquests.charquestprint(count,datatree,openfile,30521,"Haohan's Vote I: Bungalow Break-In")
	characterquests.charquestprint(count,datatree,openfile,30522,"Haohan's Vote II: The Real Culprits")
	characterquests.charquestprint(count,datatree,openfile,30523,"Growing the Farm II: The Broken Wagon")
	characterquests.charquestprint(count,datatree,openfile,30524,"Growing the Farm II: Knock on Wood")
	characterquests.charquestprint(count,datatree,openfile,30525,"Haohan's Vote III: Pure Poison")
	characterquests.charquestprint(count,datatree,openfile,30526,"Lost and Lonely")
	characterquests.charquestprint(count,datatree,openfile,30527,"Haohan's Vote IV: Melons For Felons")
	characterquests.charquestprint(count,datatree,openfile,30528,"Haohan's Vote V: Chief Yip-Yip")
	characterquests.charquestprint(count,datatree,openfile,30529,"Growing the Farm III: The Mossy Boulder")
	characterquests.charquestprint(count,datatree,openfile,30534,"A Second Hand")
	characterquests.charquestprint(count,datatree,openfile,30535,"Learn and Grow I: Seeds")
	characterquests.charquestprint(count,datatree,openfile,30622,"The Swarm Begins")
	characterquests.charquestprint(count,datatree,openfile,30623,"The Mantidote")
	characterquests.charquestprintfaction(count,datatree,openfile,30624,"It Does You No Good In The Keg","alliance")
	characterquests.charquestprint(count,datatree,openfile,30625,"Students No More")
	characterquests.charquestprint(count,datatree,openfile,30626,"Retreat!")
	characterquests.charquestprint(count,datatree,openfile,30627,"The Savior of Stoneplow")
	characterquests.charquestprint(count,datatree,openfile,30628,"The Gratitude of Stoneplow")
	characterquests.charquestprintfaction(count,datatree,openfile,30653,"It Does You No Good In The Keg","horde")
	characterquests.charquestprint(count,datatree,openfile,31312,"The Old Map")
	characterquests.charquestprint(count,datatree,openfile,31313,"Just A Folk Story")
	characterquests.charquestprint(count,datatree,openfile,31314,"Old Man Thistle's Treasure")
	characterquests.charquestprint(count,datatree,openfile,31315,"The Heartland Legacy")
	characterquests.charquestprint(count,datatree,openfile,31320,"Buy A Fish A Drink?")
	characterquests.charquestprint(count,datatree,openfile,31321,"Buy A Fish A Round?")
	characterquests.charquestprint(count,datatree,openfile,31322,"Buy A Fish A Keg?")
	characterquests.charquestprint(count,datatree,openfile,31323,"Buy A Fish A Brewery?")
	characterquests.charquestprint(count,datatree,openfile,31325,"A Very Nice Necklace")
	characterquests.charquestprint(count,datatree,openfile,31326,"Tina's Tasteful Tiara")
	characterquests.charquestprint(count,datatree,openfile,31328,"An Exquisite Earring")
	characterquests.charquestprint(count,datatree,openfile,31329,"A Beautiful Brooch")
	characterquests.charquestprint(count,datatree,openfile,31338,"Lost Sheepie")
	characterquests.charquestprint(count,datatree,openfile,31339,"Lost Sheepie... Again")
	characterquests.charquestprint(count,datatree,openfile,31340,"Oh Sheepie...")
	characterquests.charquestprint(count,datatree,openfile,31341,"A Wolf In Sheep's Clothing")
	characterquests.charquestprintfaction(count,datatree,openfile,31372,"The Tillers","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31374,"The Tillers","horde")
	characterquests.charquestprint(count,datatree,openfile,31529,"Mission: Culling The Vermin")
	characterquests.charquestprint(count,datatree,openfile,31530,"Mission: The Hozen Dozen")
	characterquests.charquestprint(count,datatree,openfile,31531,"Mission: Aerial Threat")
	characterquests.charquestprint(count,datatree,openfile,31532,"Mission: Predator of the Cliffs")
	characterquests.charquestprint(count,datatree,openfile,31534,"The Beginner's Brew")
	characterquests.charquestprint(count,datatree,openfile,31537,"Ella's Taste Test")
	characterquests.charquestprint(count,datatree,openfile,31538,"A Worthy Brew")
	characterquests.charquestprint(count,datatree,openfile,31671,"Why Not Scallions?")
	characterquests.charquestprint(count,datatree,openfile,31936,"The \\\"Jinyu Princess\\\" Irrigation System")
	characterquests.charquestprint(count,datatree,openfile,31937,"Thunder King Pest Repellers")
	characterquests.charquestprint(count,datatree,openfile,31938,"The \\\"Earth-Slasher\\\" Master Plow")
	characterquests.charquestprint(count,datatree,openfile,31945,"Learn and Grow VI: Gina's Vote")
	characterquests.charquestprint(count,datatree,openfile,31946,"Mung-Mung's Vote III: The Great Carrot Caper")
	characterquests.charquestprint(count,datatree,openfile,31947,"Farmer Fung's Vote III: Crazy For Cabbage")
	characterquests.charquestprint(count,datatree,openfile,31948,"Nana's Vote II: The Sacred Springs")
	characterquests.charquestprint(count,datatree,openfile,31949,"Nana's Vote III: Witchberry Julep")
	characterquests.charquestprint(count,datatree,openfile,32018,"His Name Was... Stormstout")
	characterquests.charquestprint(count,datatree,openfile,32019,"They Call Him... Stormstout")
	characterquests.charquestprint(count,datatree,openfile,32035,"Got Silk?")
	characterquests.charquestprint(count,datatree,openfile,32038,"Stag Mastery")
	characterquests.charquestprint(count,datatree,openfile,32045,"Children of the Water")
	characterquests.charquestprint(count,datatree,openfile,32189,"A Shabby New Face")
	characterquests.charquestprint(count,datatree,openfile,32198,"One Magical, Flying Kingdom's Trash...")
	characterquests.charquestprint(count,datatree,openfile,32682,"Inherit the Earth")
	characterquests.charquestprint(count,datatree,openfile,38935,"His Name Was... Stormstout")
	characterquests.charquestprintfaction(count,datatree,openfile,49539,"Warchief's Command: Valley of the Four Winds!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,49557,"Hero's Call: Valley of the Four Winds!","alliance")

def z_81_90_Krasarang_Wilds(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"81-90: Krasarang Wilds",openfile)
	characterquests.charquestprint(count,datatree,openfile,29873,"Ken-Ken")
	characterquests.charquestprintfaction(count,datatree,openfile,29874,"Kang Bramblestaff","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29875,"Kang Bramblestaff","horde")
	characterquests.charquestprint(count,datatree,openfile,30079,"What's Eating Zhu's Watch?")
	characterquests.charquestprint(count,datatree,openfile,30080,"Finding Yi-Mo")
	characterquests.charquestprint(count,datatree,openfile,30081,"Materia Medica")
	characterquests.charquestprint(count,datatree,openfile,30082,"Cheer Up, Yi-Mo")
	characterquests.charquestprint(count,datatree,openfile,30083,"Securing the Province")
	characterquests.charquestprint(count,datatree,openfile,30084,"Borderlands")
	characterquests.charquestprint(count,datatree,openfile,30088,"Why So Serious?")
	characterquests.charquestprint(count,datatree,openfile,30089,"Apply Directly to the Forehead")
	characterquests.charquestprint(count,datatree,openfile,30090,"Zhu's Despair")
	characterquests.charquestprint(count,datatree,openfile,30091,"Tears of Pandaria")
	characterquests.charquestprintfaction(count,datatree,openfile,30121,"Search Party","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30123,"Skitterer Stew","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30124,"Blind Them!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30127,"Threat from Dojan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30128,"The Pools of Youth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30129,"The Mogu Agenda","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30130,"Herbal Remedies","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30131,"Life","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30132,"Going West","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30133,"Into the Wilds","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30163,"For the Tribe","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30164,"The Stoneplow Convoy","horde")
	characterquests.charquestprint(count,datatree,openfile,30168,"Thieving Raiders")
	characterquests.charquestprint(count,datatree,openfile,30169,"Raid Leader Slovan")
	characterquests.charquestprintfaction(count,datatree,openfile,30174,"For Family","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30175,"The Mantid","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30178,"Into the Wilds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30179,"Poisoned!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30229,"The Greater Danger","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30230,"Re-Reclaim","horde")
	characterquests.charquestprint(count,datatree,openfile,30268,"The Murksweats")
	characterquests.charquestprint(count,datatree,openfile,30269,"Unsafe Passage")
	characterquests.charquestprint(count,datatree,openfile,30270,"Blinding the Riverblades")
	characterquests.charquestprint(count,datatree,openfile,30271,"Sha Can Awe")
	characterquests.charquestprint(count,datatree,openfile,30272,"Striking the Rain")
	characterquests.charquestprint(count,datatree,openfile,30273,"In the House of the Red Crane")
	characterquests.charquestprint(count,datatree,openfile,30274,"The Arcanic Oubliette")
	characterquests.charquestprintfaction(count,datatree,openfile,30344,"The Lost Dynasty","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30346,"Where are the Pools","alliance")
	characterquests.charquestprint(count,datatree,openfile,30347,"The Pools of Youth")
	characterquests.charquestprintfaction(count,datatree,openfile,30348,"Immortality?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30349,"Threat from Dojan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30350,"Squirmy Delight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30351,"Lotus Tea","alliance")
	characterquests.charquestprint(count,datatree,openfile,30352,"Crane Mastery")
	characterquests.charquestprint(count,datatree,openfile,30353,"Profit Mastery")
	characterquests.charquestprintfaction(count,datatree,openfile,30354,"No Sister Left Behind","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30355,"Re-Reclaim","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30356,"Sever Their Supply Line","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30357,"The Stoneplow Convoy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30359,"The Lord Reclaimer","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30361,"The Mantid","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30363,"Going on the Offensive","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30384,"Blind Them!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30445,"The Waters of Youth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30461,"Into the Wilds","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30462,"Into the Wilds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30464,"Going West","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30465,"Going on the Offensive","alliance")
	characterquests.charquestprint(count,datatree,openfile,30666,"Sudden, Unexpected Crocolisk Aggression")
	characterquests.charquestprint(count,datatree,openfile,30667,"Particular Plumage")
	characterquests.charquestprint(count,datatree,openfile,30668,"Build Your Own Raft")
	characterquests.charquestprint(count,datatree,openfile,30669,"The Lorewalker on the Lake")
	characterquests.charquestprint(count,datatree,openfile,30671,"Wisdom Has A Price")
	characterquests.charquestprint(count,datatree,openfile,30672,"Balance")
	characterquests.charquestprint(count,datatree,openfile,30674,"Balance Without Violence")
	characterquests.charquestprint(count,datatree,openfile,30675,"Buried Hozen Treasure")
	characterquests.charquestprint(count,datatree,openfile,30691,"Misery")
	characterquests.charquestprint(count,datatree,openfile,30694,"Tread Lightly")
	characterquests.charquestprint(count,datatree,openfile,30695,"Ahead on the Way")
	characterquests.charquestprint(count,datatree,openfile,31260,"Profit Mastery: Chasheen")
	characterquests.charquestprint(count,datatree,openfile,31262,"Crane Mastery: Needlebeak")
	characterquests.charquestprintfaction(count,datatree,openfile,31369,"The Anglers","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31370,"The Anglers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,49540,"Warchief's Command: Krasarang Wilds!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,49558,"Hero's Call: Krasarang Wilds!","alliance")

def z_82_90_KunLai_Summit(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"82-90: KunLai Summit",openfile)
	characterquests.charquestprint(count,datatree,openfile,30457,"Call Out Their Leader")
	characterquests.charquestprint(count,datatree,openfile,30459,"All of the Arrows")
	characterquests.charquestprint(count,datatree,openfile,30460,"Hit Medicine")
	characterquests.charquestprint(count,datatree,openfile,30467,"My Son...")
	characterquests.charquestprint(count,datatree,openfile,30468,"Enraged Vengeance")
	characterquests.charquestprint(count,datatree,openfile,30469,"Repossession")
	characterquests.charquestprint(count,datatree,openfile,30480,"The Ritual")
	characterquests.charquestprint(count,datatree,openfile,30487,"Comin' Round the Mountain")
	characterquests.charquestprint(count,datatree,openfile,30488,"The Missing Muskpaw")
	characterquests.charquestprint(count,datatree,openfile,30489,"Fresh Needle Scent")
	characterquests.charquestprint(count,datatree,openfile,30490,"Yakity Yak")
	characterquests.charquestprint(count,datatree,openfile,30491,"At the Yak Wash")
	characterquests.charquestprint(count,datatree,openfile,30492,"Back in Yak")
	characterquests.charquestprint(count,datatree,openfile,30496,"The Waterspeaker's Staff")
	characterquests.charquestprintfaction(count,datatree,openfile,30506,"Admiral Taylor has Awakened","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30507,"Admiral Taylor has Awakened","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30508,"Admiral Taylor has Awakened","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30509,"General Nazgrim has Awakened","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30510,"General Nazgrim has Awakened","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30511,"General Nazgrim has Awakened","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30512,"Westwind Rest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30513,"Eastwind Rest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30514,"Challenge Accepted","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30515,"Challenge Accepted","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30569,"Trouble on the Farmstead","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30570,"Trouble on the Farmstead","horde")
	characterquests.charquestprint(count,datatree,openfile,30571,"Farmhand Freedom")
	characterquests.charquestprintfaction(count,datatree,openfile,30575,"Round 'Em Up","alliance")
	characterquests.charquestprint(count,datatree,openfile,30581,"... and the Pot, Too!")
	characterquests.charquestprint(count,datatree,openfile,30582,"The Late Mrs. Muskpaw")
	characterquests.charquestprintfaction(count,datatree,openfile,30583,"Blue Dwarf Needs Food Badly","alliance")
	characterquests.charquestprint(count,datatree,openfile,30587,"Yakity Yak")
	characterquests.charquestprint(count,datatree,openfile,30592,"The Burlap Trail: To Burlap Waystation")
	characterquests.charquestprintfaction(count,datatree,openfile,30593,"Deanimate the Reanimated","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30594,"Deanimate the Reanimated","horde")
	characterquests.charquestprint(count,datatree,openfile,30595,"Profiting off of the Past")
	characterquests.charquestprint(count,datatree,openfile,30596,"A Zandalari Troll?")
	characterquests.charquestprint(count,datatree,openfile,30599,"A Monkey Idol")
	characterquests.charquestprint(count,datatree,openfile,30600,"No Pack Left Behind")
	characterquests.charquestprint(count,datatree,openfile,30601,"Instant Courage")
	characterquests.charquestprint(count,datatree,openfile,30602,"The Rabbitsfoot")
	characterquests.charquestprint(count,datatree,openfile,30603,"The Broketooth Ravage")
	characterquests.charquestprint(count,datatree,openfile,30604,"Breaking Broketooth")
	characterquests.charquestprint(count,datatree,openfile,30605,"Bros Before Hozen")
	characterquests.charquestprint(count,datatree,openfile,30606,"Thumping Knucklethump")
	characterquests.charquestprint(count,datatree,openfile,30607,"Hozen Love Their Keys")
	characterquests.charquestprint(count,datatree,openfile,30608,"The Snackrifice")
	characterquests.charquestprint(count,datatree,openfile,30610,"Grummle! Grummle! Grummle!")
	characterquests.charquestprint(count,datatree,openfile,30611,"Unleash The Yeti!")
	characterquests.charquestprint(count,datatree,openfile,30612,"The Leader Hozen")
	characterquests.charquestprint(count,datatree,openfile,30614,"Oil Stop")
	characterquests.charquestprint(count,datatree,openfile,30615,"A Zandalari Troll?")
	characterquests.charquestprint(count,datatree,openfile,30616,"Traffic Issues")
	characterquests.charquestprint(count,datatree,openfile,30617,"Roadside Assistance")
	characterquests.charquestprint(count,datatree,openfile,30618,"Resupplying One Keg")
	characterquests.charquestprintfaction(count,datatree,openfile,30619,"Mogu?! Oh No-gu!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30620,"Mogu?! Oh No-gu!","horde")
	characterquests.charquestprint(count,datatree,openfile,30621,"They Stole My Luck!")
	characterquests.charquestprintfaction(count,datatree,openfile,30650,"Pandaren Prisoners","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30651,"Barrels of Fun","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30652,"In Tents Channeling","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30655,"Pandaren Prisoners","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30656,"Barrels of Fun","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,30657,"In Tents Channeling","horde")
	characterquests.charquestprint(count,datatree,openfile,30660,"The Ordo Warbringer")
	characterquests.charquestprint(count,datatree,openfile,30661,"The Ordo Warbringer")
	characterquests.charquestprintfaction(count,datatree,openfile,30662,"The Ordo Warbringer","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,30663,"The Ordo Warbringer","horde")
	characterquests.charquestprint(count,datatree,openfile,30665,"The Defense of Shado-Pan Fallback")
	characterquests.charquestprint(count,datatree,openfile,30670,"Turnabout")
	characterquests.charquestprint(count,datatree,openfile,30673,"Holed Up")
	characterquests.charquestprint(count,datatree,openfile,30680,"Holed Up")
	characterquests.charquestprint(count,datatree,openfile,30681,"Holed Up")
	characterquests.charquestprint(count,datatree,openfile,30682,"Holed Up")
	characterquests.charquestprint(count,datatree,openfile,30683,"One Traveler's Misfortune")
	characterquests.charquestprint(count,datatree,openfile,30684,"Seeker's Folly")
	characterquests.charquestprint(count,datatree,openfile,30690,"Unmasking the Yaungol")
	characterquests.charquestprint(count,datatree,openfile,30692,"The Burlap Trail: To Kota Basecamp")
	characterquests.charquestprint(count,datatree,openfile,30699,"To Winter's Blossom")
	characterquests.charquestprint(count,datatree,openfile,30710,"Provoking the Trolls")
	characterquests.charquestprint(count,datatree,openfile,30715,"A Line Unbroken")
	characterquests.charquestprint(count,datatree,openfile,30723,"Honor, Even in Death")
	characterquests.charquestprint(count,datatree,openfile,30724,"To the Wall!")
	characterquests.charquestprint(count,datatree,openfile,30742,"Shut it Down")
	characterquests.charquestprint(count,datatree,openfile,30743,"Gourmet Kafa")
	characterquests.charquestprint(count,datatree,openfile,30744,"Kota Blend")
	characterquests.charquestprint(count,datatree,openfile,30745,"Trouble Brewing")
	characterquests.charquestprint(count,datatree,openfile,30746,"A Fair Trade")
	characterquests.charquestprint(count,datatree,openfile,30747,"The Burlap Grind")
	characterquests.charquestprint(count,datatree,openfile,30750,"Off the Wall!")
	characterquests.charquestprint(count,datatree,openfile,30751,"A Terrible Sacrifice")
	characterquests.charquestprint(count,datatree,openfile,30752,"Unbelievable!")
	characterquests.charquestprint(count,datatree,openfile,30765,"Regaining Honor")
	characterquests.charquestprint(count,datatree,openfile,30766,"Profiting off of the Past")
	characterquests.charquestprint(count,datatree,openfile,30794,"Emergency Care")
	characterquests.charquestprint(count,datatree,openfile,30795,"Staying Connected")
	characterquests.charquestprint(count,datatree,openfile,30796,"An End to Everything")
	characterquests.charquestprint(count,datatree,openfile,30797,"It Was Almost Alive")
	characterquests.charquestprint(count,datatree,openfile,30798,"Breaking the Emperor's Shield")
	characterquests.charquestprint(count,datatree,openfile,30799,"The Tomb of Shadows")
	characterquests.charquestprint(count,datatree,openfile,30800,"Stealing Their Thunder King")
	characterquests.charquestprint(count,datatree,openfile,30801,"Lessons from History")
	characterquests.charquestprint(count,datatree,openfile,30802,"Chasing the Storm")
	characterquests.charquestprint(count,datatree,openfile,30804,"The Fearmaster")
	characterquests.charquestprint(count,datatree,openfile,30805,"Justice")
	characterquests.charquestprint(count,datatree,openfile,30806,"The Scent of Life")
	characterquests.charquestprint(count,datatree,openfile,30807,"By the Falls, For the Fallen")
	characterquests.charquestprint(count,datatree,openfile,30808,"A Grummle's Luck")
	characterquests.charquestprint(count,datatree,openfile,30816,"Checking In")
	characterquests.charquestprint(count,datatree,openfile,30819,"Preparing the Remains")
	characterquests.charquestprint(count,datatree,openfile,30820,"A Funeral")
	characterquests.charquestprint(count,datatree,openfile,30821,"The Burlap Grind")
	characterquests.charquestprint(count,datatree,openfile,30823,"Shut it Down")
	characterquests.charquestprint(count,datatree,openfile,30824,"Gourmet Kafa")
	characterquests.charquestprint(count,datatree,openfile,30825,"Kota Blend")
	characterquests.charquestprint(count,datatree,openfile,30826,"Trouble Brewing")
	characterquests.charquestprint(count,datatree,openfile,30828,"Cleansing the Mere")
	characterquests.charquestprint(count,datatree,openfile,30829,"The Tongue of Ba-Shon")
	characterquests.charquestprint(count,datatree,openfile,30834,"Father and Child Reunion")
	characterquests.charquestprint(count,datatree,openfile,30855,"The Fall of Shai Hu")
	characterquests.charquestprint(count,datatree,openfile,30879,"Round 1: Brewmaster Chani")
	characterquests.charquestprint(count,datatree,openfile,30880,"Round 1: The Streetfighter")
	characterquests.charquestprint(count,datatree,openfile,30881,"Round 2: Clever Ashyo &amp; Ken-Ken")
	characterquests.charquestprint(count,datatree,openfile,30882,"Round 2: Kang Bramblestaff")
	characterquests.charquestprint(count,datatree,openfile,30883,"Round 3: The Wrestler")
	characterquests.charquestprint(count,datatree,openfile,30885,"Round 3: Master Boom Boom")
	characterquests.charquestprint(count,datatree,openfile,30902,"Round 4: Master Windfur")
	characterquests.charquestprint(count,datatree,openfile,30907,"Round 4: The P.U.G.")
	characterquests.charquestprint(count,datatree,openfile,30935,"Fisherman's Tale")
	characterquests.charquestprint(count,datatree,openfile,30942,"Make A Fighter Out of Me")
	characterquests.charquestprint(count,datatree,openfile,30943,"Handle With Care")
	characterquests.charquestprint(count,datatree,openfile,30944,"It Takes A Village")
	characterquests.charquestprint(count,datatree,openfile,30945,"What's Yours Is Mine")
	characterquests.charquestprint(count,datatree,openfile,30946,"Revelations")
	characterquests.charquestprint(count,datatree,openfile,30967,"Free the Dissenters")
	characterquests.charquestprint(count,datatree,openfile,30991,"Do a Barrel Roll!")
	characterquests.charquestprint(count,datatree,openfile,30992,"Finish This!")
	characterquests.charquestprint(count,datatree,openfile,30993,"Where are My Reinforcements?")
	characterquests.charquestprint(count,datatree,openfile,30994,"Lao-Chin's Gambit")
	characterquests.charquestprint(count,datatree,openfile,30999,"Path Less Traveled")
	characterquests.charquestprint(count,datatree,openfile,31011,"Enemies At Our Door")
	characterquests.charquestprint(count,datatree,openfile,31207,"The Arena of Annihilation")
	characterquests.charquestprint(count,datatree,openfile,31228,"Prophet Khar'zul")
	characterquests.charquestprintfaction(count,datatree,openfile,31251,"Best Meals Anywhere!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31252,"Back to Westwind Rest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31253,"Back to Eastwind Rest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31254,"The Road to Kun-Lai","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31255,"The Road to Kun-Lai","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31256,"Round 'Em Up","horde")
	characterquests.charquestprint(count,datatree,openfile,31285,"The Spring Drifter")
	characterquests.charquestprint(count,datatree,openfile,31286,"Robbing Robbers of Robbers")
	characterquests.charquestprint(count,datatree,openfile,31287,"Educating Saurok")
	characterquests.charquestprint(count,datatree,openfile,31306,"Seeker's Folly")
	characterquests.charquestprint(count,datatree,openfile,31380,"Trial At The Temple of the White Tiger")
	characterquests.charquestprint(count,datatree,openfile,31381,"Trial At The Temple of the White Tiger")
	characterquests.charquestprintfaction(count,datatree,openfile,31392,"Temple of the White Tiger","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31393,"Temple of the White Tiger","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31394,"A Celestial Experience","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31395,"A Celestial Experience","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31451,"The Missing Merchant","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31452,"The Missing Merchant","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31453,"The Shado-Pan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31455,"The Shado-Pan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31456,"Muskpaw Ranch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,31457,"Muskpaw Ranch","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31459,"Cho's Missive","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31460,"Cho's Missive","alliance")
	characterquests.charquestprint(count,datatree,openfile,31492,"The Torch of Strength")
	characterquests.charquestprintfaction(count,datatree,openfile,31511,"A Witness to History","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31512,"A Witness to History","alliance")
	characterquests.charquestprint(count,datatree,openfile,31517,"Contending With Bullies")
	characterquests.charquestprint(count,datatree,openfile,31518,"The Vale of Eternal Blossoms")
	characterquests.charquestprint(count,datatree,openfile,38936,"The Road to Kun-Lai")
	characterquests.charquestprintfaction(count,datatree,openfile,49541,"Warchief's Command: Kun-Lai Summit!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,49559,"Hero's Call: Kun-Lai Summit!","alliance")

def z_83_90_Townlong_Steppes(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"83-90: Townlong Steppes",openfile)

def z_84_90_Dread_Wastes(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"84-90: Dread Wastes",openfile)

def z_85_90_Vale_of_Eternal_Blossoms(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"85-90: Vale of Eternal Blossoms",openfile)

def z_85_90_Isle_of_Thunder(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"85-90: Isle of Thunder",openfile)

def z_85_90_Timeless_Isle(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"85-90: Timeless Isle",openfile)

def z_85_90_Pandaren_Campaign(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"85-90: Pandaren Campaign",openfile)
