import characterquests
from characterutil import *

def z_90_Blasted_Lands_Intro(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"90: Blasted Lands: Warlords Intro",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,35460,"Attack of the Iron Horde","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35745,"Attack of the Iron Horde","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35462,"Under Siege","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35746,"Under Siege","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35463,"Subversive Scouts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35748,"Subversive Scouts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35464,"Ending Executions","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35744,"Ending Executions","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35486,"Lunatic Lieutenants","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35750,"Lunatic Lieutenants","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35488,"Death to the Dreadmaul","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35762,"Death to the Dreadmaul","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35492,"For Nethergarde!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35751,"Attack on Nethergarde","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35494,"Mementos of the Fallen","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35761,"Ransacking Nethergarde","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35495,"Toothsmash the Annihilator","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35760,"Toothsmash the Annihilator","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35496,"Enohar's Revenge","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35764,"Okrilla's Revenge","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35500,"Gar'mak Bladetwist","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35763,"Gar'mak Bladetwist","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36292,"Investigating the Invasion","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36307,"Investigating the Invasion","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36379,"Peeking into the Portal","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36382,"Peeking into the Portal","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36498,"Iron Horde Invasion","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36499,"Iron Horde Invasion","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36941,"Report to the King","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36940,"Warning Orgrimmar","horde")

def z_90_Assault_The_Dark_Portal(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"90: Warlords Intro: Assault on the Dark Portal",openfile)
	characterquests.charquestprint(count,datatree,openfile,34398,"The Dark Portal")
	characterquests.charquestprint(count,datatree,openfile,36881,"The Dark Portal")
	characterquests.charquestprint(count,datatree,openfile,35933,"Azeroth's Last Stand")
	characterquests.charquestprint(count,datatree,openfile,34392,"Onslaught's End")
	characterquests.charquestprint(count,datatree,openfile,34393,"The Portal's Power")
	characterquests.charquestprint(count,datatree,openfile,34420,"The Cost of War")
	characterquests.charquestprint(count,datatree,openfile,34422,"Blaze of Glory")
	characterquests.charquestprintfaction(count,datatree,openfile,35242,"Vengeance for the Fallen","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35241,"Vengeance for the Fallen","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35240,"Bled Dry","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34421,"Bled Dry","horde")
	characterquests.charquestprint(count,datatree,openfile,34423,"Altar Altercation")
	characterquests.charquestprint(count,datatree,openfile,34425,"The Kargathar Proving Grounds")
	characterquests.charquestprintfaction(count,datatree,openfile,34427,"A Potential Ally","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34478,"A Potential Ally","alliance")
	characterquests.charquestprint(count,datatree,openfile,34429,"Kill Your Hundred")
	characterquests.charquestprintfaction(count,datatree,openfile,34431,"Masters of Shadow","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34737,"Masters of Shadow","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34432,"The Shadowmoon Clan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34739,"The Shadowmoon Clan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34434,"Yrel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34740,"Yrel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34436,"Keli'dan the Breaker","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34741,"Keli'dan the Breaker","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35019,"Prepare for Battle","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35005,"Prepare for Battle","horde")
	characterquests.charquestprint(count,datatree,openfile,34439,"The Battle of the Forge")
	characterquests.charquestprint(count,datatree,openfile,34442,"Ga'nar of the Frostwolf")
	characterquests.charquestprint(count,datatree,openfile,34987,"The Gunpowder Plot")
	characterquests.charquestprint(count,datatree,openfile,34958,"The Shadow of the Worldbreaker")
	characterquests.charquestprint(count,datatree,openfile,34925,"Polishing the Iron Throne")
	characterquests.charquestprint(count,datatree,openfile,34437,"The Prodigal Frostwolf")
	characterquests.charquestprint(count,datatree,openfile,35747,"Taking a Trip to the Top of the Tank")
	characterquests.charquestprint(count,datatree,openfile,34445,"A Taste of Iron")
	characterquests.charquestprintfaction(count,datatree,openfile,35884,"The Home Stretch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34446,"The Home Stretch","horde")

def z_90_100_Frostfire_Ridge(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"90-100: Frostfire Ridge",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,34228,"A Clew of Worms","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34067,"A Collection of Coils","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34264,"A Collection of Coils","horde")
	characterquests.charquestprint(count,datatree,openfile,33957,"A Gift for Raa'la")
	characterquests.charquestprintfaction(count,datatree,openfile,34592,"A Gronnling Problem","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33125,"A Proper Parting","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33815,"A Song of Frost and Fire","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39676,"A True Naval Commander","horde")
	characterquests.charquestprint(count,datatree,openfile,35346,"Abatha, the Alchemist")
	characterquests.charquestprintfaction(count,datatree,openfile,34280,"All is Revealed","horde")
	characterquests.charquestprint(count,datatree,openfile,35292,"Ang'kra, the Alchemist")
	characterquests.charquestprintfaction(count,datatree,openfile,33344,"Armed and Dangerous","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32804,"Articles of the Fallen","horde")
	characterquests.charquestprint(count,datatree,openfile,34321,"Ashes Of The Past")
	characterquests.charquestprintfaction(count,datatree,openfile,34070,"At the End of Your Rope","horde")
	characterquests.charquestprint(count,datatree,openfile,37014,"Auctioning for Parts")
	characterquests.charquestprintfaction(count,datatree,openfile,33473,"Back to Bladespire Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34375,"Back to Work","horde")
	characterquests.charquestprint(count,datatree,openfile,33443,"Barrier Destroyed")
	characterquests.charquestprint(count,datatree,openfile,34730,"Blood Oath of Lokra")
	characterquests.charquestprintfaction(count,datatree,openfile,34729,"Blood Oath of Na'Shra","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36345,"Breaking into the Trap Game","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34073,"Burn Them Down","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33546,"Deeds Left Undone","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35341,"Defection of Gronnstalker Rokash","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34379,"Den of Wolves","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34278,"Desecration of the Dead","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39401,"Destroying the Competition","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36137,"Easing into Lumberjacking","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34292,"Eliminate the Shadow Council","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34293,"Eliminate the Shadow Council","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34063,"Enemies Above","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32994,"Enfilade","horde")
	characterquests.charquestprint(count,datatree,openfile,34473,"Envoy's Log")
	characterquests.charquestprintfaction(count,datatree,openfile,39675,"Equipping Our Fleet","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34378,"Establish Your Garrison","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34230,"Eye Need That","horde")
	characterquests.charquestprint(count,datatree,openfile,34325,"Flames Of The Earth")
	characterquests.charquestprintfaction(count,datatree,openfile,34364,"For the Horde!","horde")
	characterquests.charquestprint(count,datatree,openfile,34505,"Forbidden Glacier")
	characterquests.charquestprintfaction(count,datatree,openfile,33807,"Free Our Brothers and Sisters","horde")
	characterquests.charquestprint(count,datatree,openfile,34501,"Frostbite Hollow")
	characterquests.charquestprintfaction(count,datatree,openfile,34346,"Frosted Fury","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32783,"Ga'nar's Vengeance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34069,"Getting the Points","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34093,"Getting the Points","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33784,"Gormaul Tower","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33408,"Great Balls of Fire!","horde")
	characterquests.charquestprint(count,datatree,openfile,33145,"Grimfrost Hill")
	characterquests.charquestprint(count,datatree,openfile,37919,"Gronnsbane: The Blessing of Beasts")
	characterquests.charquestprint(count,datatree,openfile,37995,"Gronnsbane: The Blessing of Beasts")
	characterquests.charquestprint(count,datatree,openfile,37917,"Gronnsbane: The Blessing of Fire")
	characterquests.charquestprint(count,datatree,openfile,37918,"Gronnsbane: The Blessing of Frost")
	characterquests.charquestprint(count,datatree,openfile,37916,"Gronnsbane: The Broken Spear")
	characterquests.charquestprint(count,datatree,openfile,39651,"Grumpus")
	characterquests.charquestprintfaction(count,datatree,openfile,33132,"Gut Guttra","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34291,"Have a Heart","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33816,"Honor Has Its Rewards","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39604,"I Sunk Your Battleship","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39674,"If At First You Fail, Try Again!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32991,"Into the Boneslag","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33785,"Karg Unchained","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33527,"Last Steps","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32792,"Leave Nothing Behind!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32791,"Let the Hunt Begin!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39236,"Let's Get To Work","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37060,"Lost in Transition","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34344,"Lurkers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33955,"Missing Pack","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34079,"Mission Successful","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33412,"Mopping Up","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33657,"Moving In","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32992,"Moving Target","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34732,"Mulverick's Offer of Service","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33483,"Mulverick's Plight","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39243,"Naval Commander","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39246,"Naval Domination","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34731,"Oath of Shadow Hunter Rala","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33013,"Of Fire and Thunder","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34402,"Of Wolves and Warriors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32981,"Only the Winner","horde")
	characterquests.charquestprint(count,datatree,openfile,36296,"Phylarch the Evergreen")
	characterquests.charquestprintfaction(count,datatree,openfile,33470,"Pool of Visions","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34345,"Poulticide","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34380,"Rally the Frostwolves","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33493,"Return to the Pack","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34216,"Safe Passage","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37045,"Salvaging the Situation","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34066,"Savage Vengeance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33468,"Save Wolf Home","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37043,"Scraps of Iron","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37092,"Scraps of Iron","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32989,"Securing the South","horde")
	characterquests.charquestprint(count,datatree,openfile,34733,"Services of Dagg")
	characterquests.charquestprintfaction(count,datatree,openfile,36142,"Sharper Blades, Bigger Timber","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39242,"Ship Shape","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39241,"Shipbuilding","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33929,"Shivertail's Den","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33119,"Slavery and Strife","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33898,"Slaying Slavers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33838,"Smeltcraft","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34277,"Stop the Flow","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36972,"Talbuk Training: Rakkiri","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37094,"Talbuk Training: Rakkiri","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34072,"Tar Get of Opportunity","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34124,"The Battle of Thunder Pass","horde")
	characterquests.charquestprint(count,datatree,openfile,34588,"The Bounty of Bladespire")
	characterquests.charquestprintfaction(count,datatree,openfile,33410,"The Butcher of Bladespire","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33454,"The Cure","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35243,"The Dark Lady's Gift","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34765,"The Den of Skog","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32795,"The Eldest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33467,"The Fall of the Warlord","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33469,"The Farseer","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34294,"The Fel Crystals","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37563,"The Frostwolves Stand Ready","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37046,"The Headhunter's Harvest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37119,"The Headhunter's Harvest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33868,"The Home of the Frostwolves","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33010,"The Iron Wolf","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34960,"The Land Provides","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34102,"The Mark of Defiance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33828,"The Master Siegesmith","horde")
	characterquests.charquestprint(count,datatree,openfile,34377,"The Portal Home")
	characterquests.charquestprintfaction(count,datatree,openfile,34348,"The Real Prey","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36427,"The Rise and Fall of Barov Industries: Alexi Barov","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36429,"The Rise and Fall of Barov Industries: Weldon Barov","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33484,"The Slavemaster's Demise","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34229,"The Sleeper Has Awakened","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32993,"The Strength of Our Bonds","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33450,"The Warlord's Guard","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33526,"These Colors Don't Run","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32929,"They Rely on Numbers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32990,"They Who Held Fast","horde")
	characterquests.charquestprint(count,datatree,openfile,33441,"Thrall Vision")
	characterquests.charquestprint(count,datatree,openfile,33462,"Thunderlord for a Day")
	characterquests.charquestprintfaction(count,datatree,openfile,34295,"To Capture Gul'dan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32796,"To the Garrison","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33622,"To the Slaughter","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34123,"To Thunder Pass","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36182,"Tree-i-cide","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37062,"Tricks of the Trade","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37088,"Tricks of the Trade","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36138,"Turning Timber into Profit","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,39245,"Upgrading The Fleet","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34209,"Vouchsafe Our Arrival","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34075,"Vul'gath's End","horde")
	characterquests.charquestprint(count,datatree,openfile,33918,"WANTED: Grondo's Bounty")
	characterquests.charquestprint(count,datatree,openfile,33919,"WANTED: Gutsmash the Destroyer")
	characterquests.charquestprintfaction(count,datatree,openfile,49545,"Warchief's Command: Frostfire Ridge!","horde")
	characterquests.charquestprint(count,datatree,openfile,36874,"Warlord of Draenor")
	characterquests.charquestprintfaction(count,datatree,openfile,34736,"We Be Needin' Supplies","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34227,"What Must Be Done","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33826,"Where's My Wolf?!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32794,"Wrath of Gronn","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33915,"Young Hearts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36912,"Capturing a Clefthoof","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36916,"Capturing a Clefthoof","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36984,"Clefthoof Training: Rakkiri","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37049,"Clefthoof Training: Rakkiri","horde")
	characterquests.charquestprint(count,datatree,openfile,36894,"Nemesis Flag, Draenei/Blood Elf")
	characterquests.charquestprint(count,datatree,openfile,36891,"Nemesis Flag, Dwarf/Forsaken")
	characterquests.charquestprint(count,datatree,openfile,36892,"Nemesis Flag, Gnome/Tauren")
	characterquests.charquestprint(count,datatree,openfile,36956,"Nemesis Flag, Human")
	characterquests.charquestprint(count,datatree,openfile,36890,"Nemesis Flag, Human/Orc")
	characterquests.charquestprint(count,datatree,openfile,36893,"Nemesis Flag, Night Elf/Troll")
	characterquests.charquestprint(count,datatree,openfile,36896,"Nemesis Flag, Pandaren (A/H)")
	characterquests.charquestprint(count,datatree,openfile,36895,"Nemesis Flag, Worgen/Goblin")
	characterquests.charquestprint(count,datatree,openfile,36897,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36923,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36925,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36927,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36929,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36931,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36933,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36930,"Nemesis: Draenei Destroyer")
	characterquests.charquestprint(count,datatree,openfile,36924,"Nemesis: Dwarfstalker")
	characterquests.charquestprint(count,datatree,openfile,36926,"Nemesis: Gnomebane")
	characterquests.charquestprint(count,datatree,openfile,36889,"Nemesis: Hunter - Hunted")
	characterquests.charquestprint(count,datatree,openfile,36921,"Nemesis: Manslayer")
	characterquests.charquestprint(count,datatree,openfile,36932,"Nemesis: Scourge of the Kaldorei")
	characterquests.charquestprint(count,datatree,openfile,36934,"Nemesis: Terror of the Tushui")
	characterquests.charquestprint(count,datatree,openfile,36928,"Nemesis: Worgen Hunter")
	characterquests.charquestprintfaction(count,datatree,openfile,37961,"Bringing the Bass","horde")

def z_90_100_Shadowmoon_Valley(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"90-100: Shadowmoon Valley",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,33059,"The Fate of Karabor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33062,"Catching His Eye","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33066,"Soul Shards of Summoning","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33070,"Think of the Children!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33072,"Into Twilight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33075,"A Hero's Welcome","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33076,"The Clarity Elixir","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33077,"A Grandmother's Remedy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33078,"The Dark that Blinds Us","alliance")
	characterquests.charquestprint(count,datatree,openfile,33079,"The Demons Among Us - Alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33080,"Going Undercover","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33081,"Escape From Shaz'gul","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33082,"Ancestor's Memory","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33083,"On the Offensive","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33084,"The Big Haul","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33111,"Bounty: Twisted Ancient","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33112,"Ominous Portents","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33113,"Shadowmoonwell","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33114,"Forging the Soul Trap","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33115,"Shrouding Stones","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33116,"To Catch a Shadow","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33120,"A Curse Upon the Woods","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33135,"Cleaning Up Gul'var","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33168,"Heart On Fire","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33255,"The Righteous March","alliance")
	characterquests.charquestprint(count,datatree,openfile,33256,"The Defense of Karabor")
	characterquests.charquestprintfaction(count,datatree,openfile,33263,"Gloomshade Grove","alliance")
	characterquests.charquestprint(count,datatree,openfile,33266,"A Light in the Dark - Tracking Quest")
	characterquests.charquestprintfaction(count,datatree,openfile,33269,"Cleaning Up Gul'var","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33271,"Game of Thorns","alliance")
	characterquests.charquestprint(count,datatree,openfile,33323,"Finale - Tracking Quest")
	characterquests.charquestprintfaction(count,datatree,openfile,33331,"Captured Critters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33359,"Meet Us at Starfall Outpost","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33419,"A Matter of Life and Death","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33461,"Gloomshade Game Hunter","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33586,"Chasing Shadows","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33765,"Dark Enemies","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33782,"Keeping the Balance","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33786,"Crippled Caravan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33787,"Fiona's Solution","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33788,"Cooking With Unstable Herbs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33793,"Harbingers of the Void","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33794,"The Great Salvation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33795,"Across the Stars","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33808,"Swamplighter Queen","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33813,"In Need of a Hero","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33814,"Fast Expansion","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33833,"WANTED: Kuu'rat's Tusks","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33834,"WANTED: Kliaa's Stinger","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33836,"WANTED: Maa'run's Hoof","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33837,"Darkness Falls","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33905,"Closing the Door","alliance")
	characterquests.charquestprint(count,datatree,openfile,33910,"Aklana Rescue")
	characterquests.charquestprintfaction(count,datatree,openfile,34019,"Shadows Awaken","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34043,"Darkest Night","alliance")
	characterquests.charquestprint(count,datatree,openfile,34054,"The Dark Side of the Moon")
	characterquests.charquestprint(count,datatree,openfile,34076,"The Burial Fields")
	characterquests.charquestprint(count,datatree,openfile,34077,"Trouble to the South")
	characterquests.charquestprint(count,datatree,openfile,34496,"The Hills of Valuun")
	characterquests.charquestprint(count,datatree,openfile,34504,"Bloodthorn Cave")
	characterquests.charquestprint(count,datatree,openfile,34575,"Step Three: Prophet!")
	characterquests.charquestprintfaction(count,datatree,openfile,34582,"Finding a Foothold","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34583,"For the Alliance!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34584,"Looking for Lumber","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34585,"Quakefist","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34616,"Ravenous Ravens","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34646,"Qiana Moonshadow","alliance")
	characterquests.charquestprint(count,datatree,openfile,34728,"The Shimmer Moor")
	characterquests.charquestprintfaction(count,datatree,openfile,34778,"Migrant Workers","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34779,"Circle the Wagon","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34780,"Invisible Ramparts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34781,"Defenstrations","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34782,"The Exarch Council","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34783,"Naielle, The Rangari","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34784,"Fun with Fungus","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34785,"Hataaru, the Artificer","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34786,"Engorged Goren","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34787,"Exarch Maladaar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34788,"Friend of the Exarchs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34789,"Speaker for the Dead","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34790,"The Sting","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34791,"Warning the Exarchs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34792,"The Traitor's True Name","alliance")
	characterquests.charquestprint(count,datatree,openfile,34806,"Prune the Podlings")
	characterquests.charquestprintfaction(count,datatree,openfile,34820,"Lost Lumberjacks","alliance")
	characterquests.charquestprint(count,datatree,openfile,34836,"Lunarblossom")
	characterquests.charquestprint(count,datatree,openfile,34847,"Forbidden Love")
	characterquests.charquestprint(count,datatree,openfile,34876,"Loola's Lost Love")
	characterquests.charquestprintfaction(count,datatree,openfile,34897,"Rangari Roundup","alliance")
	characterquests.charquestprint(count,datatree,openfile,34994,"Forever Young")
	characterquests.charquestprintfaction(count,datatree,openfile,34995,"Botani Beatdown","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34996,"Rotting Riverbeasts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34997,"Slumberbloom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35006,"Poison Paralysis","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35014,"Blademoon Bloom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35015,"Gestating Genesaur","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35032,"Into Anguish","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35070,"Shut 'er Down","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35093,"The Dark Side of the Moon","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35166,"Ship Salvage","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35174,"Pale Moonlight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35176,"Keeping it Together","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35444,"The Southern Wilds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35450,"The Southern Wilds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35459,"The Southern Wilds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35552,"Trust No One","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35614,"Artificer Romuul","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35617,"Fiona","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35618,"Gidwin Goldbraids","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35621,"Tarenar Sunstrike","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35625,"Shelly Hamby","alliance")
	characterquests.charquestprint(count,datatree,openfile,35626,"Apprentice Artificer Andren")
	characterquests.charquestprint(count,datatree,openfile,35628,"Rangari Chel")
	characterquests.charquestprint(count,datatree,openfile,35629,"Vindicator Onaala")
	characterquests.charquestprintfaction(count,datatree,openfile,35631,"Rulkan","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35905,"Supply Drop","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36189,"Easing into Lumberjacking","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36192,"Turning Timber into Profit","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36194,"Sharper Blades, Bigger Timber","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36195,"Tree-i-cide","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36271,"Breaking into the Trap Game","alliance")
	characterquests.charquestprint(count,datatree,openfile,36876,"Warlord of Draenor")
	characterquests.charquestprintfaction(count,datatree,openfile,36911,"Taming a Talbuk","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36917,"Taming a Talbuk","horde")
	characterquests.charquestprint(count,datatree,openfile,36948,"Auctioning for Parts")
	characterquests.charquestprint(count,datatree,openfile,36955,"Nemesis: Hunter - Hunted")
	characterquests.charquestprint(count,datatree,openfile,36957,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36958,"Nemesis: Slayer of Sin'dorei")
	characterquests.charquestprint(count,datatree,openfile,36959,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36960,"Nemesis: Death Stalker")
	characterquests.charquestprint(count,datatree,openfile,36961,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36962,"Nemesis: The Butcher")
	characterquests.charquestprint(count,datatree,openfile,36963,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36964,"Nemesis: Orcslayer")
	characterquests.charquestprint(count,datatree,openfile,36965,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36966,"Nemesis: Troll Hunter")
	characterquests.charquestprint(count,datatree,openfile,36967,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36968,"Nemesis: Huojin's Fall")
	characterquests.charquestprint(count,datatree,openfile,36969,"Nemesis: Becoming Death")
	characterquests.charquestprint(count,datatree,openfile,36970,"Nemesis: Killer of Kezan")
	characterquests.charquestprintfaction(count,datatree,openfile,36971,"Talbuk Training: Great-Tusk","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36983,"Clefthoof Training: Great-Tusk","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37048,"Clefthoof Training: Great-Tusk","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37086,"Salvaging the Situation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37087,"Lost in Transition","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37093,"Talbuk Training: Great-Tusk","horde")
	characterquests.charquestprint(count,datatree,openfile,37113,"Thisalee Crow")
	characterquests.charquestprint(count,datatree,openfile,37114,"Choluna")
	characterquests.charquestprintfaction(count,datatree,openfile,37322,"The Prophet's Final Message","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37332,"Fungal Bundle","alliance")
	characterquests.charquestprint(count,datatree,openfile,37882,"Dark Grimoire: The First Ingredient")
	characterquests.charquestprint(count,datatree,openfile,37883,"Dark Grimoire: The Second Ingredient")
	characterquests.charquestprint(count,datatree,openfile,37884,"Dark Grimoire: The Final Ingredient")
	characterquests.charquestprint(count,datatree,openfile,37885,"Dark Grimoire: Breaching the Barrier")
	characterquests.charquestprint(count,datatree,openfile,37976,"Dream of Argus: The First Fragment")
	characterquests.charquestprint(count,datatree,openfile,37977,"Dream of Argus: The Second Fragment")
	characterquests.charquestprint(count,datatree,openfile,37978,"Dream of Argus: The Final Fragment")
	characterquests.charquestprint(count,datatree,openfile,37979,"Dream of Argus: The Crystal Reborn")
	characterquests.charquestprint(count,datatree,openfile,37994,"Dark Grimoire: Breaching the Barrier")
	characterquests.charquestprint(count,datatree,openfile,37997,"Dream of Argus: The Crystal Reborn")
	characterquests.charquestprint(count,datatree,openfile,39054,"Shipbuilding")
	characterquests.charquestprint(count,datatree,openfile,39055,"Ship Shape")
	characterquests.charquestprint(count,datatree,openfile,39056,"Naval Commander")
	characterquests.charquestprint(count,datatree,openfile,39067,"Upgrading The Fleet")
	characterquests.charquestprint(count,datatree,openfile,39068,"Naval Domination")
	characterquests.charquestprint(count,datatree,openfile,39082,"Let's Get To Work")
	characterquests.charquestprint(count,datatree,openfile,39276,"Strange Tools")
	characterquests.charquestprint(count,datatree,openfile,39404,"Destroying the Competition")
	characterquests.charquestprint(count,datatree,openfile,39601,"I Sunk Your Battleship")
	characterquests.charquestprint(count,datatree,openfile,39655,"If At First You Fail, Try Again!")
	characterquests.charquestprint(count,datatree,openfile,39665,"A True Naval Commander")
	characterquests.charquestprint(count,datatree,openfile,39666,"Equipping Our Fleet")
	characterquests.charquestprint(count,datatree,openfile,39721,"Culling the Crew")
	characterquests.charquestprintfaction(count,datatree,openfile,49562,"Hero's Call: Shadowmoon Valley!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,38356,"Bringing the Bass","alliance")

def z_92_100_Gorgrond(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"92-100: Gorgrond",openfile)
	characterquests.charquestprint(count,datatree,openfile,36037,"A Centurion Without a Cause")
	characterquests.charquestprintfaction(count,datatree,openfile,33593,"A Flare for the Dramatic","horde")
	characterquests.charquestprint(count,datatree,openfile,35210,"A Great Escape")
	characterquests.charquestprintfaction(count,datatree,openfile,36482,"A Green Ogron?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36523,"A Green Ogron?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35030,"A Grim Harvest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35647,"A Grim Harvest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35248,"A Harsh Reminder","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35693,"A Harsh Reminder","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35065,"A Harvester Has Come","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35031,"A Heartfelt Search","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35656,"A Heartfelt Search","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35225,"A Heavy Helping Hand","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34697,"A Rediscovered Legend","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,34704,"A Rediscovered Legend","alliance")
	characterquests.charquestprint(count,datatree,openfile,36249,"Active Choice: Lumber Mill")
	characterquests.charquestprint(count,datatree,openfile,36250,"Active Choice: Lumber Mill")
	characterquests.charquestprint(count,datatree,openfile,36251,"Active Choice: Sparring Arena")
	characterquests.charquestprint(count,datatree,openfile,36252,"Active Choice: Sparring Arena")
	characterquests.charquestprint(count,datatree,openfile,36473,"Affliction Ridge")
	characterquests.charquestprintfaction(count,datatree,openfile,33685,"Ambassador to the Ancient","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36437,"Ambassador to the Ancient","alliance")
	characterquests.charquestprint(count,datatree,openfile,39309,"Arcane Orb")
	characterquests.charquestprint(count,datatree,openfile,39310,"Artillery Strike")
	characterquests.charquestprint(count,datatree,openfile,35037,"Bad at Breaking")
	characterquests.charquestprintfaction(count,datatree,openfile,35016,"Basic Skulltaking","horde")
	characterquests.charquestprint(count,datatree,openfile,35870,"Basilisk Butcher")
	characterquests.charquestprintfaction(count,datatree,openfile,33662,"Beatface vs. Boulder","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36438,"Beatface vs. Boulder","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36913,"Besting a Boar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36944,"Besting a Boar","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36995,"Boar Training: Riplash","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37032,"Boar Training: Riplash","horde")
	characterquests.charquestprint(count,datatree,openfile,39308,"Bodyguard")
	characterquests.charquestprint(count,datatree,openfile,36603,"Brimstone Springs")
	characterquests.charquestprintfaction(count,datatree,openfile,35205,"Burn the Bodies","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35206,"Bushwhacker","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35432,"Bushwhacker","horde")
	characterquests.charquestprint(count,datatree,openfile,39306,"Call to Arms")
	characterquests.charquestprint(count,datatree,openfile,35730,"Cauterizing Wounds")
	characterquests.charquestprintfaction(count,datatree,openfile,35136,"Chains of Iron","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35702,"Chains of Iron","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35508,"Chapter I: Plant Food","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35654,"Chapter I: Plant Food","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35527,"Chapter II: The Harvest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35651,"Chapter II: The Harvest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35524,"Chapter III: Ritual of the Charred","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35650,"Chapter III: Ritual of the Charred","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35027,"Clearing the Way","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36985,"Clefthoof Training: Riplash","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37050,"Clefthoof Training: Riplash","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35207,"Coalpart's Revenge","alliance")
	characterquests.charquestprint(count,datatree,openfile,34412,"Creature Treasure: Gnarljaw")
	characterquests.charquestprint(count,datatree,openfile,34411,"Creature Treasure: King Slime")
	characterquests.charquestprintfaction(count,datatree,openfile,35433,"Cut Them Down","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35430,"Cutter","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35208,"Dark Iron Down","alliance")
	characterquests.charquestprint(count,datatree,openfile,39287,"Deathtalon")
	characterquests.charquestprintfaction(count,datatree,openfile,35212,"Deeproot","alliance")
	characterquests.charquestprint(count,datatree,openfile,39289,"Doomroller")
	characterquests.charquestprintfaction(count,datatree,openfile,35501,"Doomshot","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35229,"Down the Goren Hole","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35507,"Down the Goren Hole","horde")
	characterquests.charquestprint(count,datatree,openfile,40105,"Drakum")
	characterquests.charquestprint(count,datatree,openfile,36504,"Evermorn Springs")
	characterquests.charquestprintfaction(count,datatree,openfile,33563,"Eye Candy","horde")
	characterquests.charquestprint(count,datatree,openfile,35139,"Eye in the Sky")
	characterquests.charquestprint(count,datatree,openfile,35128,"Fair Warning")
	characterquests.charquestprintfaction(count,datatree,openfile,36272,"Feeding An Army","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36344,"Feeding An Army","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36832,"Get the Xuk Outta Here!","horde")
	characterquests.charquestprint(count,datatree,openfile,34699,"Getting Gladiators")
	characterquests.charquestprint(count,datatree,openfile,40106,"Gondar")
	characterquests.charquestprintfaction(count,datatree,openfile,33544,"Goren, Goren, Gone!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35506,"Growing Wood","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35652,"Growing Wood","alliance")
	characterquests.charquestprint(count,datatree,openfile,40074,"Guk")
	characterquests.charquestprintfaction(count,datatree,openfile,36210,"Hard Shell","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36595,"He Drew Aggro...culture","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35040,"Heart of the Fen","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35659,"Heart of the Fen","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,49564,"Hero's Call: Gorgrond!","alliance")
	characterquests.charquestprint(count,datatree,openfile,34279,"I Am Blook")
	characterquests.charquestprintfaction(count,datatree,openfile,35828,"I Drew Aggro...culture","alliance")
	characterquests.charquestprint(count,datatree,openfile,35218,"Iron Horde Orders")
	characterquests.charquestprintfaction(count,datatree,openfile,35036,"Is This One of Yours?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36508,"Is This One of Yours?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35235,"Iyu","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35510,"Iyu","horde")
	characterquests.charquestprint(count,datatree,openfile,36571,"Iyun Weald")
	characterquests.charquestprintfaction(count,datatree,openfile,36460,"Just Another Stick in the Wall","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35233,"Just In Case","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35511,"Kaz the Shrieker","horde")
	characterquests.charquestprint(count,datatree,openfile,34702,"Krav'ogra")
	characterquests.charquestprintfaction(count,datatree,openfile,33706,"Laying Dionor to Rest","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36443,"Laying Dionor to Rest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35129,"Leave Every Soldier Behind","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36223,"Leave Every Soldier Behind","alliance")
	characterquests.charquestprint(count,datatree,openfile,35505,"Lost Lumberjack")
	characterquests.charquestprintfaction(count,datatree,openfile,36368,"Lost Lumberjack","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35055,"Lost Mole Machines","alliance")
	characterquests.charquestprint(count,datatree,openfile,34992,"Lumber Mill")
	characterquests.charquestprint(count,datatree,openfile,35049,"Lumber Mill")
	characterquests.charquestprintfaction(count,datatree,openfile,36828,"Lumber, I Hardly Knew 'Er","alliance")
	characterquests.charquestprint(count,datatree,openfile,34413,"Lumberstruck")
	characterquests.charquestprintfaction(count,datatree,openfile,36833,"May I Be of Service?","alliance")
	characterquests.charquestprint(count,datatree,openfile,39307,"Mechasuit")
	characterquests.charquestprintfaction(count,datatree,openfile,35644,"Mercy for the Living","alliance")
	characterquests.charquestprint(count,datatree,openfile,36563,"Mistcreep Mire")
	characterquests.charquestprintfaction(count,datatree,openfile,35399,"Mossy Fate","horde")
	characterquests.charquestprint(count,datatree,openfile,40107,"Mudlump")
	characterquests.charquestprintfaction(count,datatree,openfile,35021,"Mysterious Pod","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35642,"Mysterious Pod","alliance")
	characterquests.charquestprint(count,datatree,openfile,34700,"Nazgrel")
	characterquests.charquestprint(count,datatree,openfile,34012,"Need More Teeth")
	characterquests.charquestprint(count,datatree,openfile,35934,"Nisha's Vengeance")
	characterquests.charquestprint(count,datatree,openfile,35026,"On the Mend")
	characterquests.charquestprintfaction(count,datatree,openfile,35946,"Peckers the Majestic","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36812,"Penny For Your Thoughts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36434,"Penny From Heaven","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33689,"Plant Pruning","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36436,"Plant Pruning","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35204,"Pollen Power","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35429,"Pollen Power","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35255,"Power of the Genesaur","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35416,"Power of the Genesaur","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36092,"Proof of Strength: Ancient Branch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36094,"Proof of Strength: Ancient Branch","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36103,"Proof of Strength: Basilisk Scale","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36104,"Proof of Strength: Basilisk Scale","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36084,"Proof of Strength: Botani Bloom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36086,"Proof of Strength: Botani Bloom","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36105,"Proof of Strength: Elemental Crystal","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36106,"Proof of Strength: Elemental Crystal","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35944,"Proof of Strength: Goren Tooth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35948,"Proof of Strength: Goren Tooth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36081,"Proof of Strength: Gronn Eye","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36083,"Proof of Strength: Gronn Eye","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36078,"Proof of Strength: Gronnling Scale","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36080,"Proof of Strength: Gronnling Scale","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36075,"Proof of Strength: Ogron Horn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36076,"Proof of Strength: Ogron Horn","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36090,"Proof of Strength: Orc Thorn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36091,"Proof of Strength: Orc Thorn","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36096,"Proof of Strength: Ravager Claw","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36097,"Proof of Strength: Ravager Claw","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36098,"Proof of Strength: Wasp Stinger","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36101,"Proof of Strength: Wasp Stinger","horde")
	characterquests.charquestprint(count,datatree,openfile,40073,"Pugg")
	characterquests.charquestprintfaction(count,datatree,openfile,35686,"Rage and Wisdom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35880,"Rage and Wisdom","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35666,"Rangari in the Red","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33694,"Reagents from Rakthoth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36441,"Reclaiming Property","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35050,"Rescue Rangari","alliance")
	characterquests.charquestprint(count,datatree,openfile,33633,"Rooter the Ravenous")
	characterquests.charquestprint(count,datatree,openfile,35881,"Ruins of the First Bastion")
	characterquests.charquestprint(count,datatree,openfile,40075,"Rukdug")
	characterquests.charquestprintfaction(count,datatree,openfile,36440,"Saberon Population Reduction","alliance")
	characterquests.charquestprint(count,datatree,openfile,33705,"Sacking the Saberon Stronghold")
	characterquests.charquestprintfaction(count,datatree,openfile,35633,"Scout Forensics","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35536,"Secrets of the Botani","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35035,"Seedbearers of Bad News","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35664,"Seedbearers of Bad News","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36432,"Seeking the Scout","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35262,"Service of Rangari Kaalya","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33663,"Shredder vs. Saberon","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36439,"Shredder vs. Saberon","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35667,"Skulltakers in Crimson Fen","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35017,"Skulltaker's Revenge","horde")
	characterquests.charquestprint(count,datatree,openfile,34698,"Slave Hunters")
	characterquests.charquestprint(count,datatree,openfile,40104,"Smashum Grabb")
	characterquests.charquestprint(count,datatree,openfile,36476,"South Gronn Canyon")
	characterquests.charquestprint(count,datatree,openfile,35064,"Sparring Arena")
	characterquests.charquestprint(count,datatree,openfile,35149,"Sparring Arena")
	characterquests.charquestprintfaction(count,datatree,openfile,33661,"Steamscar \\\"Reagents\\\"","horde")
	characterquests.charquestprint(count,datatree,openfile,36566,"Stonemaul Arena")
	characterquests.charquestprintfaction(count,datatree,openfile,36573,"Strike While the Iron is Hot","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36574,"Strike While the Iron is Hot","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36575,"Strike While the Iron is Hot","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36576,"Strike While the Iron is Hot","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35216,"Super Seeds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35406,"Super Seeds","horde")
	characterquests.charquestprint(count,datatree,openfile,36520,"Tailthrasher Basin")
	characterquests.charquestprintfaction(count,datatree,openfile,33695,"Taking the Death Bloom","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36442,"Taking the Death Bloom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36973,"Talbuk Training: Riplash","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37095,"Talbuk Training: Riplash","horde")
	characterquests.charquestprint(count,datatree,openfile,39128,"Tanaan Vignette")
	characterquests.charquestprintfaction(count,datatree,openfile,35707,"Tangleheart","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35708,"Tangleheart","alliance")
	characterquests.charquestprint(count,datatree,openfile,36564,"Tangleheart")
	characterquests.charquestprint(count,datatree,openfile,39288,"Terrorfist")
	characterquests.charquestprint(count,datatree,openfile,34703,"The Axe of Kor'gall")
	characterquests.charquestprintfaction(count,datatree,openfile,36208,"The Crystal Shard","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35883,"The Fists of Vaandaam","alliance")
	characterquests.charquestprint(count,datatree,openfile,34724,"The Forgotten Caves")
	characterquests.charquestprint(count,datatree,openfile,35925,"The Gronn Strategy")
	characterquests.charquestprintfaction(count,datatree,openfile,35214,"The Infested","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35400,"The Infested","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35882,"The Interest of Bruto","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33543,"The Laughing Skull","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35209,"The Life Spring","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35434,"The Life Spring","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35213,"The Razorbloom","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36474,"The Razorbloom","horde")
	characterquests.charquestprint(count,datatree,openfile,36500,"The Razorbloom")
	characterquests.charquestprintfaction(count,datatree,openfile,33660,"The Sacking of the Saberon","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35029,"The Secret of the Fungus","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35645,"The Secret of the Fungus","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,33533,"The Secrets of Gorgrond","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,34867,"The Secrets of Gorgrond","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35556,"The Secrets of Gorgrond","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35557,"The Secrets of Gorgrond","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36632,"The Secrets of Gorgrond","alliance")
	characterquests.charquestprint(count,datatree,openfile,37945,"The Silent Skull: Taking from the Taker")
	characterquests.charquestprint(count,datatree,openfile,37996,"The Silent Skull: Taking from the Taker")
	characterquests.charquestprint(count,datatree,openfile,37942,"The Silent Skull: The First Reagent")
	characterquests.charquestprint(count,datatree,openfile,37943,"The Silent Skull: The Second Reagent")
	characterquests.charquestprint(count,datatree,openfile,37944,"The Silent Skull: The Third Reagent")
	characterquests.charquestprintfaction(count,datatree,openfile,35137,"The Sparring Arena","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35152,"The Sparring Arena","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35215,"The Voice of Iyu","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35402,"The Voice of Iyu","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36488,"Thieving Dwarves","horde")
	characterquests.charquestprint(count,datatree,openfile,35701,"Tracking: Mill Treasure 1")
	characterquests.charquestprint(count,datatree,openfile,36430,"Tracking: Mill Treasure 18")
	characterquests.charquestprint(count,datatree,openfile,35703,"Tracking: Mill Treasure Barrier 1")
	characterquests.charquestprint(count,datatree,openfile,37941,"Treasure Contract: The Infected Orc")
	characterquests.charquestprint(count,datatree,openfile,36170,"Treasure: Femur of Improbability")
	characterquests.charquestprint(count,datatree,openfile,34195,"Treasure: Gorgrond Treasure 16")
	characterquests.charquestprint(count,datatree,openfile,35709,"Treasure: Laughing Skull Cache I")
	characterquests.charquestprint(count,datatree,openfile,36118,"Treasure: Pile of Rubble")
	characterquests.charquestprintfaction(count,datatree,openfile,36108,"Trophy Hunter of Gorgrond","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36502,"Trophy of Glory: Biolante","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,36503,"Trophy of Glory: Biolante","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35815,"Trophy of Glory: Charl Doomwing","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35816,"Trophy of Glory: Charl Doomwing","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35811,"Trophy of Glory: Crater Lord Igneous","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35812,"Trophy of Glory: Crater Lord Igneous","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35809,"Trophy of Glory: Dessicus","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35810,"Trophy of Glory: Dessicus","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35807,"Trophy of Glory: Erosian","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35808,"Trophy of Glory: Erosian","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35813,"Trophy of Glory: Fungal Praetorian","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35814,"Trophy of Glory: Fungal Praetorian","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35819,"Trophy of Glory: Khargax the Devourer","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35820,"Trophy of Glory: Khargax the Devourer","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35817,"Trophy of Glory: Roardan the Sky Terror","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35818,"Trophy of Glory: Roardan the Sky Terror","horde")
	characterquests.charquestprint(count,datatree,openfile,36480,"Valley of Destruction")
	characterquests.charquestprint(count,datatree,openfile,39290,"Vengeance")
	characterquests.charquestprintfaction(count,datatree,openfile,35640,"Vengeance for the Fallen","alliance")
	characterquests.charquestprint(count,datatree,openfile,38631,"Vignette: Alpha Bat")
	characterquests.charquestprint(count,datatree,openfile,35281,"Vignette: Bahameye")
	characterquests.charquestprint(count,datatree,openfile,35335,"Vignette: Bashiok")
	characterquests.charquestprint(count,datatree,openfile,38496,"Vignette: BH Master Scout")
	characterquests.charquestprint(count,datatree,openfile,38696,"Vignette: Bleeding Hollow Horror")
	characterquests.charquestprint(count,datatree,openfile,34197,"Vignette: Bloodbloom the Colossus")
	characterquests.charquestprint(count,datatree,openfile,38600,"Vignette: Fel Saberon Shaman")
	characterquests.charquestprint(count,datatree,openfile,38628,"Vignette: Giant Python")
	characterquests.charquestprint(count,datatree,openfile,38654,"Vignette: Giant Raptor")
	characterquests.charquestprint(count,datatree,openfile,34231,"Vignette: Giant Snake")
	characterquests.charquestprint(count,datatree,openfile,36204,"Vignette: Gorger the Hungry")
	characterquests.charquestprint(count,datatree,openfile,36186,"Vignette: Greldrok the Cunning")
	characterquests.charquestprint(count,datatree,openfile,34162,"Vignette: Icklarv")
	characterquests.charquestprint(count,datatree,openfile,38751,"Vignette: Iron Houndmaster")
	characterquests.charquestprint(count,datatree,openfile,38609,"Vignette: Iron Tunnel Foreman")
	characterquests.charquestprint(count,datatree,openfile,34143,"Vignette: Kal'rak the Drunk")
	characterquests.charquestprint(count,datatree,openfile,38726,"Vignette: Magwia")
	characterquests.charquestprint(count,datatree,openfile,36178,"Vignette: Mandrakor the Night Hunter")
	characterquests.charquestprint(count,datatree,openfile,34170,"Vignette: Moltnar")
	characterquests.charquestprint(count,datatree,openfile,34127,"Vignette: Mother Bloodtusk")
	characterquests.charquestprint(count,datatree,openfile,38764,"Vignette: Murktide Alpha")
	characterquests.charquestprint(count,datatree,openfile,39564,"Vignette: Murktide Alpha")
	characterquests.charquestprint(count,datatree,openfile,38632,"Vignette: Night Haunter")
	characterquests.charquestprint(count,datatree,openfile,34160,"Vignette: Nixxie the Goblin")
	characterquests.charquestprint(count,datatree,openfile,38620,"Vignette: Pale Assassin")
	characterquests.charquestprint(count,datatree,openfile,38597,"Vignette: Panther Saberon Boss")
	characterquests.charquestprint(count,datatree,openfile,39399,"Vignette: Panther Saberon Boss")
	characterquests.charquestprint(count,datatree,openfile,39400,"Vignette: Panther Saberon Boss")
	characterquests.charquestprint(count,datatree,openfile,34243,"Vignette: Rak'nar Muzzlebash")
	characterquests.charquestprint(count,datatree,openfile,38589,"Vignette: Ravager Broodlord")
	characterquests.charquestprint(count,datatree,openfile,34198,"Vignette: Roardan")
	characterquests.charquestprint(count,datatree,openfile,43740,"Vignette: Roardan")
	characterquests.charquestprint(count,datatree,openfile,38605,"Vignette: Saberon Blademaster")
	characterquests.charquestprint(count,datatree,openfile,38604,"Vignette: Saberon Shaman")
	characterquests.charquestprint(count,datatree,openfile,38812,"Vignette: Shadowthrash")
	characterquests.charquestprint(count,datatree,openfile,38700,"Vignette: Steelsnout")
	characterquests.charquestprint(count,datatree,openfile,36858,"Vignette: Steeltusk")
	characterquests.charquestprint(count,datatree,openfile,36837,"Vignette: Stompalupagus")
	characterquests.charquestprint(count,datatree,openfile,35910,"Vignette: Stomper Kreego")
	characterquests.charquestprint(count,datatree,openfile,34168,"Vignette: Stormwave")
	characterquests.charquestprint(count,datatree,openfile,36794,"Vignette: Sylldross")
	characterquests.charquestprint(count,datatree,openfile,34191,"Vignette: Un'glok Blackfinger")
	characterquests.charquestprintfaction(count,datatree,openfile,35834,"Wake of the Genesaur","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,49546,"Warchief's Command: Gorgrond!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35487,"We Burn the Dead","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,33548,"We Die Laughing!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35025,"We Have Company","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35665,"We Have Company","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35063,"We Need An Outpost","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35033,"Welcome to Gorgrond","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35038,"What the Bony Xuk?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,36209,"What's Under There?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35234,"Will of the Genesaur","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35509,"Will of the Genesaur","horde")
	characterquests.charquestprint(count,datatree,openfile,35653,"Wood is Wood")
	characterquests.charquestprintfaction(count,datatree,openfile,35041,"Xuk It!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35202,"Xuk Me, Right?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35151,"Your Base, Your Choice","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35247,"Zero Xuks Given","horde")

def z_94_100_Talador(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"94-100: Talador",openfile)

def z_96_100_Spires_of_Arak(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"96-100: Spires of Arak: Shadows Gather",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,35554,"News from Spires of Arak","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35537,"News from Spires of Arak","horde")
	characterquests.charquestprint(count,datatree,openfile,34653,"Arakkoa Exodus")
	characterquests.charquestprint(count,datatree,openfile,34655,"The Shadows of Skettis")
	characterquests.charquestprint(count,datatree,openfile,34656,"Hidden in Plain Sight")
	characterquests.charquestprint(count,datatree,openfile,34657,"Adherents of the Sun God")
	characterquests.charquestprint(count,datatree,openfile,34658,"Orders From On High")
	characterquests.charquestprint(count,datatree,openfile,34659,"The Crone")
	characterquests.charquestprint(count,datatree,openfile,34756,"A Charming Deception")
	characterquests.charquestprint(count,datatree,openfile,34805,"Echo Hunters")
	characterquests.charquestprint(count,datatree,openfile,35636,"All Due Respect")
	characterquests.charquestprint(count,datatree,openfile,35668,"Syth's Secret")
	characterquests.charquestprint(count,datatree,openfile,35671,"A Gathering of Shadows")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Admiral Taylor's Garrison",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,35293,"Old Friends","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35295,"What's Theirs is Our","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35329,"I See Dead People","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35322,"I See Dead People","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35339,"A Parting Favor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35353,"A Piece of the Puzzle","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35380,"Second in Command","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35407,"Punishable by Death","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35408,"Prime the Cannons","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35482,"Admiral Taylor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35549,"Honoring a Hero","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35550,"Surviving in a Savage Land","horde")
	characterquests.charquestprint(count,datatree,openfile,36183,"Admiral Taylor")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Establishing Axefall",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,35274,"One of Our Own","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35272,"One of Our Own","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35276,"Inspecting the Troops","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35275,"Inspecting the Troops","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35286,"Orders, Commander?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35277,"Orders, Commander?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,35699,"Peace Offering","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,35697,"Peace Offering","horde")
	characterquests.charquestprint(count,datatree,openfile,37296,"A Lack of Wasps")
	characterquests.charquestprintfaction(count,datatree,openfile,37329,"Not Here, Not Now","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37331,"Not Here, Not Now","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37328,"Not Here, Not Now","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37330,"Not Here, Not Now","horde")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Establishing Axefall: Inn",openfile)
	characterquests.charquestprint(count,datatree,openfile,35907,"Attempted Murder")
	characterquests.charquestprint(count,datatree,openfile,35915,"Attempted Murder")
	characterquests.charquestprint(count,datatree,openfile,35924,"Assassin's Mark")
	characterquests.charquestprint(count,datatree,openfile,35926,"Assassin's Mark")
	characterquests.charquestprint(count,datatree,openfile,35947,"The Power of Poison")
	characterquests.charquestprint(count,datatree,openfile,35959,"The Power of Poison")
	characterquests.charquestprint(count,datatree,openfile,36022,"Extrinsic Motivation")
	characterquests.charquestprint(count,datatree,openfile,36023,"Extrinsic Motivation")
	characterquests.charquestprint(count,datatree,openfile,36028,"Gardul Venomshiv")
	characterquests.charquestprint(count,datatree,openfile,36029,"Gardul Venomshiv")
	characterquests.charquestprint(count,datatree,openfile,36047,"We Have Him Now")
	characterquests.charquestprint(count,datatree,openfile,36048,"We Have Him Now")
	characterquests.charquestprint(count,datatree,openfile,36165,"No Time to Waste")
	characterquests.charquestprint(count,datatree,openfile,36166,"No Time to Waste")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Establishing Axefall: Trading Post",openfile)
	characterquests.charquestprint(count,datatree,openfile,35705,"Best Deals Anywhere")
	characterquests.charquestprint(count,datatree,openfile,35706,"Sticky Situation")
	characterquests.charquestprint(count,datatree,openfile,35716,"Sticky Situation")
	characterquests.charquestprint(count,datatree,openfile,35878,"Safety Measures")
	characterquests.charquestprint(count,datatree,openfile,35879,"Safety Measures")
	characterquests.charquestprint(count,datatree,openfile,35718,"Back on Track")
	characterquests.charquestprint(count,datatree,openfile,35719,"Back on Track")
	characterquests.charquestprint(count,datatree,openfile,35738,"All Natural")
	characterquests.charquestprint(count,datatree,openfile,35739,"All Natural")
	characterquests.charquestprint(count,datatree,openfile,35766,"I See Dead Arakkoa")
	characterquests.charquestprint(count,datatree,openfile,35782,"I See Dead Arakkoa")
	characterquests.charquestprint(count,datatree,openfile,35797,"The Ebon Hunter")
	characterquests.charquestprint(count,datatree,openfile,35835,"The Ebon Hunter")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Secrets of the Talonpriests",openfile)
	characterquests.charquestprint(count,datatree,openfile,35611,"Return to Veil Terokk")
	characterquests.charquestprint(count,datatree,openfile,34827,"Last of the Talonpriests")
	characterquests.charquestprint(count,datatree,openfile,34828,"Ishaal's Orb")
	characterquests.charquestprint(count,datatree,openfile,34830,"Behind the Veil")
	characterquests.charquestprint(count,datatree,openfile,34882,"Blades in the Dark")
	characterquests.charquestprint(count,datatree,openfile,34883,"A Feast of Shadows")
	characterquests.charquestprint(count,datatree,openfile,34942,"Back from Beyond")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Legacy of the Apexis",openfile)
	characterquests.charquestprint(count,datatree,openfile,35257,"Power Unearthed")
	characterquests.charquestprint(count,datatree,openfile,35258,"Legacy of the Apexis")
	characterquests.charquestprint(count,datatree,openfile,35259,"Sol Sisters")
	characterquests.charquestprint(count,datatree,openfile,35260,"Hardly Working")
	characterquests.charquestprint(count,datatree,openfile,35261,"Shot-Caller")
	characterquests.charquestprint(count,datatree,openfile,35273,"Hot Seat")
	characterquests.charquestprint(count,datatree,openfile,35634,"Control is King")
	characterquests.charquestheader(count,"96-100: Spires of Arak: The Gods of Arak",openfile)
	characterquests.charquestprint(count,datatree,openfile,34998,"Talon Watch")
	characterquests.charquestprint(count,datatree,openfile,35000,"Banished From the Sky")
	characterquests.charquestprint(count,datatree,openfile,35001,"Gaze of the Raven God")
	characterquests.charquestprint(count,datatree,openfile,35002,"Sons of Sethe")
	characterquests.charquestprint(count,datatree,openfile,35003,"Ritual Severance")
	characterquests.charquestprint(count,datatree,openfile,35004,"Servants of a Dead God")
	characterquests.charquestprint(count,datatree,openfile,35011,"The False Talon King")
	characterquests.charquestprint(count,datatree,openfile,35013,"Lithic's Gift")
	characterquests.charquestprint(count,datatree,openfile,35012,"Sethe, the Dead God")
	characterquests.charquestprint(count,datatree,openfile,35245,"A Sentimental Relic")
	characterquests.charquestheader(count,"96-100: Spires of Arak: When the Raven Swallows the Day",openfile)
	characterquests.charquestprint(count,datatree,openfile,34921,"Cult of the Ravenspeakers")
	characterquests.charquestprint(count,datatree,openfile,34991,"To the... Rescue?")
	characterquests.charquestprint(count,datatree,openfile,35010,"The High Ravenspeaker")
	characterquests.charquestprint(count,datatree,openfile,35007,"Rendezvous with the Ritualists")
	characterquests.charquestprint(count,datatree,openfile,34922,"Words of the Raven Mother")
	characterquests.charquestprint(count,datatree,openfile,34923,"The Bloodmane")
	characterquests.charquestprint(count,datatree,openfile,34924,"The Egg Thieves")
	characterquests.charquestprint(count,datatree,openfile,34938,"Ralshiara's Demise")
	characterquests.charquestprint(count,datatree,openfile,34939,"Declawing The Bloodmane")
	characterquests.charquestprint(count,datatree,openfile,36790,"The Initiate's Revenge")
	characterquests.charquestprint(count,datatree,openfile,35009,"Call of the Raven Mother")
	characterquests.charquestprint(count,datatree,openfile,36085,"On Ebon Wings")
	characterquests.charquestprint(count,datatree,openfile,35704,"When All Is Aligned")
	characterquests.charquestprint(count,datatree,openfile,37141,"Talonpriest Ishaal")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Terrok's Legend",openfile)
	characterquests.charquestprint(count,datatree,openfile,34884,"The Kaliri Whisperer")
	characterquests.charquestprint(count,datatree,openfile,34898,"Ikky")
	characterquests.charquestprint(count,datatree,openfile,34838,"Ikky's Egg")
	characterquests.charquestprint(count,datatree,openfile,34886,"Baby Bird")
	characterquests.charquestprint(count,datatree,openfile,35733,"Rites of the Talonpriests")
	characterquests.charquestprint(count,datatree,openfile,35734,"The Talon King")
	characterquests.charquestprint(count,datatree,openfile,35897,"The Missing Piece")
	characterquests.charquestprint(count,datatree,openfile,35895,"Terokk's Fall")
	characterquests.charquestprint(count,datatree,openfile,36059,"A Worthy Vessel")
	characterquests.charquestprint(count,datatree,openfile,35896,"The Avatar of Terokk")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Pinchwhistle Gearworks",openfile)
	characterquests.charquestprint(count,datatree,openfile,35619,"Pinchwhistle Gearworks")
	characterquests.charquestprint(count,datatree,openfile,35620,"Pinchwhistle Gearworks")
	characterquests.charquestprint(count,datatree,openfile,36861,"Pinchwhistle Gearworks")
	characterquests.charquestprint(count,datatree,openfile,36862,"Pinchwhistle Gearworks")
	characterquests.charquestprint(count,datatree,openfile,35077,"Defungination")
	characterquests.charquestprint(count,datatree,openfile,35079,"Spore-be-Gone")
	characterquests.charquestprint(count,datatree,openfile,36179,"Unwanted Pests")
	characterquests.charquestprint(count,datatree,openfile,35080,"The Mother Lode")
	characterquests.charquestprint(count,datatree,openfile,35082,"Getting the Crew Back Together")
	characterquests.charquestprint(count,datatree,openfile,35089,"Skimming Off the Top")
	characterquests.charquestprint(count,datatree,openfile,36384,"Field Trial")
	characterquests.charquestprint(count,datatree,openfile,35091,"Sporicide")
	characterquests.charquestprint(count,datatree,openfile,35211,"Preventing the Worst")
	characterquests.charquestprint(count,datatree,openfile,36428,"Curing With Force")
	characterquests.charquestprint(count,datatree,openfile,35298,"Flame On")
	characterquests.charquestprint(count,datatree,openfile,36062,"Kimzee Pinchwhistle")
	characterquests.charquestheader(count,"96-100: Spires of Arak: Other/Unknown",openfile)
	characterquests.charquestprint(count,datatree,openfile,34829,"New Neighbors")
	characterquests.charquestprint(count,datatree,openfile,34885,"Mother of Thorns")
	characterquests.charquestprint(count,datatree,openfile,34999,"Hatred Undying")
	characterquests.charquestprint(count,datatree,openfile,35081,"Clearing Out Before Cleaning Up")
	characterquests.charquestprint(count,datatree,openfile,35090,"The Right Parts for the Job")
	characterquests.charquestprint(count,datatree,openfile,35285,"Follow that Hotrod!")
	characterquests.charquestprint(count,datatree,openfile,35649,"The Writhing Mire")
	characterquests.charquestprint(count,datatree,openfile,35669,"Wanted: Keeho's Severed Paw")
	characterquests.charquestprint(count,datatree,openfile,35670,"Wanted: Spineslicer's Husk")
	characterquests.charquestprint(count,datatree,openfile,35672,"Wanted: Venombarb")
	characterquests.charquestprint(count,datatree,openfile,35674,"Wanted: Keeho's Severed Paw")
	characterquests.charquestprint(count,datatree,openfile,35675,"Wanted: Spineslicer's Husk")
	characterquests.charquestprint(count,datatree,openfile,35676,"Wanted: Venombarb")
	characterquests.charquestprint(count,datatree,openfile,35713,"The Tinkertoss Twins")
	characterquests.charquestprint(count,datatree,openfile,36316,"Victory is Within Reach")
	characterquests.charquestprint(count,datatree,openfile,36425,"Egg Punt")
	characterquests.charquestprint(count,datatree,openfile,36951,"Arakkoa Exodus")
	characterquests.charquestprint(count,datatree,openfile,36975,"Talbuk Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,36987,"Clefthoof Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,36997,"Boar Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37006,"Riverbeast Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37034,"Boar Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37052,"Clefthoof Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37072,"Riverbeast Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37097,"Talbuk Training: Bulbapore")
	characterquests.charquestprint(count,datatree,openfile,37144,"Talon Guard Kurekk")
	characterquests.charquestprint(count,datatree,openfile,37168,"Leorajh, the Enlightened")
	characterquests.charquestprint(count,datatree,openfile,37177,"Call of the Talon King")
	characterquests.charquestprint(count,datatree,openfile,37276,"Standing United")
	characterquests.charquestprint(count,datatree,openfile,37281,"Standing United")
	characterquests.charquestprint(count,datatree,openfile,37287,"Cleaning House")
	characterquests.charquestprint(count,datatree,openfile,37292,"Not In Your Army")
	characterquests.charquestprint(count,datatree,openfile,37326,"Befriending the Locals")
	characterquests.charquestprint(count,datatree,openfile,37327,"Befriending the Locals")
	characterquests.charquestprint(count,datatree,openfile,37416,"Feast of the Spires")
	characterquests.charquestprint(count,datatree,openfile,37417,"Feast of the Spires")

def z_98_100_Nagrand(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"98-100: Nagrand",openfile)
	characterquests.charquestprint(count,datatree,openfile,36601,"News from Nagrand")
	characterquests.charquestprint(count,datatree,openfile,36602,"News from Nagrand")
	characterquests.charquestprint(count,datatree,openfile,36606,"News from Nagrand")
	characterquests.charquestprint(count,datatree,openfile,36607,"News from Nagrand")

def z_100_Tanaan_Jungle(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"100: Tanaan Jungle",openfile)
