import characterquests
from characterutil import *

def prof_tailoring_1vanilla(count,datatree,openfile):
	characterquests.charquestheader(count,"Vanilla Tailoring",openfile)
	characterquests.charquestprint(count,datatree,openfile,6032,"Sacred Cloth")

def prof_tailoring_7legion(count,datatree,openfile):
	characterquests.charquestheader(count,"Legion Tailoring",openfile)
	characterquests.charquestprint(count,datatree,openfile,38944,"Sew It Begins")
	characterquests.charquestprint(count,datatree,openfile,38945,"This Should Be Simple... Right?")
	characterquests.charquestprint(count,datatree,openfile,38946,"Consult the Locals")
	characterquests.charquestprint(count,datatree,openfile,38947,"Runic Catgut")
	characterquests.charquestprint(count,datatree,openfile,38948,"Hard Times")
	characterquests.charquestprint(count,datatree,openfile,38949,"So You Think You Can Sew")
	characterquests.charquestprint(count,datatree,openfile,38950,"The Wayward Tailor")
	characterquests.charquestprint(count,datatree,openfile,38952,"Meticulous Precision")
	characterquests.charquestprint(count,datatree,openfile,38953,"Advanced Needlework")
	characterquests.charquestprint(count,datatree,openfile,38954,"Where's Lyndras?")
	characterquests.charquestprint(count,datatree,openfile,38955,"Sew Far, Sew Good")
	characterquests.charquestprint(count,datatree,openfile,38956,"Where's Lyndras Again?")
	characterquests.charquestprint(count,datatree,openfile,38957,"Taking Inspiration")
	characterquests.charquestprint(count,datatree,openfile,38958,"The Right Color")
	characterquests.charquestprint(count,datatree,openfile,38959,"Left Behind")
	characterquests.charquestprint(count,datatree,openfile,38960,"Lining Them Up")
	characterquests.charquestprint(count,datatree,openfile,38963,"The Final Lesson?")
	characterquests.charquestprint(count,datatree,openfile,38961,"Eye of Azshara: The Depraved Nightfallen")
	characterquests.charquestprint(count,datatree,openfile,38964,"Where's Lyndras Now?")
	characterquests.charquestprint(count,datatree,openfile,39602,"Where's Lyndras: Sewer Sleuthing")
	characterquests.charquestprint(count,datatree,openfile,39605,"Where's Lyndras: Downward Spiral")
	characterquests.charquestprint(count,datatree,openfile,39667,"Where's Lyndras: Leyflame Larceny")
	characterquests.charquestprint(count,datatree,openfile,38965,"Assault on Violet Hold: Into the Hold")
	characterquests.charquestprint(count,datatree,openfile,38966,"Secret Silkweaving Methods")
	characterquests.charquestprint(count,datatree,openfile,38962,"The Path to Suramar City")
	characterquests.charquestprint(count,datatree,openfile,38967,"The Nightborne Connection")
	characterquests.charquestprint(count,datatree,openfile,38968,"Proof of Loyalty")
	characterquests.charquestprint(count,datatree,openfile,38969,"Master of Silkweave")
	characterquests.charquestprint(count,datatree,openfile,38970,"The Queen's Grace Loom")
	characterquests.charquestprint(count,datatree,openfile,38971,"Exotic Textiles")
	characterquests.charquestprint(count,datatree,openfile,38974,"Halls of Valor: The Right Question")
	characterquests.charquestprint(count,datatree,openfile,38975,"Inspire Me!")
	characterquests.charquestprint(count,datatree,openfile,44741,"Return to Karazhan: The Big Bag Theory")
	characterquests.charquestprint(count,datatree,openfile,48074,"Looming Over Me")
