import characterquests
from characterutil import *

def legendary_cloak(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary Cloak",openfile)
	characterquests.charquestheader(count,"Chapter I: Sha Touched Gem",openfile)
	characterquests.charquestprint(count,datatree,openfile,31488,"Stranger in a Strange Land")
	characterquests.charquestprint(count,datatree,openfile,31454,"A Legend in the Making")
	characterquests.charquestprint(count,datatree,openfile,31468,"Trial of the Black Prince")
	characterquests.charquestprint(count,datatree,openfile,31473,"The Strength of One's Foes")
	characterquests.charquestprint(count,datatree,openfile,31481,"Fear Itself")
	characterquests.charquestprint(count,datatree,openfile,31482,"Breath of the Black Prince")
	characterquests.charquestheader(count,"Chapter II: Eye of the Black Prince",openfile)
	characterquests.charquestprint(count,datatree,openfile,31483,"Incoming...")
	characterquests.charquestprintfaction(count,datatree,openfile,32373,"The Measure of a Leader","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32427,"The Measure of a Leader","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32374,"The Prince's Pursuit","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32429,"The Prince's Pursuit","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32474,"A Test of Valor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32476,"A Test of Valor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32388,"A Change of Command","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32430,"A Change of Command","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32389,"The Lion Roars","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32431,"Glory to the Horde","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,32390,"Call of the Packmaster","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,32432,"The Soul of the Horde","horde")
	characterquests.charquestheader(count,"Chapter III: Legendary Meta-Gem",openfile)
	characterquests.charquestprint(count,datatree,openfile,32590,"Meet Me Upstairs")
	characterquests.charquestprint(count,datatree,openfile,32591,"Secrets of the First Empire")
	characterquests.charquestprint(count,datatree,openfile,32592,"I Need a Champion")
	characterquests.charquestprint(count,datatree,openfile,32593,"The Thunder Forge")
	characterquests.charquestprint(count,datatree,openfile,32594,"Spirit of the Storm Lord")
	characterquests.charquestprint(count,datatree,openfile,32595,"The Crown of Heaven")
	characterquests.charquestprint(count,datatree,openfile,32596,"Echoes of the Titans")
	characterquests.charquestprint(count,datatree,openfile,32597,"Heart of the Thunder King")
	characterquests.charquestheader(count,"Chapter IV: Epic Cloak",openfile)
	characterquests.charquestprint(count,datatree,openfile,32598,"A Reckoning")
	characterquests.charquestprint(count,datatree,openfile,32805,"Celestial Blessings")
	characterquests.charquestprint(count,datatree,openfile,32861,"Cloak of Virtue")
	characterquests.charquestheader(count,"Chapter V: Legendary Cloak",openfile)
	characterquests.charquestprint(count,datatree,openfile,32870,"Preparing to Strike")
	characterquests.charquestprint(count,datatree,openfile,33087,"Meet Me Back at the Inn")
	characterquests.charquestprint(count,datatree,openfile,33088,"A Timeless Discovery")
	characterquests.charquestprint(count,datatree,openfile,33098,"Secrets of the Timeless Isle")
	characterquests.charquestprint(count,datatree,openfile,33100,"The Emperor's Way")
	characterquests.charquestprint(count,datatree,openfile,33104,"A Pandaren Legend")
	characterquests.charquestprint(count,datatree,openfile,33105,"Judgment of the Black Prince")

def legendary_thunderfury(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary: Thunderfury, Blessed Blade of the Windseeker",openfile)
	characterquests.charquestprint(count,datatree,openfile,7785,"Examine the Vessel")
	characterquests.charquestprint(count,datatree,openfile,7786,"Thunderaan the Windseeker")
	characterquests.charquestprint(count,datatree,openfile,7787,"Rise, Thunderfury!")

def legendary_ring(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary Ring",openfile)
	characterquests.charquestheader(count,"Chapter I: Call of the Archmage",openfile)
	characterquests.charquestprint(count,datatree,openfile,39018,"Call of the Archmage")
	characterquests.charquestprint(count,datatree,openfile,36157,"Spires of the Betrayer")
	characterquests.charquestprint(count,datatree,openfile,35989,"Khadgar's Task")
	characterquests.charquestprint(count,datatree,openfile,35990,"Core of Flame")
	characterquests.charquestprint(count,datatree,openfile,35991,"Core of Iron")
	characterquests.charquestprint(count,datatree,openfile,35992,"Core of Life")
	characterquests.charquestprint(count,datatree,openfile,36158,"Draenor's Secret Power")
	characterquests.charquestprint(count,datatree,openfile,35993,"Tackling Teron'gor")
	characterquests.charquestprint(count,datatree,openfile,36000,"Fugitive Dragon")
	characterquests.charquestprint(count,datatree,openfile,36004,"Power Unleashed")
	characterquests.charquestheader(count,"Chapter II: Gul'dan Strikes Back",openfile)
	characterquests.charquestprint(count,datatree,openfile,35997,"Empire's Fall")
	characterquests.charquestprint(count,datatree,openfile,35998,"Legacy of the Sorcerer Kings")
	characterquests.charquestprint(count,datatree,openfile,36005,"The Scrying Game")
	characterquests.charquestprint(count,datatree,openfile,36006,"Hunter: Hunted")
	characterquests.charquestprint(count,datatree,openfile,36007,"Touch of the Kirin-Tor")
	characterquests.charquestheader(count,"Chapter III: The Foundry Falls",openfile)
	characterquests.charquestprint(count,datatree,openfile,36013,"Might of the Elemental Lords")
	characterquests.charquestprint(count,datatree,openfile,36009,"Heart of the Fury")
	characterquests.charquestprint(count,datatree,openfile,36010,"Flamebender's Tome")
	characterquests.charquestprint(count,datatree,openfile,36012,"Reverse Piracy")
	characterquests.charquestprint(count,datatree,openfile,36016,"The Unbroken Circle")
	characterquests.charquestheader(count,"Chapter IV: Darkness Incarnate",openfile)
	characterquests.charquestprint(count,datatree,openfile,36014,"Blackhand's Secret")
	characterquests.charquestprint(count,datatree,openfile,36017,"Prisoner of the Mind")
	characterquests.charquestprint(count,datatree,openfile,37835,"The Shadow War")
	characterquests.charquestprint(count,datatree,openfile,37834,"Orb of Dominion")
	characterquests.charquestprint(count,datatree,openfile,37836,"Breaking Badness")
	characterquests.charquestprint(count,datatree,openfile,37964,"To Gul'dan!")
	characterquests.charquestprint(count,datatree,openfile,37837,"An Inside Job")
	characterquests.charquestprint(count,datatree,openfile,37838,"My Garona")
	characterquests.charquestprint(count,datatree,openfile,37841,"The Final Assault")
	characterquests.charquestprint(count,datatree,openfile,39057,"Command of the Seas")
	characterquests.charquestprint(count,datatree,openfile,39697,"Master vs. Commander")
	characterquests.charquestprint(count,datatree,openfile,39000,"We Don't Need No Library Card")
	characterquests.charquestprint(count,datatree,openfile,39003,"Cooking the Books")
	characterquests.charquestprint(count,datatree,openfile,37839,"Light Be With You (Alliance)")
	characterquests.charquestprint(count,datatree,openfile,37840,"Draenor's Blessing (Horde)")
	characterquests.charquestprint(count,datatree,openfile,39004,"Darkness Incarnate")

def legendary_valanyr(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary: Val'anyr, Hammer of Ancient Kings",openfile)
	characterquests.charquestprint(count,datatree,openfile,13622,"Ancient History")
	characterquests.charquestprint(count,datatree,openfile,13629,"Val'anyr, Hammer of Ancient Kings")

def legendary_shadowmourne(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary: Shadowmourne",openfile)
	characterquests.charquestprint(count,datatree,openfile,24545,"The Sacred and the Corrupt")
	characterquests.charquestprint(count,datatree,openfile,24547,"A Feast of Souls")
	characterquests.charquestprint(count,datatree,openfile,24743,"Shadow's Edge")
	characterquests.charquestprint(count,datatree,openfile,24749,"Unholy Infusion")
	characterquests.charquestprint(count,datatree,openfile,24756,"Blood Infusion")
	characterquests.charquestprint(count,datatree,openfile,24757,"Frost Infusion")
	characterquests.charquestprint(count,datatree,openfile,24548,"The Splintered Throne")
	characterquests.charquestprint(count,datatree,openfile,24549,"Shadowmourne...")
	characterquests.charquestprint(count,datatree,openfile,24748,"The Lich King's Last Stand")
	characterquests.charquestheader(count,"Legendary: Shadowmourne: Rewards",openfile)
	characterquests.charquestprint(count,datatree,openfile,24914,"Personal Property")
	characterquests.charquestprint(count,datatree,openfile,24915,"Mograine's Reunion")
	characterquests.charquestprint(count,datatree,openfile,24916,"Jaina's Locket")
	characterquests.charquestprint(count,datatree,openfile,24917,"Muradin's Lament")
	characterquests.charquestprint(count,datatree,openfile,24918,"Sylvanas' Vengeance")
	characterquests.charquestprint(count,datatree,openfile,24919,"The Lightbringer's Redemption")

def legendary_rogue_daggers(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary: Fangs of the Father",openfile)
	characterquests.charquestprint(count,datatree,openfile,29801,"Proving Your Worth")
	characterquests.charquestprint(count,datatree,openfile,29802,"A Hidden Message")
	characterquests.charquestprint(count,datatree,openfile,29934,"To Ravenholdt")
	characterquests.charquestprint(count,datatree,openfile,29847,"To Catch a Thief")
	characterquests.charquestprint(count,datatree,openfile,30092,"Our Man in Gilneas")
	characterquests.charquestprint(count,datatree,openfile,30093,"Assassinate Creed")
	characterquests.charquestprint(count,datatree,openfile,30106,"The Deed is Done")
	characterquests.charquestprint(count,datatree,openfile,30107,"Cluster Clutch")
	characterquests.charquestprint(count,datatree,openfile,30108,"Our Man in Karazhan")
	characterquests.charquestprint(count,datatree,openfile,30109,"Blood of the Betrayer")
	characterquests.charquestprint(count,datatree,openfile,30113,"Victory in the Depths")
	characterquests.charquestprint(count,datatree,openfile,30116,"Sharpening Your Fangs")
	characterquests.charquestprint(count,datatree,openfile,30118,"Patricide")

def legendary_dragonwrath(count,datatree,openfile):
	characterquests.charquestheader(count,"Legendary: Dragonwrath: Tarecgosa's Rest",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29453,"Your Time Has Come","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29452,"Your Time Has Come","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29132,"A Legendary Engagement","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29129,"A Legendary Engagement","horde")
	characterquests.charquestprint(count,datatree,openfile,29134,"A Wrinkle in Time")
	characterquests.charquestprint(count,datatree,openfile,29135,"All-Seeing Eye")
	characterquests.charquestprint(count,datatree,openfile,29193,"On a Wing and a Prayer")
	characterquests.charquestprint(count,datatree,openfile,29194,"Through a Glass, Darkly")
	characterquests.charquestprint(count,datatree,openfile,29225,"Actionable Intelligence")
	characterquests.charquestprint(count,datatree,openfile,29234,"Delegation")
	characterquests.charquestprint(count,datatree,openfile,29239,"Nordrassil's Bough")
	characterquests.charquestprint(count,datatree,openfile,29240,"Emergency Extraction")
	characterquests.charquestprint(count,datatree,openfile,29269,"At One")
	characterquests.charquestprint(count,datatree,openfile,29270,"Time Grows Short")
	characterquests.charquestprint(count,datatree,openfile,29285,"Alignment")
	characterquests.charquestprintfaction(count,datatree,openfile,29307,"Heart of Flame","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29308,"Heart of Flame","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29312,"The Stuff of Legends","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29309,"The Stuff of Legends","horde")
