import characterquests
from characterutil import *

def sz_01_20_Durotar(count,datatree,openfile):
	characterquests.charquestheaderfaction(count,"01-20: Durotar","horde",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,834,"Winds in the Desert","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,835,"Securing the Lines","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,6365,"Meats to Orgrimmar","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,6384,"Ride to Orgrimmar","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,6385,"Doras the Wind Rider Master","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,6386,"Return to Razor Hill","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24607,"The Rise of the Darkspear","horde","class_warrior")
	characterquests.charquestprintfaction(count,datatree,openfile,24622,"A Troll's Truest Companion","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24623,"Saving the Young","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24624,"Mercy for the Lost","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24625,"Consort of the Sea Witch","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24626,"Young and Vicious","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24639,"The Basics: Hitting Things","horde","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24641,"A Rough Start","horde","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24642,"Proving Pit","horde","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24643,"More Than Expected","horde","class_warrior")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24750,"The Rise of the Darkspear","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24751,"The Basics: Hitting Things","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24752,"The Arts of a class_mage","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24753,"A Rough Start","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24754,"Proving Pit","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24755,"More Than Expected","horde","class_mage")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24758,"The Rise of the Darkspear","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24759,"The Basics: Hitting Things","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24761,"A Rough Start","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24762,"Proving Pit","horde","class_shaman")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24763,"More Than Expected","horde","class_shaman")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,24764,"The Rise of the Darkspear","horde","class_druid","race_troll_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,24765,"The Basics: Hitting Things","horde","class_druid","race_troll_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,24767,"A Rough Start","horde","class_druid","race_troll_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,24768,"Proving Pit","horde","class_druid","race_troll_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,24769,"More Than Expected","horde","class_druid","race_troll_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24770,"The Rise of the Darkspear","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24771,"The Basics: Hitting Things","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24773,"A Rough Start","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24774,"Proving Pit","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24775,"More Than Expected","horde","class_rogue")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24776,"The Rise of the Darkspear","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24777,"The Basics: Hitting Things","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24779,"A Rough Start","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24780,"Proving Pit","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24781,"More Than Expected","horde","class_hunter")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24782,"The Rise of the Darkspear","horde","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24783,"The Basics: Hitting Things","horde","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24785,"A Rough Start","horde","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24786,"Proving Pit","horde","class_priest")
	characterquests.charquestprintfactionclass(count,datatree,openfile,24787,"More Than Expected","horde","class_priest")
	characterquests.charquestprintfaction(count,datatree,openfile,24812,"No More Mercy","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24813,"Territorial Fetish","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24814,"An Ancient Enemy","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25035,"Breaking the Line","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25037,"Crab Fishin'","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25064,"Moraya","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25073,"Sen'jin Village","horde","race_troll_female")
	characterquests.charquestprintfaction(count,datatree,openfile,25126,"Cutting Teeth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25127,"Sting of the Scorpid","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25128,"Hana'zua","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25129,"Sarkoth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25130,"Back to the Den","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25131,"Vile Familiars","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25132,"Burning Blade Medallion","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25133,"Report to Sen'jin Village","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25134,"Lazy Peons","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25135,"Thazz'ril's Pick","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25136,"Galgar's Cactus Apple Surprise","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25152,"Your Place In The World","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25165,"Never Trust a Big Barb and a Smile","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25167,"Breaking the Chain","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25168,"Purge the Valley","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25169,"The War of Northwatch Aggression","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25170,"Cleaning Up the Coastline","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25171,"Riding On","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25172,"Invaders in Our Home","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25173,"From Bad to Worse","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25176,"Exploiting the Situation","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25177,"Storming the Beaches","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25178,"Shipwreck Searching","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25179,"Loss Reduction","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25187,"Lost in the Floods","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25188,"Watershed Patrol","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25190,"Raggaran's Rage","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25192,"Raggaran's Fury","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25193,"Lost But Not Forgotten","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25194,"Unbidden Visitors","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25195,"That's the End of That Raptor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25196,"The Dranosh'ar Blockade","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25205,"The Wolf and The Kodo","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25206,"Ignoring the Warnings","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25227,"Thonk","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25232,"The Burning Blade","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25236,"Thunder Down Under","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25256,"Sent for Help","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25257,"Ghislania","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25258,"Griswold Hanniston","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25259,"Gaur Icehorn","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25260,"Fizzled","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25261,"Margoz","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25262,"Skull Rock","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25263,"Arnak Fireblade","horde")
	characterquests.charquestprintfactionclass(count,datatree,openfile,26272,"The Rise of the Darkspear","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,26273,"The Basics: Hitting Things","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,26275,"A Rough Start","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,26276,"Proving Pit","horde","class_warlock")
	characterquests.charquestprintfactionclass(count,datatree,openfile,26277,"More Than Expected","horde","class_warlock")
	characterquests.charquestprintfaction(count,datatree,openfile,31158,"The Basics: Hitting Things","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31159,"The Rise of the Darkspear","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31160,"A Rough Start","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31161,"Proving Pit","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,31163,"More Than Expected","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,37446,"Lazy Peons","horde")

def sz_01_20_Mulgore(count,datatree,openfile):
	characterquests.charquestheaderfaction(count,"01-20: Mulgore","horde",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,743,"Dangers of the Windfury","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,744,"Preparation for Ceremony","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,749,"The Ravaged Caravan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,751,"The Ravaged Caravan","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,761,"Swoop Hunting","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,764,"The Venture Co.","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,765,"Supervisor Fizsprocket","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,770,"The Demon Scarred Cloak","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,773,"Rite of Wisdom","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,833,"A Sacred Burial","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,6361,"A Bundle of Hides","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,6362,"Ride to Thunder Bluff","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,6363,"Tal the Wind Rider Master","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,6364,"Return to Varg","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,11129,"Kyle's Gone Missing!","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14087,"Learn to Ride in Mulgore","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,14436,"Dwarven Digging","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14438,"Sharing the Land","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14439,"Journey into Thunder Bluff","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14449,"The First Step","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14452,"Rite of Strength","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14455,"Stop the Thorncallers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14456,"Rite of Courage","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14458,"Go to Adana","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14459,"The Battleboars","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14460,"Rite of Honor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14461,"Feed of Evil","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14491,"The Restless Earth","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,20440,"Poison Water","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,20441,"Rite of Vision","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,23733,"Rites of the Earthmother","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24215,"Rite of the Winds","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24440,"Winterhoof Cleansing","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24441,"Thunderhorn Totem","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24456,"Thunderhorn Cleansing","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24457,"Rite of Vision","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,24459,"Morin Cloudstalker","horde")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24523,"Wildmane Totem","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24524,"Wildmane Cleansing","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24540,"War Dance","horde","race_tauren_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24550,"Journey into Thunder Bluff","horde","race_tauren_female")
	characterquests.charquestprintfaction(count,datatree,openfile,24852,"Our Tribe, Imprisoned","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24861,"Last Rites, First Rites","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26179,"The Venture Co.","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26180,"Supervisor Fizsprocket","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26188,"Mazzranache","horde")

def sz_01_20_Teldrassil(count,datatree,openfile):
	characterquests.charquestheaderfaction(count,"01-20: Teldrassil","alliance",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,475,"A Troubling Breeze","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,476,"Gnarlpine Corruption","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,483,"The Relics of Wakening","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,486,"Ursal the Mauler","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,487,"The Road to Darnassus","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,488,"Zenn's Bidding","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,489,"Seek Redemption!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,918,"Timberling Seeds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,919,"Timberling Sprouts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,922,"Rellian Greenspyre","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,923,"Mossy Tumors","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,927,"The Moss-twined Heart","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,929,"Teldrassil: The Refusal of the Aspects","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,930,"The Glowing Fruit","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,931,"The Shimmering Frond","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,932,"Twisted Hatred","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,933,"Teldrassil: The Coming Dawn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,935,"The Waters of Teldrassil","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,937,"The Enchanted Glade","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,938,"Mist","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,941,"Planting the Heart","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,997,"Denalan's Earth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2159,"Dolanaar Delivery","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2399,"The Sprouted Fronds","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2438,"The Emerald Dreamcatcher","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2459,"Ferocitas the Dream Eater","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2499,"Oakenscowl","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2518,"Tears of the Moon","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2541,"The Sleeping Druid","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,2561,"Druid of the Claw","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,6341,"To Darnassus","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,6342,"An Unexpected Gift","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,6343,"Return to Nyoma","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,6344,"Reminders of Home","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,7383,"Teldrassil: The Burden of the Kaldorei","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,13945,"Resident Danger","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,13946,"Nature's Reprisal","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14005,"The Vengeance of Elune","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14039,"Home of the Kaldorei","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28713,"The Balance of Nature","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28714,"Fel Moss Corruption","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28715,"Demonic Thieves","alliance")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28723,"Priestess of the Moon","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28724,"Iverron's Antidote","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28725,"The Woodland Protector","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28726,"Webwood Corruption","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28727,"Vile Touch","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28728,"Signs of Things to Come","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28729,"Teldrassil: Crown of Azeroth","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28730,"Precious Waters","alliance","race_nightelf_female")
	characterquests.charquestprintfactionclass(count,datatree,openfile,28731,"Teldrassil: Passing Awareness","alliance","race_nightelf_female")
	characterquests.charquestprintfaction(count,datatree,openfile,28734,"A Favor for Melithar","alliance")

def sz_01_20_Azuremyst_Isle(count,datatree,openfile):
	characterquests.charquestheaderfaction(count,"01-20: Azuremyst Isle","alliance",openfile)
	characterquests.charquestprintfactionclass(count,datatree,openfile,9279,"You Survived!","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9280,"Replenishing the Healing Crystals","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9283,"Rescue the Survivors!","alliance","Draenei")
	characterquests.charquestprintfaction(count,datatree,openfile,9293,"What Must Be Done...","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9294,"Healing the Lake","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9303,"Inoculation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9305,"Spare Parts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9309,"The Missing Scout","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9311,"Blood Elf Spy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9312,"The Emitter","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9313,"Travel to Azure Watch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9314,"Word from Azure Watch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9369,"Replenishing the Healing Crystals","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9371,"Botanist Taerix","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9409,"Urgent Delivery!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9452,"Red Snapper - Very Tasty!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9453,"Find Acteon!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9454,"The Great Moongraze Hunt","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9455,"Strange Findings","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9456,"Nightstalker Clean Up, Isle 2...","alliance")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9463,"Medicinal Purpose","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9473,"An Alternative Alternative","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9505,"The Prophecy of Velen","alliance","Draenei")
	characterquests.charquestprintfaction(count,datatree,openfile,9506,"A Small Start","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9512,"Cookie's Jumbo Gumbo","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9513,"Reclaiming the Ruins","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9514,"Rune Covered Tablet","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9515,"Warlord Sriss'tiz","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9523,"Precious and Fragile Things Need Special Handling","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9527,"All That Remains","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9528,"A Cry For Help","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9530,"I've Got a Plant","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9531,"Tree's Company","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9537,"Show Gnomercy","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9538,"Learning the Language","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9539,"Totem of Coo","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9540,"Totem of Tikti","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9541,"Totem of Yor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9542,"Totem of Vark","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9544,"The Prophecy of Akida","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9559,"Stillpine Hold","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9560,"Beasts of the Apocalypse!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9562,"Murlocs... Why Here? Why Now?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9564,"Gurf's Dignity","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9565,"Search Stillpine Hold","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9566,"Blood Crystals","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9570,"The Kurken is Lurkin'","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9571,"The Kurken's Hide","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9573,"Chieftain Oomooroo","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9602,"Deliver Them From Evil...","alliance")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9603,"Beds, Bandages, and Beyond","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9604,"On the Wings of a Hippogryph","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9605,"Hippogryph Master Stephanos","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9606,"Return to Caregiver Chellan","alliance","Draenei")
	characterquests.charquestprintfactionclass(count,datatree,openfile,9612,"A Hearty Thanks!","alliance","Draenei")
	characterquests.charquestprintfaction(count,datatree,openfile,9616,"Bandits!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9622,"Warn Your People","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9798,"Blood Elf Plans","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9799,"Botanical Legwork","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10302,"Volatile Mutations","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10303,"The Blood Elves","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10304,"Vindicator Aldar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10324,"The Great Moongraze Hunt","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,10428,"The Missing Fisherman","alliance")
	characterquests.charquestprintfactionclass(count,datatree,openfile,14082,"Learn to Ride at the Exodar","alliance","Draenei")
	characterquests.charquestprintfaction(count,datatree,openfile,37444,"Inoculation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,37445,"Spare Parts","alliance")

def z_10_60_Azshara(count,datatree,openfile):
	characterquests.charquestheader(count,"header",openfile)
	characterquests.charquestprint(count,datatree,openfile,28496,"Warchief's Command: Azshara!")
	characterquests.charquestprint(count,datatree,openfile,25275,"Report to the Labor Captain")
	characterquests.charquestprint(count,datatree,openfile,14129,"Runaway Shredder!")
	characterquests.charquestprint(count,datatree,openfile,14134,"The Captain's Logs")
	characterquests.charquestprint(count,datatree,openfile,14135,"Up a Tree")
	characterquests.charquestprint(count,datatree,openfile,14146,"Defend the Gates!")
	characterquests.charquestprint(count,datatree,openfile,14155,"Arborcide")
	characterquests.charquestprint(count,datatree,openfile,14118,"Venison for the Troops")
	characterquests.charquestprint(count,datatree,openfile,14117,"The Eyes of Ashenvale")
	characterquests.charquestprint(count,datatree,openfile,14127,"Return of the Highborne?")
	characterquests.charquestheaderfaction(count,"10-20: Azshara: Orgrimmar Rocketway Exchange","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,14162,"Report to Horzak")
	characterquests.charquestprint(count,datatree,openfile,14128,"Return of the Highborne?")
	characterquests.charquestheaderfaction(count,"10-20: Azshara (Unsorted)","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,14130,"Friends Come In All Colors")
	characterquests.charquestprint(count,datatree,openfile,14131,"A Little Pick-me-up")
	characterquests.charquestprint(count,datatree,openfile,14132,"That's Just Rude!")
	characterquests.charquestprint(count,datatree,openfile,14161,"Basilisk Bashin'")
	characterquests.charquestprint(count,datatree,openfile,14165,"Stone Cold")
	characterquests.charquestprint(count,datatree,openfile,14190,"The Perfect Prism")
	characterquests.charquestprint(count,datatree,openfile,14192,"Prismbreak")
	characterquests.charquestprint(count,datatree,openfile,14194,"Refleshification")
	characterquests.charquestprint(count,datatree,openfile,14197,"A Quota to Meet")
	characterquests.charquestprint(count,datatree,openfile,14201,"A Thousand Stories in the Sand")
	characterquests.charquestprint(count,datatree,openfile,14202,"Survey the Lakeshore")
	characterquests.charquestprint(count,datatree,openfile,14209,"Gunk in the Trunk")
	characterquests.charquestprint(count,datatree,openfile,14215,"Memories of the Dead")
	characterquests.charquestprint(count,datatree,openfile,14216,"Mystery of the Sarcen Stone")
	characterquests.charquestprint(count,datatree,openfile,14226,"Trouble Under Foot")
	characterquests.charquestprint(count,datatree,openfile,14230,"Manual Labor")
	characterquests.charquestprint(count,datatree,openfile,14249,"Shear Will")
	characterquests.charquestprint(count,datatree,openfile,14250,"Renewable Resource")
	characterquests.charquestprint(count,datatree,openfile,14258,"Mortar the Point")
	characterquests.charquestprint(count,datatree,openfile,14261,"Ice Cold")
	characterquests.charquestprint(count,datatree,openfile,14262,"To Gut a Fish")
	characterquests.charquestprint(count,datatree,openfile,14263,"Waste of Thyme")
	characterquests.charquestprint(count,datatree,openfile,14267,"Investigating the Sea Shrine")
	characterquests.charquestprint(count,datatree,openfile,14270,"The Keystone Shard")
	characterquests.charquestprint(count,datatree,openfile,14271,"Report to Twocrush")
	characterquests.charquestprint(count,datatree,openfile,14295,"Sisters of the Sea")
	characterquests.charquestprint(count,datatree,openfile,14296,"Watch Your Step")
	characterquests.charquestprint(count,datatree,openfile,14297,"Pro-liberation")
	characterquests.charquestprint(count,datatree,openfile,14299,"Xylem's Asylum")
	characterquests.charquestprint(count,datatree,openfile,14300,"The Trial of Fire")
	characterquests.charquestprint(count,datatree,openfile,14308,"When Science Attacks")
	characterquests.charquestprint(count,datatree,openfile,14310,"Segmentation Fault: Core Dumped")
	characterquests.charquestprint(count,datatree,openfile,14322,"Bad Science! Bad!")
	characterquests.charquestprint(count,datatree,openfile,14323,"Absorbent")
	characterquests.charquestprint(count,datatree,openfile,14324,"Full of Hot Water")
	characterquests.charquestprint(count,datatree,openfile,14340,"Dressed to Impress")
	characterquests.charquestprint(count,datatree,openfile,14345,"Wash Out")
	characterquests.charquestprint(count,datatree,openfile,14370,"Mysterious Azsharite")
	characterquests.charquestprint(count,datatree,openfile,14371,"A Gigantic Snack")
	characterquests.charquestprint(count,datatree,openfile,14377,"Befriending Giants")
	characterquests.charquestprint(count,datatree,openfile,14383,"The Terrible Tinkers of the Ruined Reaches")
	characterquests.charquestprint(count,datatree,openfile,14385,"Azsharite Experiment Number One")
	characterquests.charquestprint(count,datatree,openfile,14388,"Azsharite Experiment Number Two")
	characterquests.charquestprint(count,datatree,openfile,14389,"Wasn't It Obvious?")
	characterquests.charquestprint(count,datatree,openfile,14390,"Easy is Boring")
	characterquests.charquestprint(count,datatree,openfile,14391,"Turning the Tables")
	characterquests.charquestprint(count,datatree,openfile,14392,"Farewell, Minnow")
	characterquests.charquestprint(count,datatree,openfile,14407,"Azshara Blues")
	characterquests.charquestprint(count,datatree,openfile,14408,"Nine's Plan")
	characterquests.charquestprint(count,datatree,openfile,14413,"The Pinnacle of Learning")
	characterquests.charquestprint(count,datatree,openfile,14422,"Raptor Raptor Rocket")
	characterquests.charquestprint(count,datatree,openfile,14423,"Dozercism")
	characterquests.charquestprint(count,datatree,openfile,14424,"Need More Science")
	characterquests.charquestprint(count,datatree,openfile,14428,"Amberwind's Journal")
	characterquests.charquestprint(count,datatree,openfile,14429,"Arcane De-Construction")
	characterquests.charquestprint(count,datatree,openfile,14430,"Hacking the Construct")
	characterquests.charquestprint(count,datatree,openfile,14431,"The Blackmaw Scar")
	characterquests.charquestprint(count,datatree,openfile,14432,"A Pale Brew")
	characterquests.charquestprint(count,datatree,openfile,14433,"Diplomacy by Another Means")
	characterquests.charquestprint(count,datatree,openfile,14435,"The Blackmaw Doublecross")
	characterquests.charquestprint(count,datatree,openfile,14442,"My Favorite Subject")
	characterquests.charquestprint(count,datatree,openfile,14462,"Where's My Head?")
	characterquests.charquestprint(count,datatree,openfile,14464,"Lightning Strike Assassination")
	characterquests.charquestprint(count,datatree,openfile,14468,"Another Warm Body")
	characterquests.charquestprint(count,datatree,openfile,14469,"Hand-me-downs")
	characterquests.charquestprint(count,datatree,openfile,14470,"Military Breakthrough")
	characterquests.charquestprint(count,datatree,openfile,14471,"First Degree Mortar")
	characterquests.charquestprint(count,datatree,openfile,14472,"In The Face!")
	characterquests.charquestprint(count,datatree,openfile,14475,"Grounded!")
	characterquests.charquestprint(count,datatree,openfile,14476,"Rigged to Blow")
	characterquests.charquestprint(count,datatree,openfile,14477,"Push the Button!")
	characterquests.charquestprint(count,datatree,openfile,14478,"Operation Fishgut")
	characterquests.charquestprint(count,datatree,openfile,14479,"There Are Many Like It")
	characterquests.charquestprint(count,datatree,openfile,14480,"Extermination")
	characterquests.charquestprint(count,datatree,openfile,14484,"Head of the Snake")
	characterquests.charquestprint(count,datatree,openfile,14485,"Ticker Required")
	characterquests.charquestprint(count,datatree,openfile,14486,"Handling the Goods")
	characterquests.charquestprint(count,datatree,openfile,14487,"Still Beating Heart")
	characterquests.charquestprint(count,datatree,openfile,24430,"Blacken the Skies")
	characterquests.charquestprint(count,datatree,openfile,24433,"Let Them Feast on Fear")
	characterquests.charquestprint(count,datatree,openfile,24434,"Commando Drop")
	characterquests.charquestprint(count,datatree,openfile,24435,"Mop Up")
	characterquests.charquestprint(count,datatree,openfile,24436,"Halo Drops")
	characterquests.charquestprint(count,datatree,openfile,24437,"First Come, First Served")
	characterquests.charquestprint(count,datatree,openfile,24439,"The Conquest of Azshara")
	characterquests.charquestprint(count,datatree,openfile,24448,"Field Promotion")
	characterquests.charquestprint(count,datatree,openfile,24449,"Shore Leave")
	characterquests.charquestprint(count,datatree,openfile,24452,"Profitability Scouting")
	characterquests.charquestprint(count,datatree,openfile,24453,"Private Chat")
	characterquests.charquestprint(count,datatree,openfile,24455,"Rapid Deployment")
	characterquests.charquestprint(count,datatree,openfile,24458,"A Hello to Arms")
	characterquests.charquestprint(count,datatree,openfile,24463,"Probing into Ashenvale")
	characterquests.charquestprint(count,datatree,openfile,24467,"Fade to Black")
	characterquests.charquestprint(count,datatree,openfile,24478,"The Trial of Frost")
	characterquests.charquestprint(count,datatree,openfile,24479,"The Trial of Shadow")
	characterquests.charquestprint(count,datatree,openfile,24497,"Airborne Again")

def z_10_60_Bloodmyst_Isle(count,datatree,openfile):
	characterquests.charquestheader(count,"10-60: Bloodmyst Isle",openfile)

def z_10_60_Darkshore(count,datatree,openfile):
	characterquests.charquestheader(count,"10-60: Darkshore",openfile)

def z_10_60_Northern_Barrens(count,datatree,openfile):
	characterquests.charquestheader(count,"10-60: Northern Barrens",openfile)

def z_15_60_Ashenvale(count,datatree,openfile):
	characterquests.charquestheader(count,"15-60: Ashenvale",openfile)

def z_20_60_Stonetalon_Mountains(count,datatree,openfile):
	characterquests.charquestheader(count,"20-60: Stonetalon Mountains",openfile)

def z_25_60_Southern_Barrens(count,datatree,openfile):
	characterquests.charquestheader(count,"25-60: Southern Barrens",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,24504,"Clear the High Road","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24505,"Holdout at Hunter's Hill","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24512,"Warriors' Redemption","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24513,"Eye for an Eye","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24514,"Raptor Scraps","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24515,"Signals in the Sky","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24517,"Put the Fear in Them","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24518,"The Low Road","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24519,"Stalling the Survey","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24525,"Keeping the Dogs at Bay","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24529,"Bad to Worse","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24534,"Speaking Their Language","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24539,"When Plants Attack","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24542,"A Curious Bloom","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24543,"A Family Divided","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24546,"A Line in the Dirt","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24551,"Meet the New Boss","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24552,"Lion's Pride","horde")
	characterquests.charquestprint(count,datatree,openfile,24565,"Biological Intervention")
	characterquests.charquestprint(count,datatree,openfile,24566,"Sowing a Solution")
	characterquests.charquestprint(count,datatree,openfile,24568,"To the Walls!")
	characterquests.charquestprintfaction(count,datatree,openfile,24569,"Siegebreaker","horde")
	characterquests.charquestprint(count,datatree,openfile,24570,"Adder Subtraction")
	characterquests.charquestprint(count,datatree,openfile,24571,"Lashvine Seeds")
	characterquests.charquestprintfaction(count,datatree,openfile,24572,"Taking Back Taurajo","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24573,"Honoring the Dead","horde")
	characterquests.charquestprint(count,datatree,openfile,24574,"To Harvest Chaos")
	characterquests.charquestprintfaction(count,datatree,openfile,24577,"Desolation Hold Inspection","horde")
	characterquests.charquestprint(count,datatree,openfile,24591,"Changing of the Gar'dul")
	characterquests.charquestprint(count,datatree,openfile,24601,"The Nightmare Scar")
	characterquests.charquestprintfaction(count,datatree,openfile,24603,"Don't Stop Bereavin'","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24604,"Concern for Mankrik","horde")
	characterquests.charquestprint(count,datatree,openfile,24606,"Blood of the Barrens")
	characterquests.charquestprintfaction(count,datatree,openfile,24608,"Mangletooth","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24618,"Claim the Battle Scar","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24619,"Parts-is-Parts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24620,"Hearts-is-Hearts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24621,"Smarts-is-Smarts","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24631,"Flightmare","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24632,"Tauren Vengeance","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24633,"Mahka's Plea","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24634,"Intelligence Warfare","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24637,"The Butcher of Taurajo","horde")
	characterquests.charquestprint(count,datatree,openfile,24653,"Echoes of Agamaggan")
	characterquests.charquestprintfaction(count,datatree,openfile,24654,"Silithissues","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24667,"Firestone Point","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24684,"A Weezil in the Henhouse","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24685,"Dwarf Fortress","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24747,"Sabotage!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24807,"Winnoa Pineforest","horde")
	characterquests.charquestprint(count,datatree,openfile,24824,"The Disturbed Earth")
	characterquests.charquestprintfaction(count,datatree,openfile,24862,"Running the Gauntlet","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24863,"Breaking the Siege","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24921,"Report to Aubrey","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24934,"Repel Boarders!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24938,"The Guns of Northwatch","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24939,"Run Out the Guns","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24941,"Langridge Shot","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24943,"Re-Take the Courtyard","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24944,"Back in the Fight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24948,"Lifting the Siege","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,24956,"Silencing Rageroar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25000,"Teegan's People","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25002,"Scavenged","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25008,"Filthy Animals","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25015,"Make 'em Squeal","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25022,"A Failure to Communicate","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25027,"You Flicked a Fine Vine to Leaf Me","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25028,"Trouble From the Ground Up","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25034,"To the Front!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25036,"Teegan's Troubles","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25041,"Lion's Pride","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25042,"Marching On Our Stomachs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25043,"Fields of Blood","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25044,"Diplomacy By Another Means","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25045,"A Line in the Dirt","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25057,"Clap 'Em In Irons","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25059,"The Taurajo Briefs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25074,"Meet Me at Triumph","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25075,"Pick-a-Part","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25079,"Powder Play","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25080,"Batteries Not Yet Included","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25081,"Claim the Battlescar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25082,"Working the Bugs Out","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25084,"A Growing Threat","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25085,"Mangletooth","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25086,"Firestone Point","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25087,"Report to Twinbraid","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25102,"No Bull","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25104,"Digsite Status","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25106,"Hands Off Me Dig!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25108,"Feegly the Exiled","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25120,"Marley's Final Flight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25151,"He Needs Ale!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25153,"Bael'dun Rescue","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25163,"Who Did This?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25174,"Twinbraid Needs to Know","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25175,"The Bad News","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25182,"Kill 'em All!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25183,"...And Bury the Rest","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25185,"The Deed Is Done","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25186,"Futile Resistance","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25191,"Survey the Destruction","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25197,"The Admiral Won't Back Down","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25284,"Feeding the Fear","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25852,"All's Clear","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26069,"Nura Pathfinder","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28549,"Warchief's Command: Southern Barrens!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28550,"Hero's Call: Southern Barrens!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28551,"Hero's Call: Southern Barrens!","alliance")

def z_30_60_Desolace(count,datatree,openfile):
	characterquests.charquestheader(count,"30-60: Desolace",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,14184,"My Time Has Passed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14188,"Avenge Furien!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14189,"Translation","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14191,"Furien's Footsteps","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14193,"Nothing a Couple of Melons Won't Fix","alliance")
	characterquests.charquestprint(count,datatree,openfile,14195,"All Becoming Clearer")
	characterquests.charquestprintfaction(count,datatree,openfile,14196,"Firestarter","horde")
	characterquests.charquestprint(count,datatree,openfile,14198,"Rider on the Storm")
	characterquests.charquestprintfaction(count,datatree,openfile,14213,"Ten Pounds of Flesh","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14217,"Satyrical Offerings","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14219,"To the Hilt!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14223,"Peace of Mind","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14225,"You'll Know It When You See It","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14227,"Putting Their Heads Together","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14232,"Ears Are Burning","horde")
	characterquests.charquestprint(count,datatree,openfile,14246,"Early Adoption")
	characterquests.charquestprint(count,datatree,openfile,14247,"Stubborn Lands")
	characterquests.charquestprint(count,datatree,openfile,14251,"New Beginnings")
	characterquests.charquestprint(count,datatree,openfile,14252,"Good Gold For Bad Tail")
	characterquests.charquestprint(count,datatree,openfile,14253,"Fletch Me Some Plumage!")
	characterquests.charquestprint(count,datatree,openfile,14254,"Heavy Metal")
	characterquests.charquestprintfaction(count,datatree,openfile,14255,"Ethel Rethor","horde")
	characterquests.charquestprint(count,datatree,openfile,14256,"The Emerging Threat")
	characterquests.charquestprint(count,datatree,openfile,14257,"Slitherblade Slaughter")
	characterquests.charquestprint(count,datatree,openfile,14260,"Going Deep")
	characterquests.charquestprint(count,datatree,openfile,14264,"Wetter Than Wet")
	characterquests.charquestprint(count,datatree,openfile,14268,"Deep Impact")
	characterquests.charquestprint(count,datatree,openfile,14282,"Mystery Solved")
	characterquests.charquestprint(count,datatree,openfile,14284,"A Revenant's Vengeance")
	characterquests.charquestprint(count,datatree,openfile,14292,"The Enemy of Our Enemy")
	characterquests.charquestprint(count,datatree,openfile,14301,"Return and Report")
	characterquests.charquestprint(count,datatree,openfile,14302,"Official Assessment")
	characterquests.charquestprint(count,datatree,openfile,14304,"Blood Theory")
	characterquests.charquestprint(count,datatree,openfile,14305,"A Time to Reap")
	characterquests.charquestprint(count,datatree,openfile,14306,"Pulling Weeds")
	characterquests.charquestprint(count,datatree,openfile,14307,"Stubborn Winds")
	characterquests.charquestprint(count,datatree,openfile,14309,"Calming the Kodo")
	characterquests.charquestprint(count,datatree,openfile,14311,"Taking Part")
	characterquests.charquestprint(count,datatree,openfile,14312,"An Introduction Is In Order")
	characterquests.charquestprint(count,datatree,openfile,14314,"Breakout!")
	characterquests.charquestprint(count,datatree,openfile,14316,"Cenarion Property")
	characterquests.charquestprint(count,datatree,openfile,14318,"Delicate Negotiations")
	characterquests.charquestprint(count,datatree,openfile,14325,"Will Work For Food")
	characterquests.charquestprint(count,datatree,openfile,14327,"My Word is My Bond")
	characterquests.charquestprint(count,datatree,openfile,14328,"Three Princes")
	characterquests.charquestprint(count,datatree,openfile,14329,"Not So Fast!")
	characterquests.charquestprint(count,datatree,openfile,14330,"Behind Closed Doors")
	characterquests.charquestprint(count,datatree,openfile,14332,"Time For Change")
	characterquests.charquestprint(count,datatree,openfile,14333,"While You're Here")
	characterquests.charquestprintfaction(count,datatree,openfile,14334,"Blubbergut","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14335,"Chipping In","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14337,"Shadowprey Village","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14338,"Ghost Walker Post","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14339,"Delivery Device","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14341,"Smeed's Harnesses","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14342,"Infernal Encroachment","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14343,"Maurin's Concoction","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14344,"Jugkar's Undoing","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14346,"Cleansing Our Crevasse","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14354,"Elune's Gifts","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14357,"To the Hilt!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14358,"Ten Pounds of Flesh","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14359,"Blessings From Above","alliance")
	characterquests.charquestprint(count,datatree,openfile,14360,"Nothing a Couple of Melons Won't Fix")
	characterquests.charquestprintfaction(count,datatree,openfile,14361,"Peace of Mind","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14362,"Ears Are Burning","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14363,"You'll Know It When You See It","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14364,"Putting Their Heads Together","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14365,"Ethel Rethor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14372,"Thargad's Camp","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14373,"Infernal Encroachment","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14374,"Portals of the Legion","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14376,"Jugkar's Undoing","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14378,"Hunting Brendol","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14379,"Rock Lobstrock!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14380,"An Impactful Discovery","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14381,"Cleansing Our Crevasse","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14384,"Rerouted!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,14387,"Lay of the Land","alliance")
	characterquests.charquestprint(count,datatree,openfile,14393,"Into the Fray!")
	characterquests.charquestprint(count,datatree,openfile,14394,"Death to Agogridon")
	characterquests.charquestprintfaction(count,datatree,openfile,1454,"The Karnitol Shipwreck","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,1455,"The Karnitol Shipwreck","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,1456,"The Karnitol Shipwreck","alliance")
	characterquests.charquestprint(count,datatree,openfile,1467,"Reagents for Reclaimers Inc.")
	characterquests.charquestprintfaction(count,datatree,openfile,25938,"Help for Desolace","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26134,"Nothing Left for You Here","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28531,"Hero's Call: Desolace!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28548,"Warchief's Command: Desolace!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,5421,"Fish in a Bucket","horde")
	characterquests.charquestprint(count,datatree,openfile,5501,"Bone Collector")
	characterquests.charquestprint(count,datatree,openfile,5561,"Kodo Roundup")
	characterquests.charquestprintfaction(count,datatree,openfile,5581,"Portals of the Legion","horde")
	characterquests.charquestprint(count,datatree,openfile,5821,"Bodyguard for Hire")
	characterquests.charquestprint(count,datatree,openfile,5943,"Gizelton Caravan")
	characterquests.charquestprint(count,datatree,openfile,6132,"Get Me Out of Here!")
	characterquests.charquestprint(count,datatree,openfile,6134,"Ghost-o-plasm Round Up")
	characterquests.charquestprintfaction(count,datatree,openfile,6142,"Clam Bait","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,6143,"Other Fish to Fry","horde")

def z_35_60_Dustwallow_Marsh(count,datatree,openfile):
	characterquests.charquestheader(count,"35-60: Dustwallow Marsh",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,1168,"Army of the Black Dragon","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,1201,"Theramore Spies","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,1202,"The Theramore Docks","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,1204,"Mudrock Soup and Bugs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,1205,"Deadmire","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,1222,"Stinky's Escape","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,1258,"... and Bugs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,1270,"Stinky's Escape","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,1271,"Feast at the Blue Recluse","alliance")
	characterquests.charquestprint(count,datatree,openfile,11208,"Delivery for Drazzit")
	characterquests.charquestprint(count,datatree,openfile,11211,"Help for Mudsprocket")
	characterquests.charquestprintfaction(count,datatree,openfile,11212,"Tabetha's Farm","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,11213,"Check Up on Tabetha","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,11215,"Help Mudsprocket","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25051,"Darkmist Extermination","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25292,"Next of Kin","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26596,"The Call of Kalimdor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26682,"A Shambling Threat","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26687,"Reinforcements From Theramore","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26696,"The Call of Kalimdor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26701,"Flight to Brackenwall","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26702,"Flight to Theramore","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27182,"The Hermit of Witch Hill","horde")
	characterquests.charquestprint(count,datatree,openfile,27183,"Marsh Frog Legs")
	characterquests.charquestprint(count,datatree,openfile,27184,"Jarl Needs Eyes")
	characterquests.charquestprint(count,datatree,openfile,27186,"Jarl Needs a Blade")
	characterquests.charquestprint(count,datatree,openfile,27188,"What's Haunting Witch Hill?")
	characterquests.charquestprint(count,datatree,openfile,27189,"The Witch's Bane")
	characterquests.charquestprint(count,datatree,openfile,27190,"Cleansing Witch Hill")
	characterquests.charquestprint(count,datatree,openfile,27191,"Hungry as an Ogre!")
	characterquests.charquestprintfaction(count,datatree,openfile,27210,"Traitors Among Us","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27211,"Propaganda War","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27212,"Discrediting the Deserters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27213,"The End of the Deserters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27214,"A Disturbing Development","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27215,"The Hermit of Swamplight Manor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27216,"This Old Lighthouse","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27217,"Thresher Oil","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27218,"Dastardly Denizens of the Deep","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27219,"Is it Real?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27220,"Nat's Bargain","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27221,"Oh, It's Real","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27222,"Take Down Tethyr!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27229,"SMASH BROODQUEEN","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27234,"Defias in Dustwallow?","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27235,"Renn McGill","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27236,"Secondhand Diving Gear","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27237,"Recover the Cargo!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27238,"Jaina Must Know","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27239,"Survey Alcaz Island","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27240,"Proof of Treachery","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27241,"Return to Jaina","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27242,"Raptor Captor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27243,"Unleash the Raptors","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27244,"The Lost Report","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27245,"Prisoners of the Grimtotems","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27246,"The Orc Report","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27247,"Captain Vimes","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27248,"Mission to Mudsprocket","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27249,"Inspecting the Ruins","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27251,"They Call Him Smiling Jim","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27252,"The Black Shield","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27253,"Inspecting the Ruins","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27254,"The Black Shield","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27255,"The Black Shield","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27256,"The Black Shield","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27257,"The Black Shield","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27258,"The Black Shield","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27259,"Suspicious Hoofprints","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27260,"Lieutenant Paval Reethe","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27261,"Questioning Reethe","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27262,"Suspicious Hoofprints","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27263,"Lieutenant Paval Reethe","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27264,"Lieutenant Paval Reethe","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27284,"The Black Shield","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27285,"The Black Shield","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27286,"Daelin's Men","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27287,"The Deserters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27288,"The Deserters","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27291,"Peace at Last","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27292,"Return to Krog","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27293,"The Grimtotem Plot","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27294,"More than Coincidence","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27295,"Seek Out Tabetha","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27296,"Raze Direhorn Post!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27297,"Justice Dispensed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27306,"Talk to Ogron","horde")
	characterquests.charquestprint(count,datatree,openfile,27336,"The Grimtotem Weapon")
	characterquests.charquestprint(count,datatree,openfile,27339,"The Reagent Thief")
	characterquests.charquestprint(count,datatree,openfile,27340,"Direhorn Raiders")
	characterquests.charquestprint(count,datatree,openfile,27346,"The Zeppelin Crash")
	characterquests.charquestprint(count,datatree,openfile,27347,"Corrosion Prevention")
	characterquests.charquestprint(count,datatree,openfile,27348,"Secure the Cargo!")
	characterquests.charquestprint(count,datatree,openfile,27407,"Bloodfen Feathers")
	characterquests.charquestprint(count,datatree,openfile,27408,"Banner of the Stonemaul")
	characterquests.charquestprint(count,datatree,openfile,27409,"The Essence of Enmity")
	characterquests.charquestprint(count,datatree,openfile,27410,"Spirits of Stonemaul Hold")
	characterquests.charquestprint(count,datatree,openfile,27411,"Challenge to the Black Flight")
	characterquests.charquestprint(count,datatree,openfile,27412,"WANTED: Goreclaw the Ravenous")
	characterquests.charquestprint(count,datatree,openfile,27413,"Catch a Dragon by the Tail")
	characterquests.charquestprintfaction(count,datatree,openfile,27414,"Identifying the Brood","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27415,"The Brood of Onyxia","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27416,"The Brood of Onyxia","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27417,"The Brood of Onyxia","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27418,"Challenge Overlord Mok'Morokk","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27424,"Overlord Mok'Morokk's Concern","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27425,"A Grim Connection","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27426,"Confirming the Suspicion","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27427,"Arms of the Grimtotems","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27428,"Tabetha's Assistance","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27429,"Raze Direhorn Post!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27430,"Justice for the Hyals","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28552,"Hero's Call: Dustwallow Marsh!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28554,"Warchief's Command: Dustwallow Marsh!","horde")

def z_35_60_Feralas(count,datatree,openfile):
	characterquests.charquestheader(count,"35-60: Ferelas",openfile)

def z_40_60_Thousand_Needles(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Thousand Needles",openfile)

def z_40_60_Felwood(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Felwood",openfile)

def z_40_60_Tanaris(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Tanaris",openfile)

def z_40_60_UnGoro_Crater(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Un'Goro Crater",openfile)

def z_40_60_Winterspring(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Winterspring: Unsorted",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28544,"Hero's Call: Winterspring!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28545,"Warchief's Command: Winterspring!","horde")
	characterquests.charquestprint(count,datatree,openfile,28460,"Threat of the Winterfall")
	characterquests.charquestprint(count,datatree,openfile,28462,"Winterfall Firewater")
	characterquests.charquestprint(count,datatree,openfile,28464,"Falling to Corruption")
	characterquests.charquestprint(count,datatree,openfile,28467,"Mystery Goo")
	characterquests.charquestprint(count,datatree,openfile,28469,"Winterfall Runners")
	characterquests.charquestprint(count,datatree,openfile,28470,"High Chief Winterfall")
	characterquests.charquestprint(count,datatree,openfile,28471,"The Final Piece")
	characterquests.charquestprint(count,datatree,openfile,28472,"Words of the High Chief")
	characterquests.charquestprint(count,datatree,openfile,28479,"The Ruins of Kel'Theril")
	characterquests.charquestprint(count,datatree,openfile,28513,"Pride of the Highborne")
	characterquests.charquestprint(count,datatree,openfile,28516,"Centuries of Suffering")
	characterquests.charquestprint(count,datatree,openfile,28518,"Legacy of the High Elves")
	characterquests.charquestprint(count,datatree,openfile,28519,"Pain of the Blood Elves")
	characterquests.charquestprint(count,datatree,openfile,28521,"Speak to Salfa")
	characterquests.charquestprint(count,datatree,openfile,28522,"Winterfall Activity")
	characterquests.charquestprint(count,datatree,openfile,28524,"Delivery for Donova")
	characterquests.charquestprint(count,datatree,openfile,28530,"Scalding Signs")
	characterquests.charquestprint(count,datatree,openfile,28534,"Descendants of the Highborne")
	characterquests.charquestprint(count,datatree,openfile,28535,"Descendants of the High Elves")
	characterquests.charquestprint(count,datatree,openfile,28536,"The Curse of Zin-Malor")
	characterquests.charquestprint(count,datatree,openfile,28537,"In Pursuit of Shades")
	characterquests.charquestprint(count,datatree,openfile,28540,"Doin' De E'ko Magic")
	characterquests.charquestprint(count,datatree,openfile,28609,"Hammer Time")
	characterquests.charquestprint(count,datatree,openfile,28610,"Rubble Trouble")
	characterquests.charquestprint(count,datatree,openfile,28614,"Bearzerker")
	characterquests.charquestprint(count,datatree,openfile,28615,"Turning the Earth")
	characterquests.charquestprint(count,datatree,openfile,28618,"Boulder Delivery")
	characterquests.charquestprint(count,datatree,openfile,28624,"Kilram's Boast")
	characterquests.charquestprint(count,datatree,openfile,28625,"Chop Chop")
	characterquests.charquestprint(count,datatree,openfile,28626,"Tree Delivery")
	characterquests.charquestprint(count,datatree,openfile,28627,"Seril's Boast")
	characterquests.charquestprint(count,datatree,openfile,28628,"Ice Delivery")
	characterquests.charquestprint(count,datatree,openfile,28629,"Are We There, Yeti?")
	characterquests.charquestprint(count,datatree,openfile,28630,"Echo Three")
	characterquests.charquestprint(count,datatree,openfile,28631,"The Perfect Horns")
	characterquests.charquestprint(count,datatree,openfile,28632,"Fresh From The Hills")
	characterquests.charquestprint(count,datatree,openfile,28637,"A Taste for Bear")
	characterquests.charquestprint(count,datatree,openfile,28638,"The Owls Have It")
	characterquests.charquestprint(count,datatree,openfile,28639,"Ursius")
	characterquests.charquestprint(count,datatree,openfile,28640,"Fresh Frostsabers")
	characterquests.charquestprint(count,datatree,openfile,28641,"Pride of the Dinner Table")
	characterquests.charquestprint(count,datatree,openfile,28656,"Strange Life Forces")
	characterquests.charquestprint(count,datatree,openfile,28674,"Starfall Village")
	characterquests.charquestprint(count,datatree,openfile,28676,"Exterminators at Work")
	characterquests.charquestprint(count,datatree,openfile,28701,"Out of Harm's Way")
	characterquests.charquestprint(count,datatree,openfile,28703,"Step Into My Barrow")
	characterquests.charquestprint(count,datatree,openfile,28706,"Spray it Forward")
	characterquests.charquestprint(count,datatree,openfile,28707,"Spray it Again")
	characterquests.charquestprint(count,datatree,openfile,28710,"Spray it One More Time")
	characterquests.charquestprint(count,datatree,openfile,28718,"Where There's Smoke, There's Delicious Meat")
	characterquests.charquestprint(count,datatree,openfile,28719,"A Little Gamy")
	characterquests.charquestprint(count,datatree,openfile,28722,"Yetiphobia")
	characterquests.charquestprint(count,datatree,openfile,28742,"Shy-Rotam")
	characterquests.charquestprint(count,datatree,openfile,28745,"Screechy Keen")
	characterquests.charquestprint(count,datatree,openfile,28768,"Winterspring!")
	characterquests.charquestprint(count,datatree,openfile,28782,"A Bird of Legend")
	characterquests.charquestprint(count,datatree,openfile,28828,"You Gotta Have Eggs")
	characterquests.charquestprint(count,datatree,openfile,28829,"Razor Beak and Antlers Pointy")
	characterquests.charquestprint(count,datatree,openfile,28830,"Chips off the Old Block")
	characterquests.charquestprint(count,datatree,openfile,28831,"Damn You, Frostilicus")
	characterquests.charquestprint(count,datatree,openfile,28837,"Altered Beasts")
	characterquests.charquestprint(count,datatree,openfile,28838,"The Owlbeasts' Defense")
	characterquests.charquestprint(count,datatree,openfile,28839,"Magic Prehistoric")
	characterquests.charquestprint(count,datatree,openfile,28840,"Winterwater")
	characterquests.charquestprint(count,datatree,openfile,28841,"The Arcane Storm Within")
	characterquests.charquestprint(count,datatree,openfile,28842,"Umbranse's Deliverance")
	characterquests.charquestprint(count,datatree,openfile,28847,"The Pursuit of Umbranse")
	characterquests.charquestprint(count,datatree,openfile,28848,"Trailing the Spiritspeaker")

def z_40_60_Silithus(count,datatree,openfile):
	characterquests.charquestheader(count,"40-60: Silithus: Breadcrumbs",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28528,"Hero's Call: Silithus!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28527,"Warchief's Command: Silithus!","horde")
	characterquests.charquestprint(count,datatree,openfile,28859,"The Dunes of Silithus")
	characterquests.charquestprint(count,datatree,openfile,28856,"The Sands of Silithus")
	characterquests.charquestheader(count,"55-60: Silithus: Cenarian Hold",openfile)
	characterquests.charquestprint(count,datatree,openfile,8280,"Securing the Supply Lines")
	characterquests.charquestprint(count,datatree,openfile,8308,"Brann Bronzebeard's Lost Letter")
	characterquests.charquestprint(count,datatree,openfile,8281,"Stepping Up Security")
	characterquests.charquestprint(count,datatree,openfile,8283,"Wanted - Deathclasp, Terror of the Sands")
	characterquests.charquestprint(count,datatree,openfile,8318,"Secret Communication")
	characterquests.charquestheader(count,"55-60: Silithus: Saving Noggle",openfile)
	characterquests.charquestprint(count,datatree,openfile,8277,"Deadly Desert Venom")
	characterquests.charquestprint(count,datatree,openfile,8278,"Noggle's Last Hope")
	characterquests.charquestprint(count,datatree,openfile,8282,"Noggle's Lost Satchel")
	characterquests.charquestheader(count,"55-60: Silithus: Twilight Geolords",openfile)
	characterquests.charquestprint(count,datatree,openfile,8320,"Twilight Geolords")
	characterquests.charquestprint(count,datatree,openfile,8321,"Vyral the Vile")
	characterquests.charquestheader(count,"55-60: Silithus: Hive'Regal",openfile)
	characterquests.charquestprint(count,datatree,openfile,8304,"Dearest Natalia")
	characterquests.charquestprint(count,datatree,openfile,8306,"Into The Maw of Madness")
	characterquests.charquestprint(count,datatree,openfile,8310,"Breaking the Code")
	characterquests.charquestprint(count,datatree,openfile,8309,"Glyph Chasing")
	characterquests.charquestprint(count,datatree,openfile,8314,"Unraveling the Mystery")
	characterquests.charquestprintclass(count,datatree,openfile,8381,"Armaments of War (Obsolete)","class_mage")
	characterquests.charquestprintclass(count,datatree,openfile,8381,"Armaments of War (Obsolete)","class_warlock")
	characterquests.charquestprintclass(count,datatree,openfile,8379,"Armaments of War (Obsolete)","class_priest")
	characterquests.charquestprintclass(count,datatree,openfile,8382,"Armaments of War (Obsolete)","class_druid")
	characterquests.charquestprintclass(count,datatree,openfile,8378,"Armaments of War (Obsolete)","class_rogue")
	characterquests.charquestprintclass(count,datatree,openfile,8377,"Armaments of War (Obsolete)","class_hunter")
	characterquests.charquestprintclass(count,datatree,openfile,8380,"Armaments of War (Obsolete)","class_shaman")
	characterquests.charquestprintclass(count,datatree,openfile,8376,"Armaments of War (Obsolete)","class_paladin")
	characterquests.charquestheader(count,"55-60: Silithus: Hermit Ortell",openfile)
	characterquests.charquestprint(count,datatree,openfile,8284,"The Twilight Mystery")
	characterquests.charquestprint(count,datatree,openfile,8285,"The Deserter")
	characterquests.charquestprint(count,datatree,openfile,8279,"The Twilight Lexicon")
	characterquests.charquestprint(count,datatree,openfile,8323,"True Believers")
	characterquests.charquestprint(count,datatree,openfile,8287,"A Terrible Purpose")
	characterquests.charquestheader(count,"55-60: Silithus: PvP",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,9415,"Report to Marshal Bluewall","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,9416,"Report to General Kirika","horde")
