import characterquests
from characterutil import *

def sz_01_05_Gilneas_City(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"01-05: Gilneas City","alliance",openfile)
	characterquests.charquestprintfactionrace(count,datatree,openfile,14078,"Lockdown!","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14091,"Something's Amiss","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14093,"All Hell Breaks Loose","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14094,"Salvage the Supplies","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14098,"Evacuate the Merchant Square","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14099,"Royal Orders","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14154,"By the Skin of His Teeth","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14157,"Old Divisions","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14159,"The Rebel Lord's Arsenal","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14204,"From the Shadows","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14212,"Sacrifices","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14214,"Message to Greymane","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14218,"By Blood and Ash","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14221,"Never Surrender, Sometimes Retreat","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14222,"Last Stand","alliance","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14280,"The Winds Know Your Name... Apparently","alliance","class_druid","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14291,"Safety in Numbers","alliance","class_druid","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14275,"Someone's Keeping Track of You","alliance","class_hunter","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14290,"Safety in Numbers","alliance","class_hunter","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14277,"Arcane Inquiries","alliance","class_mage","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14288,"Safety in Numbers","alliance","class_mage","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14278,"Seek the Sister","alliance","class_priest","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14289,"Safety in Numbers","alliance","class_priest","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14269,"Someone's Looking for You","alliance","class_rogue","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14285,"Safety in Numbers","alliance","class_rogue","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14273,"Shady Associates","alliance","class_warlock","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14287,"Safety in Numbers","alliance","class_warlock","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14265,"Your Instructor","alliance","class_warrior","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14286,"Safety in Numbers","alliance","class_warrior","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14293,"Save Krennan Aranas","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14294,"Time to Regroup","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14467,"Alas, Gilneas!","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24930,"While You're At It","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,26129,"Brothers In Arms","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,28850,"The Prison Rooftop","alliance","race_worgen_female")

def sz_01_20_Gilneas(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"01-20: Gilneas","alliance",openfile)
	characterquests.charquestprintfactionrace(count,datatree,openfile,14220,"This Is the End","alliance","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14272,"Eviscerate","alliance","class_rogue","race_worgen_female")
	characterquests.charquestprintfactionclassrace(count,datatree,openfile,14274,"Corruption","alliance","class_warlock","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14313,"Among Humans Again","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14319,"Further Treatment","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14320,"In Need of Ingredients","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14321,"Invasion","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14336,"Kill or Be Killed","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14347,"Hold the Line","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14348,"You Can't Take 'Em Alone","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14366,"Holding Steady","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14367,"The Allens' Storm Cellar","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14368,"Save the Children!","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14369,"Unleash the Beast","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14375,"Last Chance at Humanity","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14382,"Two By Sea","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14386,"Leader of the Pack","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14395,"Gasping for Breath","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14396,"As the Land Shatters","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14397,"Evacuation","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14398,"Grandma Wahl","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14399,"Grandma's Lost It Alright","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14400,"I Can't Wear This","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14401,"Grandma's Cat","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14402,"Ready to Go","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14403,"The Hayward Brothers","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14404,"Not Quite Shipshape","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14405,"Escape By Sea","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14406,"The Crowley Orchard","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14412,"Washed Up","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14416,"The Hungry Ettin","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14463,"Horses for Duskhaven","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14465,"To Greymane Manor","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14466,"The King's Observatory","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24438,"Exodus","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24468,"Stranded at the Marsh","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24472,"Introductions Are in Order","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24483,"Stormglen","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24484,"Pest Control","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24495,"Pieces of the Past","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24501,"Queen-Sized Troubles","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24575,"Liberation Day","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24578,"The Blackwald","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24592,"Betrayal at Tempest's Reach","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24593,"Neither Human Nor Beast","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24602,"Laid to Rest","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24616,"Losing Your Tail","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24617,"Tal'doren, the Wild Home","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24627,"At Our Doorstep","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24628,"Preparations","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24646,"Take Back What's Ours","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24672,"Onwards and Upwards","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24673,"Return to Stormglen","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24674,"Slaves to No One","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24675,"Last Meal","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24676,"Push Them Out","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24677,"Flank the Forsaken","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24678,"Knee-Deep","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24679,"Patriarch's Blessing","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24680,"Keel Harbor","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24681,"They Have Allies, But So Do We","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24902,"The Hunt For Sylvanas","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24903,"Vengeance or Survival","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24904,"The Battle for Gilneas City","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24920,"Slowing the Inevitable","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,26706,"Endgame","alliance","race_worgen_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14434,"Rut'theran Village","alliance","race_worgen_female")

def sz_10_60_Ruins_of_Gilneas(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"10:60 Ruins of Gilneas","horde",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27290,"To Forsaken Forward Command","horde")
	characterquests.charquestprint(count,datatree,openfile,27322,"Korok the Colossus")
	characterquests.charquestprintfaction(count,datatree,openfile,27333,"Losing Ground","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27342,"In Time, All Will Be Revealed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27345,"The F.C.D.","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27349,"Break in Communications: Dreadwatch Outpost","horde")
	characterquests.charquestprint(count,datatree,openfile,27350,"Break in Communications: Rutsak's Guard")
	characterquests.charquestprintfaction(count,datatree,openfile,27360,"Vengeance for Our Soldiers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27364,"On Whose Orders?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27401,"What Tomorrow Brings","horde")
	characterquests.charquestprint(count,datatree,openfile,27405,"Fall Back!")
	characterquests.charquestprintfaction(count,datatree,openfile,27406,"A Man Named Godfrey","horde")
	characterquests.charquestprint(count,datatree,openfile,27423,"Resistance is Futile")

def sz_01_05_Kezan(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"01-05: Kezan","horde",openfile)
	characterquests.charquestprintfactionrace(count,datatree,openfile,14069,"Good Help is Hard to Find","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14070,"Do it Yourself","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14071,"Rolling with my Homies","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14075,"Trouble in the Mines","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14109,"The New You","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14110,"The New You","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14113,"Life of the Party","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14115,"Pirate Party Crashers","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14116,"The Uninvited Guest","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14120,"A Bazillion Macaroons?!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14121,"Robbing Hoods","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14122,"The Great Bank Heist","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14123,"Waltz Right In","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14124,"Liberate the Kaja'mite","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14125,"447","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14126,"Life Savings","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14138,"Taking Care of Business","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14153,"Life of the Party","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24488,"The Replacements","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24502,"Necessary Roughness","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24503,"Fourth and Goal","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24520,"Give Sassy the News","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24567,"Report for Tryouts","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25473,"Kaja'Cola","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,26711,"Off to the Bank","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,26712,"Off to the Bank","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,28349,"Megs in Marketing","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,28414,"Fourth and Goal","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,28606,"The Keys to the Hot Rod","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,28607,"The Keys to the Hot Rod","horde","race_goblin_female")

def sz_01_10_Lost_Isles(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"01-20: Lost Isles","horde",openfile)
	characterquests.charquestprintfactionrace(count,datatree,openfile,14001,"Goblin Escape Pods","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14014,"Get Our Stuff Back!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14019,"Monkey Business","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14021,"Miner Troubles","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14031,"Capturing the Unknown","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14233,"Orcs Can Write?","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14234,"The Enemy of My Enemy","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14235,"The Vicious Vale","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14236,"Weed Whacker","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14237,"Forward Movement","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14238,"Infrared = Infradead","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14239,"Don't Go Into the Light!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14240,"To the Cliffs","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14241,"Get to the Gyrochoppa!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14242,"Precious Cargo","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14243,"Warchief's Revenge","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14244,"Up, Up &amp; Away!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14245,"It's a Town-In-A-Box","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14248,"Help Wanted","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14303,"Back to Aggra","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14326,"Meet Me Up Top","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14445,"Farewell, For Now","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14473,"It's Our Problem Now","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,14474,"Goblin Escape Pods","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24671,"Cluster Cluck","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24741,"Trading Up","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24744,"The Biggest Egg Ever","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24816,"Who's Top of the Food Chain Now?","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24817,"A Goblin in Shark's Clothing","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24856,"Invasion Imminent!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24858,"Bilgewater Cartel Represent","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24859,"Naga Hide","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24864,"Irresistible Pool Pony","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24868,"Surrender or Else!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24897,"Get Back to Town","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24901,"Town-In-A-Box: Under Attack","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24924,"Oomlot Village","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24925,"Free the Captives","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24929,"Send a Message","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24937,"Oomlot Dealt With","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24940,"Up the Volcano","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24942,"Zombies vs. Super Booster Rocket Boots","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24945,"Three Little Pygmies","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24946,"Rockin' Powder","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24952,"Rocket Boot Boost","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24954,"Children of a Turtle God","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,24958,"Volcanoth!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25023,"Old Friends","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25024,"Repel the Paratroopers","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25058,"Mine Disposal, the Goblin Way","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25066,"The Pride of Kezan","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25093,"The Heads of the SI:7","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25098,"The Warchief Wants You","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25099,"Borrow Bastia","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25100,"Let's Ride","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25109,"The Gallywix Labor Mine","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25110,"Kaja'Cola Gives You IDEAS! (TM)","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25122,"Morale Boost","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25123,"Throw It On the Ground!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25125,"Light at the End of the Tunnel","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25184,"Wild Mine Cart Ride","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25200,"Shredder Shutdown","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25201,"The Ultimate Footbomb Uniform","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25202,"The Fastest Way to His Heart","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25203,"What Kind of Name is Chip, Anyway?","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25204,"Release the Valves","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25207,"Good-bye, Sweet Oil","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25213,"The Slave Pits","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25214,"Escape Velocity","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25243,"She Loves Me, She Loves Me NOT!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25244,"What Kind of Name is Candy, Anyway?","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25251,"Final Confrontation","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,25265,"Victory!","horde","race_goblin_female")
	characterquests.charquestprintfactionrace(count,datatree,openfile,27139,"Hobart Needs You","horde","race_goblin_female")

def z_80_90_Mount_Hyjal(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"80-90: Mount Hyjal: Intro",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27726,"Hero's Call: Mount Hyjal!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27721,"Warchief's Command: Mount Hyjal!","horde")
	characterquests.charquestprint(count,datatree,openfile,25316,"As Hyjal Burns")
	characterquests.charquestprint(count,datatree,openfile,25370,"Inciting the Elements")
	characterquests.charquestprint(count,datatree,openfile,25460,"The Earth Rises")
	characterquests.charquestprint(count,datatree,openfile,25574,"Flames from Above")
	characterquests.charquestprint(count,datatree,openfile,25317,"Protect the World Tree")
	characterquests.charquestprint(count,datatree,openfile,25319,"War on the Twilight's Hammer")
	characterquests.charquestprint(count,datatree,openfile,25323,"Flamebreaker")
	characterquests.charquestprint(count,datatree,openfile,25464,"The Return of Baron Geddon")
	characterquests.charquestprint(count,datatree,openfile,25430,"Emerald Allies")
	characterquests.charquestprint(count,datatree,openfile,25320,"The Captured Scout")
	characterquests.charquestprint(count,datatree,openfile,25321,"Twilight Captivity")
	characterquests.charquestprint(count,datatree,openfile,25424,"Return to Alysra")
	characterquests.charquestprint(count,datatree,openfile,25324,"A Prisoner of Interest")
	characterquests.charquestprint(count,datatree,openfile,25325,"Through the Dream")
	characterquests.charquestprint(count,datatree,openfile,25578,"Return to Nordrassil")
	characterquests.charquestheader(count,"80-90: Mount Hyjal: Shrine of Goldrinn",openfile)
	characterquests.charquestprint(count,datatree,openfile,25584,"The Return of the Ancients")
	characterquests.charquestprint(count,datatree,openfile,25233,"End of the Supply Line")
	characterquests.charquestprint(count,datatree,openfile,25234,"In the Rear With the Gear")
	characterquests.charquestprint(count,datatree,openfile,25255,"Harrying the Hunters")
	characterquests.charquestprintfaction(count,datatree,openfile,25268,"The Voice of Goldrinn","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25269,"The Voice of Lo'Gosh","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25271,"Goldrinn's Ferocity","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25270,"Howling Mad","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25273,"Lycanthoth the Corruptor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25272,"Lycanthoth the Corruptor","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25280,"The Shrine Reclaimed","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25279,"The Shrine Reclaimed","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25278,"Cleaning House","alliance")
	characterquests.charquestprint(count,datatree,openfile,25297,"From the Mouth of Madness")
	characterquests.charquestprint(count,datatree,openfile,25298,"Free Your Mind, the Rest Follows")
	characterquests.charquestheader(count,"80-90: Mount Hyjal: (Unsorted)",openfile)
	characterquests.charquestprint(count,datatree,openfile,25223,"Trial By Fire")
	characterquests.charquestprint(count,datatree,openfile,25224,"In Bloom")
	characterquests.charquestprint(count,datatree,openfile,25274,"Signed in Blood")
	characterquests.charquestprint(count,datatree,openfile,25276,"Your New Identity")
	characterquests.charquestprint(count,datatree,openfile,25291,"Twilight Training")
	characterquests.charquestprint(count,datatree,openfile,25294,"Walking the Dog")
	characterquests.charquestprint(count,datatree,openfile,25296,"Gather the Intelligence")
	characterquests.charquestprint(count,datatree,openfile,25299,"Mental Training: Speaking the Truth to Power")
	characterquests.charquestprint(count,datatree,openfile,25308,"Seeds of Discord")
	characterquests.charquestprint(count,datatree,openfile,25309,"Spiritual Training: Mercy is for the Weak")
	characterquests.charquestprint(count,datatree,openfile,25310,"The Greater of Two Evils")
	characterquests.charquestprint(count,datatree,openfile,25311,"Twilight Territory")
	characterquests.charquestprint(count,datatree,openfile,25314,"Speech Writing for Dummies")
	characterquests.charquestprint(count,datatree,openfile,25315,"Graduation Speech")
	characterquests.charquestprint(count,datatree,openfile,25330,"Waste of Flesh")
	characterquests.charquestprint(count,datatree,openfile,25372,"Aessina's Miracle")
	characterquests.charquestprint(count,datatree,openfile,25381,"Fighting Fire With ... Anything")
	characterquests.charquestprint(count,datatree,openfile,25382,"Disrupting the Rituals")
	characterquests.charquestprint(count,datatree,openfile,25385,"Save the Wee Animals")
	characterquests.charquestprint(count,datatree,openfile,25392,"Oh, Deer!")
	characterquests.charquestprint(count,datatree,openfile,25404,"If You're Not Against Us...")
	characterquests.charquestprint(count,datatree,openfile,25408,"Seeds of Their Demise")
	characterquests.charquestprint(count,datatree,openfile,25411,"A New Master")
	characterquests.charquestprint(count,datatree,openfile,25412,"The Name Never Spoken")
	characterquests.charquestprint(count,datatree,openfile,25428,"Black Heart of Flame")
	characterquests.charquestprint(count,datatree,openfile,25462,"The Bears Up There")
	characterquests.charquestprint(count,datatree,openfile,25472,"The Flameseer's Staff")
	characterquests.charquestprint(count,datatree,openfile,25490,"Smashing Through Ashes")
	characterquests.charquestprint(count,datatree,openfile,25491,"Durable Seeds")
	characterquests.charquestprint(count,datatree,openfile,25492,"Firebreak")
	characterquests.charquestprint(count,datatree,openfile,25493,"Fresh Bait")
	characterquests.charquestprint(count,datatree,openfile,25494,"A Champion's Collar")
	characterquests.charquestprint(count,datatree,openfile,25496,"Grudge Match")
	characterquests.charquestprint(count,datatree,openfile,25499,"Agility Training: Run Like Hell!")
	characterquests.charquestprint(count,datatree,openfile,25502,"Prepping the Soil")
	characterquests.charquestprint(count,datatree,openfile,25507,"Hell's Shells")
	characterquests.charquestprint(count,datatree,openfile,25509,"Physical Training: Forced Labor")
	characterquests.charquestprint(count,datatree,openfile,25510,"Tortolla Speaks")
	characterquests.charquestprint(count,datatree,openfile,25514,"Breaking the Bonds")
	characterquests.charquestprint(count,datatree,openfile,25519,"Children of Tortolla")
	characterquests.charquestprint(count,datatree,openfile,25520,"An Ancient Awakens")
	characterquests.charquestprint(count,datatree,openfile,25523,"Flight in the Firelands")
	characterquests.charquestprint(count,datatree,openfile,25525,"Wave One")
	characterquests.charquestprint(count,datatree,openfile,25531,"Twilight Riot")
	characterquests.charquestprint(count,datatree,openfile,25544,"Wave Two")
	characterquests.charquestprint(count,datatree,openfile,25548,"Might of the Firelord")
	characterquests.charquestprint(count,datatree,openfile,25549,"The Sanctum of the Prophets")
	characterquests.charquestprint(count,datatree,openfile,25554,"Secrets of the Flame")
	characterquests.charquestprint(count,datatree,openfile,25560,"Egg Wave")
	characterquests.charquestprint(count,datatree,openfile,25597,"Commander Jarod Shadowsong")
	characterquests.charquestprint(count,datatree,openfile,25601,"Head of the Class")
	characterquests.charquestprint(count,datatree,openfile,25608,"Slash and Burn")
	characterquests.charquestprint(count,datatree,openfile,25653,"The Ancients are With Us")
	characterquests.charquestprint(count,datatree,openfile,25655,"The Wormwing Problem")
	characterquests.charquestprint(count,datatree,openfile,25656,"Scrambling for Eggs")
	characterquests.charquestprint(count,datatree,openfile,25663,"An Offering for Aviana")
	characterquests.charquestprint(count,datatree,openfile,25664,"A Prayer and a Wing")
	characterquests.charquestprint(count,datatree,openfile,25665,"A Plea From Beyond")
	characterquests.charquestprint(count,datatree,openfile,25731,"A Bird in Hand")
	characterquests.charquestprint(count,datatree,openfile,25740,"Fact-Finding Mission")
	characterquests.charquestprint(count,datatree,openfile,25746,"Sethria's Brood")
	characterquests.charquestprint(count,datatree,openfile,25758,"A Gap in Their Armor")
	characterquests.charquestprint(count,datatree,openfile,25761,"Disassembly")
	characterquests.charquestprint(count,datatree,openfile,25763,"The Codex of Shadows")
	characterquests.charquestprint(count,datatree,openfile,25764,"Egg Hunt")
	characterquests.charquestprint(count,datatree,openfile,25776,"Sethria's Demise")
	characterquests.charquestprint(count,datatree,openfile,25795,"Return to the Shrine")
	characterquests.charquestprint(count,datatree,openfile,25807,"An Ancient Reborn")
	characterquests.charquestprint(count,datatree,openfile,25810,"The Hatchery Must Burn")
	characterquests.charquestprint(count,datatree,openfile,25830,"The Last Living Lorekeeper")
	characterquests.charquestprint(count,datatree,openfile,25832,"Return to Aviana")
	characterquests.charquestprint(count,datatree,openfile,25842,"Firefight")
	characterquests.charquestprint(count,datatree,openfile,25843,"Tortolla's Revenge")
	characterquests.charquestprint(count,datatree,openfile,25881,"Lost Wardens")
	characterquests.charquestprint(count,datatree,openfile,25886,"Pressing the Advantage")
	characterquests.charquestprint(count,datatree,openfile,25899,"Breakthrough")
	characterquests.charquestprint(count,datatree,openfile,25901,"Hyjal Recycling Program")
	characterquests.charquestprint(count,datatree,openfile,25904,"The Hammer and the Key")
	characterquests.charquestprint(count,datatree,openfile,25906,"The Third Flamegate")
	characterquests.charquestprint(count,datatree,openfile,25910,"The Time for Mercy has Passed")
	characterquests.charquestprint(count,datatree,openfile,25915,"The Strength of Tortolla")
	characterquests.charquestprint(count,datatree,openfile,25923,"Finish Nemesis")
	characterquests.charquestprint(count,datatree,openfile,25928,"Tortolla's Triumph")
	characterquests.charquestprint(count,datatree,openfile,25940,"Last Stand at Whistling Grove")
	characterquests.charquestprint(count,datatree,openfile,25985,"Wings Over Mount Hyjal")
	characterquests.charquestprint(count,datatree,openfile,27874,"Aviana's Legacy")
	characterquests.charquestprint(count,datatree,openfile,29066,"Good News... and Bad News")
	characterquests.charquestprint(count,datatree,openfile,25550,"Magma Monarch")
	characterquests.charquestprint(count,datatree,openfile,25551,"The Firelord")
	characterquests.charquestprint(count,datatree,openfile,25552,"Brood of Evil")
	characterquests.charquestprint(count,datatree,openfile,25553,"Death to the Broodmother")
	characterquests.charquestprint(count,datatree,openfile,25555,"The Gatekeeper")
	characterquests.charquestprint(count,datatree,openfile,25644,"The Twilight Egg")
	characterquests.charquestprint(count,datatree,openfile,29234,"Delegation")
	characterquests.charquestprint(count,datatree,openfile,29437,"The Fallen Guardian")

def z_80_90_Vashjir(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"Vash'jir: Kelp'thar Forest",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28825,"A Personal Summons","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28790,"A Personal Summons","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28826,"The Eye of the Storm","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28805,"The Eye of the Storm","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14481,"Into The Abyss","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27724,"Hero's Call: Vashj'ir!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27718,"Warchief's Command: Vashj'ir!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28827,"To the Depths","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28816,"To the Depths","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,14482,"Call of Duty","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25924,"Call of Duty","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,24432,"Sea Legs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25929,"Sea Legs","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25281,"Pay It Forward","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25936,"Pay It Forward","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25405,"Rest For the Weary","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25941,"Rest For the Weary","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25357,"Buy Us Some Time","alliance")
	characterquests.charquestprint(count,datatree,openfile,25358,"Nerve Tonic")
	characterquests.charquestprint(count,datatree,openfile,25371,"The Abyssal Ride")
	characterquests.charquestprint(count,datatree,openfile,25377,"The Horde's Hoard")
	characterquests.charquestprint(count,datatree,openfile,25384,"Raw Materials")
	characterquests.charquestprint(count,datatree,openfile,25388,"A Case of Crabs")
	characterquests.charquestprint(count,datatree,openfile,25389,"A Taste For Tail")
	characterquests.charquestprint(count,datatree,openfile,25390,"A Girl's Best Friend")
	characterquests.charquestprint(count,datatree,openfile,25413,"Change of Plans")
	characterquests.charquestprint(count,datatree,openfile,25419,"Lady La-La's Medallion")
	characterquests.charquestprint(count,datatree,openfile,25459,"Ophidophobia")
	characterquests.charquestprint(count,datatree,openfile,25467,"Kliklak's Craw")
	characterquests.charquestprint(count,datatree,openfile,25477,"Better Late Than Dead")
	characterquests.charquestprint(count,datatree,openfile,25497,"Back in the Saddle")
	characterquests.charquestprint(count,datatree,openfile,25498,"Shark Bait")
	characterquests.charquestprint(count,datatree,openfile,25503,"Blackfin's Booty")
	characterquests.charquestprintfaction(count,datatree,openfile,25545,"To Arms!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25546,"Traveling on Our Stomachs","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25547,"On Our Own Terms","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25558,"All or Nothing","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25564,"Stormwind Elite Aquatic and Land Forces","alliance")
	characterquests.charquestprint(count,datatree,openfile,25587,"Gimme Shelter!")
	characterquests.charquestprint(count,datatree,openfile,25598,"Ain't Too Proud to Beg")
	characterquests.charquestprint(count,datatree,openfile,25602,"Can't Start a Fire Without a Spark")
	characterquests.charquestprint(count,datatree,openfile,25636,"Starve a Fever, Feed a Cold")
	characterquests.charquestprint(count,datatree,openfile,25638,"A Desperate Plea")
	characterquests.charquestprint(count,datatree,openfile,25651,"Oh, the Insanity!")
	characterquests.charquestprint(count,datatree,openfile,25657,"Dah, Nunt... Dah, Nunt...")
	characterquests.charquestprint(count,datatree,openfile,25666,"Getting Your Hands Dirty")
	characterquests.charquestprint(count,datatree,openfile,25670,"DUN-dun-DUN-dun-DUN-dun")
	characterquests.charquestprint(count,datatree,openfile,25732,"A Bone to Pick")
	characterquests.charquestprint(count,datatree,openfile,25737,"Tenuous Negotiations")
	characterquests.charquestprint(count,datatree,openfile,25738,"Shallow End of the Gene Pool")
	characterquests.charquestprint(count,datatree,openfile,25742,"What? This Old Thing?")
	characterquests.charquestprint(count,datatree,openfile,25743,"Decisions, Decisions")
	characterquests.charquestprint(count,datatree,openfile,25794,"Undersea Sanctuary")
	characterquests.charquestprintfaction(count,datatree,openfile,25812,"Spelunking","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25824,"Debriefing","alliance")
	characterquests.charquestprint(count,datatree,openfile,25883,"How Disarming")
	characterquests.charquestprint(count,datatree,openfile,25884,"Come Hell or High Water")
	characterquests.charquestprintfaction(count,datatree,openfile,25885,"What? What? In My Gut...?","alliance")
	characterquests.charquestprint(count,datatree,openfile,25887,"Wake of Destruction")
	characterquests.charquestprintfaction(count,datatree,openfile,25888,"Decompression","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25942,"Buy Us Some Time","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25943,"Traveling on Our Stomachs","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25944,"Girding Our Loins","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25946,"Helm's Deep","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25947,"Finders, Keepers","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25948,"Bring It On!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25949,"Blood and Thunder!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26000,"Spelunking","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26007,"Debriefing","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26008,"Decompression","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26040,"What? What? In My Gut...?","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27668,"Pay Attention!","horde")
	characterquests.charquestprint(count,datatree,openfile,27685,"Good Deed Left Undone")
	characterquests.charquestprint(count,datatree,openfile,27687,"An Opened Can of Whoop Gnash")
	characterquests.charquestprint(count,datatree,openfile,27699,"Shark Weak")
	characterquests.charquestprint(count,datatree,openfile,27708,"The Warden's Time")
	characterquests.charquestprint(count,datatree,openfile,27729,"Once More, With Eeling")
	characterquests.charquestheader(count,"Vash'jir: Abyssal Depths",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,25950,"Sira'kess Slaying","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25974,"Sira'kess Slaying","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25975,"Treasure Reclamation","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25976,"Treasure Reclamation","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25977,"A Standard Day for Azrajar","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25980,"A Standard Day for Azrajar","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25981,"Those Aren't Masks","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25982,"Those Aren't Masks","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25983,"Promontory Point","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25984,"Promontory Point","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,25987,"Put It On","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,25988,"Put It On","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26014,"The Brothers Digsong","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26015,"Phosphora Hunting","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26017,"A Lure","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26018,"Coldlights Out","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26019,"Enormous Eel Egg","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26021,"The Brothers Digsong 2: Eel-Egg-Trick Boogaloo","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26056,"The Wavespeaker","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26057,"The Wavespeaker","horde")
	characterquests.charquestprint(count,datatree,openfile,26065,"Free Wil'hai")
	characterquests.charquestprintfaction(count,datatree,openfile,26070,"Clearing the Defiled","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26071,"Clearing the Defiled","horde")
	characterquests.charquestprint(count,datatree,openfile,26072,"Into the Totem")
	characterquests.charquestprintfaction(count,datatree,openfile,26080,"One Last Favor","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26086,"Orako","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26087,"Glow-Juice","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26088,"Here Fishie Fishie","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26089,"Die Fishman Die","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26090,"I Brought You This Egg","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26091,"Here Fishie Fishie 2: Eel-Egg-Trick Boogaloo","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26092,"Orako's Report","horde")
	characterquests.charquestprint(count,datatree,openfile,26096,"Scalding Shrooms")
	characterquests.charquestprintfaction(count,datatree,openfile,26103,"Bio-Fuel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26105,"Claim Korthun's End","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26106,"Fuel-ology 101","alliance")
	characterquests.charquestprint(count,datatree,openfile,26111,"... It Will Come")
	characterquests.charquestprintfaction(count,datatree,openfile,26121,"Claim Korthun's End","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26122,"Environmental Awareness","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26124,"Secure Seabrush","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26125,"Secure Seabrush","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26126,"The Perfect Fuel","horde")
	characterquests.charquestprint(count,datatree,openfile,26130,"Unplug L'ghorek")
	characterquests.charquestprintfaction(count,datatree,openfile,26132,"Fiends from the Netherworld","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26133,"Fiends from the Netherworld","horde")
	characterquests.charquestprint(count,datatree,openfile,26140,"Communing with the Ancient")
	characterquests.charquestprint(count,datatree,openfile,26141,"Runestones of Binding")
	characterquests.charquestprint(count,datatree,openfile,26142,"Ascend No More!")
	characterquests.charquestprint(count,datatree,openfile,26143,"All that Rises")
	characterquests.charquestprintfaction(count,datatree,openfile,26144,"Prisoners","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26149,"Prisoners","horde")
	characterquests.charquestprint(count,datatree,openfile,26154,"Twilight Extermination")
	characterquests.charquestprintfaction(count,datatree,openfile,26181,"Back to Darkbreak Cove","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26182,"Back to the Tenebrous Cavern","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,26193,"Defending the Rift","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,26194,"Defending the Rift","horde")

def z_82_90_Deepholm(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"82-90: Deepholm: Intro",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27722,"Warchief's Command: Deepholm!","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27722,"Hero's Call: Deepholm!","alliance")
	characterquests.charquestprint(count,datatree,openfile,27203,"The Maelstrom")
	characterquests.charquestprint(count,datatree,openfile,27123,"Deepholm, Realm of Earth")
	characterquests.charquestheader(count,"82-90: Deepholm: Upper World Pillar Fragment",openfile)
	characterquests.charquestprint(count,datatree,openfile,26245,"Gunship Down")
	characterquests.charquestprint(count,datatree,openfile,26246,"Captain's Log")
	characterquests.charquestprint(count,datatree,openfile,27136,"Elemental Energy")
	characterquests.charquestprint(count,datatree,openfile,26244,"The Earth Claims All")
	characterquests.charquestprint(count,datatree,openfile,26247,"Diplomacy First")
	characterquests.charquestprint(count,datatree,openfile,26248,"All Our Friends Are Dead")
	characterquests.charquestprint(count,datatree,openfile,26249,"The Admiral's Cabin")
	characterquests.charquestprint(count,datatree,openfile,26427,"Without a Captain or Crew")
	characterquests.charquestprint(count,datatree,openfile,26251,"Take No Prisoners")
	characterquests.charquestprint(count,datatree,openfile,26250,"On Second Thought, Take One Prisoner")
	characterquests.charquestprint(count,datatree,openfile,26254,"Some Spraining to Do")
	characterquests.charquestprint(count,datatree,openfile,26255,"Return to the Temple of Earth")
	characterquests.charquestprint(count,datatree,openfile,26258,"Deathwing's Fall")
	characterquests.charquestprint(count,datatree,openfile,26259,"Blood of the Earthwarder")
	characterquests.charquestprint(count,datatree,openfile,26256,"Bleed the Bloodshaper")
	characterquests.charquestprint(count,datatree,openfile,26261,"Question the Slaves")
	characterquests.charquestprint(count,datatree,openfile,26260,"The Forgemaster's Log")
	characterquests.charquestprint(count,datatree,openfile,27007,"Silvermarsh Rendezvous")
	characterquests.charquestprint(count,datatree,openfile,27010,"Quicksilver Submersion")
	characterquests.charquestprint(count,datatree,openfile,27100,"Twilight Research")
	characterquests.charquestprint(count,datatree,openfile,27101,"Maziel's Revelation")
	characterquests.charquestprint(count,datatree,openfile,27102,"Maziel's Ascendancy")
	characterquests.charquestprint(count,datatree,openfile,27061,"The Twilight Overlook")
	characterquests.charquestprint(count,datatree,openfile,26766,"Big Game, Big Bait")
	characterquests.charquestprint(count,datatree,openfile,26768,"To Catch a Dragon")
	characterquests.charquestprint(count,datatree,openfile,26771,"Testing the Trap")
	characterquests.charquestprint(count,datatree,openfile,26857,"Abyssion's Minions")
	characterquests.charquestprint(count,datatree,openfile,26861,"Block the Gates")
	characterquests.charquestprint(count,datatree,openfile,26876,"The World Pillar Fragment")
	characterquests.charquestheader(count,"82-90: Deepholm: Middle World Pillar Fragment",openfile)
	characterquests.charquestprint(count,datatree,openfile,26409,"Where's Goldmine?")
	characterquests.charquestprint(count,datatree,openfile,26410,"Explosive Bonding Compound")
	characterquests.charquestprint(count,datatree,openfile,27135,"Something that Burns")
	characterquests.charquestprint(count,datatree,openfile,26411,"Apply and Flash Dry")
	characterquests.charquestprint(count,datatree,openfile,26413,"Take Him to the Earthcaller")
	characterquests.charquestprint(count,datatree,openfile,26484,"To Stonehearth's Aid")
	characterquests.charquestprint(count,datatree,openfile,27931,"The Quaking Fields")
	characterquests.charquestprint(count,datatree,openfile,27932,"The Axe of Earthly Sundering")
	characterquests.charquestprint(count,datatree,openfile,27933,"Elemental Ore")
	characterquests.charquestprint(count,datatree,openfile,27934,"One With the Ground")
	characterquests.charquestprint(count,datatree,openfile,27935,"Bring Down the Avalanche")
	characterquests.charquestprint(count,datatree,openfile,26499,"Stonefather's Boon")
	characterquests.charquestprint(count,datatree,openfile,26501,"Sealing the Way")
	characterquests.charquestprint(count,datatree,openfile,26500,"We're Surrounded")
	characterquests.charquestprint(count,datatree,openfile,26502,"Thunder Stones")
	characterquests.charquestprint(count,datatree,openfile,26537,"Shatter Them!")
	characterquests.charquestprint(count,datatree,openfile,26564,"Fixer Upper")
	characterquests.charquestprint(count,datatree,openfile,26591,"Battlefront Triage")
	characterquests.charquestprint(count,datatree,openfile,26625,"Troggzor the Earthinator")
	characterquests.charquestprint(count,datatree,openfile,27126,"Rush Delivery")
	characterquests.charquestprint(count,datatree,openfile,26632,"Close Escort")
	characterquests.charquestprint(count,datatree,openfile,26755,"Keep Them off the Front")
	characterquests.charquestprint(count,datatree,openfile,26762,"Reactivate the Constructs")
	characterquests.charquestprint(count,datatree,openfile,26770,"Mystic Masters")
	characterquests.charquestprint(count,datatree,openfile,26834,"Down Into the Chasm")
	characterquests.charquestprint(count,datatree,openfile,26791,"Sprout No More")
	characterquests.charquestprint(count,datatree,openfile,26792,"Fungal Monstrosities")
	characterquests.charquestprint(count,datatree,openfile,26835,"A Slight Problem")
	characterquests.charquestprint(count,datatree,openfile,26836,"Rescue the Stonefather... and Flint")
	characterquests.charquestprint(count,datatree,openfile,27937,"The Hero Returns")
	characterquests.charquestprint(count,datatree,openfile,27938,"The Middle Fragment")
	characterquests.charquestheader(count,"82-90: Deepholm: Lower World Pillar Fragment",openfile)
	characterquests.charquestprint(count,datatree,openfile,26326,"The Very Earth Beneath Our Feet")
	characterquests.charquestprint(count,datatree,openfile,26312,"Crumbling Defenses")
	characterquests.charquestprint(count,datatree,openfile,26313,"Core of Our Troubles")
	characterquests.charquestprint(count,datatree,openfile,26314,"On Even Ground")
	characterquests.charquestprint(count,datatree,openfile,26315,"Imposing Confrontation")
	characterquests.charquestprint(count,datatree,openfile,26328,"Rocky Relations")
	characterquests.charquestprint(count,datatree,openfile,26375,"Loose Stones")
	characterquests.charquestprint(count,datatree,openfile,26376,"Hatred Runs Deep")
	characterquests.charquestprint(count,datatree,openfile,26377,"Unsolid Ground")
	characterquests.charquestprint(count,datatree,openfile,26426,"Violent Gale")
	characterquests.charquestprint(count,datatree,openfile,26869,"Depth of the Depths")
	characterquests.charquestprint(count,datatree,openfile,26871,"A Rock Amongst Many")
	characterquests.charquestprint(count,datatree,openfile,26436,"Entrenched")
	characterquests.charquestprint(count,datatree,openfile,26437,"Making Things Crystal Clear")
	characterquests.charquestprint(count,datatree,openfile,26438,"Intervention")
	characterquests.charquestprint(count,datatree,openfile,26439,"Putting the Pieces Together")
	characterquests.charquestprint(count,datatree,openfile,28869,"Pebble")
	characterquests.charquestprint(count,datatree,openfile,26440,"Clingy")
	characterquests.charquestprint(count,datatree,openfile,26441,"So Big, So Round...")
	characterquests.charquestprint(count,datatree,openfile,26575,"Rock Bottom")
	characterquests.charquestprint(count,datatree,openfile,26507,"Petrified Delicacies")
	characterquests.charquestprint(count,datatree,openfile,26576,"Steady Hand")
	characterquests.charquestprint(count,datatree,openfile,26656,"Don't. Stop. Moving.")
	characterquests.charquestprint(count,datatree,openfile,26657,"Hard Falls")
	characterquests.charquestprint(count,datatree,openfile,26658,"Fragile Values")
	characterquests.charquestprint(count,datatree,openfile,26659,"Resonating Blow")
	characterquests.charquestprint(count,datatree,openfile,26577,"Rocky Upheaval")
	characterquests.charquestprint(count,datatree,openfile,26578,"Doomshrooms")
	characterquests.charquestprint(count,datatree,openfile,26579,"Gone Soft")
	characterquests.charquestprint(count,datatree,openfile,26580,"Familiar Intruders")
	characterquests.charquestprint(count,datatree,openfile,26581,"A Head Full of Wind")
	characterquests.charquestprint(count,datatree,openfile,26582,"Unnatural Causes")
	characterquests.charquestprint(count,datatree,openfile,26583,"Wrath of the Fungalmancer")
	characterquests.charquestprint(count,datatree,openfile,26584,"Shaken and Stirred")
	characterquests.charquestprint(count,datatree,openfile,26585,"Corruption Destruction")
	characterquests.charquestprint(count,datatree,openfile,26750,"At the Stonemother's Call")
	characterquests.charquestprint(count,datatree,openfile,26752,"Audience with the Stonemother")
	characterquests.charquestprint(count,datatree,openfile,26827,"Rallying the Earthen Ring")
	characterquests.charquestprint(count,datatree,openfile,26828,"Our Part of the Bargain")
	characterquests.charquestprint(count,datatree,openfile,26829,"The Stone March")
	characterquests.charquestprint(count,datatree,openfile,26832,"Therazane's Mercy")
	characterquests.charquestprint(count,datatree,openfile,26831,"The Twilight Flight")
	characterquests.charquestprint(count,datatree,openfile,26833,"Word In Stone")
	characterquests.charquestprint(count,datatree,openfile,26875,"Undying Twilight")
	characterquests.charquestprint(count,datatree,openfile,26971,"The Binding")
	characterquests.charquestprint(count,datatree,openfile,26709,"The Stone Throne")
	characterquests.charquestheaderfaction(count,"82-90: Deepholm: To Uldum","alliance",openfile)
	characterquests.charquestprint(count,datatree,openfile,27952,"The Explorers")
	characterquests.charquestprint(count,datatree,openfile,27004,"The Twilight Plot")
	characterquests.charquestprint(count,datatree,openfile,27006,"Fly Over")
	characterquests.charquestprint(count,datatree,openfile,27040,"Decryption Made Easy")
	characterquests.charquestprint(count,datatree,openfile,27042,"Fight Fire and Water and Air with...")
	characterquests.charquestprint(count,datatree,openfile,27058,"The Wrong Sequence")
	characterquests.charquestprint(count,datatree,openfile,28292,"That's No Pyramid!")
	characterquests.charquestheaderfaction(count,"82-90: Deepholm: To Uldum","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,27953,"The Reliquary")
	characterquests.charquestprint(count,datatree,openfile,27005,"The Twilight Plot")
	characterquests.charquestprint(count,datatree,openfile,27008,"Fly Over")
	characterquests.charquestprint(count,datatree,openfile,27041,"Decryption Made Easy")
	characterquests.charquestprint(count,datatree,openfile,27043,"Fight Fire and Water and Air with...")
	characterquests.charquestprint(count,datatree,openfile,27059,"The Wrong Sequence")
	characterquests.charquestprint(count,datatree,openfile,28293,"That's No Pyramid!")

def z_83_90_Uldum(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"83-90: Uldum (Unsorted)",openfile)
	characterquests.charquestprint(count,datatree,openfile,27003,"Easy Money")
	characterquests.charquestprint(count,datatree,openfile,27141,"Premature Explosionation")
	characterquests.charquestprint(count,datatree,openfile,27176,"Just the Tip")
	characterquests.charquestprint(count,datatree,openfile,27179,"Field Work")
	characterquests.charquestprint(count,datatree,openfile,27187,"Do the World a Favor")
	characterquests.charquestprint(count,datatree,openfile,27196,"On to Something")
	characterquests.charquestprint(count,datatree,openfile,27431,"Tipping the Balance")
	characterquests.charquestprint(count,datatree,openfile,27511,"The Thrill of Discovery")
	characterquests.charquestprint(count,datatree,openfile,27517,"Be Prepared")
	characterquests.charquestprint(count,datatree,openfile,27519,"Under the Choking Sands")
	characterquests.charquestprint(count,datatree,openfile,27520,"Minions of Al'Akir")
	characterquests.charquestprint(count,datatree,openfile,27541,"Lessons From the Past")
	characterquests.charquestprint(count,datatree,openfile,27549,"By the Light of the Stars")
	characterquests.charquestprint(count,datatree,openfile,27595,"The Prophet Hadassi")
	characterquests.charquestprint(count,datatree,openfile,27602,"The Prophet's Dying Words")
	characterquests.charquestprint(count,datatree,openfile,27623,"Colossal Guardians")
	characterquests.charquestprint(count,datatree,openfile,27624,"After the Fall")
	characterquests.charquestprint(count,datatree,openfile,27627,"Just a Fancy Cockroach")
	characterquests.charquestprint(count,datatree,openfile,27628,"Send Word to Phaoris")
	characterquests.charquestprint(count,datatree,openfile,27630,"The High Priest's Vote")
	characterquests.charquestprint(count,datatree,openfile,27631,"The High Commander's Vote")
	characterquests.charquestprint(count,datatree,openfile,27632,"Tanotep's Son")
	characterquests.charquestprint(count,datatree,openfile,27669,"Do the Honors")
	characterquests.charquestprint(count,datatree,openfile,27706,"The Scepter of Orsis")
	characterquests.charquestprint(count,datatree,openfile,27707,"Neferset Prison")
	characterquests.charquestprint(count,datatree,openfile,27738,"The Pit of Scales")
	characterquests.charquestprint(count,datatree,openfile,27748,"Fortune and Glory")
	characterquests.charquestprint(count,datatree,openfile,27755,"The Curse of the Tombs")
	characterquests.charquestprint(count,datatree,openfile,27760,"Artificial Intelligence")
	characterquests.charquestprint(count,datatree,openfile,27761,"A Disarming Distraction")
	characterquests.charquestprint(count,datatree,openfile,27777,"Core Access Codes")
	characterquests.charquestprint(count,datatree,openfile,27778,"Hacking the Wibson")
	characterquests.charquestprint(count,datatree,openfile,27779,"Gnomebliteration")
	characterquests.charquestprint(count,datatree,openfile,27836,"Stopping the Spread")
	characterquests.charquestprint(count,datatree,openfile,27837,"Trespassers in the Water")
	characterquests.charquestprint(count,datatree,openfile,27838,"The Root of the Corruption")
	characterquests.charquestprint(count,datatree,openfile,27839,"Ancient Weapons")
	characterquests.charquestprint(count,datatree,openfile,27899,"That Gleam in his Eye")
	characterquests.charquestprint(count,datatree,openfile,27900,"I've Got This Guy")
	characterquests.charquestprint(count,datatree,openfile,27901,"They Don't Know What They've Got Here")
	characterquests.charquestprint(count,datatree,openfile,27903,"Ignition")
	characterquests.charquestprint(count,datatree,openfile,27905,"Tailgunner!")
	characterquests.charquestprint(count,datatree,openfile,27922,"Traitors!")
	characterquests.charquestprint(count,datatree,openfile,27923,"Smoke in Their Eyes")
	characterquests.charquestprint(count,datatree,openfile,27924,"Budd's Plan")
	characterquests.charquestprint(count,datatree,openfile,27926,"Eastern Hospitality")
	characterquests.charquestprint(count,datatree,openfile,27928,"A Favor for the Furrier")
	characterquests.charquestprint(count,datatree,openfile,27939,"The Desert Fox")
	characterquests.charquestprint(count,datatree,openfile,27941,"Fashionism")
	characterquests.charquestprint(count,datatree,openfile,27942,"Idolatry")
	characterquests.charquestprint(count,datatree,openfile,27943,"Angered Spirits")
	characterquests.charquestprint(count,datatree,openfile,27950,"Gobbles!")
	characterquests.charquestprint(count,datatree,openfile,27969,"Make Yourself Useful")
	characterquests.charquestprint(count,datatree,openfile,27990,"Battlezone")
	characterquests.charquestprint(count,datatree,openfile,27993,"Take it to 'Em!")
	characterquests.charquestprint(count,datatree,openfile,28002,"Crisis Management")
	characterquests.charquestprint(count,datatree,openfile,28105,"Kavem the Callous")
	characterquests.charquestprint(count,datatree,openfile,28112,"Escape From the Lost City")
	characterquests.charquestprint(count,datatree,openfile,28132,"Efficient Excavations")
	characterquests.charquestprint(count,datatree,openfile,28134,"Impending Retribution")
	characterquests.charquestprint(count,datatree,openfile,28135,"Al'Akir's Vengeance")
	characterquests.charquestprint(count,datatree,openfile,28141,"Relics of the Sun King")
	characterquests.charquestprint(count,datatree,openfile,28145,"Venomblood Antidote")
	characterquests.charquestprint(count,datatree,openfile,28187,"Missed Me By Zhat Much!")
	characterquests.charquestprint(count,datatree,openfile,28193,"Lockdown!")
	characterquests.charquestprint(count,datatree,openfile,28194,"The Great Escape")
	characterquests.charquestprint(count,datatree,openfile,28195,"Sending a Message")
	characterquests.charquestprint(count,datatree,openfile,28198,"The Weakest Link")
	characterquests.charquestprint(count,datatree,openfile,28200,"The Element of Supplies")
	characterquests.charquestprint(count,datatree,openfile,28201,"Ploughshares to Swords")
	characterquests.charquestprint(count,datatree,openfile,28210,"Shaping Up")
	characterquests.charquestprint(count,datatree,openfile,28267,"Firing Squad")
	characterquests.charquestprint(count,datatree,openfile,28269,"Meet Me In Vir'sar")
	characterquests.charquestprint(count,datatree,openfile,28271,"Reduced Productivity")
	characterquests.charquestprint(count,datatree,openfile,28272,"Missing Pieces")
	characterquests.charquestprint(count,datatree,openfile,28273,"Friend of a Friend")
	characterquests.charquestprint(count,datatree,openfile,28274,"Two Tents")
	characterquests.charquestprint(count,datatree,openfile,28276,"Salhet's Secret")
	characterquests.charquestprint(count,datatree,openfile,28277,"Salhet the Tactician")
	characterquests.charquestprint(count,datatree,openfile,28291,"Return to Camp")
	characterquests.charquestprint(count,datatree,openfile,28350,"Master Trapper")
	characterquests.charquestprint(count,datatree,openfile,28351,"Unlimited Potential")
	characterquests.charquestprint(count,datatree,openfile,28352,"Camel Tow")
	characterquests.charquestprint(count,datatree,openfile,28353,"Jonesy Sent For You")
	characterquests.charquestprint(count,datatree,openfile,28363,"Stirred the Hornet's Nest")
	characterquests.charquestprint(count,datatree,openfile,28367,"Shroud of the Makers")
	characterquests.charquestprint(count,datatree,openfile,28376,"Myzerian's Head")
	characterquests.charquestprint(count,datatree,openfile,28402,"Schnottz So Fast")
	characterquests.charquestprint(count,datatree,openfile,28403,"Bad Datas")
	characterquests.charquestprint(count,datatree,openfile,28404,"I'll Do It By Hand")
	characterquests.charquestprint(count,datatree,openfile,28482,"Sullah's Gift")
	characterquests.charquestprint(count,datatree,openfile,28497,"Fire From the Sky")
	characterquests.charquestprint(count,datatree,openfile,28602,"Be Prepared")
	characterquests.charquestprint(count,datatree,openfile,28621,"Put That Baby in the Cradle!")
	characterquests.charquestprint(count,datatree,openfile,28622,"Three if by Air")
	characterquests.charquestprint(count,datatree,openfile,28633,"The Coffer of Promise")
	characterquests.charquestprint(count,datatree,openfile,27629,"The Vizier's Vote")
	characterquests.charquestprint(count,datatree,openfile,28480,"Lieutenants of Darkness")
	characterquests.charquestprint(count,datatree,openfile,28483,"Bleeding the Enemy")
	characterquests.charquestprint(count,datatree,openfile,28486,"Salhet's Gambit")
	characterquests.charquestprint(count,datatree,openfile,28498,"The Secret of Nahom")
	characterquests.charquestprint(count,datatree,openfile,28499,"Punish the Trespassers")
	characterquests.charquestprint(count,datatree,openfile,28500,"The Cypher of Keset")
	characterquests.charquestprint(count,datatree,openfile,28501,"The Defense of Nahom")
	characterquests.charquestprint(count,datatree,openfile,28502,"The Bandit Warlord")
	characterquests.charquestprint(count,datatree,openfile,28520,"The Fall of Neferset City")
	characterquests.charquestprint(count,datatree,openfile,28533,"The High Council's Decision")
	characterquests.charquestprint(count,datatree,openfile,28561,"Nahom Must Hold")
	characterquests.charquestprint(count,datatree,openfile,28611,"The Defilers' Ritual")
	characterquests.charquestprint(count,datatree,openfile,28623,"The Push Westward")

def z_84_90_Twilight_Highlands(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: Intro","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,28909,"Sauranok Will Point the Way")
	characterquests.charquestprint(count,datatree,openfile,26311,"Unfamiliar Waters")
	characterquests.charquestprint(count,datatree,openfile,28717,"Warchief's Command: Twilight Highlands!")
	characterquests.charquestprint(count,datatree,openfile,26293,"Machines of War")
	characterquests.charquestprint(count,datatree,openfile,26294,"Weapons of Mass Dysfunction")
	characterquests.charquestprint(count,datatree,openfile,26324,"Where Is My Warfleet?")
	characterquests.charquestprint(count,datatree,openfile,26374,"Ready the Ground Troops")
	characterquests.charquestprint(count,datatree,openfile,26335,"Ready the Navy")
	characterquests.charquestprint(count,datatree,openfile,26337,"Beating the Market")
	characterquests.charquestprint(count,datatree,openfile,26358,"Ready the Air Force")
	characterquests.charquestprint(count,datatree,openfile,26361,"Smoot's Samophlange")
	characterquests.charquestprint(count,datatree,openfile,26372,"Pre-Flight Checklist")
	characterquests.charquestprint(count,datatree,openfile,28849,"Twilight Skies")
	characterquests.charquestprint(count,datatree,openfile,26388,"Twilight Skies")
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: The Dragonmaw Clan and the Horde","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,26539,"Stalled Negotiations")
	characterquests.charquestprint(count,datatree,openfile,26539,"Stalled Negotiations")
	characterquests.charquestprint(count,datatree,openfile,26549,"Madness")
	characterquests.charquestprint(count,datatree,openfile,26608,"Negotiations Terminated")
	characterquests.charquestprint(count,datatree,openfile,26538,"Emergency Aid")
	characterquests.charquestprint(count,datatree,openfile,26540,"Dangerous Compassion")
	characterquests.charquestprint(count,datatree,openfile,26619,"You Say You Want a Revolution")
	characterquests.charquestprint(count,datatree,openfile,26621,"Insurrection")
	characterquests.charquestprint(count,datatree,openfile,26622,"Death to Mor'ghor")
	characterquests.charquestprint(count,datatree,openfile,26786,"Securing the Beach Head")
	characterquests.charquestprint(count,datatree,openfile,26784,"Muddied Waters")
	characterquests.charquestprint(count,datatree,openfile,26788,"Cementing Our Victory")
	characterquests.charquestprint(count,datatree,openfile,26798,"Saurfang Will be Pleased")
	characterquests.charquestprint(count,datatree,openfile,26830,"Traitor's Bait")
	characterquests.charquestprint(count,datatree,openfile,26840,"Return to the Highlands")
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: The Southern Flank","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,27607,"The Southern Flank")
	characterquests.charquestprint(count,datatree,openfile,27610,"Scouting the Shore")
	characterquests.charquestprint(count,datatree,openfile,27611,"Blood on the Sand")
	characterquests.charquestprint(count,datatree,openfile,27622,"Mo' Better Shredder")
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: Krazzworks","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,28583,"Krazzworks")
	characterquests.charquestprint(count,datatree,openfile,28584,"Quality Construction")
	characterquests.charquestprint(count,datatree,openfile,28586,"Pool Pony Rescue")
	characterquests.charquestprint(count,datatree,openfile,28588,"Wildhammer Infestation")
	characterquests.charquestprint(count,datatree,openfile,28589,"Everything But the Kitchen Sink")
	characterquests.charquestprint(count,datatree,openfile,28590,"Reprisal")
	characterquests.charquestprint(count,datatree,openfile,28591,"Off The Wall")
	characterquests.charquestprint(count,datatree,openfile,28592,"Parting Packages")
	characterquests.charquestprint(count,datatree,openfile,28593,"Of Utmost Importance")
	characterquests.charquestprint(count,datatree,openfile,28594,"Highbank, Crybank")
	characterquests.charquestprint(count,datatree,openfile,28595,"Krazz Works!")
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: The Northern Flank","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,27583,"The Northern Flank")
	characterquests.charquestprint(count,datatree,openfile,27584,"Blood in the Surf")
	characterquests.charquestprint(count,datatree,openfile,27586,"Shells on the Sea Shore")
	characterquests.charquestprint(count,datatree,openfile,27606,"Blast Him!")
	characterquests.charquestheaderfaction(count,"84-90: Twilight Highlands: Bloodgulch","horde",openfile)
	characterquests.charquestprint(count,datatree,openfile,27690,"Narkrall, the Drake-Tamer")
	characterquests.charquestprint(count,datatree,openfile,27751,"Crushing the Wildhammer")
	characterquests.charquestprint(count,datatree,openfile,27929,"Drag 'em Down")
	characterquests.charquestprint(count,datatree,openfile,27747,"Total War")
	characterquests.charquestprint(count,datatree,openfile,27750,"War Forage")
	characterquests.charquestprint(count,datatree,openfile,27947,"A Vision of Twilight")
	characterquests.charquestprint(count,datatree,openfile,27951,"We All Must Sacrifice")
	characterquests.charquestprint(count,datatree,openfile,27954,"The Eyes Have It")
	characterquests.charquestprint(count,datatree,openfile,27955,"Eye Spy")
	characterquests.charquestprint(count,datatree,openfile,28041,"Bait and Throttle")
	characterquests.charquestprint(count,datatree,openfile,28043,"How to Maim Your Dragon")
	characterquests.charquestprint(count,datatree,openfile,28123,"The Demon Chain")
	characterquests.charquestprint(count,datatree,openfile,28133,"Fury Unbound")
	characterquests.charquestprint(count,datatree,openfile,28147,"Purple is Your Color")
	characterquests.charquestprint(count,datatree,openfile,28151,"Dressed to Kill")
	characterquests.charquestprint(count,datatree,openfile,28149,"Whispers in the Wind")
	characterquests.charquestprint(count,datatree,openfile,28166,"Thog's Nightlight")
	characterquests.charquestprint(count,datatree,openfile,28170,"Night Terrors")
	characterquests.charquestheader(count,"84-90: Twilight Highlands: The Maw of Madness",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27945,"Paint it Black","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27375,"The Weeping Wound","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27374,"The Maw of Madness","alliance")
	characterquests.charquestprint(count,datatree,openfile,27299,"Torn Ground")
	characterquests.charquestprint(count,datatree,openfile,27300,"Pushing Back")
	characterquests.charquestprint(count,datatree,openfile,27302,"Simple Solutions")
	characterquests.charquestprint(count,datatree,openfile,27301,"Unbroken")
	characterquests.charquestprint(count,datatree,openfile,27303,"Mercy for the Bound")
	characterquests.charquestprint(count,datatree,openfile,27376,"The Maw of Iso'rath")
	characterquests.charquestprint(count,datatree,openfile,27377,"Devoured")
	characterquests.charquestprint(count,datatree,openfile,27378,"The Worldbreaker")
	characterquests.charquestprint(count,datatree,openfile,27379,"The Terrors of Iso'rath")
	characterquests.charquestprint(count,datatree,openfile,27380,"Nightmare")
	characterquests.charquestheader(count,"84-90: Twilight Highlands: Vermillion Redoubt",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,27485,"Warm Welcome","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27486,"Warm Welcome","horde")
	characterquests.charquestprint(count,datatree,openfile,27504,"Even Dragons Bleed")
	characterquests.charquestprint(count,datatree,openfile,27505,"Draconic Mending")
	characterquests.charquestprint(count,datatree,openfile,27506,"Life from Death")
	characterquests.charquestprint(count,datatree,openfile,27564,"In Defense of the Redoubt")
	characterquests.charquestprint(count,datatree,openfile,27507,"Encroaching Twilight")
	characterquests.charquestprint(count,datatree,openfile,27508,"Far from the Nest")
	characterquests.charquestprint(count,datatree,openfile,27509,"Breach in the Defenses")
	characterquests.charquestprintfaction(count,datatree,openfile,28101,"Mathias' Command","alliance")
	characterquests.charquestprint(count,datatree,openfile,27576,"Patchwork Command")
	characterquests.charquestprintfaction(count,datatree,openfile,28091,"Easy Pickings","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28103,"Easy Pickings","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28090,"Precious Goods","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28104,"Precious Goods","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28097,"The Gates of Grim Batol","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28108,"If The Key Fits","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28092,"If The Key Fits","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28107,"Paving the Way","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28094,"Paving the Way","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,28109,"Pressing Forward","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28093,"Pressing Forward","horde")
	characterquests.charquestprint(count,datatree,openfile,28712,"Enter the Dragon Queen")
	characterquests.charquestprint(count,datatree,openfile,28758,"Battle of Life and Death")
	characterquests.charquestprint(count,datatree,openfile,28171,"And the Sky Streaked Red")
	characterquests.charquestprint(count,datatree,openfile,28191,"A Fitting End")
	characterquests.charquestprint(count,datatree,openfile,28173,"Blackout")
	characterquests.charquestprint(count,datatree,openfile,28175,"Shining Through the Dark")
	characterquests.charquestprint(count,datatree,openfile,28176,"Following the Young Home")
	characterquests.charquestprint(count,datatree,openfile,28247,"Last of Her Kind")
	characterquests.charquestheader(count,"84-90: Twilight Highlands: Twilight Rising",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,28248,"Victors' Point","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28249,"Crushblow","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27492,"Ogres & Ettins","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27493,"Ogres & Ettins","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27496,"Call in the Artillery","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27497,"Call in the Artillery","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27490,"SI:7 Drop","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27491,"Kor'kron Drop","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27494,"Move the Mountain","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27495,"Move the Mountain","horde")
	characterquests.charquestprint(count,datatree,openfile,27498,"Signal the Attack")
	characterquests.charquestprint(count,datatree,openfile,27499,"Signal the Attack")
	characterquests.charquestprintfaction(count,datatree,openfile,27500,"Four Heads are Better than None","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27501,"Four Heads are Better than None","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27502,"Up to the Citadel","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27503,"Up to the Citadel","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27636,"Just You and Mathias","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27638,"Just You and Garona","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27652,"Dark Assassins","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27653,"Dark Assassins","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27654,"Bring the Hammer Down","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27655,"Bring the Hammer Down","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27688,"Distract Them for Me","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27689,"Distract Them for Me","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27695,"The Elementium Axe","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27696,"The Elementium Axe","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27700,"Dragon, Unchained","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27701,"Dragon, Unchained","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27702,"Coup de Grace","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27703,"Coup de Grace","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27657,"Help from the Earthcaller","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27658,"Help from the Earthcaller","horde")
	characterquests.charquestprint(count,datatree,openfile,27660,"Spirit of the Loch")
	characterquests.charquestprint(count,datatree,openfile,27659,"Portal Overload")
	characterquests.charquestprint(count,datatree,openfile,27662,"Unbinding")
	characterquests.charquestprint(count,datatree,openfile,27661,"Fire the Cannon")
	characterquests.charquestprintfaction(count,datatree,openfile,27719,"Water of Life","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27798,"Water of Life","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27711,"Back to the Elementium Depths","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27712,"Back to the Elementium Depths","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27720,"Mr. Goldmine's Wild Ride","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,28885,"Mr. Goldmine's Wild Ride","horde")
	characterquests.charquestprint(count,datatree,openfile,27742,"A Little on the Side")
	characterquests.charquestprint(count,datatree,openfile,27743,"While We're Here")
	characterquests.charquestprint(count,datatree,openfile,27744,"Rune Ruination")
	characterquests.charquestprint(count,datatree,openfile,27745,"A Fiery Reunion")
	characterquests.charquestprint(count,datatree,openfile,27782,"Mathias Needs You")
	characterquests.charquestprint(count,datatree,openfile,27783,"Garona Needs You")
	characterquests.charquestprintfaction(count,datatree,openfile,27784,"The Hammer of Twilight","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27786,"The Hammer of Twilight","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,27787,"Skullcrusher the Mountain","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27788,"Skullcrusher the Mountain","horde")
	characterquests.charquestheader(count,"84-90: Twilight Highlands: The Crucible of Carnage",openfile)
	characterquests.charquestprint(count,datatree,openfile,28038,"Blood in the Highlands")
	characterquests.charquestprint(count,datatree,openfile,27861,"The Crucible of Carnage: The Bloodeye Bruiser!")
	characterquests.charquestprint(count,datatree,openfile,27862,"The Crucible of Carnage: The Bloodeye Bruiser!")
	characterquests.charquestprint(count,datatree,openfile,27863,"The Crucible of Carnage: The Bloodeye Bruiser!")
	characterquests.charquestprintfaction(count,datatree,openfile,27864,"The Crucible of Carnage: The Deadly Dragonmaw!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,27865,"The Crucible of Carnage: The Wayward Wildhammer!","horde")
	characterquests.charquestprint(count,datatree,openfile,27866,"The Crucible of Carnage: Calder's Creation!")
	characterquests.charquestprint(count,datatree,openfile,27867,"The Crucible of Carnage: The Earl of Evisceration!")
	characterquests.charquestprint(count,datatree,openfile,27868,"The Crucible of Carnage: The Twilight Terror!")

def z_85_Molten_Front(count,datatree,openfile):
	printdataheader(count,datatree,openfile)
	characterquests.charquestheader(count,"85: Molten Front: The Invasion",openfile)
	characterquests.charquestprintfaction(count,datatree,openfile,29391,"Guardians of Hyjal: Call of the Ancients","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29390,"Guardians of Hyjal: Call of the Ancients","horde")
	characterquests.charquestprintfaction(count,datatree,openfile,29387,"Guardians of Hyjal: Firelands Invasion!","alliance")
	characterquests.charquestprintfaction(count,datatree,openfile,29388,"Guardians of Hyjal: Firelands Invasion!","horde")
	characterquests.charquestprint(count,datatree,openfile,29145,"Opening the Door")
	characterquests.charquestprint(count,datatree,openfile,29195,"A Ritual of Flame")
	characterquests.charquestprint(count,datatree,openfile,29196,"To the Sanctuary!")
	characterquests.charquestprint(count,datatree,openfile,29197,"Caught Unawares")
	characterquests.charquestprint(count,datatree,openfile,29198,"The Sanctuary Must Not Fall")
	characterquests.charquestheader(count,"85: Molten Front: The Sanctuary of Malorn",openfile)
	characterquests.charquestprint(count,datatree,openfile,29199,"Calling for Reinforcements")
	characterquests.charquestprint(count,datatree,openfile,29200,"Leyara")
	characterquests.charquestprint(count,datatree,openfile,29201,"Through the Gates of Hell")
	characterquests.charquestheader(count,"85: Molten Front: Druids of the Talon",openfile)
	characterquests.charquestprint(count,datatree,openfile,29181,"Druids of the Talon")
	characterquests.charquestprint(count,datatree,openfile,29182,"Flight of the Storm Crows")
	characterquests.charquestprint(count,datatree,openfile,29272,"Need... Water... Badly...")
	characterquests.charquestheader(count,"85: Molten Front: The Shadow Wardens",openfile)
	characterquests.charquestprint(count,datatree,openfile,29214,"The Shadow Wardens")
	characterquests.charquestprint(count,datatree,openfile,29215,"The Hunt Begins")
	characterquests.charquestprint(count,datatree,openfile,29245,"The Mysterious Seed")
	characterquests.charquestprint(count,datatree,openfile,29249,"Planting Season")
	characterquests.charquestprint(count,datatree,openfile,29254,"Little Lasher")
	characterquests.charquestheader(count,"85: Molten Front: Additional Armaments",openfile)
	characterquests.charquestprint(count,datatree,openfile,29281,"Additional Armaments")
	characterquests.charquestprint(count,datatree,openfile,29282,"Well Armed")
	characterquests.charquestheader(count,"85: Molten Front: Calling the Ancients",openfile)
	characterquests.charquestprint(count,datatree,openfile,29283,"Calling the Ancients")
	characterquests.charquestprint(count,datatree,openfile,29284,"Aid of the Ancients")
	characterquests.charquestheader(count,"85: Molten Front: Filling the Moonwell",openfile)
	characterquests.charquestprint(count,datatree,openfile,29279,"Filling the Moonwell")
	characterquests.charquestprint(count,datatree,openfile,29280,"Nourishing Waters")
	characterquests.charquestprint(count,datatree,openfile,29203,"Into the Depths")
	characterquests.charquestprint(count,datatree,openfile,29298,"A Smoke-Stained Locket")
	characterquests.charquestprint(count,datatree,openfile,29302,"Unlocking the Secrets Within")
	characterquests.charquestprint(count,datatree,openfile,29303,"Tragedy and Family")
	characterquests.charquestprint(count,datatree,openfile,29310,"The Tipping Point")
	characterquests.charquestprint(count,datatree,openfile,29311,"The Rest is History")
