package BNet::Professions;

use strict;
use warnings;




sub cooking ($%) {
	my ($count, %multiusercriteria) = @_;

	BNet::Utils::groupheader ("Old World Recipies");
	BNet::Utils::preprintprofcooking($count, '18247', "Baked Salmon", "inv_misc_fish_20", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '4094', "Barbecued Buzzard Wing", "inv_misc_food_18", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33278', "Bat Bites", "inv_misc_food_86_basilisk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2795', "Beer Basted Boar Ribs", "inv_misc_food_48", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3397', "Big Bear Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3371', "Blood Sausage", "inv_misc_food_49", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6499', "Boiled Clams", "inv_misc_shell_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7751', "Brilliant Smallfish", "inv_misc_fish_07", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7755', "Bristle Whisker Catfish", "inv_misc_fish_30", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15863', "Carrion Surprise", "inv_misc_food_49", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '46684', "Charred Bear Kabobs", "inv_misc_food_68", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6501', "Clam Chowder", "inv_potion_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '64054', "Clamlette Magnifique", "inv_misc_shell_03", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2545', "Cooked Crab Claw", "inv_misc_birdbeck_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18239', "Cooked Glossy Mightfish", "inv_misc_monsterhead_03", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2541', "Coyote Steak", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2544', "Crab Cake", "inv_misc_food_08", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15935', "Crispy Bat Wing", "inv_misc_food_46", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6418', "Crispy Lizard Tail", "inv_misc_food_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3373', "Crocolisk Gumbo", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3370', "Crocolisk Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '28267', "Crunchy Spider Surprise", "inv_misc_food_88_ravagernuggets", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3376', "Curiously Tasty Omelet", "inv_egg_04", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6417', "Dig Rat Stew", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '25659', "Dirge's Kickin' Chimaerok Chops", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2546', "Dry Pork Ribs", "inv_misc_food_48", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18241', "Filet of Redgill", "inv_misc_fish_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6415', "Fillet of Frenzy", "inv_misc_fish_05", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7213', "Giant Clam Scorcho", "inv_ammo_firetar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6500', "Goblin Deviled Clams", "inv_misc_shell_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '13028', "Goldthorn Tea", "inv_drink_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3377', "Gooey Spider Cake", "inv_misc_food_10", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2542', "Goretusk Liver Pie", "inv_misc_food_10", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18240', "Grilled Squid", "inv_misc_fish_13", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '24418', "Heavy Crocolisk Stew", "inv_misc_food_64", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15910', "Heavy Kodo Stew", "inv_drink_19", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '8604', "Herb Baked Egg", "inv_egg_03", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3398', "Hot Lion Chops", "inv_misc_food_18", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18242', "Hot Smoked Bass", "inv_misc_fish_03", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15856', "Hot Wolf Ribs", "inv_misc_food_48", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '46688', "Juicy Bear Burger", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15861', "Jungle Stew", "inv_drink_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6412', "Kaldorei Spider Kabob", "inv_misc_food_68", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6419', "Lean Venison", "inv_misc_organ_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15853', "Lean Wolf Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18245', "Lobster Stew", "inv_drink_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7754', "Loch Frenzy Delight", "inv_potion_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7753', "Longjaw Mud Snapper", "inv_misc_fish_32", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33276', "Lynx Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18246', "Mightfish Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '20916', "Mithril Head Trout", "inv_misc_fish_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15933', "Monster Omelet", "inv_misc_food_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3372', "Murloc Fin Soup", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15865', "Mystery Stew", "inv_drink_19", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18243', "Nightfin Soup", "inv_drink_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18244', "Poached Sunscale Salmon", "inv_misc_fish_19", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7827', "Rainbow Fin Albacore", "inv_misc_fish_27", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2547', "Redridge Goulash", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15855', "Roast Raptor", "inv_misc_food_50", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2540', "Roasted Boar Meat", "inv_misc_food_18", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6414', "Roasted Kodo Meat", "inv_misc_food_60", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33277', "Roasted Moongraze Tenderloin", "inv_misc_food_60", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7828', "Rockscale Cod", "inv_misc_fish_04", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '22761', "Runn Tum Tuber Surprise", "inv_misc_food_63", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '25954', "Sagefish Delight", "inv_misc_fish_21", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6413', "Scorpid Surprise", "inv_misc_food_10", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2549', "Seasoned Wolf Kabob", "inv_misc_food_16", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '7752', "Slitherskin Mackerel", "inv_misc_fish_24", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '8607', "Smoked Bear Meat", "inv_misc_food_13", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '24801', "Smoked Desert Dumplings", "inv_misc_food_64", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '25704', "Smoked Sagefish", "inv_misc_fish_20", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3400', "Soothing Turtle Bisque", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '37836', "Spice Bread", "inv_misc_food_95_grainbread", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15915', "Spiced Chili Crab", "inv_misc_food_48", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2539', "Spiced Wolf Meat", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '21175', "Spider Sausage", "inv_misc_food_66", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '18238', "Spotted Yellowtail", "inv_misc_fish_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '6416', "Strider Stew", "inv_misc_bowl_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2548', "Succulent Pork Ribs", "inv_misc_food_16", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '3399', "Tasty Lion Steak", "inv_misc_food_14", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '22480', "Tender Wolf Steak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '9513', "Thistle Tea", "inv_drink_milk_05", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '20626', "Undermine Clam Chowder", "inv_drink_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '93741', "Venison Jerky", "inv_misc_food_13", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '2543', "Westfall Stew", "inv_misc_bowl_01", %multiusercriteria);

	BNet::Utils::groupheader ("Darkmoon Faire");
	BNet::Utils::preprintprofcooking($count, '185705', "Fancy Darkmoon Feast", "inv_misc_food_157_fish_80", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '185704', "Lemon Herb Filet", "inv_misc_food_78", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '185708', "Sugar-Crusted Fish Feast", "inv_misc_food_draenor_grilledsaberfish", %multiusercriteria);
	BNet::Utils::groupheader ("Outlandish Dishes");
	BNet::Utils::preprintprofcooking($count, '33286', "Blackened Basilisk", "inv_misc_food_86_basilisk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33292', "Blackened Sporefish", "inv_misc_food_79", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33290', "Blackened Trout", "inv_misc_food_77", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43761', "Broiled Bloodfin", "inv_misc_fish_29", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33279', "Buzzard Bites", "inv_misc_food_85_stegadonbite", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '36210', "Clam Bar", "inv_misc_food_27", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '38868', "Crunchy Serpent", "inv_misc_food_88_ravagernuggets", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33291', "Feltail Delight", "inv_misc_food_74", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '42302', "Fisherman's Feast", "inv_misc_food_88_ravagernuggets", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33295', "Golden Fish Sticks", "inv_misc_fish_18", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33293', "Grilled Mudfish", "inv_misc_food_78", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '42305', "Hot Buttered Trout", "inv_misc_food_76", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '38867', "Mok'Nathal Shortribs", "inv_misc_food_48", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33294', "Poached Bluefish", "inv_misc_food_76", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33284', "Ravager Dog", "inv_misc_food_53", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33287', "Roasted Clefthoof", "inv_misc_food_60", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43707', "Skullfish Soup", "inv_misc_food_63", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33296', "Spicy Crawdad", "inv_misc_fish_16", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43765', "Spicy Hot Talbuk", "inv_misc_food_84_roastclefthoof", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '42296', "Stewed Trout", "inv_misc_food_64", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43758', "Stormchops", "inv_misc_food_91", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33289', "Talbuk Steak", "inv_misc_food_84_roastclefthoof", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '33288', "Warp Burger", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::groupheader ("Holiday");
	BNet::Utils::groupheader ("Pilgrim's Bounty");
	BNet::Utils::preprintprofcooking($count, '62051', "Candied Sweet Potato", "inv_thanksgiving_sweetpotato", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '66034', "Candied Sweet Potato", "inv_thanksgiving_sweetpotato", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '62049', "Cranberry Chutney", "inv_thanksgiving_cranberrysauce", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '66035', "Cranberry Chutney", "inv_thanksgiving_cranberrysauce", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '62044', "Pumpkin Pie", "inv_thanksgiving_pumpkinpie", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '66036', "Pumpkin Pie", "inv_thanksgiving_pumpkinpie", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '62045', "Slow-Roasted Turkey", "inv_thanksgiving_turkey", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '66037', "Slow-Roasted Turkey", "inv_thanksgiving_turkey", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '62050', "Spice Bread Stuffing", "inv_thanksgiving_stuffing", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '66038', "Spice Bread Stuffing", "inv_thanksgiving_stuffing", %multiusercriteria);
	BNet::Utils::groupheader ("Winter Veil");
	BNet::Utils::preprintprofcooking($count, '45022', "Hot Apple Cider", "inv_drink_23", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '21143', "Gingerbread Cookie", "inv_misc_food_62", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '21144', "Winter Veil Egg Nog", "inv_drink_04", %multiusercriteria);
	BNet::Utils::groupheader ("Day of the Dead");
	BNet::Utils::preprintprofcooking($count, '65454', "Bread of the Dead", "inv_misc_breadofthedead", %multiusercriteria);
	BNet::Utils::groupheader ("Cooking with Feeling");
	BNet::Utils::preprintprofcooking($count, '58523', "Bad Clams", "inv_misc_shell_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88013', "Chocolate Cookie", "inv_misc_food_150_cookie", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43779', "Delicious Chocolate Cake", "inv_misc_celebrationcake_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '58521', "Last Week's Mammoth", "inv_misc_food_114_orcablubber", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '58525', "Haunted Herring", "inv_misc_fish_66", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '58512', "Tasty Cupcake", "inv_valentineschocolate01", %multiusercriteria);
	BNet::Utils::groupheader ("Unusual Delights");
	BNet::Utils::preprintprofcooking($count, '58527', "Gigantic Feast", "ability_hunter_pet_boar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '58528', "Small Feast", "ability_hunter_pet_boar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '43772', "Kibler's Bits", "inv_misc_food_49", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '15906', "Dragonbreath Chili", "inv_drink_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '8238', "Savory Deviate Delight", "inv_misc_monsterhead_04", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45695', "Captain Rumsey's Lager", "inv_drink_03", %multiusercriteria);
	BNet::Utils::groupheader ("Cataclysm Recipes");
	BNet::Utils::preprintprofcooking($count, '88003', "Baked Rockfish", "inv_misc_food_155_fish_78", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88004', "Basilisk Liverdog", "inv_misc_food_17", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88005', "Beer-Basted Crocolisk", "inv_misc_food_meat_cooked_08", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88034', "Blackbelly Sushi", "inv_misc_food_161_fish_89", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88006', "Blackened Surprise", "inv_misc_food_108_meadcaribou", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88011', "Broiled Dragon Feast", "inv_misc_food_99", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88012', "Broiled Mountain Trout", "inv_misc_food_159_fish_82", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88014', "Crocolisk Au Gratin", "inv_misc_food_meat_cooked_10", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88015', "Darkbrew Lager", "spell_misc_drink", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88016', "Delicious Sagefish Tail", "inv_misc_food_158_fish_81", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88017', "Feathered Lure", "spell_magic_featherfall", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88018', "Fish Fry", "inv_misc_food_88_ravagernuggets", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88019', "Fortune Cookie", "inv_misc_fortunecookie", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88021', "Hearty Seafood Soup", "inv_misc_food_meat_cooked_03", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88022', "Highland Spirits", "inv_drink_26_goatsmilk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88020', "Grilled Dragon", "inv_misc_food_122_steak", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88024', "Lavascale Fillet", "inv_misc_food_156_fish_79", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88025', "Lavascale Minestrone", "inv_misc_food_154_fish_77", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88028', "Lightly Fried Lurker", "inv_misc_food_157_fish_80", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88030', "Lurker Lunch", "inv_misc_food_meat_cooked_05", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88031', "Mushroom Sauce Mudfish", "inv_misc_food_meat_cooked_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88033', "Pickled Guppy", "inv_misc_food_162_fish_90", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '96133', "Scalding Murglesnout", "inv_misc_food_159_fish_white", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88035', "Salted Eye", "inv_misc_eye_04", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88036', "Seafood Magnifique Feast", "inv_misc_food_meat_cooked_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88037', "Seasoned Crab", "inv_misc_birdbeck_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88039', "Severed Sagefish Head", "inv_misc_food_160_fish_87", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88042', "Skewered Eel", "inv_misc_food_163_fish_91", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88045', "Starfire Espresso", "inv_drink_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88044', "South Island Iced Tea", "inv_misc_goblincup01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88046', "Tender Baked Turtle", "inv_misc_food_meat_cooked_05", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '88047', "Whitecrest Gumbo", "inv_misc_food_meat_cooked_02", %multiusercriteria);
	BNet::Utils::groupheader ("Recipes of the Cold North");
	BNet::Utils::preprintprofcooking($count, '45569', "Baked Manta Ray", "inv_misc_food_140_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57441', "Blackened Dragonfin", "inv_misc_food_142_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57438', "Blackened Worg Steak", "inv_misc_food_84_roastclefthoof", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '64358', "Black Jelly", "inv_misc_slime_02", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57435', "Critter Bites", "inv_misc_food_88_ravagernuggets", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57439', "Cuttlesteak", "inv_misc_food_133_meat", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '58065', "Dalaran Clam Chowder", "inv_misc_cauldron_frost", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57442', "Dragonfin Filet", "inv_misc_food_75", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45568', "Firecracker Salmon", "inv_misc_food_141_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57423', "Fish Feast", "inv_misc_fish_52", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45554', "Great Feast", "ability_hunter_pet_boar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45561', "Grilled Bonescale", "inv_misc_food_143_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45563', "Grilled Sculpin", "inv_misc_food_79", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57436', "Hearty Rhino", "inv_misc_food_115_condorsoup", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45570', "Imperial Manta Steak", "inv_misc_food_121_buttermeat", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '53056', "Kungaloosh", "inv_drink_21", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45549', "Mammoth Meal", "inv_misc_food_116_condorleg", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45555', "Mega Mammoth Meal", "inv_misc_food_108_meadcaribou", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45559', "Mighty Rhino Dogs", "inv_misc_food_66", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57421', "Northern Stew", "inv_misc_food_117_heartysoup", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45566', "Pickled Fangtooth", "inv_misc_food_76", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45565', "Poached Nettlefish", "inv_misc_food_138_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45567', "Poached Northern Sculpin", "inv_misc_food_77", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45553', "Rhino Dogs", "inv_misc_food_53", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57434', "Rhinolicious Wormsteak", "inv_misc_food_47", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45552', "Roasted Worg", "inv_misc_food_86_basilisk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45562', "Sauteed Goby", "inv_misc_food_125_fishchunk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45550', "Shoveltusk Steak", "inv_misc_food_89", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45560', "Smoked Rockfin", "inv_misc_food_131_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45564', "Smoked Salmon", "inv_misc_food_130_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57437', "Snapper Extreme", "inv_misc_food_129_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57440', "Spiced Mammoth Treats", "inv_misc_food_123_roast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45557', "Spiced Worm Burger", "inv_misc_food_65", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45571', "Spicy Blue Nettlefish", "inv_misc_food_139_fish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57433', "Spicy Fried Herring", "inv_misc_food_78", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45556', "Tender Shoveltusk Steak", "inv_misc_food_122_steak", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '57443', "Tracker Snacks", "inv_misc_food_85_stegadonbite", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45558', "Very Burnt Worg", "inv_misc_food_60", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '62350', "Worg Tartare", "inv_misc_food_71", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '45551', "Worm Delight", "inv_misc_food_124_skewer", %multiusercriteria);
	BNet::Utils::groupheader ("Pandaren Cuisine");
	BNet::Utils::groupheader ("Way of the Grill");
	BNet::Utils::preprintprofcooking($count, '125142', "Great Banquet of the Grill", "inv_misc_food_cooked_pabanquet_grill", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125141', "Banquet of the Grill", "inv_misc_food_cooked_greatpabanquet_grill", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104300', "Black Pepper Ribs and Shrimp", "inv_misc_food_cooked_golden_black_pepper_ribs_and_shrimp", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145311', "Fluffy Silkfeather Omelet", "inv_misc_food_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104299', "Eternal Blossom Fish", "inv_misc_food_cooked_eternalblossomfish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104298', "Charbroiled Tiger Steak", "inv_misc_food_cooked_tigersteak", %multiusercriteria);
	BNet::Utils::groupheader ("Way of the Wok");
	BNet::Utils::preprintprofcooking($count, '125595', "Great Banquet of the Wok", "inv_misc_food_cooked_greatpabanquet_wok", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125594', "Banquet of the Wok", "inv_misc_food_cooked_pabanquet_wok", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104303', "Sea Mist Rice Noodles", "inv_misc_food_cooked_seamistricenoodles", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145305', "Seasoned Pomfruit Slices", "inv_misc_food_vendor_slicedpeaches", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104302', "Valley Stir Fry", "inv_misc_food_cooked_valleystirfry", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104301', "Sauteed Carrots", "inv_misc_food_cooked_sauteedcarrots", %multiusercriteria);
	BNet::Utils::groupheader ("Way of the Pot");
	BNet::Utils::preprintprofcooking($count, '125597', "Great Banquet of the Pot", "inv_misc_food_cooked_greatpabanquet_pot", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125596', "Banquet of the Pot", "inv_misc_food_cooked_pabanquet_pot", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104306', "Mogu Fish Stew", "inv_misc_food_cooked_mogufishstew", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145307', "Spiced Blossom Soup", "inv_misc_herb_frostlotus", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104305', "Braised Turtle", "inv_misc_food_cooked_braisedturtle", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104304', "Swirling Mist Soup", "inv_misc_food_cooked_swirlingmistsoup", %multiusercriteria);
	BNet::Utils::groupheader ("Way of the Steamer");
	BNet::Utils::preprintprofcooking($count, '125599', "Great Banquet of the Steamer", "inv_misc_food_cooked_greatpabanquet_steamer", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125598', "Banquet of the Steamer", "inv_misc_food_cooked_pabanquet_steamer", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145309', "Farmer's Delight", "inv_misc_food_117_heartysoup", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104309', "Steamed Crab Surprise", "inv_misc_food_cooked_steamcrabsurprise", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104308', "Fire Spirit Salmon", "inv_misc_food_cooked_firespiritsalmon", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104307', "Shrimp Dumplings", "inv_misc_food_cooked_shrimpdumplings", %multiusercriteria);
	BNet::Utils::groupheader ("Way of the Oven");
	BNet::Utils::preprintprofcooking($count, '125601', "Great Banquet of the Oven", "inv_misc_food_cooked_greatpabanquet_oven", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125600', "Banquet of the Oven", "inv_misc_food_cooked_pabanquet_oven", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104312', "Chun Tian Spring Rolls", "inv_misc_food_cooked_springrolls", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145310', "Stuffed Lushrooms", "spell_druid_wildmushroom", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104311', "Twin Fish Platter", "inv_misc_food_cooked_twinfishplatter", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104310', "Wildfowl Roast", "inv_misc_food_cooked_wildfowlroast", %multiusercriteria);
	BNet::Utils::groupheader ("Way of the Brew");
	BNet::Utils::preprintprofcooking($count, '125603', "Great Banquet of the Brew", "inv_misc_food_cooked_greatpabanquet_brew", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125602', "Banquet of the Brew", "inv_misc_food_cooked_pabanquet_brew", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '126655', "Banana Infused Rum", "inv_drink_01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '126654', "Four Senses Brew", "inv_misc_food_cooked_madbrewbreakfast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124054', "Mad Brewer's Breakfast", "inv_drink_32_disgustingrotgut", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124053', "Jade Witch Brew", "inv_drink_31_embalmingfluid", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124052', "Ginseng Tea", "inv_misc_food_cooked_ginsengtea", %multiusercriteria);
	BNet::Utils::groupheader ("Everyday Cooking");
	BNet::Utils::preprintprofcooking($count, '145062', "Pandaren Treasure Noodle Cart Kit", "inv_misc_noodle_cart_epic_level", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145061', "Deluxe Noodle Cart Kit", "inv_misc_noodle_cart_intermediate_level", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145038', "Noodle Cart Kit", "inv_misc_noodle_cart_base_level", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '105194', "Great Pandaren Banquet", "inv_misc_food_cooked_greatpabanquet_general", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '105190', "Pandaren Banquet", "inv_misc_food_cooked_pabanquet_general", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104297', "Fish Cake", "inv_misc_food_cooked_fishcake", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '104237', "Golden Carp Consomme", "inv_misc_food_cooked_goldcarpconsomme", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124032', "Krasarang Fritters", "inv_misc_food_124_skewer", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '145308', "Mango Ice", "inv_misc_food_mango_ice", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125122', "Rice Pudding", "inv_misc_food_vendor_poundedricecake_1", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125120', "Spicy Salmon", "inv_misc_food_meat_cooked_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125123', "Spicy Vegetable Chips", "inv_misc_food_vendor_poundedricecakes", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124029', "Viseclaw Soup", "inv_misc_food_64", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125121', "Wildfowl Ginseng Soup", "inv_misc_food_vendor_needlemushroomsoup", %multiusercriteria);
	BNet::Utils::groupheader ("Training Recipes");
	BNet::Utils::preprintprofcooking($count, '125117', "Sliced Peaches", "inv_misc_food_vendor_slicedpeaches", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125067', "Perfectly Cooked Instant Noodles", "inv_misc_cookednoodles", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124225', "Toasted Fish Jerky", "inv_misc_food_vendor_toastedfishjerky", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124227', "Dried Needle Mushrooms", "inv_misc_food_vendor_needlemushroom", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124223', "Pounded Rice Cake", "inv_misc_food_168_ricecake01", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124224', "Yak Cheese Curds", "inv_misc_food_vendor_yakcheesecurds", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124226', "Dried Peaches", "inv_misc_leatherscrap_06", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124228', "Boiled Silkworm Pupa", "inv_misc_food_vendor_boiledsilkwormpupa", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125078', "Roasted Barley Tea", "inv_misc_food_vendor_roastedbarlytea", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124233', "Blanched Needle Mushrooms", "inv_misc_food_vendor_blanchedneedlemushroom", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124229', "Red Bean Bun", "inv_misc_food_vendor_redbeanbun", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124234', "Skewered Peanut Chicken", "inv_misc_skeweredpeanutchicken", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124231', "Green Curry Fish", "inv_misc_food_vendor_greenfishbonescurry", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124232', "Peach Pie", "inv_misc_food_vendor_peachpie", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '124230', "Tangy Yogurt", "inv_misc_food_vendor_tangypeachyogurt", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '125080', "Pearl Milk Tea", "inv_drink_milk_01", %multiusercriteria);
	BNet::Utils::groupheader ("Food of Draenor");
	BNet::Utils::groupheader ("Feasts");
	BNet::Utils::preprintprofcooking($count, '173978', "Feast of Blood", "inv_tradeskill_cooking_feastofblood", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '173979', "Feast of the Waters", "inv_tradeskill_cooking_feastofthewater", %multiusercriteria);
	BNet::Utils::groupheader ("Delicacies");
	BNet::Utils::preprintprofcooking($count, '160986', "Blackrock Barbecue", "inv_misc_blackrockbarbeque", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160999', "Calamari Crepes", "inv_misc_calamaricrepes", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160987', "Frosty Stew", "inv_misc_frostystew", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '161000', "Gorgrond Chowder", "inv_misc_gorgrondchowder", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160989', "Sleeper Surprise", "inv_misc_sleepersurprise", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160984', "Talador Surf and Turf", "inv_misc_taladorsurfandturf", %multiusercriteria);
	BNet::Utils::groupheader ("Meat Dishes");
	BNet::Utils::preprintprofcooking($count, '190788', "Fel Eggs and Ham", "inv_food_feleggsnham", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160962', "Blackrock Ham", "inv_misc_blackrockham", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160968', "Braised Riverbeast", "inv_misc_braisedriverbeast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160971', "Clefthoof Sausages", "inv_misc_clefhoofsausages", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160958', "Hearty Elekk Steak", "inv_misc_heartyelekksteak", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160966', "Pan-Seared Talbuk", "inv_misc_panseardtalbuk", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160969', "Rylak Crepes", "inv_misc_rylakcrepes", %multiusercriteria);
	BNet::Utils::groupheader ("Fish Dishes");
	BNet::Utils::preprintprofcooking($count, '180761', "Buttered Sturgeon", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160981', "Fat Sleeper Cakes", "inv_misc_food_draenor_fatsleepercakes", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160982', "Fiery Calamari", "inv_misc_food_draenor_fierycalamari", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160978', "Grilled Gulper", "inv_misc_food_draenor_grilledgulper", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '161002', "Grilled Saberfish", "inv_misc_food_draenor_grilledsaberfish", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '180759', "Jumbo Sea Dog", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '180758', "Pickled Eel", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '180757', "Salty Squid Roll", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160983', "Skulker Chowder", "inv_misc_food_draenor_whiptailchowder", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '180762', "Sleeper Sushi", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160973', "Steamed Scorpion", "inv_misc_food_draenor_steamedscorpion", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '160979', "Sturgeon Stew", "inv_misc_food_draenor_sturgeonstew", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '180760', "Whiptail Fillet", "inv_misc_food_15", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '161001', "Saberfish Broth", "inv_misc_food_draenor_saberfishbroth", %multiusercriteria);
	BNet::Utils::groupheader ("Food of the Broken Isles");
	BNet::Utils::groupheader ("Snacks");
#	BNet::Utils::preprintprofcookinglegion($count, '201513', '201540', '201560', "Bear Tartare", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201513', "Bear Tartare (Rank 1)", "inv_misc_food_legion_beartartare", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201540', "Bear Tartare (Rank 2)", "inv_misc_food_legion_beartartare", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201560', "Bear Tartare (Rank 3)", "inv_misc_food_legion_beartartare", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201683', "Crispy Bacon (Rank 1)", "inv_misc_food_legion_baconcrispy", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201684', "Crispy Bacon (Rank 2)", "inv_misc_food_legion_baconcrispy", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201685', "Crispy Bacon (Rank 3)", "inv_misc_food_legion_baconcrispy", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201512', "Dried Mackerel Strips (Rank 1)", "inv_misc_food_legion_driedmackerelstrips", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201539', "Dried Mackerel Strips (Rank 2)", "inv_misc_food_legion_driedmackerelstrips", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201559', "Dried Mackerel Strips (Rank 3)", "inv_misc_food_legion_driedmackerelstrips", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201514', "Fighter Chow (Rank 1)", "inv_misc_food_legion_fighterchow", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201541', "Fighter Chow (Rank 2)", "inv_misc_food_legion_fighterchow", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201561', "Fighter Chow (Rank 3)", "inv_misc_food_legion_fighterchow", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '230046', "Spiced Falcosaur Omelet", "inv_misc_food_cooked_fishcake", %multiusercriteria);
	BNet::Utils::groupheader ("Light Meals");
	BNet::Utils::preprintprofcooking($count, '201496', "Deep-Fried Mossgill (Rank 1)", "inv_misc_food_legion_deepfriedmossgill", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201525', "Deep-Fried Mossgill (Rank 2)", "inv_misc_food_legion_deepfriedmossgill", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201545', "Deep-Fried Mossgill (Rank 3)", "inv_misc_food_legion_deepfriedmossgill", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201498', "Faronaar Fizz (Rank 1)", "inv_misc_food_legion_faronaarfizz", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201527', "Faronaar Fizz (Rank 2)", "inv_misc_food_legion_faronaarfizz", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201547', "Faronaar Fizz (Rank 3)", "inv_misc_food_legion_faronaarfizz", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201497', "Pickled Stormray (Rank 1)", "inv_misc_food_legion_pickledstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201526', "Pickled Stormray (Rank 2)", "inv_misc_food_legion_pickledstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201546', "Pickled Stormray (Rank 3)", "inv_misc_food_legion_pickledstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201413', "Salt and Pepper Shank (Rank 1)", "inv_misc_food_legion_saltpeppershank", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201524', "Salt and Pepper Shank (Rank 2)", "inv_misc_food_legion_saltpeppershank", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201544', "Salt and Pepper Shank (Rank 3)", "inv_misc_food_legion_saltpeppershank", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201499', "Spiced Rib Roast (Rank 1)", "inv_misc_food_legion_spicedribroast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201528', "Spiced Rib Roast (Rank 2)", "inv_misc_food_legion_spicedribroast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201548', "Spiced Rib Roast (Rank 3)", "inv_misc_food_legion_spicedribroast", %multiusercriteria);
	BNet::Utils::groupheader ("Large Meals");
	BNet::Utils::preprintprofcooking($count, '201502', "Barracuda Mrglgagh (Rank 1)", "inv_misc_food_legion_barracudamrglgagh", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201531', "Barracuda Mrglgagh (Rank 2)", "inv_misc_food_legion_barracudamrglgagh", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201551', "Barracuda Mrglgagh (Rank 3)", "inv_misc_food_legion_barracudamrglgagh", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201504', "Drogbar-Style Salmon (Rank 1)", "inv_misc_food_legion_drogbarstylesalmon", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201533', "Drogbar-Style Salmon (Rank 2)", "inv_misc_food_legion_drogbarstylesalmon", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201553', "Drogbar-Style Salmon (Rank 3)", "inv_misc_food_legion_drogbarstylesalmon", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201503', "Koi-Scented Stormray (Rank 1)", "inv_misc_food_legion_koiscentedstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201532', "Koi-Scented Stormray (Rank 2)", "inv_misc_food_legion_koiscentedstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201552', "Koi-Scented Stormray (Rank 3)", "inv_misc_food_legion_koiscentedstormray", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201500', "Leybeque Ribs (Rank 1)", "inv_misc_food_legion_leybequeribs", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201529', "Leybeque Ribs (Rank 2)", "inv_misc_food_legion_leybequeribs", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201549', "Leybeque Ribs (Rank 3)", "inv_misc_food_legion_leybequeribs", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201501', "Suramar Surf and Turf (Rank 1)", "inv_misc_food_legion_suramarsurfandturf", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201530', "Suramar Surf and Turf (Rank 2)", "inv_misc_food_legion_suramarsurfandturf", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201550', "Suramar Surf and Turf (Rank 3)", "inv_misc_food_legion_suramarsurfandturf", %multiusercriteria);
	BNet::Utils::groupheader ("Delicacies");
	BNet::Utils::preprintprofcooking($count, '201506', "Azshari Salad (Rank 1)", "inv_misc_food_legion_azsharisalad", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201535', "Azshari Salad (Rank 2)", "inv_misc_food_legion_azsharisalad", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201555', "Azshari Salad (Rank 3)", "inv_misc_food_legion_azsharisalad", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201511', "Fishbrul Special (Rank 1)", "inv_misc_food_legion_fishbrulspecial", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201538', "Fishbrul Special (Rank 2)", "inv_misc_food_legion_fishbrulspecial", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201558', "Fishbrul Special (Rank 3)", "inv_misc_food_legion_fishbrulspecial", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201507', "Nightborne Delicacy Platter (Rank 1)", "inv_misc_food_legion_nightbornedelicacyplatter", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201536', "Nightborne Delicacy Platter (Rank 2)", "inv_misc_food_legion_nightbornedelicacyplatter", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201556', "Nightborne Delicacy Platter (Rank 3)", "inv_misc_food_legion_nightbornedelicacyplatter", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201508', "Seed-Battered Fish Plate (Rank 1)", "inv_misc_food_legion_seedbatteredfishplate", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201537', "Seed-Battered Fish Plate (Rank 2)", "inv_misc_food_legion_seedbatteredfishplate", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201557', "Seed-Battered Fish Plate (Rank 3)", "inv_misc_food_legion_seedbatteredfishplate", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201505', "The Hungry Magister (Rank 1)", "inv_misc_food_legion_thehungrymagistar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201534', "The Hungry Magister (Rank 2)", "inv_misc_food_legion_thehungrymagistar", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201554', "The Hungry Magister (Rank 3)", "inv_misc_food_legion_thehungrymagistar", %multiusercriteria);
	BNet::Utils::groupheader ("Feasts");
	BNet::Utils::preprintprofcooking($count, '201515', "Hearty Feast (Rank 1)", "inv_misc_food_legion_heartyfeast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201542', "Hearty Feast (Rank 2)", "inv_misc_food_legion_heartyfeast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201562', "Hearty Feast (Rank 3)", "inv_misc_food_legion_heartyfeast", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201516', "Lavish Suramar Feast (Rank 1)", "inv_misc_food_legion_lavishsuramarfiest", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201543', "Lavish Suramar Feast (Rank 2)", "inv_misc_food_legion_lavishsuramarfiest", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '201563', "Lavish Suramar Feast (Rank 3)", "inv_misc_food_legion_lavishsuramarfiest", %multiusercriteria);
	BNet::Utils::preprintprofcooking($count, '251258', "Feast of the Fishes", "inv_misc_basket_04", %multiusercriteria);

}

1;
