package BNet::Quests_BC;

use strict;
use warnings;

sub z_58_80_Hellfire_Peninsula ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("58: Hellfire Peninsula <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '28705', "Warchief's Command: Outland!", %multiuserquests);
	BNet::Utils::preprint ($count, '9407', "Through the Dark Portal", %multiuserquests);
	BNet::Utils::preprint ($count, '10120', "Arrival in Outland", %multiuserquests);
	BNet::Utils::preprint ($count, '10289', "Journey to Thrallmar", %multiuserquests);
	BNet::Utils::preprint ($count, '10291', "Report to Nazgrel", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar: Initial <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10121', "Eradicate the Burning Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '10123', "Felspark Ravine", %multiuserquests);
	BNet::Utils::preprint ($count, '10124', "Forward Base: Reaver's Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '10208', "Disrupt Their Reinforcements", %multiuserquests);
	BNet::Utils::preprint ($count, '10129', "Mission: Gateways Murketh and Shaadraz", %multiuserquests);
	BNet::Utils::preprint ($count, '10162', "Mission: The Abyssal Shelf", %multiuserquests);
	BNet::Utils::preprint ($count, '10388', "Return to Thrallmar", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10086', "I Work... For the Horde!", %multiuserquests);
	BNet::Utils::preprint ($count, '10087', "Burn It Up... For the Horde!", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar PvP <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10349', "Hellfire Fortifications", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Mag'har <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9400', "The Assassin", %multiuserquests);
	BNet::Utils::preprint ($count, '9401', "A Strange Weapon", %multiuserquests);
	BNet::Utils::preprint ($count, '9405', "The Warchief's Mandate", %multiuserquests);
	BNet::Utils::preprint ($count, '9410', "A Spirit Guide", %multiuserquests);
	BNet::Utils::preprint ($count, '9406', "The Mag'har", %multiuserquests);
	BNet::Utils::preprint ($count, '9442', "A Debilitating Sickness (Obsolete)", %multiuserquests);
	BNet::Utils::preprint ($count, '9447', "Administering the Salve (Obsolete)", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Fel Orc Blood <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10450', "Bonechewer Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '10449', "Apothecary Zelana", %multiuserquests);
	BNet::Utils::preprint ($count, '10242', "Spinebreaker Post", %multiuserquests);
	BNet::Utils::preprint ($count, '10538', "Boiling Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '10835', "Apothecary Antonivich", %multiuserquests);
	BNet::Utils::preprint ($count, '10864', "A Burden of Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '10838', "The Demoniac Scryer", %multiuserquests);
	BNet::Utils::preprint ($count, '10875', "Report to Nazgrel", %multiuserquests);
	BNet::Utils::preprint ($count, '10876', "The Foot of the Citadel", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Forge Camp: Mageddon <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10390', "Forge Camp: Mageddon", %multiuserquests);
	BNet::Utils::preprint ($count, '10391', "Cannons of Rage", %multiuserquests);
	BNet::Utils::preprint ($count, '10392', "Doorway to the Abyss", %multiuserquests);
	BNet::Utils::preprint ($count, '10389', "The Agony and the Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '10136', "Cruel's Intentions", %multiuserquests);
	BNet::Utils::preprint ($count, '10393', "Vile Plans", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Honor the Fallen <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10220', "Make Them Listen", %multiuserquests);
	BNet::Utils::preprint ($count, '10229', "Decipher the Tome", %multiuserquests);
	BNet::Utils::preprint ($count, '10230', "The Battle Horn", %multiuserquests);
	BNet::Utils::preprint ($count, '10250', "Bloody Vengeance", %multiuserquests);
	BNet::Utils::preprint ($count, '10258', "Honor the Fallen", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Ogath the Mad <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10278', "The Warp Rifts", %multiuserquests);
	BNet::Utils::preprint ($count, '10294', "Void Ridge", %multiuserquests);
	BNet::Utils::preprint ($count, '10295', "From the Abyss", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Zeth'gor <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10792', "Zeth'Gor Must Burn!", %multiuserquests);
	BNet::Utils::preprint ($count, '10809', "Wanted: Worg Master Kruush", %multiuserquests);
	BNet::Utils::preprint ($count, '10813', "The Eyes of Grillok", %multiuserquests);
	BNet::Utils::preprint ($count, '10834', "Grillok \"Darkeye\"", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Zeppelin <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9345', "Preparing the Salve", %multiuserquests);
	BNet::Utils::preprint ($count, '10213', "Investigate the Crash", %multiuserquests);
	BNet::Utils::preprint ($count, '10161', "In Case of Emergency...", %multiuserquests);
	BNet::Utils::preprint ($count, '9351', "Voidwalkers Gone Wild", %multiuserquests);
	BNet::Utils::preprint ($count, '9349', "Ravager Egg Roundup", %multiuserquests);
	BNet::Utils::preprint ($count, '9361', "Helboar, the Other White Meat", %multiuserquests);
	BNet::Utils::preprint ($count, '9356', "Smooth as Butter", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9375', "The Road to Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9498', "Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9499', "Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9340', "The Great Fissure", %multiuserquests);
	BNet::Utils::preprint ($count, '9391', "Marking the Path", %multiuserquests);
	BNet::Utils::preprint ($count, '9376', "A Pilgrim's Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '9381', "Trueflight Arrows", %multiuserquests);
	BNet::Utils::preprint ($count, '9466', "Wanted: Blacktalon the Savage", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch: Arelion's Mistress <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9374', "Arelion's Journal", %multiuserquests);
	BNet::Utils::preprint ($count, '10286', "Arelion's Secret", %multiuserquests);
	BNet::Utils::preprint ($count, '10287', "The Mistress Revealed", %multiuserquests);
	BNet::Utils::preprint ($count, '9483', "Life's Finer Pleasures", %multiuserquests);
	BNet::Utils::preprint ($count, '9472', "Arelion's Mistress", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch: Miscellaneou <img src=\"http://wow.zamimg.com/images/icons/horde.png\">s");
	BNet::Utils::preprint ($count, '9397', "Birds of a Feather", %multiuserquests);
	BNet::Utils::preprint ($count, '9366', "In Need of Felblood", %multiuserquests);
	BNet::Utils::preprint ($count, '9370', "The Cleansing Must Be Stopped", %multiuserquests);
	BNet::Utils::preprint ($count, '9387', "Source of the Corruption", %multiuserquests);
	BNet::Utils::preprint ($count, '9396', "Magic of the Arakkoa", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Cenarion Post <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10442', "Helping the Cenarion Post", %multiuserquests);
	BNet::Utils::preprint ($count, '9373', "Missing Missive", %multiuserquests);
	BNet::Utils::preprint ($count, '9372', "Demonic Contamination", %multiuserquests);
	BNet::Utils::preprint ($count, '10255', "Testing the Antidote", %multiuserquests);
	BNet::Utils::preprint ($count, '10159', "Keep Thornfang Hill Clear!", %multiuserquests);
	BNet::Utils::preprint ($count, '10132', "Colossal Menace", %multiuserquests);
	BNet::Utils::preprint ($count, '10134', "Crimson Crystal Clue", %multiuserquests);
	BNet::Utils::preprint ($count, '10349', "The Earthbinder", %multiuserquests);
	BNet::Utils::preprint ($count, '10351', "Natural Remedies", %multiuserquests);
	BNet::Utils::preprint ($count, '9912', "The Cenarion Expedition", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Neutral quest chains");
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Outland Sucks!");
	BNet::Utils::preprint ($count, '10236', "Outland Sucks!", %multiuserquests);
	BNet::Utils::preprint ($count, '10238', "How to Serve Goblins", %multiuserquests);
	BNet::Utils::preprint ($count, '10629', "Shizz Work", %multiuserquests);
	BNet::Utils::preprint ($count, '10630', "Beneath Thrallmar", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Dreghood");
	BNet::Utils::preprint ($count, '10403', "Naladu", %multiuserquests);
	BNet::Utils::preprint ($count, '10367', "A Traitor Among Us", %multiuserquests);
	BNet::Utils::preprint ($count, '10368', "The Dreghood Elders", %multiuserquests);
	BNet::Utils::preprint ($count, '10369', "Arzeth's Demise", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Miscellaneous");
	BNet::Utils::preprint ($count, '9418', "Avruu's Orb", %multiuserquests);

}

sub z_60_80_Zangarmarsh ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Zangarmarsh: Cenarion Refuge");
	BNet::Utils::preprint ($count, '9912', "The Cenarion Expedition", %multiuserquests);
	BNet::Utils::preprint ($count, '39180', "Warchief's Command: Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9895', "The Dying Balance", %multiuserquests);
	BNet::Utils::preprint ($count, '9747', "The Umbrafen Tribe", %multiuserquests);
	BNet::Utils::preprint ($count, '9788', "A Damp, Dark Place", %multiuserquests);
	BNet::Utils::preprint ($count, '10096', "Saving the Sporeloks", %multiuserquests);
	BNet::Utils::preprint ($count, '9894', "Safeguarding the Watchers", %multiuserquests);
	BNet::Utils::preprint ($count, '9716', "Disturbance at Umbrafen Lake", %multiuserquests);
	BNet::Utils::preprint ($count, '9718', "As the Crow Flies", %multiuserquests);
	BNet::Utils::preprint ($count, '9720', "Balance Must Be Preserved", %multiuserquests);
	BNet::Utils::preprint ($count, '9731', "Drain Schematics", %multiuserquests);
	BNet::Utils::preprint ($count, '9724', "Warning the Cenarion Circle", %multiuserquests);
	BNet::Utils::preprint ($count, '9732', "Return to the Marsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9876', "Failed Incursion (Obsolete)", %multiuserquests);
	BNet::Utils::preprint ($count, '9817', "Leader of the Bloodscale", %multiuserquests);
	BNet::Utils::preprint ($count, '9802', "Plants of Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9697', "Watcher Leesa'oh", %multiuserquests);
	BNet::Utils::preprint ($count, '9957', "What's Wrong at Cenarion Thicket?", %multiuserquests);
	BNet::Utils::preprint ($count, '9785', "Blessings of the Ancients", %multiuserquests);
	BNet::Utils::preprint ($count, '9730', "Leader of the Darkcrest", %multiuserquests);
	BNet::Utils::preprint ($count, '9778', "Warden Hamoot", %multiuserquests);
	BNet::Utils::preprint ($count, '9728', "A Warm Welcome", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Cenarion Watchpost");
	BNet::Utils::preprint ($count, '9701', "Observing the Sporelings", %multiuserquests);
	BNet::Utils::preprint ($count, '9702', "A Question of Gluttony", %multiuserquests);
	BNet::Utils::preprint ($count, '9708', "Familiar Fungi", %multiuserquests);
	BNet::Utils::preprint ($count, '9709', "Stealing Back the Mushrooms", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Sporeggar");
	BNet::Utils::preprint ($count, '9806', "Fertile Spores", %multiuserquests);
	BNet::Utils::preprint ($count, '9808', "Glowcap Mushrooms", %multiuserquests);
	BNet::Utils::preprint ($count, '9726', "Now That We're Friends...", %multiuserquests);
	BNet::Utils::preprint ($count, '9729', "Fhwoor Smash!", %multiuserquests);
	BNet::Utils::preprint ($count, '9739', "The Sporelings' Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '9743', "Natural Enemies", %multiuserquests);
	BNet::Utils::preprint ($count, '9919', "Sporeggar", %multiuserquests);
	BNet::Utils::preprint ($count, '9911', "The Count of the Marshes", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Swamprat Post (Horde)");
	BNet::Utils::preprint ($count, '9899', "A Job Undone", %multiuserquests);
	BNet::Utils::preprint ($count, '9773', "No More Mushrooms!", %multiuserquests);
	BNet::Utils::preprint ($count, '9770', "Menacing Marshfangs", %multiuserquests);
	BNet::Utils::preprint ($count, '9898', "Nothin' Says Lovin' Like a Big Stinger", %multiuserquests);
	BNet::Utils::preprint ($count, '9796', "News from Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9775', "Report to Shadow Hunter Denjai", %multiuserquests);
	BNet::Utils::preprint ($count, '9769', "There's No Explanation for Fashion", %multiuserquests);
	BNet::Utils::preprint ($count, '9774', "Thick Hydra Scales", %multiuserquests);
	BNet::Utils::preprint ($count, '9771', "Searching for Scout Jyoba", %multiuserquests);
	BNet::Utils::preprint ($count, '9772', "Jyoba's Report", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Zabra'jin (Horde)");
	BNet::Utils::preprint ($count, '10105', "News for Rakoria", %multiuserquests);
	BNet::Utils::preprint ($count, '9846', "Spirits of the Feralfen", %multiuserquests);
	BNet::Utils::preprint ($count, '9847', "A Spirit Ally?", %multiuserquests);
	BNet::Utils::preprint ($count, '9845', "Angling to Beat the Competition", %multiuserquests);
	BNet::Utils::preprint ($count, '9904', "Pursuing Terrorclaw", %multiuserquests);
	BNet::Utils::preprint ($count, '9903', "The Biggest of Them All", %multiuserquests);
	BNet::Utils::preprint ($count, '9814', "Burstcap Mushrooms, Mon!", %multiuserquests);
	BNet::Utils::preprint ($count, '9816', "Have You Ever Seen One of These?", %multiuserquests);
	BNet::Utils::preprint ($count, '9797', "Reinforcements for Garadar", %multiuserquests);
	BNet::Utils::preprint ($count, '9795', "The Ogre Threat", %multiuserquests);
	BNet::Utils::preprint ($count, '9841', "Stinging the Stingers", %multiuserquests);
	BNet::Utils::preprint ($count, '9842', "The Sharpest Blades", %multiuserquests);
	BNet::Utils::preprint ($count, '9820', "WANTED: Boss Grog'ak", %multiuserquests);
	BNet::Utils::preprint ($count, '9822', "Impending Attack", %multiuserquests);
	BNet::Utils::preprint ($count, '9823', "Us or Them", %multiuserquests);
	BNet::Utils::preprint ($count, '10117', "Wanted: Chieftain Mummaki", %multiuserquests);
	BNet::Utils::preprint ($count, '10118', "Message to the Daggerfen", %multiuserquests);
	BNet::Utils::preprint ($count, '9828', "Withered Basidium", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Umbrafen Village");
	BNet::Utils::preprint ($count, '9752', "Escape from Umbrafen", %multiuserquests);
}


sub z_62_80_Terokkar_Forest ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("62: Terrokar Forest");
	BNet::Utils::preprint ($count, '39188', "Hero's Call: Terokkar Forest <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '39182', "Warchief's Command: Terokkar Forest <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Shattrath");
	BNet::Utils::preprint ($count, '10210', "A'dal", %multiuserquests);
	BNet::Utils::preprint ($count, '10211', "City of Light", %multiuserquests);
	BNet::Utils::preprint ($count, '10037', "Rather Be Fishin'", %multiuserquests);
	BNet::Utils::preprint ($count, '10917', "The Outcast's Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '10180', "Can't Stay Away", %multiuserquests);
	BNet::Utils::preprint ($count, '10847', "The Eyes of Skettis", %multiuserquests);
	BNet::Utils::preprint ($count, '10849', "Seek Out Kirrik", %multiuserquests);
	BNet::Utils::preprint ($count, '10839', "Veil Skith: Darkstone of Terokk", %multiuserquests);
	BNet::Utils::preprint ($count, '10848', "Veil Rhaze: Unliving Evil", %multiuserquests);
	BNet::Utils::preprint ($count, '10861', "Veil Lithic: Preemptive Strike", %multiuserquests);
	BNet::Utils::preprint ($count, '10874', "Veil Shalas: Signal Fires", %multiuserquests);
	BNet::Utils::preprint ($count, '10889', "Return to Shattrath", %multiuserquests);
	BNet::Utils::preprint ($count, '10879', "The Skettis Offensive", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Cenarian Thicket");
	BNet::Utils::preprint ($count, '9957', "What's Wrong at Cenarion Thicket?", %multiuserquests);
	BNet::Utils::preprint ($count, '9960', "What's Wrong at Cenarion Thicket? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9961', "What's Wrong at Cenarion Thicket? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9968', "Strange Energy", %multiuserquests);
	BNet::Utils::preprint ($count, '9971', "Clues in the Thicket", %multiuserquests);
	BNet::Utils::preprint ($count, '9978', "By Any Means Necessary", %multiuserquests);
	BNet::Utils::preprint ($count, '9979', "Wind Trader Lathrai", %multiuserquests);
	BNet::Utils::preprint ($count, '10112', "A Personal Favor", %multiuserquests);
	BNet::Utils::preprint ($count, '9990', "Investigate Tuurem", %multiuserquests);
	BNet::Utils::preprint ($count, '9951', "It's Watching You!", %multiuserquests);
	BNet::Utils::preprint ($count, '9994', "What Are These Things? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9995', "What Are These Things? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10444', "Report to the Allerian Post <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10448', "Report to Stonebreaker Camp <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9996', "Attack on Firewing Point <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9997', "Attack on Firewing Point <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10446', "The Final Code <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10447', "The Final Code <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10005', "Letting Earthbinder Tavgren Know <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10006', "Letting Earthbinder Tavgren Know <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Firewing Point");
	BNet::Utils::preprint ($count, '10051', "Escape from Firewing Point! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10052', "Escape from Firewing Point! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Bonechewer Ruins");
	BNet::Utils::preprint ($count, '10012', "Fel Orc Plans <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10013', "An Unseen Hand <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Refugee Caravan");
	BNet::Utils::preprint ($count, '10842', "Vengeful Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '10908', "Speak with Rilak the Redeemed", %multiuserquests);
	BNet::Utils::preprint ($count, '10863', "Secrets of the Arakkoa <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10862', "Surrender to the Horde <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10896', "The Infested Protectors", %multiuserquests);
	BNet::Utils::preprint ($count, '10878', "Before Darkness Falls", %multiuserquests);
	BNet::Utils::preprint ($count, '10852', "Missing Friends", %multiuserquests);
	BNet::Utils::preprint ($count, '10840', "The Tomb of Lights", %multiuserquests);
	BNet::Utils::preprint ($count, '10030', "Recover the Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '10031', "Helping the Lost Find Their Way", %multiuserquests);
	BNet::Utils::preprint ($count, '10880', "Cabal Orders", %multiuserquests);
	BNet::Utils::preprint ($count, '10881', "The Shadow Tomb", %multiuserquests);
	BNet::Utils::preprint ($count, '10887', "Escaping the Tomb", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Sha'tari Base Camp");
	BNet::Utils::preprint ($count, '10922', "Digging Through Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '10929', "Fumping", %multiuserquests);
	BNet::Utils::preprint ($count, '10930', "The Big Bone Worm", %multiuserquests);
	BNet::Utils::preprint ($count, '10877', "The Dread Relic", %multiuserquests);
	BNet::Utils::preprint ($count, '10923', "Evil Draws Near", %multiuserquests);
	BNet::Utils::preprint ($count, '10913', "An Improper Burial", %multiuserquests);
	BNet::Utils::preprint ($count, '10914', "A Hero Is Needed", %multiuserquests);
	BNet::Utils::preprint ($count, '10915', "The Fallen Exarch", %multiuserquests);
	BNet::Utils::preprint ($count, '10873', "Taken in the Night", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Netherweb Ridge");
	BNet::Utils::preprint ($count, '10898', "Skywing", %multiuserquests);
	BNet::Utils::preprint ($count, '10920', "For the Fallen", %multiuserquests);
	BNet::Utils::preprint ($count, '10921', "Terokkarantula", %multiuserquests);
	BNet::Utils::preprint ($count, '10926', "Return to Sha'tari Base Camp", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Auchindoun");
	BNet::Utils::preprint ($count, '10227', "I See Dead Draenei", %multiuserquests);
	BNet::Utils::preprint ($count, '10228', "Ezekiel", %multiuserquests);
	BNet::Utils::preprint ($count, '10231', "What Book? I Don't See Any Book.", %multiuserquests);
	BNet::Utils::preprint ($count, '10251', "The Master's Grand Design?", %multiuserquests);
	BNet::Utils::preprint ($count, '10252', "Vision of the Dead", %multiuserquests);
	BNet::Utils::preprint ($count, '10253', "Levixus the Soul Caller", %multiuserquests);
	BNet::Utils::preprint ($count, '29595', "Everything Will Be Alright", %multiuserquests);
	BNet::Utils::preprint ($count, '29596', "The End of the Exarch", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Stonebreaker Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10105', "News for Rakoria", %multiuserquests);
	BNet::Utils::preprint ($count, '9993', "Olemba Seed Oil", %multiuserquests);
	BNet::Utils::preprint ($count, '10201', "And Now, the Moment of Truth", %multiuserquests);
	BNet::Utils::preprint ($count, '9987', "Stymying the Arakkoa", %multiuserquests);
	BNet::Utils::preprint ($count, '10000', "An Unwelcome Presence", %multiuserquests);
	BNet::Utils::preprint ($count, '10003', "The Firewing Liaison", %multiuserquests);
	BNet::Utils::preprint ($count, '10008', "What Happens in Terokkar Stays in Terokkar", %multiuserquests);
	BNet::Utils::preprint ($count, '10027', "Magical Disturbances", %multiuserquests);
	BNet::Utils::preprint ($count, '10039', "Speak with Scout Neftis", %multiuserquests);
	BNet::Utils::preprint ($count, '10041', "Who Are They?", %multiuserquests);
	BNet::Utils::preprint ($count, '10043', "Kill the Shadow Council!", %multiuserquests);
	BNet::Utils::preprint ($count, '10018', "Vestments of the Wolf Spirit", %multiuserquests);
	BNet::Utils::preprint ($count, '10023', "Patriarch Ironjaw", %multiuserquests);
	BNet::Utils::preprint ($count, '10791', "Welcoming the Wolf Spirit", %multiuserquests);
	BNet::Utils::preprint ($count, '10034', "Wanted: Bonelashers Dead!", %multiuserquests);
	BNet::Utils::preprint ($count, '10036', "Torgos!", %multiuserquests);
	BNet::Utils::preprint ($count, '10868', "Arakkoa War Path", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Allerian Hold <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '9992', "Olemba Seeds", %multiuserquests);
	BNet::Utils::preprint ($count, '10028', "Vessels of Power", %multiuserquests);
	BNet::Utils::preprint ($count, '10026', "Magical Disturbances", %multiuserquests);
	BNet::Utils::preprint ($count, '10038', "Speak with Private Weeks", %multiuserquests);
	BNet::Utils::preprint ($count, '10040', "Who Are They?", %multiuserquests);
	BNet::Utils::preprint ($count, '10042', "Kill the Shadow Council!", %multiuserquests);
	BNet::Utils::preprint ($count, '9998', "Unruly Neighbors", %multiuserquests);
	BNet::Utils::preprint ($count, '10007', "Thinning the Ranks", %multiuserquests);
	BNet::Utils::preprint ($count, '9986', "Stymying the Arakkoa", %multiuserquests);
	BNet::Utils::preprint ($count, '10016', "Timber Worg Tails", %multiuserquests);
	BNet::Utils::preprint ($count, '10022', "The Elusive Ironjaw", %multiuserquests);
	BNet::Utils::preprint ($count, '10002', "The Firewing Liaison", %multiuserquests);
	BNet::Utils::preprint ($count, '10869', "Thin the Flock", %multiuserquests);
	BNet::Utils::preprint ($count, '10033', "Wanted: Bonelashers Dead!", %multiuserquests);
	BNet::Utils::preprint ($count, '10035', "Torgos!", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Skettis");
	BNet::Utils::preprint ($count, '11096', "Threat from Above", %multiuserquests);
	BNet::Utils::preprint ($count, '11098', "To Skettis!", %multiuserquests);
	BNet::Utils::preprint ($count, '11093', "Hungry Nether Rays", %multiuserquests);
	BNet::Utils::preprint ($count, '11004', "World of Shadows", %multiuserquests);
	BNet::Utils::preprint ($count, '11005', "Secrets of the Talonpriests", %multiuserquests);
	BNet::Utils::preprint ($count, '11021', "Ishaal's Almanac", %multiuserquests);
	BNet::Utils::preprint ($count, '11024', "An Ally in Lower City", %multiuserquests);
	BNet::Utils::preprint ($count, '11028', "Countdown to Doom", %multiuserquests);
	BNet::Utils::preprint ($count, '11056', "Hazzik's Bargain", %multiuserquests);
	BNet::Utils::preprint ($count, '11029', "A Shabby Disguise", %multiuserquests);
	BNet::Utils::preprint ($count, '11073', "Terokk's Downfall", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Rep");
	BNet::Utils::preprint ($count, '10551', "Allegiance to the Aldor", %multiuserquests);
	BNet::Utils::preprint ($count, '10554', "Ishanah", %multiuserquests);
	BNet::Utils::preprint ($count, '10021', "Restoring the Light", %multiuserquests);
	BNet::Utils::preprint ($count, '10017', "Strained Supplies", %multiuserquests);
	BNet::Utils::preprint ($count, '10325', "Marks of Kil'jaeden", %multiuserquests);
	BNet::Utils::preprint ($count, '10020', "A Cure for Zahlia", %multiuserquests);
	BNet::Utils::preprint ($count, '10552', "Allegiance to the Scryers", %multiuserquests);
	BNet::Utils::preprint ($count, '10412', "Firewing Signets", %multiuserquests);
	BNet::Utils::preprint ($count, '10553', "Voren'thal the Seer", %multiuserquests);

}

sub z_64_80_Nagrand ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("64: Nagrand: Breadcrumbs");
	BNet::Utils::preprint ($count, '39189', "Warchief's Command: Nagrand <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '39197', "Hero's Call: Nagrand <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::groupheader ("64: Nagrand: Garadar <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9888', "The Impotent Leader <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9889', "Don't Kill the Fat One <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9890', "Success! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9891', "Because Kilrath is a Coward <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9906', "Message in a Battle <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9907', "An Audacious Advance <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10107', "Diplomatic Measures <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9910', "Standards and Practices <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9916', "Bleeding Hollow Supply Crates <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9935', "Wanted: Giselda the Crone <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9939', "Wanted: Zorbo the Advisor <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9937', "Wanted: Durn the Hungerer <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9863', "Vile Idolatry <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9944', "Missing Mag\'hari Procession <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9945', "War on the Warmaul <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9946', "Cho\'war the Pillager <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9864', "The Missing War Party <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9865', "Once Were Warriors <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9866', "He Will Walk The Earth... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10479', "Proving Your Strength <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9867', "Murkblood Leaders... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9872', "Murkblood Invaders <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Garadar: Finale <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10044', "A Visit With the Greatmother <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10045', "Material Components <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10081', "To Meet Mother Kashur <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10082', "The Agitated Ancestors <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10085', "A Visit With The Ancestors <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10101', "When Spirits Speak <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10102', "A Secret Revealed <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10167', "Auchindoun... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10168', "What the Soul Sees <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10170', "Return to the Greatmother <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10171', "The Inconsolable Chieftain <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10172', "There Is No Hope <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10175', "Thrall, Son of Durotan (Obsolete)  <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10212', "Hero of the Mag\'har <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Throne of the Elements");
	BNet::Utils::preprint ($count, '9869', "The Throne of the Elements <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9870', "The Throne of the Elements <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9861', "The Howling Wind", %multiuserquests);
	BNet::Utils::preprint ($count, '9862', "Murkblood Corrupters", %multiuserquests);
	BNet::Utils::preprint ($count, '9800', "A Rare Bean", %multiuserquests);
	BNet::Utils::preprint ($count, '9804', "Agitated Spirits of Skysong", %multiuserquests);
	BNet::Utils::preprint ($count, '9805', "Blessing of Incineratus", %multiuserquests);
	BNet::Utils::preprint ($count, '9810', "The Spirit Polluted", %multiuserquests);
	BNet::Utils::preprint ($count, '9815', "Muck Diving", %multiuserquests);
	BNet::Utils::preprint ($count, '9818', "The Underneath", %multiuserquests);
	BNet::Utils::preprint ($count, '9819', "The Tortured Earth", %multiuserquests);
	BNet::Utils::preprint ($count, '9821', "Eating Damnation", %multiuserquests);
	BNet::Utils::preprint ($count, '9849', "Shattering the Veil", %multiuserquests);
	BNet::Utils::preprint ($count, '9853', "Gurok the Usurper", %multiuserquests);
	BNet::Utils::preprint ($count, '9852', "The Ultimate Bloodsport", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Mag'hari Procession");
	BNet::Utils::preprint ($count, '9948', "Finding the Survivors <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9879', "The Totem of Kar\'dash <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9868', "The Totem of Kar\'dash <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Nesingwary Safari");
	BNet::Utils::preprint ($count, '10113', "The Nesingwary Safari <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10114', "The Nesingwary Safari <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9897', "I\'m Saved!", %multiuserquests);
	BNet::Utils::preprint ($count, '9857', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9858', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9859', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9854', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9855', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9856', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9850', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9851', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9789', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9852', "The Ultimate Bloodsport", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Burning Blade Ruins");
	BNet::Utils::preprint ($count, '9928', "Armaments for Deception", %multiuserquests);
	BNet::Utils::preprint ($count, '9927', "Ruthless Cunning", %multiuserquests);
	BNet::Utils::preprint ($count, '9932', "Body of Evidence", %multiuserquests);
	BNet::Utils::preprint ($count, '9931', "Returning the Favor", %multiuserquests);
	BNet::Utils::preprint ($count, '9933', "Message to Telaar <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9934', "Message to Garadar <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);


	BNet::Utils::groupheader ("64: Nagrand: Telaar <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '9917', "Do My Eyes Deceive Me <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9918', "Not On My Watch! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9920', "Mo\'mor the Breaker <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9921', "The Ruins of Burning Blade <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9922', "The Twin Clefts of Nagrand <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10108', "Diplomatic Measures <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9936', "Wanted: Giselda the Crone <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9940', "Wanted: Zorbo the Advisor <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9938', "Wanted: Durn the Hungerer <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9871', "Murkblood Invaders <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10476', "Fierce Enemies <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9923', "HELP! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9924', "Corki\'s Gone Missing Again! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9954', "Corki\'s Ransom <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9955', "Cho\'war the Pillager <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9956', "The Ravaged Caravan <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9874', "Stopping the Spread <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9878', "Solving the Problem <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Ring of Blood");
	BNet::Utils::preprint ($count, '9962', "The Ring of Blood: Brokentoe", %multiuserquests);
	BNet::Utils::preprint ($count, '9967', "The Ring of Blood: The Blue Brothers", %multiuserquests);
	BNet::Utils::preprint ($count, '9970', "The Ring of Blood: Rokdar the Sundered Lord", %multiuserquests);
	BNet::Utils::preprint ($count, '9972', "The Ring of Blood: Skra\'gath", %multiuserquests);
	BNet::Utils::preprint ($count, '9973', "The Ring of Blood: The Warmaul Champion", %multiuserquests);
	BNet::Utils::preprint ($count, '9977', "The Ring of Blood: The Final Challenge", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Aeris Landing");
	BNet::Utils::preprint ($count, '9913', "The Consortium Needs You!", %multiuserquests);
	BNet::Utils::preprint ($count, '9914', "A Head Full of Ivory", %multiuserquests);
	BNet::Utils::preprint ($count, '9925', "Matters of Security", %multiuserquests);
	BNet::Utils::preprint ($count, '9900', "Gava\'xi", %multiuserquests);
	BNet::Utils::preprint ($count, '9882', "Stealing from Thieves", %multiuserquests);
	BNet::Utils::preprint ($count, '9893', "Obsidian Warbeads", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Miscellaneous");
	BNet::Utils::preprint ($count, '10111', "Bring Me The Egg!", %multiuserquests);
	BNet::Utils::preprint ($count, '10109', "I Must Have Them!", %multiuserquests);
	BNet::Utils::preprint ($count, '13799', "Where Are My Keys?", %multiuserquests);
	BNet::Utils::preprint ($count, '13800', "Get My Keys!", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Altruis the Sufferer");
	BNet::Utils::preprint ($count, '9983', "He Called Himself Altruis... <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9982', "He Called Himself Altruis... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9991', "Survey the Land", %multiuserquests);
	BNet::Utils::preprint ($count, '9999', "Buying Time", %multiuserquests);
	BNet::Utils::preprint ($count, '10001', "The Master Planner", %multiuserquests);
	BNet::Utils::preprint ($count, '10004', "Patience and Understanding", %multiuserquests);
	BNet::Utils::preprint ($count, '10009', "Crackin' Some Skulls", %multiuserquests);
	BNet::Utils::preprint ($count, '10010', "It's Just That Easy?", %multiuserquests);
	BNet::Utils::preprint ($count, '10011', "Forge Camp: Annihilated", %multiuserquests);

}

sub z_65_80_Blades_Edge_Mountains ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::preprint ($count, '10984', "Speak with the Ogre", %multiuserquests);
	BNet::Utils::preprint ($count, '10983', "Mog'dorg the Wizened", %multiuserquests);
	BNet::Utils::preprint ($count, '10989', "Mog'dorg the Wizened", %multiuserquests);
	BNet::Utils::preprint ($count, '10615', "Ruuan Weald", %multiuserquests);
	BNet::Utils::preprint ($count, '10618', "The Softest Wings", %multiuserquests);
	BNet::Utils::preprint ($count, '10565', "The Stones of Vekh'nir", %multiuserquests);
	BNet::Utils::preprint ($count, '10566', "Trial and Error", %multiuserquests);
	BNet::Utils::preprint ($count, '10567', "Creating the Pendant", %multiuserquests);
	BNet::Utils::preprint ($count, '10617', "Silkwing Cocoons", %multiuserquests);
	BNet::Utils::preprint ($count, '10584', "Picking Up Some Power Converters", %multiuserquests);
	BNet::Utils::preprint ($count, '10657', "Ride the Lightning", %multiuserquests);
	BNet::Utils::preprint ($count, '10674', "Trapping the Light Fantastic", %multiuserquests);
	BNet::Utils::preprint ($count, '10682', "A Time for Negotiation...", %multiuserquests);
	BNet::Utils::preprint ($count, '10713', "...and a Time for Action", %multiuserquests);
	BNet::Utils::preprint ($count, '10717', "Poaching from Poachers", %multiuserquests);
	BNet::Utils::preprint ($count, '10719', "Did You Get The Note?", %multiuserquests);
	BNet::Utils::preprint ($count, '10753', "Culling the Wild", %multiuserquests);
	BNet::Utils::preprint ($count, '10770', "Little Embers", %multiuserquests);
	BNet::Utils::preprint ($count, '10771', "From the Ashes", %multiuserquests);
	BNet::Utils::preprint ($count, '10846', "Understanding the Mok'Nathal", %multiuserquests);
	BNet::Utils::preprint ($count, '10851', "The Totems of My Enemy", %multiuserquests);
	BNet::Utils::preprint ($count, '10853', "Spirit Calling", %multiuserquests);
	BNet::Utils::preprint ($count, '10860', "Mok'Nathal Treats", %multiuserquests);
	BNet::Utils::preprint ($count, '11036', "Out of This World Produce!", %multiuserquests);
	BNet::Utils::preprint ($count, '11040', "Parts for the Rocket-Chief", %multiuserquests);
	BNet::Utils::preprint ($count, '11043', "Building a Better Gryphon", %multiuserquests);
	BNet::Utils::preprint ($count, '11047', "The Apprentice's Request", %multiuserquests);
	BNet::Utils::preprint ($count, '10675', "Show Them Gnome Mercy!", %multiuserquests);
	BNet::Utils::preprint ($count, '10810', "Damaged Mask", %multiuserquests);
	BNet::Utils::preprint ($count, '10812', "Mystery Mask", %multiuserquests);
	BNet::Utils::preprint ($count, '10819', "Felsworn Gas Mask", %multiuserquests);
	BNet::Utils::preprint ($count, '10820', "Deceive thy Enemy", %multiuserquests);
	BNet::Utils::preprint ($count, '10821', "You're Fired!", %multiuserquests);
	BNet::Utils::preprint ($count, '10843', "Since Time Forgotten...", %multiuserquests);
	BNet::Utils::preprint ($count, '10845', "Slay the Brood Mother", %multiuserquests);
	BNet::Utils::preprint ($count, '10974', "Stasis Chambers of Bash'ir", %multiuserquests);
	BNet::Utils::preprint ($count, '10976', "The Mark of the Nexus-King", %multiuserquests);
	BNet::Utils::preprint ($count, '10982', "The Eye of Haramad", %multiuserquests);
	BNet::Utils::preprint ($count, '10995', "Grulloc Has Two Skulls", %multiuserquests);
	BNet::Utils::preprint ($count, '10996', "Maggoc's Treasure Chest", %multiuserquests);
	BNet::Utils::preprint ($count, '10998', "Grim(oire) Business", %multiuserquests);
	BNet::Utils::preprint ($count, '11000', "Into the Soulgrinder", %multiuserquests);
	BNet::Utils::preprint ($count, '11009', "Ogre Heaven", %multiuserquests);
	BNet::Utils::preprint ($count, '11010', "Bombing Run", %multiuserquests);
	BNet::Utils::preprint ($count, '11025', "The Crystals", %multiuserquests);
	BNet::Utils::preprint ($count, '11026', "Banish the Demons", %multiuserquests);
	BNet::Utils::preprint ($count, '11030', "Our Boy Wants To Be A Skyguard Ranger", %multiuserquests);
	BNet::Utils::preprint ($count, '11057', "The Trouble Below", %multiuserquests);
	BNet::Utils::preprint ($count, '11058', "An Apexis Relic", %multiuserquests);
	BNet::Utils::preprint ($count, '11059', "Guardian of the Monument", %multiuserquests);
	BNet::Utils::preprint ($count, '11061', "A Father's Duty", %multiuserquests);
	BNet::Utils::preprint ($count, '11062', "The Skyguard Outpost", %multiuserquests);
	BNet::Utils::preprint ($count, '11065', "Wrangle Some Aether Rays!", %multiuserquests);
	BNet::Utils::preprint ($count, '11078', "To Rule The Skies", %multiuserquests);
	BNet::Utils::preprint ($count, '11079', "A Fel Whip For Gahk", %multiuserquests);
	BNet::Utils::preprint ($count, '11091', "A Special Thank You", %multiuserquests);
	BNet::Utils::preprint ($count, '11102', "Bombing Run", %multiuserquests);
	BNet::Utils::preprint ($count, '11119', "Assault on Bash'ir Landing!", %multiuserquests);

}

sub z_67_80_Netherstorm ($%) {
	my ($count, %multiuserquests) = @_;
	BNet::Utils::groupheader ("67: Netherstorm");
	BNet::Utils::preprint ($count, '11042', "A Mystifying Vision <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11037', "A Strange Vision <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11039', "Report to Spymaster Thalodien", %multiuserquests);
	BNet::Utils::preprint ($count, '11038', "Assist Exarch Orelis", %multiuserquests);

	BNet::Utils::preprint ($count, '39201', "Warchief's Command: Netherstorm", %multiuserquests);
	BNet::Utils::preprint ($count, '39202', "Hero's Call: Netherstorm", %multiuserquests);
	BNet::Utils::preprint ($count, '10173', "The Archmage's Staff", %multiuserquests);
	BNet::Utils::preprint ($count, '10174', "Curse of the Violet Tower", %multiuserquests);
	BNet::Utils::preprint ($count, '10176', "Ar'kelos the Guardian", %multiuserquests);
	BNet::Utils::preprint ($count, '10182', "Battle-Mage Dathric", %multiuserquests);
	BNet::Utils::preprint ($count, '10183', "Off To Area 52", %multiuserquests);
	BNet::Utils::preprint ($count, '10184', "Malevolent Remnants", %multiuserquests);
	BNet::Utils::preprint ($count, '10185', "A Fate Worse Than Death", %multiuserquests);
	BNet::Utils::preprint ($count, '10186', "You're Hired!", %multiuserquests);
	BNet::Utils::preprint ($count, '10189', "Manaforge B'naar", %multiuserquests);
	BNet::Utils::preprint ($count, '10190', "Recharging the Batteries", %multiuserquests);
	BNet::Utils::preprint ($count, '10191', "Mark V is Alive!", %multiuserquests);
	BNet::Utils::preprint ($count, '10193', "High Value Targets", %multiuserquests);
	BNet::Utils::preprint ($count, '10194', "Stealth Flight", %multiuserquests);
	BNet::Utils::preprint ($count, '10197', "A Convincing Disguise", %multiuserquests);
	BNet::Utils::preprint ($count, '10198', "Information Gathering", %multiuserquests);
	BNet::Utils::preprint ($count, '10199', "That Little Extra Kick", %multiuserquests);
	BNet::Utils::preprint ($count, '10200', "Return to Thalodien", %multiuserquests);
	BNet::Utils::preprint ($count, '10204', "Bloodgem Crystals", %multiuserquests);
	BNet::Utils::preprint ($count, '10206', "Pick Your Part", %multiuserquests);
	BNet::Utils::preprint ($count, '10221', "Dr. Boom!", %multiuserquests);
	BNet::Utils::preprint ($count, '10224', "Essence for the Engines", %multiuserquests);
	BNet::Utils::preprint ($count, '10225', "Report to Engineering", %multiuserquests);
	BNet::Utils::preprint ($count, '10226', "Elemental Power Extraction", %multiuserquests);
	BNet::Utils::preprint ($count, '10241', "Distraction at Manaforge B'naar", %multiuserquests);
	BNet::Utils::preprint ($count, '10243', "Naaru Technology", %multiuserquests);
	BNet::Utils::preprint ($count, '10245', "B'naar Console Transcription", %multiuserquests);
	BNet::Utils::preprint ($count, '10246', "Attack on Manaforge Coruu", %multiuserquests);
	BNet::Utils::preprint ($count, '10261', "Wanted: Annihilator Servo!", %multiuserquests);
	BNet::Utils::preprint ($count, '10262', "A Heap of Ethereals", %multiuserquests);
	BNet::Utils::preprint ($count, '10299', "Shutting Down Manaforge B'naar", %multiuserquests);
	BNet::Utils::preprint ($count, '10309', "It's a Fel Reaver, But with Heart", %multiuserquests);
	BNet::Utils::preprint ($count, '10313', "Measuring Warp Energies", %multiuserquests);
	BNet::Utils::preprint ($count, '10329', "Shutting Down Manaforge B'naar", %multiuserquests);
	BNet::Utils::preprint ($count, '10342', "Securing the Shaleskin Shale", %multiuserquests);
	BNet::Utils::preprint ($count, '10417', "Run a Diagnostic!", %multiuserquests);
	BNet::Utils::preprint ($count, '10418', "Deal With the Saboteurs", %multiuserquests);
	BNet::Utils::preprint ($count, '10701', "Breaking Down Netherock", %multiuserquests);
	BNet::Utils::preprint ($count, '10188', "The Sigil of Krasus", %multiuserquests);
	BNet::Utils::preprint ($count, '10192', "Krasus's Compendium", %multiuserquests);
	BNet::Utils::preprint ($count, '10203', "Invaluable Asset Zapping", %multiuserquests);
	BNet::Utils::preprint ($count, '10205', "Warp-Raider Nesaad", %multiuserquests);
	BNet::Utils::preprint ($count, '10209', "Summoner Kanthin's Prize", %multiuserquests);
	BNet::Utils::preprint ($count, '10222', "The Sunfury Garrison", %multiuserquests);
	BNet::Utils::preprint ($count, '10232', "In A Scrap With The Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '10234', "One Demon's Trash...", %multiuserquests);
	BNet::Utils::preprint ($count, '10235', "Declawing Doomclaw", %multiuserquests);
	BNet::Utils::preprint ($count, '10237', "Warn Area 52!", %multiuserquests);
	BNet::Utils::preprint ($count, '10239', "Potential Energy Source", %multiuserquests);
	BNet::Utils::preprint ($count, '10240', "Building a Perimeter", %multiuserquests);
	BNet::Utils::preprint ($count, '10247', "Doctor Vomisa, Ph.T.", %multiuserquests);
	BNet::Utils::preprint ($count, '10248', "You, Robot", %multiuserquests);
	BNet::Utils::preprint ($count, '10249', "Back to the Chief!", %multiuserquests);
	BNet::Utils::preprint ($count, '10256', "Finding the Keymaster", %multiuserquests);
	BNet::Utils::preprint ($count, '10265', "Consortium Crystal Collection", %multiuserquests);
	BNet::Utils::preprint ($count, '10266', "Request for Assistance", %multiuserquests);
	BNet::Utils::preprint ($count, '10267', "Rightful Repossession", %multiuserquests);
	BNet::Utils::preprint ($count, '10268', "An Audience with the Prince", %multiuserquests);
	BNet::Utils::preprint ($count, '10269', "Triangulation Point One", %multiuserquests);
	BNet::Utils::preprint ($count, '10293', "Hitting the Motherlode", %multiuserquests);
	BNet::Utils::preprint ($count, '10300', "Rebuilding the Staff", %multiuserquests);
	BNet::Utils::preprint ($count, '10301', "Unlocking the Compendium", %multiuserquests);
	BNet::Utils::preprint ($count, '10305', "Abjurist Belmara", %multiuserquests);
	BNet::Utils::preprint ($count, '10307', "Cohlien Frostweaver", %multiuserquests);
	BNet::Utils::preprint ($count, '10312', "The Annals of Kirin'Var", %multiuserquests);
	BNet::Utils::preprint ($count, '10314', "A Lingering Suspicion", %multiuserquests);
	BNet::Utils::preprint ($count, '10316', "Searching for Evidence", %multiuserquests);
	BNet::Utils::preprint ($count, '10319', "Capturing the Phylactery", %multiuserquests);
	BNet::Utils::preprint ($count, '10320', "Destroy Naberius!", %multiuserquests);
	BNet::Utils::preprint ($count, '10321', "Shutting Down Manaforge Coruu", %multiuserquests);
	BNet::Utils::preprint ($count, '10330', "Shutting Down Manaforge Coruu", %multiuserquests);
	BNet::Utils::preprint ($count, '10331', "Indispensable Tools", %multiuserquests);
	BNet::Utils::preprint ($count, '10332', "Master Smith Rhonsus", %multiuserquests);
	BNet::Utils::preprint ($count, '10333', "Help Mama Wheeler", %multiuserquests);
	BNet::Utils::preprint ($count, '10334', "Needs More Cowbell", %multiuserquests);
	BNet::Utils::preprint ($count, '10337', "When the Cows Come Home", %multiuserquests);
	BNet::Utils::preprint ($count, '10343', "The Unending Invasion", %multiuserquests);
	BNet::Utils::preprint ($count, '10348', "New Opportunities", %multiuserquests);
	BNet::Utils::preprint ($count, '10423', "To the Stormspire", %multiuserquests);
	BNet::Utils::preprint ($count, '10424', "Diagnosis: Critical", %multiuserquests);
	BNet::Utils::preprint ($count, '10426', "Flora of the Eco-Domes", %multiuserquests);
	BNet::Utils::preprint ($count, '10427', "Creatures of the Eco-Domes", %multiuserquests);
	BNet::Utils::preprint ($count, '10429', "When Nature Goes Too Far", %multiuserquests);
	BNet::Utils::preprint ($count, '10430', "Testing the Prototype", %multiuserquests);
	BNet::Utils::preprint ($count, '10433', "Keeping Up Appearances", %multiuserquests);
	BNet::Utils::preprint ($count, '10434', "The Dynamic Duo", %multiuserquests);
	BNet::Utils::preprint ($count, '10435', "Retrieving the Goods", %multiuserquests);
	BNet::Utils::preprint ($count, '10436', "All Clear!", %multiuserquests);
	BNet::Utils::preprint ($count, '10440', "Success!", %multiuserquests);
	BNet::Utils::preprint ($count, '10652', "Behind Enemy Lines", %multiuserquests);
	BNet::Utils::preprint ($count, '10855', "Fel Reavers, No Thanks!", %multiuserquests);
	BNet::Utils::preprint ($count, '10856', "The Best Defense", %multiuserquests);
	BNet::Utils::preprint ($count, '10857', "Teleport This!", %multiuserquests);
	BNet::Utils::preprint ($count, '10924', "Bloody Imp-ossible!", %multiuserquests);
	BNet::Utils::preprint ($count, '10257', "Capturing the Keystone", %multiuserquests);
	BNet::Utils::preprint ($count, '10270', "A Not-So-Modest Proposal", %multiuserquests);
	BNet::Utils::preprint ($count, '10271', "Getting Down to Business", %multiuserquests);
	BNet::Utils::preprint ($count, '10272', "A Promising Start", %multiuserquests);
	BNet::Utils::preprint ($count, '10273', "Troublesome Distractions", %multiuserquests);
	BNet::Utils::preprint ($count, '10274', "Securing the Celestial Ridge", %multiuserquests);
	BNet::Utils::preprint ($count, '10275', "Triangulation Point Two", %multiuserquests);
	BNet::Utils::preprint ($count, '10276', "Full Triangle", %multiuserquests);
	BNet::Utils::preprint ($count, '10281', "Formal Introductions", %multiuserquests);
	BNet::Utils::preprint ($count, '10290', "In Search of Farahlite", %multiuserquests);
	BNet::Utils::preprint ($count, '10335', "Surveying the Ruins", %multiuserquests);
	BNet::Utils::preprint ($count, '10336', "The Minions of Culuthas", %multiuserquests);
	BNet::Utils::preprint ($count, '10339', "The Ethereum", %multiuserquests);
	BNet::Utils::preprint ($count, '10345', "The Flesh Lies...", %multiuserquests);
	BNet::Utils::preprint ($count, '10353', "Arconus the Insatiable", %multiuserquests);
	BNet::Utils::preprint ($count, '10384', "Ethereum Data", %multiuserquests);
	BNet::Utils::preprint ($count, '10385', "Potential for Brain Damage = High", %multiuserquests);
	BNet::Utils::preprint ($count, '10405', "S-A-B-O-T-A-G-E", %multiuserquests);
	BNet::Utils::preprint ($count, '10406', "Delivering the Message", %multiuserquests);
	BNet::Utils::preprint ($count, '10408', "Nexus-King Salhadaar", %multiuserquests);
	BNet::Utils::preprint ($count, '10411', "Electro-Shock Goodness!", %multiuserquests);
	BNet::Utils::preprint ($count, '10422', "Captain Tyralius", %multiuserquests);
	BNet::Utils::preprint ($count, '10437', "Recipe for Destruction", %multiuserquests);
	BNet::Utils::preprint ($count, '10438', "On Nethery Wings", %multiuserquests);
	BNet::Utils::preprint ($count, '10439', "Dimensius the All-Devouring", %multiuserquests);
	BNet::Utils::preprint ($count, '10969', "Seek Out Ameer", %multiuserquests);
	BNet::Utils::preprint ($count, '10970', "A Mission of Mercy", %multiuserquests);
	BNet::Utils::preprint ($count, '10971', "Ethereum Secrets", %multiuserquests);
	BNet::Utils::preprint ($count, '10973', "A Thousand Worlds", %multiuserquests);

}

sub z_67_80_Shadowmoon_Valley ($%) {
	my ($count, %multiuserquests) = @_;
	BNet::Utils::groupheader ("67: Shadowmoon Valley");
	BNet::Utils::preprint ($count, '11044', "Visions of Destruction <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11048', "Kroghan\'s Report <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11045', "Zorus the Judicator <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11046', "Chief Apothecary Hildagard <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("70: Shadowmoon Valley/Nagrand: Altruis the Sufferer");
	BNet::Utils::preprint ($count, '10640', "Altruis (Aldor)", %multiuserquests);
	BNet::Utils::preprint ($count, '10689', "Altruis (Scryers)", %multiuserquests);
	BNet::Utils::preprint ($count, '10641', "Against the Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '10668', "Against the Illidari", %multiuserquests);
	BNet::Utils::preprint ($count, '10669', "Against All Odds", %multiuserquests);
	BNet::Utils::preprint ($count, '10646', "Illidan's Pupil", %multiuserquests);
	BNet::Utils::preprint ($count, '10649', "The Book of Fel Names", %multiuserquests);
	BNet::Utils::preprint ($count, '10650', "Return to the Aldor", %multiuserquests);
	BNet::Utils::preprint ($count, '10691', "Return to the Scryers", %multiuserquests);
	BNet::Utils::preprint ($count, '10651', "Varedis Must Be Stopped (Aldor)", %multiuserquests);
	BNet::Utils::preprint ($count, '10692', "Varedis Must Be Stopped (Scryers)", %multiuserquests);


	BNet::Utils::groupheader ("67-80: Shadowmoon Valley (Unsorted)");
	BNet::Utils::preprint ($count, '10562', "Besieged!", %multiuserquests);
	BNet::Utils::preprint ($count, '10563', "To Legion Hold", %multiuserquests);
	BNet::Utils::preprint ($count, '10564', "Blast the Infernals!", %multiuserquests);
	BNet::Utils::preprint ($count, '10572', "Setting Up the Bomb", %multiuserquests);
	BNet::Utils::preprint ($count, '10582', "Minions of the Shadow Council", %multiuserquests);
	BNet::Utils::preprint ($count, '10595', "Besieged!", %multiuserquests);
	BNet::Utils::preprint ($count, '10596', "To Legion Hold", %multiuserquests);
	BNet::Utils::preprint ($count, '10597', "Setting Up the Bomb", %multiuserquests);
	BNet::Utils::preprint ($count, '10598', "Blast the Infernals!", %multiuserquests);
	BNet::Utils::preprint ($count, '10599', "The Deathforge", %multiuserquests);
	BNet::Utils::preprint ($count, '10600', "Minions of the Shadow Council", %multiuserquests);
	BNet::Utils::preprint ($count, '10624', "A Haunted History", %multiuserquests);
	BNet::Utils::preprint ($count, '10625', "Spectrecles", %multiuserquests);
	BNet::Utils::preprint ($count, '10660', "What Strange Creatures...", %multiuserquests);
	BNet::Utils::preprint ($count, '10672', "Frankly, It Makes No Sense...", %multiuserquests);
	BNet::Utils::preprint ($count, '10702', "A Grunt's Work...", %multiuserquests);
	BNet::Utils::preprint ($count, '10759', "Find the Deserter", %multiuserquests);
	BNet::Utils::preprint ($count, '10760', "The Sketh'lon Wreckage", %multiuserquests);
	BNet::Utils::preprint ($count, '10761', "Find the Deserter", %multiuserquests);
	BNet::Utils::preprint ($count, '10777', "Asghar's Totem", %multiuserquests);
	BNet::Utils::preprint ($count, '10451', "Escape from Coilskar Cistern", %multiuserquests);
	BNet::Utils::preprint ($count, '10633', "Teron Gorefiend - Lore and Legend", %multiuserquests);
	BNet::Utils::preprint ($count, '10804', "Kindness", %multiuserquests);
	BNet::Utils::preprint ($count, '10811', "Seek Out Neltharaku", %multiuserquests);
	BNet::Utils::preprint ($count, '10814', "Neltharaku's Tale", %multiuserquests);
	BNet::Utils::preprint ($count, '10824', "Sunfury Signets", %multiuserquests);
	BNet::Utils::preprint ($count, '10836', "Infiltrating Dragonmaw Fortress", %multiuserquests);
	BNet::Utils::preprint ($count, '10837', "To Netherwing Ledge!", %multiuserquests);
	BNet::Utils::preprint ($count, '10854', "The Force of Neltharaku", %multiuserquests);
	BNet::Utils::preprint ($count, '10858', "Karynaku", %multiuserquests);
	BNet::Utils::preprint ($count, '10866', "Zuluhed the Whacked", %multiuserquests);
	BNet::Utils::preprint ($count, '10870', "Ally of the Netherwing", %multiuserquests);
	BNet::Utils::preprint ($count, '10871', "Ally of the Netherwing", %multiuserquests);
	BNet::Utils::preprint ($count, '10872', "Zuluhed the Whacked", %multiuserquests);
	BNet::Utils::preprint ($count, '11012', "Blood Oath of the Netherwing", %multiuserquests);
	BNet::Utils::preprint ($count, '11013', "In Service of the Illidari", %multiuserquests);
	BNet::Utils::preprint ($count, '11014', "Enter the Taskmaster", %multiuserquests);
	BNet::Utils::preprint ($count, '11019', "Your Friend On The Inside", %multiuserquests);
	BNet::Utils::preprint ($count, '11041', "A Job Unfinished...", %multiuserquests);
	BNet::Utils::preprint ($count, '11049', "The Great Netherwing Egg Hunt", %multiuserquests);
	BNet::Utils::preprint ($count, '11053', "Rise, Overseer!", %multiuserquests);
	BNet::Utils::preprint ($count, '11054', "Overseeing and You: Making the Right Choices", %multiuserquests);
	BNet::Utils::preprint ($count, '11063', "Earning Your Wings...", %multiuserquests);
	BNet::Utils::preprint ($count, '11064', "Dragonmaw Race: The Ballad of Oldie McOld", %multiuserquests);
	BNet::Utils::preprint ($count, '11067', "Dragonmaw Race: Trope the Filth-Belcher", %multiuserquests);
	BNet::Utils::preprint ($count, '11068', "Dragonmaw Race: Corlok the Vet", %multiuserquests);
	BNet::Utils::preprint ($count, '11069', "Dragonmaw Race: Wing Commander Ichman", %multiuserquests);
	BNet::Utils::preprint ($count, '11070', "Dragonmaw Race: Wing Commander Mulverick", %multiuserquests);
	BNet::Utils::preprint ($count, '11071', "Dragonmaw Race: Captain Skyshatter", %multiuserquests);
	BNet::Utils::preprint ($count, '11075', "The Netherwing Mines", %multiuserquests);
	BNet::Utils::preprint ($count, '11081', "The Great Murkblood Revolt", %multiuserquests);
	BNet::Utils::preprint ($count, '11082', "Seeker of Truth", %multiuserquests);
	BNet::Utils::preprint ($count, '11083', "Crazed and Confused", %multiuserquests);
	BNet::Utils::preprint ($count, '11084', "Stand Tall, Captain!", %multiuserquests);
	BNet::Utils::preprint ($count, '11089', "The Soul Cannon of Reth'hedron", %multiuserquests);
	BNet::Utils::preprint ($count, '11090', "Subdue the Subduer", %multiuserquests);
	BNet::Utils::preprint ($count, '11092', "Hail, Commander!", %multiuserquests);
	BNet::Utils::preprint ($count, '11094', "Kill Them All!", %multiuserquests);
	BNet::Utils::preprint ($count, '11095', "Commander Hobb", %multiuserquests);
	BNet::Utils::preprint ($count, '11099', "Kill Them All!", %multiuserquests);
	BNet::Utils::preprint ($count, '11100', "Commander Arcus", %multiuserquests);
	BNet::Utils::preprint ($count, '11107', "Bow to the Highlord", %multiuserquests);
	BNet::Utils::preprint ($count, '11108', "Lord Illidan Stormrage", %multiuserquests);

}

sub z_70_Isle_Of_Queldanas ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("70: Isle of Quel'Danas");
	BNet::Utils::preprint ($count, '11554', "A Friend in the Frontlines", %multiuserquests);
	BNet::Utils::preprint ($count, '11555', "Honored by Your Allies", %multiuserquests);
	BNet::Utils::preprint ($count, '11556', "Revered in the Field of Battle", %multiuserquests);
	BNet::Utils::preprint ($count, '11557', "Exalted Among All Combatants", %multiuserquests);
	BNet::Utils::preprint ($count, '11549', "A Magnanimous Benefactor", %multiuserquests);

}

1;
