package BNet::Quests_Wrath;

use strict;
use warnings;


sub z_68_72_borean_tundra ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("68: Borean Tundra: Intro");
	BNet::Utils::preprint ($count, '28709', "Hero's Call: Northrend! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28711', "Warchief's Command: Northrend! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Valiance Keep <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '11672', "Enlistment Day <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11727', "A Time for Heroes <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11797', "The Siege <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11889', "Death From Above <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11897', "Plug the Sinkholes <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11789', "A Soldier in Need <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11790', "Cultists Among Us <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11920', "Cultists Among Us <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11791', "Notify Arlos <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11792', "Enemies of the Light <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11793', "Further Investigation <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11794', "The Hunt is On <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11928', "Farshire <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11901', "Military? What Military? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11902', "Pernicious Evidence <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11903', "It's Time for Action <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11913', "Take No Chances <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11908', "Reference Material <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '12035', "Repurposed Technology <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11904', "Fruits of Our Labor <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11962', "One Last Delivery <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11963', "Weapons for Farshire <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11965', "Call to Arms! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11927', "Word on the Street <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11599', "Thassarian, My Brother <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11600', "The Late William Allerton <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11601', "Lost and Found <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11603', "In Wine, Truth <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11604', "A Deserter <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11932', "Cowards and Fools <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '12086', "The Son of Karkut <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11944', "Surrounded! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '12088', "Thassarian, the Death Knight <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11956', "Finding the Phylactery <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11938', "Buying Some Time <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11942', "Words of Power <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '12019', "Last Rites <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Fizzcrank Airstrip <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '11707', "Distress Call <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11708', "The Mechagnomes <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11712', "Re-Cursive <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11788', "Lefty Loosey, Righty Tighty <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11798', "The Gearmaster <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11710', "What's the Matter with the Transmatter? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11692', "Check in With Bixie <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11693', "Oh Great... Plagued Magnataur! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11694', "There's Something Going On In Those Caves <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11697', "Rats, Tinky Went into the Necropolis! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11698', "Might As Well Wipe Out the Scourge <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11699', "I'm Stuck in this Damned Cage... But Not For Long! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11700', "Let Bixie Know <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11701', "Back to the Airstrip <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11645', "Dirty, Stinkin' Snobolds! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11650', "Just a Few More Things... <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11653', "Hah... You're Not So Big Now! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11658', "Plan B <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11670', "It Was The Orcs, Honest! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11729', "The Ultrasonic Screwdriver <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11730', "Master and Servant <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11725', "Finding Pilot Tailspin <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11726', "A Little Bit of Spice <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11728', "Lupus Pupus <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11795', "Emergency Protocol: Section 8.2, Paragraph C <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11796', "Emergency Protocol: Section 8.2, Paragraph D <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11873', "Give Fizzcrank the News <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11713', "Scouting the Sinkholes <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11715', "Fueling the Project <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11718', "A Bot in Mammoth's Clothing <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11723', "Deploy the Shake-n-Quake! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11673', "Get Me Outa Here! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Warsong Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '11585', "Hellscream's Vigil <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11586', "Hellscream's Vigil <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11595', "The Defense of Warsong Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11596', "The Defense of Warsong Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11597', "The Defense of Warsong Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11632', "What the Cold Wind Brings... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11598', "Taking Back Mightstone Quarry <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11602', "Cutting Off the Source <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11634', "Wind Master To'bor <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11636', "Magic Carpet Ride <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11642', "Tank Ain't Gonna Fix Itself <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11643', "Mobu's Pneumatic Tank Transjigamarig <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11644', "Super Strong Metal Plates! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11651', "Tanks a lot... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11652', "The Plains of Nasam <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11916', "Hellscream's Champion <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11606', "Patience is a Virtue that We Don't Need <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11608', "Bury Those Cockroaches! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11614', "Untold Truths <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11615', "Nerub'ar Secrets <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11616', "Message to Hellscream <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11618', "Reinforcements Incoming... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11686', "The Warsong Farms <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11676', "Merciful Freedom <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11688', "Damned Filthy Swine <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11690', "Bring 'Em Back Alive <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11703', "Get to Getry <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11705', "Foolish Endeavors <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11709', "Nork Bloodfrenzy's Charge <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11711', "Coward Delivery... Under 30 Minutes or it's Free <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11714', "Vermin Extermination <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11611', "Taken by the Scourge <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Steeljaw's Caravan <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '11591', "Report to Steeljaw's Caravan <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11594', "Put Them to Rest <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11593', "The Honored Dead <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11592', "We Strike! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Bor'gorok Outpost <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '12486', "To Bor'gorok Outpost, Quickly! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11624', "The Sky Will Know <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11631', "Vision of Air <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11635', "Farseer Grimwalker's Spirit <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11639', "Revenge Upon Magmoth <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11637', "Kaganishu <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11638', "Return My Remains <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11627', "Boiling Point <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11649', "Motes of the Enraged <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11629', "Return to the Spirit Talker <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Taunka'le Village <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '11888', "Ride to Taunka'le Village <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11628', "Shrouds of the Scourge <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11630', "The Bad Earth <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11633', "Blending In <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11640', "Words of Power <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11898', "Breaking Through <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11641', "A Courageous Strike <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11647', "Neutralizing the Cauldrons <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11654', "The Spire of Blood <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11659', "Shatter the Orbs! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11674', "Sage Highmesa is Missing <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11675', "A Proper Death <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11683', "Fallen Necropolis <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11677', "Stop the Plague <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11678', "Find Bristlehorn <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11687', "The Doctor and the Lich-Lord <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11689', "Return with the Bad News <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11899', "Souls of the Decursed <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11906', "Cleaning Up the Pools <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11909', "Defeat the Gearmaster <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11881', "Load'er Up! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11887', "Emergency Supplies <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11893', "The Power of the Elements <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11894', "Patching Up <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11890', "What Are They Up To? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11895', "Master the Storm <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11896', "Weakness to Lightning <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11907', "The Sub-Chieftains <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11684', "Scouting the Sinkholes <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11685', "The Heart of the Elements <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11695', "The Horn of Elemental Fury <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11706', "The Collapse <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11929', "The Fall of Taunka'le Village <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11930', "Across Transborea <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Bloodspore Plains <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '11724', "Massive Moth Omelet? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11716', "The Wondrous Bloodspore <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11717', "Pollen from the Source <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11719', "A Suitable Test Subject <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11720', "The Invasion of Gammoth <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11721', "Gammothra the Tormentor <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11722', "Trophies of Gammoth <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Coast of Echoes <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '11655', "Into the Mist <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11664', "Escaping the Mist <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11656', "Burn in Effigy <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11660', "Horn of the Ancient Mariner <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11661', "Orabus the Helmsman <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Riplash Strand");
	BNet::Utils::preprint ($count, '12141', "A Diplomatic Mission <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11662', "Seek Out Karuk! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11613', "Karuk's Oath", %multiuserquests);
	BNet::Utils::preprint ($count, '11619', "Gamel the Cruel", %multiuserquests);
	BNet::Utils::preprint ($count, '11620', "A Father's Words", %multiuserquests);
	BNet::Utils::preprint ($count, '11625', "The Trident of Naz'jan", %multiuserquests);
	BNet::Utils::preprint ($count, '11626', "The Emissary", %multiuserquests);
	BNet::Utils::preprint ($count, '12471', "Cruelty of the Kvaldir", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Amber Ledge");
	BNet::Utils::preprint ($count, '11575', "Nick of Time <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11574', "Too Close For Comfort <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11576', "Monitoring the Rift: Cleftcliff Anomaly", %multiuserquests);
	BNet::Utils::preprint ($count, '11582', "Monitoring the Rift: Sundered Chasm", %multiuserquests);
	BNet::Utils::preprint ($count, '12728', "Monitoring the Rift: Winterfin Cavern", %multiuserquests);
	BNet::Utils::preprint ($count, '11587', "Prison Break", %multiuserquests);
	BNet::Utils::preprint ($count, '11590', "Abduction", %multiuserquests);
	BNet::Utils::preprint ($count, '11646', "The Borean Inquisition", %multiuserquests);
	BNet::Utils::preprint ($count, '11648', "The Art of Persuasion", %multiuserquests);
	BNet::Utils::preprint ($count, '11663', "Sharing Intelligence", %multiuserquests);
	BNet::Utils::preprint ($count, '11671', "A Race Against Time", %multiuserquests);
	BNet::Utils::preprint ($count, '11679', "Reforging the Key", %multiuserquests);
	BNet::Utils::preprint ($count, '11680', "Taking Wing", %multiuserquests);
	BNet::Utils::preprint ($count, '11681', "Rescuing Evanor", %multiuserquests);
	BNet::Utils::preprint ($count, '11682', "Dragonspeak", %multiuserquests);
	BNet::Utils::preprint ($count, '11733', "Traversing the Rift", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Coldara");
	BNet::Utils::preprint ($count, '11918', "Basic Training", %multiuserquests);
	BNet::Utils::preprint ($count, '11936', "Hatching a Plan", %multiuserquests);
	BNet::Utils::preprint ($count, '11919', "Drake Hunt", %multiuserquests);
	BNet::Utils::preprint ($count, '11931', "Cracking the Code", %multiuserquests);
	BNet::Utils::preprint ($count, '11912', "Nuts for Berries", %multiuserquests);
	BNet::Utils::preprint ($count, '11914', "Keep the Secret Safe", %multiuserquests);
	BNet::Utils::preprint ($count, '11900', "Reading the Meters", %multiuserquests);
	BNet::Utils::preprint ($count, '11910', "Secrets of the Ancients", %multiuserquests);
	BNet::Utils::preprint ($count, '11941', "Puzzling...", %multiuserquests);
	BNet::Utils::preprint ($count, '11943', "The Cell", %multiuserquests);
	BNet::Utils::preprint ($count, '11946', "Keristrasza", %multiuserquests);
	BNet::Utils::preprint ($count, '11951', "Bait and Switch", %multiuserquests);
	BNet::Utils::preprint ($count, '11957', "Saragosa's End", %multiuserquests);
	BNet::Utils::preprint ($count, '11967', "Mustering the Reds", %multiuserquests);
	BNet::Utils::preprint ($count, '11969', "Springing the Trap", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: D.E.H.T.A. Encampment");
	BNet::Utils::preprint ($count, '11864', "A Mission Statement", %multiuserquests);
	BNet::Utils::preprint ($count, '11866', "Ears of Our Enemies", %multiuserquests);
	BNet::Utils::preprint ($count, '11876', "Help Those That Cannot Help Themselves", %multiuserquests);
	BNet::Utils::preprint ($count, '11878', "Khu'nok Will Know", %multiuserquests);
	BNet::Utils::preprint ($count, '11879', "Kaw the Mammoth Destroyer", %multiuserquests);
	BNet::Utils::preprint ($count, '11869', "Happy as a Clam", %multiuserquests);
	BNet::Utils::preprint ($count, '11870', "The Abandoned Reach", %multiuserquests);
	BNet::Utils::preprint ($count, '11871', "Not On Our Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '11872', "The Nefarious Clam Master...", %multiuserquests);
	BNet::Utils::preprint ($count, '11865', "Unfit for Death", %multiuserquests);
	BNet::Utils::preprint ($count, '11868', "The Culler Cometh", %multiuserquests);
	BNet::Utils::preprint ($count, '11884', "Nedar, Lord of Rhinos...", %multiuserquests);
	BNet::Utils::preprint ($count, '11892', "The Assassination of Harold Lane", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Kaskala");
	BNet::Utils::preprint ($count, '11949', "Not Without a Fight!", %multiuserquests);
	BNet::Utils::preprint ($count, '11950', "Muahit's Wisdom", %multiuserquests);
	BNet::Utils::preprint ($count, '11961', "Spirits Watch Over Us", %multiuserquests);
	BNet::Utils::preprint ($count, '11968', "The Tides Turn", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Coldrock Quarry");
	BNet::Utils::preprint ($count, '11612', "Reclaiming the Quarry", %multiuserquests);
	BNet::Utils::preprint ($count, '11617', "Hampering Their Escape", %multiuserquests);
	BNet::Utils::preprint ($count, '11623', "A Visit to the Curator", %multiuserquests);
	BNet::Utils::preprint ($count, '11605', "The Honored Ancestors", %multiuserquests);
	BNet::Utils::preprint ($count, '11607', "The Lost Spirits", %multiuserquests);
	BNet::Utils::preprint ($count, '11609', "Picking Up the Pieces", %multiuserquests);
	BNet::Utils::preprint ($count, '11610', "Leading the Ancestors Home", %multiuserquests);
	BNet::Utils::groupheader ("68: Borean Tundra: Winterfin Retreat");
	BNet::Utils::preprint ($count, '11704', "King Mrgl-Mrgl <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11702', "King Mrgl-Mrgl <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11571', "Learning to Communicate", %multiuserquests);
	BNet::Utils::preprint ($count, '11559', "Winterfin Commerce", %multiuserquests);
	BNet::Utils::preprint ($count, '11560', "Oh Noes, the Tadpoles!", %multiuserquests);
	BNet::Utils::preprint ($count, '11561', "Them!", %multiuserquests);
	BNet::Utils::preprint ($count, '11562', "I'm Being Blackmailed By My Cleaner", %multiuserquests);
	BNet::Utils::preprint ($count, '11563', "Grmmurggll Mrllggrl Glrggl!!!", %multiuserquests);
	BNet::Utils::preprint ($count, '11564', "Succulent Orca Stew", %multiuserquests);
	BNet::Utils::preprint ($count, '11565', "The Spare Suit", %multiuserquests);
	BNet::Utils::preprint ($count, '11566', "Surrender... Not!", %multiuserquests);
	BNet::Utils::preprint ($count, '11569', "Keymaster Urmgrgl", %multiuserquests);
	BNet::Utils::preprint ($count, '11570', "Escape from the Winterfin Caverns", %multiuserquests);
	BNet::Utils::groupheader ("80: Borean Tundra: Wyrmrest Accord Daily");
	BNet::Utils::preprint ($count, '13412', "Corastrasza", %multiuserquests);
	BNet::Utils::preprint ($count, '13413', "Aces High!", %multiuserquests);

}

1;
