package BNet::Quests_Legion;

use strict;
use warnings;




sub z_98_legion_intro ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Legion Invasion: Alliance");
	BNet::Utils::preprint ($count, '40519', "The Legion Returns", %multiuserquests);
	BNet::Utils::preprint ($count, '42782', "To Be Prepared", %multiuserquests);
	BNet::Utils::preprint ($count, '42740', "The Battle for Broken Shore", %multiuserquests);
	BNet::Utils::preprint ($count, '40517', "The Fallen Lion", %multiuserquests);
	BNet::Utils::preprint ($count, '40593', "Demons Among Us", %multiuserquests);
	BNet::Utils::preprint ($count, '44120', "Illidari Allies", %multiuserquests);
	BNet::Utils::preprint ($count, '40717', "Calling of the Council", %multiuserquests);

	BNet::Utils::groupheader ("Legion Invasion: Horde");
	BNet::Utils::preprint ($count, '43926', "The Legion Returns", %multiuserquests);
	BNet::Utils::preprint ($count, '44281', "To Be Prepared", %multiuserquests);
	BNet::Utils::preprint ($count, '40518', "The Battle for Broken Shore", %multiuserquests);
	BNet::Utils::preprint ($count, '40522', "Fate of the Horde", %multiuserquests);
	BNet::Utils::preprint ($count, '40976', "Audience with the Warchief", %multiuserquests);
	BNet::Utils::preprint ($count, '40760', "Emissary", %multiuserquests);
	BNet::Utils::preprint ($count, '40607', "Demons Among Us", %multiuserquests);
	BNet::Utils::preprint ($count, '40605', "Keep Your Friends Close", %multiuserquests);
	BNet::Utils::preprint ($count, '40718', "Calling of the Council", %multiuserquests);

	BNet::Utils::groupheader ("Legion Invasion: Teleportation");
	BNet::Utils::preprint ($count, '42970', "The Diamond King", %multiuserquests);
	BNet::Utils::preprint ($count, '40755', "Hiding in the Stacks", %multiuserquests);
	BNet::Utils::preprint ($count, '44182', "City Under Siege", %multiuserquests);
	BNet::Utils::preprint ($count, '44421', "Anomalous Anomalies", %multiuserquests);
	BNet::Utils::preprint ($count, '44500', "Author! Author!", %multiuserquests);
	BNet::Utils::preprint ($count, '44184', "In the Blink of an Eye", %multiuserquests);
}


sub z_100_azsuna ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Azsuna: Behind Legion Lines");
	BNet::Utils::preprint ($count, '39718', "Paradise Lost", %multiuserquests);
	BNet::Utils::preprint ($count, '41220', "Down to Azsuna", %multiuserquests);
	BNet::Utils::preprint ($count, '38834', "Into the Fray", %multiuserquests);
	BNet::Utils::preprint ($count, '37658', "Reignite the Wards", %multiuserquests);
	BNet::Utils::preprint ($count, '37653', "Demon Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '37660', "The Scythe of Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '44140', "From Within", %multiuserquests);
	BNet::Utils::preprint ($count, '37656', "Fel Machinations", %multiuserquests);
	BNet::Utils::preprint ($count, '37450', "Saving Stellagosa", %multiuserquests);
	BNet::Utils::preprint ($count, '37449', "Dark Revelations", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Defending Azurewing Repose");
	BNet::Utils::preprint ($count, '38443', "Journey to the Repose", %multiuserquests);
	BNet::Utils::preprint ($count, '37853', "The Death of the Eldest", %multiuserquests);
	BNet::Utils::preprint ($count, '37991', "Agapanthus", %multiuserquests);
	BNet::Utils::preprint ($count, '42271', "Their Dying Breaths", %multiuserquests);
	BNet::Utils::preprint ($count, '37855', "The Last of the Last", %multiuserquests);
	BNet::Utils::preprint ($count, '37859', "The Consumed", %multiuserquests);
	BNet::Utils::preprint ($count, '37856', "The Withered", %multiuserquests);
	BNet::Utils::preprint ($count, '37858', "Stellagosa", %multiuserquests);
	BNet::Utils::preprint ($count, '37957', "Runas the Shamed", %multiuserquests);
	BNet::Utils::preprint ($count, '37857', "Runas Knows the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '37960', "Leyline Abuse", %multiuserquests);
	BNet::Utils::preprint ($count, '37959', "The Hunger Returns", %multiuserquests);
	BNet::Utils::preprint ($count, '37861', "The Nightborne Prince", %multiuserquests);
	BNet::Utils::preprint ($count, '37860', "You Scratch My Back...", %multiuserquests);
	BNet::Utils::preprint ($count, '37862', "Still Alive", %multiuserquests);
	BNet::Utils::preprint ($count, '38015', "On the Brink", %multiuserquests);
	BNet::Utils::preprint ($count, '38014', "Feasting on the Dragon", %multiuserquests);
	BNet::Utils::preprint ($count, '42567', "Cursed to Wither", %multiuserquests);
	BNet::Utils::preprint ($count, '42756', "Hunger's End", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Azsuna versus Azshara");
	BNet::Utils::preprint ($count, '37690', "Those Who Remember", %multiuserquests);
	BNet::Utils::preprint ($count, '37256', "They Came From the Sea", %multiuserquests);
	BNet::Utils::preprint ($count, '37733', "Prince Farondis", %multiuserquests);
	BNet::Utils::preprint ($count, '37257', "Our Very Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '37492', "A Rather Long Walk", %multiuserquests);
	BNet::Utils::preprint ($count, '37728', "Presentation is Everything", %multiuserquests);
	BNet::Utils::preprint ($count, '37727', "The Magister of Mixology", %multiuserquests);
	BNet::Utils::preprint ($count, '37497', "Trailing the Tidestone", %multiuserquests);
	BNet::Utils::preprint ($count, '37486', "Nar'thalas Still Suffers", %multiuserquests);
	BNet::Utils::preprint ($count, '42692', "Children of Nar'thalas", %multiuserquests);
	BNet::Utils::preprint ($count, '42693', "You Never Know Until You Scry", %multiuserquests);
	BNet::Utils::preprint ($count, '42694', "Back from the Dead", %multiuserquests);
	BNet::Utils::preprint ($count, '37467', "The Walk of Shame", %multiuserquests);
	BNet::Utils::preprint ($count, '37468', "Into the Academy", %multiuserquests);
	BNet::Utils::preprint ($count, '37736', "Dressing With Class", %multiuserquests);
	BNet::Utils::preprint ($count, '37678', "Hit the Books", %multiuserquests);
	BNet::Utils::preprint ($count, '37518', "The Haunted Halls", %multiuserquests);
	BNet::Utils::preprint ($count, '42370', "Wanding 101", %multiuserquests);
	BNet::Utils::preprint ($count, '42371', "Study Hall: Combat Research", %multiuserquests);
	BNet::Utils::preprint ($count, '37729', "Pop Quiz: Advanced Rune Drawing", %multiuserquests);
	BNet::Utils::preprint ($count, '37730', "The Headmistress' Keys", %multiuserquests);
	BNet::Utils::preprint ($count, '37469', "The Tidestone: Shattered", %multiuserquests);
	BNet::Utils::preprint ($count, '37530', "Save Yourself", %multiuserquests);
	BNet::Utils::preprint ($count, '37470', "The Head of the Snake", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Eye of Azshara");
	BNet::Utils::preprint ($count, '38286', "Eye of Azshara: Wrath of Azshara", %multiuserquests);
	BNet::Utils::preprint ($count, '42213', "Eye of Azshara: The Tidestone of Golganneth", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Against the Giants");
	BNet::Utils::preprint ($count, '38407', "Bottled Up", %multiuserquests);
	BNet::Utils::preprint ($count, '37496', "Infiltrating Shipwreck Arena", %multiuserquests);
	BNet::Utils::preprint ($count, '37507', "Boss Whalebelly's in Charge", %multiuserquests);
	BNet::Utils::preprint ($count, '37542', "No Time for Tryouts", %multiuserquests);
	BNet::Utils::preprint ($count, '37528', "Let Sleeping Giants Lie", %multiuserquests);
	BNet::Utils::preprint ($count, '37510', "Sternfathom's Champion", %multiuserquests);
	BNet::Utils::preprint ($count, '37536', "Morale Booster", %multiuserquests);
	BNet::Utils::preprint ($count, '37538', "Round 1, Fight!", %multiuserquests);
	BNet::Utils::preprint ($count, '37565', "The Right Weapon for the Job", %multiuserquests);
	BNet::Utils::preprint ($count, '37566', "The Prince is Going Down", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Mak'rana and the Fate of the Queen's Reprisal");
	BNet::Utils::preprint ($count, '38857', "A Favor for Mr. Shackle", %multiuserquests);
	BNet::Utils::preprint ($count, '37654', "Maritime Law", %multiuserquests);
	BNet::Utils::preprint ($count, '37659', "The Captain's Foot Locker", %multiuserquests);
	BNet::Utils::preprint ($count, '42268', "Shipwrecked Sailors", %multiuserquests);
	BNet::Utils::preprint ($count, '42244', "Fate of the Queen's Reprisal", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Daglop");
	BNet::Utils::preprint ($count, '42238', "Missing Demon", %multiuserquests);
	BNet::Utils::preprint ($count, '38460', "Let's Make A Deal", %multiuserquests);
	BNet::Utils::preprint ($count, '38232', "Minion! Kill Them!", %multiuserquests);
	BNet::Utils::preprint ($count, '38237', "This IS In My Contract.", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: PVP");
	BNet::Utils::preprint ($count, '43942', "Timeworn Artifact", %multiuserquests);
	BNet::Utils::groupheader ("Azsuna: Bonus Objectives");
	BNet::Utils::preprint ($count, '36811', "Retake Faronaar", %multiuserquests);
	BNet::Utils::preprint ($count, '37466', "The Broken Academy", %multiuserquests);
	BNet::Utils::preprint ($count, '37963', "Those Beyond Redemption", %multiuserquests);
	BNet::Utils::preprint ($count, '37779', "Tip the Scales", %multiuserquests);
	BNet::Utils::preprint ($count, '37965', "A Tainted Vintage", %multiuserquests);
	BNet::Utils::preprint ($count, '37495', "Plunder the Cove", %multiuserquests);
	
}
sub z_100_valsharah ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Val'sharah: Intro");
	BNet::Utils::preprint ($count, '39731', "The Tranquil Forest", %multiuserquests);
	BNet::Utils::preprint ($count, '39861', "Tying Up Loose Ends", %multiuserquests);
	BNet::Utils::preprint ($count, '38305', "Cenarius, Keeper of the Grove", %multiuserquests);
	BNet::Utils::preprint ($count, '38384', "Nature's Call", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Archdruid of Lore");
	BNet::Utils::preprint ($count, '38381', "Archdruid of Lore", %multiuserquests);
	BNet::Utils::preprint ($count, '38235', "Solid as a Rock", %multiuserquests);
	BNet::Utils::preprint ($count, '38225', "Death to the Witchmother", %multiuserquests);
	BNet::Utils::preprint ($count, '38322', "Return to the Grove", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Archdruid of the Claw");
	BNet::Utils::preprint ($count, '38142', "Archdruid of the Claw", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Archdruid of the Claw: Furlbolgs");
	BNet::Utils::preprint ($count, '38455', "Frenzied Furbolgs", %multiuserquests);
	BNet::Utils::preprint ($count, '38922', "Littlefur", %multiuserquests);
	BNet::Utils::preprint ($count, '38246', "Totemic Call", %multiuserquests);
	BNet::Utils::preprint ($count, '38146', "The Chieftain's Beads", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Archdruid of the Claw: Awakening the Archdruid");
	BNet::Utils::preprint ($count, '38143', "Awakening the Archdruid", %multiuserquests);
	BNet::Utils::preprint ($count, '38145', "Out of the Dream", %multiuserquests);
	BNet::Utils::preprint ($count, '38144', "The Demons Below", %multiuserquests);
	BNet::Utils::preprint ($count, '38147', "Entangled Dreams", %multiuserquests);
	BNet::Utils::preprint ($count, '38148', "Return to the Grove", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Archdruid of the Vale");
	BNet::Utils::preprint ($count, '38382', "Archdruid of the Vale", %multiuserquests);
	BNet::Utils::preprint ($count, '39383', "Dishonored", %multiuserquests);
	BNet::Utils::preprint ($count, '39384', "The Corruptor", %multiuserquests);
	BNet::Utils::preprint ($count, '40573', "The Nightmare Lord", %multiuserquests);
	BNet::Utils::preprint ($count, '38323', "Return to the Grove", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Into the Nightmare");
	BNet::Utils::preprint ($count, '38377', "The Emerald Queen", %multiuserquests);
	BNet::Utils::preprint ($count, '38641', "The Temple of Elune", %multiuserquests);
	BNet::Utils::preprint ($count, '38662', "Tears for Fears", %multiuserquests);
	BNet::Utils::preprint ($count, '38655', "Root Cause", %multiuserquests);
	BNet::Utils::preprint ($count, '38656', "Mark of the Demon", %multiuserquests);
	BNet::Utils::preprint ($count, '38663', "The Die is Cast", %multiuserquests);
	BNet::Utils::preprint ($count, '38595', "Malfurion's Fury", %multiuserquests);
	BNet::Utils::preprint ($count, '38582', "To Old Friends", %multiuserquests);
	BNet::Utils::preprint ($count, '38753', "The Demon's Trail", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: All Nightmare Long");
	BNet::Utils::preprint ($count, '41054', "Love Lost", %multiuserquests);
	BNet::Utils::preprint ($count, '41890', "Dark Side of the Moon", %multiuserquests);
	BNet::Utils::preprint ($count, '38671', "Lost in Retreat", %multiuserquests);
	BNet::Utils::preprint ($count, '41707', "Wormtalon Wreckage", %multiuserquests);
	BNet::Utils::preprint ($count, '43576', "Regroup at the Refuge", %multiuserquests);
	BNet::Utils::preprint ($count, '38675', "Heart of the Nightmare", %multiuserquests);
	BNet::Utils::preprint ($count, '38684', "Reading the Leaves", %multiuserquests);
	BNet::Utils::preprint ($count, '41749', "Given to Corruption", %multiuserquests);
	BNet::Utils::preprint ($count, '43702', "Softening the Target", %multiuserquests);
	BNet::Utils::preprint ($count, '41763', "Close Enough to Touch", %multiuserquests);
	BNet::Utils::preprint ($count, '38743', "The Fate of Val'sharah", %multiuserquests);
	BNet::Utils::preprint ($count, '40890', "The Tears of Elune", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Darkheart Thicket");
	BNet::Utils::preprint ($count, '40567', "Darkheart Thicket: Enter the Nightmare", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Bradensbrook");
	BNet::Utils::preprint ($count, '38643', "A Village in Peril", %multiuserquests);
	BNet::Utils::preprint ($count, '38645', "Children of the Night", %multiuserquests);
	BNet::Utils::preprint ($count, '38644', "The Farmsteads", %multiuserquests);
	BNet::Utils::preprint ($count, '39117', "Shriek No More", %multiuserquests);
	BNet::Utils::preprint ($count, '38646', "A Sight For Sore Eyes", %multiuserquests);
	BNet::Utils::preprint ($count, '38647', "For the Corn!", %multiuserquests);
	BNet::Utils::preprint ($count, '38691', "Jarod's Mission", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Black Rook Hold");
	BNet::Utils::preprint ($count, '38718', "Kur'talos Ravencrest", %multiuserquests);
	BNet::Utils::preprint ($count, '38714', "Maiev's Trail", %multiuserquests);
	BNet::Utils::preprint ($count, '38715', "The Rook's Guard", %multiuserquests);
	BNet::Utils::preprint ($count, '38717', "Black Rook Prison", %multiuserquests);
	BNet::Utils::preprint ($count, '38724', "Brotherly Love", %multiuserquests);
	BNet::Utils::preprint ($count, '38719', "Illidari Freedom", %multiuserquests);
	BNet::Utils::preprint ($count, '38721', "Lieutenant of the Tower", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Bonus Areas");
	BNet::Utils::preprint ($count, '38716', "Black Rook Hold", %multiuserquests);
	BNet::Utils::preprint ($count, '39029', "Defend The Temple", %multiuserquests);
	BNet::Utils::preprint ($count, '38842', "Faerie Fracas", %multiuserquests);
	BNet::Utils::preprint ($count, '43241', "Flow of the Nightmare", %multiuserquests);
	BNet::Utils::preprint ($count, '39393', "Moonclaw Vale", %multiuserquests);
	BNet::Utils::preprint ($count, '38748', "Ruins of Shala'nir", %multiuserquests);
	BNet::Utils::preprint ($count, '38372', "Wretched Sisters", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Saylanna Riverbreeze");
	BNet::Utils::preprint ($count, '40220', "Thorny Dancing", %multiuserquests);
	BNet::Utils::preprint ($count, '38862', "Thieving Thistleleaf", %multiuserquests);
	BNet::Utils::preprint ($count, '40221', "Spread Your Lunarwings and Fly", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Grizzleweald");
	BNet::Utils::preprint ($count, '42857', "Moist Around the Hedges", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Lightsong");
	BNet::Utils::preprint ($count, '42747', "Where the Wildkin Are", %multiuserquests);
	BNet::Utils::preprint ($count, '42748', "Emerald Sisters", %multiuserquests);
	BNet::Utils::preprint ($count, '42750', "Dreamcatcher", %multiuserquests);
	BNet::Utils::preprint ($count, '42786', "Grotesque Remains", %multiuserquests);
	BNet::Utils::preprint ($count, '42751', "Moon Reaver", %multiuserquests);
	BNet::Utils::groupheader ("Val'sharah: Single Quests");
	BNet::Utils::preprint ($count, '39354', "Wisp in the Willows", %multiuserquests);
	BNet::Utils::preprint ($count, '38889', "Adopting the Adorable", %multiuserquests);

}

sub z_100_highmountain ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Highmountain (Incomplete?)");
	BNet::Utils::groupheader ("Highmountain: Thunder Totem");
	BNet::Utils::preprint ($count, '39733', "The Lone Mountain", %multiuserquests);
	BNet::Utils::preprint ($count, '38907', "Keepers of the Hammer", %multiuserquests);
	BNet::Utils::preprint ($count, '38911', "The Rivermane Tribe", %multiuserquests);
	BNet::Utils::preprint ($count, '39491', "Ormgul the Pestilent", %multiuserquests);
	BNet::Utils::preprint ($count, '39272', "Poisoned Crops", %multiuserquests);
	BNet::Utils::preprint ($count, '39490', "Infestation", %multiuserquests);
	BNet::Utils::preprint ($count, '39496', "The Flow of the River", %multiuserquests);
	BNet::Utils::preprint ($count, '39316', "Trapped Tauren", %multiuserquests);
	BNet::Utils::preprint ($count, '39277', "Spray and Prey", %multiuserquests);
	BNet::Utils::preprint ($count, '39614', "Fish Out of Water", %multiuserquests);
	BNet::Utils::preprint ($count, '39572', "Moozy's Adventure", %multiuserquests);
	BNet::Utils::preprint ($count, '39323', "Moozy's Sojourn", %multiuserquests);
	BNet::Utils::preprint ($count, '42590', "Moozy's Reunion", %multiuserquests);
	BNet::Utils::preprint ($count, '39661', "Lifespring Cavern", %multiuserquests);
	BNet::Utils::preprint ($count, '39488', "Balance of Elements", %multiuserquests);
	BNet::Utils::preprint ($count, '39489', "Invading Spelunkers", %multiuserquests);
	BNet::Utils::preprint ($count, '39487', "Crystal Fury", %multiuserquests);
	BNet::Utils::preprint ($count, '39498', "High Water", %multiuserquests);
	BNet::Utils::preprint ($count, '42104', "The Underking Comes", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Riverbend");
	BNet::Utils::preprint ($count, '39025', "Grasp of the Underking", %multiuserquests);
	BNet::Utils::preprint ($count, '39026', "The Drogbar", %multiuserquests);
	BNet::Utils::preprint ($count, '39043', "Bitestone Enclave", %multiuserquests);
	BNet::Utils::preprint ($count, '39027', "Dargrul and the Hammer", %multiuserquests);
	BNet::Utils::preprint ($count, '38909', "Get to High Ground", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: The Skyhorn Tribe");
	BNet::Utils::preprint ($count, '38913', "The Skyhorn Tribe", %multiuserquests);
	BNet::Utils::preprint ($count, '39318', "Nursing the Wounds", %multiuserquests);
	BNet::Utils::preprint ($count, '38910', "Rocs vs Eagles", %multiuserquests);
	BNet::Utils::preprint ($count, '39321', "The Three", %multiuserquests);
	BNet::Utils::preprint ($count, '39429', "Assaulting the Haglands", %multiuserquests);
	BNet::Utils::preprint ($count, '39322', "The Witchqueen", %multiuserquests);
	BNet::Utils::preprint ($count, '39387', "The Skies of Highmountain", %multiuserquests);
	BNet::Utils::preprint ($count, '39419', "Hex-a-Gone", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: The Bloodtotem Tribe");
	BNet::Utils::preprint ($count, '38912', "The Bloodtotem Tribe", %multiuserquests);
	BNet::Utils::preprint ($count, '39372', "Witch of the Wood", %multiuserquests);
	BNet::Utils::preprint ($count, '39373', "Hags of a Feather", %multiuserquests);
	BNet::Utils::preprint ($count, '39873', "I Have a Bad Feeling About This", %multiuserquests);
	BNet::Utils::preprint ($count, '39374', "An Audience with Torok", %multiuserquests);
	BNet::Utils::preprint ($count, '39455', "Cave of the Blood Trial", %multiuserquests);
	BNet::Utils::preprint ($count, '39860', "Rite of Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '39381', "Rock Troll in a Hard Place", %multiuserquests);
	BNet::Utils::preprint ($count, '39391', "Pet Rocks", %multiuserquests);
	BNet::Utils::preprint ($count, '39425', "Stonedark Crystal", %multiuserquests);
	BNet::Utils::preprint ($count, '39588', "They Will Pay With Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '39426', "Blood Debt", %multiuserquests);
	BNet::Utils::preprint ($count, '40229', "Step into the Dark", %multiuserquests);
	BNet::Utils::preprint ($count, '39456', "Unexpected Allies", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Huln's War");
	BNet::Utils::preprint ($count, '40515', "A Walk With the Spirits", %multiuserquests);
	BNet::Utils::preprint ($count, '40167', "The Story of Huln", %multiuserquests);
	BNet::Utils::preprint ($count, '40520', "To See the Past", %multiuserquests);
	BNet::Utils::preprint ($count, '39983', "Huln's War - The Arrival", %multiuserquests);
	BNet::Utils::preprint ($count, '40112', "Huln's War - Malorne's Favored", %multiuserquests);
	BNet::Utils::preprint ($count, '39988', "Huln's War - Stormrage", %multiuserquests);
	BNet::Utils::preprint ($count, '39990', "Huln's War - Reinforcements", %multiuserquests);
	BNet::Utils::preprint ($count, '40388', "Huln's War - Shadowsong", %multiuserquests);
	BNet::Utils::preprint ($count, '39992', "Huln's War - The Nathrezim", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Secrets of Highmountain");
	BNet::Utils::preprint ($count, '38916', "Secrets of Highmountain", %multiuserquests);
	BNet::Utils::preprint ($count, '39575', "The Path of Huln", %multiuserquests);
	BNet::Utils::preprint ($count, '40219', "In Defiance of Deathwing", %multiuserquests);
	BNet::Utils::preprint ($count, '39578', "Titanic Showdown", %multiuserquests);
	BNet::Utils::preprint ($count, '39577', "An Ancient Secret", %multiuserquests);
	BNet::Utils::preprint ($count, '39579', "The Backdoor", %multiuserquests);
	BNet::Utils::preprint ($count, '39580', "The High Chieftain", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Battle of Snowblind Mesa");
	BNet::Utils::preprint ($count, '38915', "Battle of Snowblind Mesa", %multiuserquests);
	BNet::Utils::preprint ($count, '39776', "Battle Worms", %multiuserquests);
	BNet::Utils::preprint ($count, '39777', "Buy Us Time", %multiuserquests);
	BNet::Utils::preprint ($count, '39862', "The Siegebrul", %multiuserquests);
	BNet::Utils::preprint ($count, '42088', "Evacuate Snowmane", %multiuserquests);
	BNet::Utils::preprint ($count, '42512', "Highmountain Stands", %multiuserquests);
	BNet::Utils::preprint ($count, '40594', "Justice Rains from Above", %multiuserquests);
	BNet::Utils::preprint ($count, '39780', "The Underking", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Neltharion\'s Lair");
	BNet::Utils::preprint ($count, '39781', "Neltharion\'s Lair", %multiuserquests);
	BNet::Utils::preprint ($count, '42454', "Eye of Azshara: The Hammer of Khaz\'goroth", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Stonedark Cavern");
	BNet::Utils::preprint ($count, '39440', "You Lift, Brul?", %multiuserquests);
	BNet::Utils::preprint ($count, '39439', "Stonedark Relics", %multiuserquests);
	BNet::Utils::preprint ($count, '39437', "Deep in the Cavern", %multiuserquests);
	BNet::Utils::preprint ($count, '39438', "Guhruhlruhlruh", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Rockcrawler Chasm");
	BNet::Utils::preprint ($count, '40070', "Eagle Egg Recovery", %multiuserquests);
	BNet::Utils::preprint ($count, '39305', "Empty Nest", %multiuserquests);
	BNet::Utils::preprint ($count, '40069', "Fledgling Worm Guts", %multiuserquests);
	BNet::Utils::preprint ($count, '42425', "Going Down, Going Up", %multiuserquests);
	BNet::Utils::preprint ($count, '40071', "Tamer Takedown", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Hemet Nesingwary");
	BNet::Utils::preprint ($count, '40217', "An Offering of Ammo", %multiuserquests);
	BNet::Utils::preprint ($count, '39417', "Rating Razik", %multiuserquests);
	BNet::Utils::preprint ($count, '40170', "Amateur Hour", %multiuserquests);
	BNet::Utils::preprint ($count, '39859', "Note-Eating Goats", %multiuserquests);
	BNet::Utils::preprint ($count, '40216', "A Hunter at Heart", %multiuserquests);
	BNet::Utils::preprint ($count, '40228', "Scout It Out", %multiuserquests);
	BNet::Utils::preprint ($count, '39392', "Bear Huntin'", %multiuserquests);
	BNet::Utils::preprint ($count, '39123', "Lion Stalkin'", %multiuserquests);
	BNet::Utils::preprint ($count, '39124', "Moose Shootin'", %multiuserquests);
	BNet::Utils::preprint ($count, '39178', "Moose on the Loose'", %multiuserquests);
	BNet::Utils::preprint ($count, '39867', "I\'m Not Lion!", %multiuserquests);
	BNet::Utils::preprint ($count, '40244', "That Guy in the Costume", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Shipwreck Cove");
	BNet::Utils::preprint ($count, '40049', "Slime Time", %multiuserquests);
	BNet::Utils::preprint ($count, '40047', "I'll Huff, I'll Puff...", %multiuserquests);
	BNet::Utils::preprint ($count, '40045', "Nature vs. Nurture", %multiuserquests);
	BNet::Utils::preprint ($count, '40102', "Murlocs: The Next Generation", %multiuserquests);
	BNet::Utils::preprint ($count, '40230', "Oh, the Clawdacity!", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Candle King");
	BNet::Utils::preprint ($count, '39768', "Candle to the Grave", %multiuserquests);
	BNet::Utils::preprint ($count, '39765', "Wax On, Wax Off", %multiuserquests);
	BNet::Utils::preprint ($count, '39769', "The Gates of Wax", %multiuserquests);
	BNet::Utils::preprint ($count, '40339', "Candle of Command", %multiuserquests);
	BNet::Utils::preprint ($count, '40345', "Burn the Candle at Both Ends", %multiuserquests);
	BNet::Utils::preprint ($count, '39772', "Can\'t Hold a Candle To You", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Aviana");
	BNet::Utils::preprint ($count, '41094', "Hatchlings of the Talon", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Thunder Totem Misc.");
	BNet::Utils::preprint ($count, '42622', "Ceremonial Drums", %multiuserquests);
	BNet::Utils::preprint ($count, '42596', "Mountainstrider Round-Up", %multiuserquests);
	BNet::Utils::preprint ($count, '39133', "No Time to Talk", %multiuserquests);
	BNet::Utils::preprint ($count, '39134', "Wrathshard", %multiuserquests);
	BNet::Utils::groupheader ("Highmountain: Bonus Objectives");
	BNet::Utils::preprint ($count, '39274', "Defend the Riverlands", %multiuserquests);
	BNet::Utils::preprint ($count, '39576', "Echoes of Deathwing", %multiuserquests);
	BNet::Utils::preprint ($count, '40050', "Shipwreck Cove", %multiuserquests);
	BNet::Utils::preprint ($count, '39317', "Siege of Crawliac", %multiuserquests);
	BNet::Utils::preprint ($count, '40316', "The Screeching Crag", %multiuserquests);
	BNet::Utils::preprint ($count, '42373', "Vengeance for the Stonedark", %multiuserquests);
	BNet::Utils::preprint ($count, '39371', "Witches of the Sky", %multiuserquests);
	BNet::Utils::preprint ($count, '39123', "Lion Stalkin'", %multiuserquests);



}


sub z_100_stormheim ($%) {
	my ($count, %multiuserquests) = @_;


	BNet::Utils::groupheader ("Stormheim: Intro: Alliance <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '39735', "Stormheim", %multiuserquests);
	BNet::Utils::preprint ($count, '38035', "A Royal Summons", %multiuserquests);
	BNet::Utils::preprint ($count, '38206', "Making the Rounds", %multiuserquests);
	BNet::Utils::preprint ($count, '39800', "Greymane's Gambit", %multiuserquests);
	BNet::Utils::preprint ($count, '38052', "Boarded!", %multiuserquests);
	BNet::Utils::preprint ($count, '38036', "Supplies From the Skies", %multiuserquests);
	BNet::Utils::preprint ($count, '38053', "Assault and Battery", %multiuserquests);
	BNet::Utils::preprint ($count, '38558', "See Ya Later, Oscillator", %multiuserquests);
	BNet::Utils::preprint ($count, '38058', "Lightning Rod", %multiuserquests);
	BNet::Utils::preprint ($count, '38057', "The Lost Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '38059', "Pins and Needles", %multiuserquests);
	BNet::Utils::preprint ($count, '38060', "Signal Boost", %multiuserquests);
	BNet::Utils::preprint ($count, '39775', "Stormforged Grapple Launcher", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Intro: Horde  <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '39864', "Stormheim", %multiuserquests);
	BNet::Utils::preprint ($count, '38307', "The Warchief Beckons", %multiuserquests);
	BNet::Utils::preprint ($count, '39698', "Making the Rounds", %multiuserquests);
	BNet::Utils::preprint ($count, '39801', "The Splintered Fleet", %multiuserquests);
	BNet::Utils::preprint ($count, '38332', "The Ranger Lord", %multiuserquests);
	BNet::Utils::preprint ($count, '38358', "Pump it Up", %multiuserquests);
	BNet::Utils::preprint ($count, '38357', "Side Effects May Include Mild Undeath", %multiuserquests);
	BNet::Utils::preprint ($count, '38360', "The Windrunner's Fate", %multiuserquests);
	BNet::Utils::preprint ($count, '38361', "Wrath of the Blightcaller", %multiuserquests);
	BNet::Utils::preprint ($count, '38362', "A Grim Trophy", %multiuserquests);
	BNet::Utils::preprint ($count, '38308', "Eyes in the Overlook", %multiuserquests);
	BNet::Utils::preprint ($count, '38317', "Masters of Disguise", %multiuserquests);
	BNet::Utils::preprint ($count, '39775', "Stormforged Grapple Launcher", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Ancient Trials: The Blessing of the Watchers");
	BNet::Utils::preprint ($count, '38210', "The Ancient Trials <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38459', "The Ancient Trials <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38331', "Havi's Test", %multiuserquests);
	BNet::Utils::preprint ($count, '39590', "Ahead of the Game", %multiuserquests);
	BNet::Utils::preprint ($count, '39595', "Blood and Gold", %multiuserquests);
	BNet::Utils::preprint ($count, '39591', "A Trial of Valor", %multiuserquests);
	BNet::Utils::preprint ($count, '39592', "A Trial of Will", %multiuserquests);
	BNet::Utils::preprint ($count, '39593', "The Shattered Watcher", %multiuserquests);
	BNet::Utils::preprint ($count, '39594', "A Trial of Might", %multiuserquests);
	BNet::Utils::preprint ($count, '39597', "The Blessing of the Watchers", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Ancient Trials: Where Dragons Rule");
	BNet::Utils::preprint ($count, '38473', "Will of the Thorignir <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38611', "Will of the Thorignir <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38312', "A Grapple a Day <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38612', "A Grapple a Day <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38318', "No Wings Required <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38613', "No Wings Required <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38405', "To Weather the Storm <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38614', "To Weather the Storm <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38616', "Built to Scale <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38337', "Built to Scale <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38410', "Impalement Insurance <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38615', "Impalement Insurance <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38342', "Another Way <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38617', "Another Way <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38412', "Above the Winter Moonlight <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38618', "Above the Winter Moonlight <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '38414', "Heart of a Dragon", %multiuserquests);
	BNet::Utils::preprint ($count, '38413', "Wings of Liberty", %multiuserquests);
	BNet::Utils::preprint ($count, '40568', "Fury of the Storm", %multiuserquests);
	BNet::Utils::preprint ($count, '39652', "Where Dragons Rule", %multiuserquests);
	BNet::Utils::preprint ($count, '38624', "Cry Thunder!", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Ancient Trials: The Final Judgement");
	BNet::Utils::preprint ($count, '39803', "The Trials Continue", %multiuserquests);
	BNet::Utils::preprint ($count, '39804', "Speaking of Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '39796', "To Haustvald", %multiuserquests);
	BNet::Utils::preprint ($count, '38778', "Turn the Keys", %multiuserquests);
	BNet::Utils::preprint ($count, '39788', "The Runewood's Revenge", %multiuserquests);
	BNet::Utils::preprint ($count, '38810', "The Dreaming Fungus", %multiuserquests);
	BNet::Utils::preprint ($count, '38808', "Bjornharta", %multiuserquests);
	BNet::Utils::preprint ($count, '38811', "Judgment Day", %multiuserquests);
	BNet::Utils::preprint ($count, '39791', "Lay Them to Rest", %multiuserquests);
	BNet::Utils::preprint ($count, '38817', "Regal Remains", %multiuserquests);
	BNet::Utils::preprint ($count, '38816', "Breaking the Bonespeakers", %multiuserquests);
	BNet::Utils::preprint ($count, '38823', "The Runes that Bind", %multiuserquests);
	BNet::Utils::preprint ($count, '38815', "Waking the Shieldmaiden", %multiuserquests);
	BNet::Utils::preprint ($count, '38818', "The Final Judgment", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Ancient Trials: Victory is Eternal (Helheim)");
	BNet::Utils::preprint ($count, '39837', "An Unworthy Task", %multiuserquests);
	BNet::Utils::preprint ($count, '38339', "A Little Kelp From My Foes", %multiuserquests);
	BNet::Utils::preprint ($count, '38324', "Accessories of the Cursed", %multiuserquests);
	BNet::Utils::preprint ($count, '38347', "Stealth by Seaweed", %multiuserquests);
	BNet::Utils::preprint ($count, '39848', "A Desperate Bargain", %multiuserquests);
	BNet::Utils::preprint ($count, '39857', "The Eternal Nemesis", %multiuserquests);
	BNet::Utils::preprint ($count, '39849', "To Light the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '39850', "Sundered", %multiuserquests);
	BNet::Utils::preprint ($count, '39851', "Allies in Death", %multiuserquests);
	BNet::Utils::preprint ($count, '39853', "Victory is Eternal", %multiuserquests);
	BNet::Utils::preprint ($count, '39855', "Paid in Lifeblood", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: The Aegis of Agrammar");
	BNet::Utils::preprint ($count, '40078', "A Heavy Burden", %multiuserquests);
	BNet::Utils::preprint ($count, '40001', "Knocking on Valor's Door", %multiuserquests);
	BNet::Utils::preprint ($count, '40002', "A Familiar Fate", %multiuserquests);
	BNet::Utils::preprint ($count, '40003', "Stem the Tide", %multiuserquests);
	BNet::Utils::preprint ($count, '40004', "Break the Spine", %multiuserquests);
	BNet::Utils::preprint ($count, '40005', "Stormheim's Salvation", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Halls of Valor");
	BNet::Utils::preprint ($count, '40072', "Halls of Valor: Securing the Aegis", %multiuserquests);
	BNet::Utils::preprint ($count, '43349', "The Aegis of Aggramar", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Skold-Ashil (Alliance)");
	BNet::Utils::preprint ($count, '39059', "To Catch a Banshee", %multiuserquests);
	BNet::Utils::preprint ($count, '39060', "Combustible Contagion", %multiuserquests);
	BNet::Utils::preprint ($count, '39061', "Whispers from the Dark", %multiuserquests);
	BNet::Utils::preprint ($count, '39472', "Cut Out the Heart", %multiuserquests);
	BNet::Utils::preprint ($count, '39062', "To Skold-Ashil", %multiuserquests);
	BNet::Utils::preprint ($count, '39063', "Shielded Secrets", %multiuserquests);
	BNet::Utils::preprint ($count, '39092', "Becoming the Ascendant", %multiuserquests);
	BNet::Utils::preprint ($count, '39122', "Ending the New Beginning", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Skold-Ashil (Horde)");
	BNet::Utils::preprint ($count, '38872', "The Dark Lady's Bidding", %multiuserquests);
	BNet::Utils::preprint ($count, '38873', "Clear the Deck!", %multiuserquests);
	BNet::Utils::preprint ($count, '39153', "Dreadwake's Dilemma", %multiuserquests);
	BNet::Utils::preprint ($count, '39385', "A Gift for Greymane", %multiuserquests);
	BNet::Utils::preprint ($count, '39154', "To Skold-Ashil", %multiuserquests);
	BNet::Utils::preprint ($count, '38878', "Shielded Secrets", %multiuserquests);
	BNet::Utils::preprint ($count, '39405', "Stories of Battle", %multiuserquests);
	BNet::Utils::preprint ($count, '39155', "Becoming the Ascendant", %multiuserquests);
	BNet::Utils::preprint ($count, '38882', "A New Life for Undeath", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Sixtrigger Brothers");
	BNet::Utils::preprint ($count, '39789', "Eating Into Our Business", %multiuserquests);
	BNet::Utils::preprint ($count, '39793', "Only the Finest", %multiuserquests);
	BNet::Utils::preprint ($count, '39787', "Rigging the Wager", %multiuserquests);
	BNet::Utils::preprint ($count, '39786', "A Stone Cold Gamble", %multiuserquests);
	BNet::Utils::preprint ($count, '39792', "A Stack of Racks", %multiuserquests);
	BNet::Utils::preprint ($count, '42483', "Put It All on Red", %multiuserquests);
	BNet::Utils::preprint ($count, '43331', "Time to Collect", %multiuserquests);
	BNet::Utils::groupheader ("Stormheim: Bonus Objectives");
	BNet::Utils::preprint ($count, '38442', "A Worthy Challenger", %multiuserquests);
	BNet::Utils::preprint ($count, '38343', "Raze Hel", %multiuserquests);
	BNet::Utils::preprint ($count, '38939', "Assault on Skold-Ashil", %multiuserquests);
	BNet::Utils::preprint ($count, '38374', "Assault the Drekirjar", %multiuserquests);
	BNet::Utils::preprint ($count, '39998', "Drive Back the Tideskorn", %multiuserquests);
	BNet::Utils::preprint ($count, '40111', "Rout the Bilgefin Invaders", %multiuserquests);
	BNet::Utils::preprint ($count, '42431', "The Brood of Nithogg", %multiuserquests);

}

sub z_110_suramar ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: Nightfall");
	BNet::Utils::preprint ($count, '39985', "Khadgar's Discovery", %multiuserquests);
#	BNet::Utils::preprint ($count, '44555', "Khadgar's Discovery", %multiuserquests);
	BNet::Utils::preprint ($count, '39986', "Magic Message", %multiuserquests);
	BNet::Utils::preprint ($count, '39987', "Trail of Echoes", %multiuserquests);
	BNet::Utils::preprint ($count, '40008', "The Only Way Out is Through", %multiuserquests);
	BNet::Utils::preprint ($count, '40123', "The Nightborne Pact", %multiuserquests);
	BNet::Utils::preprint ($count, '40009', "Arcane Thirst", %multiuserquests);
	BNet::Utils::preprint ($count, '42229', "Shal'Aran", %multiuserquests);
	BNet::Utils::preprint ($count, '44672', "Ancient Mana", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: Arcanist Kel'danath");
	BNet::Utils::preprint ($count, '40012', "An Old Ally", %multiuserquests);
	BNet::Utils::preprint ($count, '41149', "A Re-Warding Effort", %multiuserquests);
	BNet::Utils::preprint ($count, '40326', "Scattered Memories", %multiuserquests);
	BNet::Utils::preprint ($count, '41702', "Written in Stone", %multiuserquests);
	BNet::Utils::preprint ($count, '41704', "Subject 16", %multiuserquests);
	BNet::Utils::preprint ($count, '41760', "Kel'danath's Legacy", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: Chief Telemancer Oculeth");
	BNet::Utils::preprint ($count, '40011', "Oculeth's Workshop", %multiuserquests);
	BNet::Utils::preprint ($count, '40747', "The Delicate Art of Telemancy", %multiuserquests);
	BNet::Utils::preprint ($count, '40748', "Network Security", %multiuserquests);
	BNet::Utils::preprint ($count, '40830', "Close Enough", %multiuserquests);
	BNet::Utils::preprint ($count, '44691', "Hungry Work", %multiuserquests);
	BNet::Utils::preprint ($count, '40956', "Survey Says...", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: Feeding Shal'Aran");
	BNet::Utils::preprint ($count, '40010', "Tapping the Leylines", %multiuserquests);
	BNet::Utils::preprint ($count, '41028', "Power Grid", %multiuserquests);
	BNet::Utils::preprint ($count, '41138', "Feeding Shal'Aran", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: Masquerade");
	BNet::Utils::preprint ($count, '41762', "Sympathizers Among the Shal'dorei", %multiuserquests);
	BNet::Utils::preprint ($count, '41834', "The Masks We Wear", %multiuserquests);
	BNet::Utils::preprint ($count, '41989', "Blood of My Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '42079', "Masquerade", %multiuserquests);
	BNet::Utils::preprint ($count, '42147', "First Contact", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Nightfallen But Not Forgotten: The Light Below");
	BNet::Utils::preprint ($count, '40324', "Arcane Communion", %multiuserquests);
	BNet::Utils::preprint ($count, '40325', "Scenes from a Memory", %multiuserquests);
	BNet::Utils::preprint ($count, '42224', "Cloaked in Moonshade", %multiuserquests);
	BNet::Utils::preprint ($count, '42225', "Breaking the Seal", %multiuserquests);
	BNet::Utils::preprint ($count, '42226', "Moonshade Holdout", %multiuserquests);
	BNet::Utils::preprint ($count, '42227', "Into the Crevasse", %multiuserquests);
	BNet::Utils::preprint ($count, '42228', "The Hidden City", %multiuserquests);
	BNet::Utils::preprint ($count, '42230', "The Valewalker's Burden", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: The Waning Crescent");
	BNet::Utils::preprint ($count, '41877', "Lady Lunastre", %multiuserquests);
	BNet::Utils::preprint ($count, '40746', "One of the People", %multiuserquests);
	BNet::Utils::preprint ($count, '41148', "Dispensing Compassion", %multiuserquests);
	BNet::Utils::preprint ($count, '40947', "Special Delivery", %multiuserquests);
	BNet::Utils::preprint ($count, '41878', "The Gondolier", %multiuserquests);
	BNet::Utils::preprint ($count, '40727', "All Along the Waterways", %multiuserquests);
	BNet::Utils::preprint ($count, '40730', "Redistribution", %multiuserquests);
	BNet::Utils::preprint ($count, '40745', "Shift Change", %multiuserquests);
	BNet::Utils::preprint ($count, '42722', "Friends in Cages", %multiuserquests);
	BNet::Utils::preprint ($count, '42486', "Little One Lost", %multiuserquests);
	BNet::Utils::preprint ($count, '42487', "Friends On the Outside", %multiuserquests);
	BNet::Utils::preprint ($count, '44051', "Wasted Potential", %multiuserquests);
	BNet::Utils::preprint ($count, '42488', "Thalyssra's Abode", %multiuserquests);
	BNet::Utils::preprint ($count, '42489', "Thalyssra's Drawers", %multiuserquests);
	BNet::Utils::preprint ($count, '44636', "Building an Army", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Blood and Wine");
	BNet::Utils::preprint ($count, '44561', "Seed of Hope", %multiuserquests);
	BNet::Utils::preprint ($count, '42828', "Moths to a Flame", %multiuserquests);
	BNet::Utils::preprint ($count, '42829', "Make an Entrance", %multiuserquests);
	BNet::Utils::preprint ($count, '42832', "The Fruit of Our Efforts", %multiuserquests);
	BNet::Utils::preprint ($count, '42833', "How It's Made: Arcwine", %multiuserquests);
	BNet::Utils::preprint ($count, '42834', "Intense Concentration", %multiuserquests);
	BNet::Utils::preprint ($count, '42835', "The Old Fashioned Way", %multiuserquests);
	BNet::Utils::preprint ($count, '42836', "Silkwing Sabotage", %multiuserquests);
	BNet::Utils::preprint ($count, '42837', "Balance to Spare", %multiuserquests);
	BNet::Utils::preprint ($count, '42838', "Reversal", %multiuserquests);
	BNet::Utils::preprint ($count, '44084', "Vengeance for Margaux", %multiuserquests);
	BNet::Utils::preprint ($count, '42839', "Seek the Unsavory", %multiuserquests);
	BNet::Utils::preprint ($count, '43969', "Hired Help", %multiuserquests);
	BNet::Utils::preprint ($count, '42840', "If Words Don't Work...", %multiuserquests);
	BNet::Utils::preprint ($count, '42841', "A Big Score", %multiuserquests);
	BNet::Utils::preprint ($count, '43352', "Asset Security", %multiuserquests);
	BNet::Utils::preprint ($count, '42792', "Make Your Mark", %multiuserquests);
	BNet::Utils::preprint ($count, '44052', "And They Will Tremble", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Statecraft");
	BNet::Utils::preprint ($count, '43309', "The Perfect Opportunity", %multiuserquests);
	BNet::Utils::preprint ($count, '43310', "Either With Us", %multiuserquests);
	BNet::Utils::preprint ($count, '43312', "Thinly Veiled Threats", %multiuserquests);
	BNet::Utils::preprint ($count, '44040', "Vote of Confidence", %multiuserquests);
	BNet::Utils::preprint ($count, '43311', "Or Against Us", %multiuserquests);
	BNet::Utils::preprint ($count, '43315', "Death Becomes Him", %multiuserquests);
	BNet::Utils::preprint ($count, '43313', "Rumor Has It", %multiuserquests);
	BNet::Utils::preprint ($count, '43317', "In the Bag", %multiuserquests);
	BNet::Utils::preprint ($count, '43318', "Ly'leth's Champion", %multiuserquests);
	BNet::Utils::preprint ($count, '44053', "Friends With Benefits", %multiuserquests);
	BNet::Utils::preprint ($count, '42490', "The Arcway: Opening the Arcway", %multiuserquests);
	BNet::Utils::preprint ($count, '42491', "The Arcway: Long Buried Knowledge", %multiuserquests);
	BNet::Utils::preprint ($count, '43314', "Court of Stars: Beware the Fury of a Patient Elf", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: A Growing Crisis");
	BNet::Utils::preprint ($count, '44562', "Growing Strong", %multiuserquests);
	BNet::Utils::preprint ($count, '44152', "A Growing Crisis", %multiuserquests);
	BNet::Utils::preprint ($count, '43360', "The Shardmaidens", %multiuserquests);
	BNet::Utils::preprint ($count, '43361', "Fragments of Disaster", %multiuserquests);
	BNet::Utils::preprint ($count, '44156', "Another Arcan'dor Closes...", %multiuserquests);
	BNet::Utils::preprint ($count, '40125', "Branch of the Arcan'dor", %multiuserquests);
	BNet::Utils::preprint ($count, '43362', "The Emerald Nightmare: The Stuff of Dreams", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: A Change of Seasons");
	BNet::Utils::preprint ($count, '43502', "A Change of Seasons", %multiuserquests);
	BNet::Utils::preprint ($count, '43562', "Giving It All We've Got", %multiuserquests);
	BNet::Utils::preprint ($count, '43563', "Ephemeral Manastorm Projector", %multiuserquests);
	BNet::Utils::preprint ($count, '43564', "Flow Control", %multiuserquests);
	BNet::Utils::preprint ($count, '43565', "Bring Home the Beacon", %multiuserquests);
	BNet::Utils::preprint ($count, '43567', "All In", %multiuserquests);
	BNet::Utils::preprint ($count, '43568', "Arcan'dor, Gift of the Ancient Magi", %multiuserquests);
	BNet::Utils::preprint ($count, '43569', "Arluin's Request", %multiuserquests);
	BNet::Utils::preprint ($count, '44563', "Redemption for the Fallen", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Leylines");
	BNet::Utils::preprint ($count, '43587', "Leyline Feed: Elor'shan", %multiuserquests);
	BNet::Utils::preprint ($count, '43588', "Leyline Feed: Kel'balor", %multiuserquests);
	BNet::Utils::preprint ($count, '43590', "Leyline Feed: Ley Station Moonfall", %multiuserquests);
	BNet::Utils::preprint ($count, '43591', "Leyline Feed: Ley Station Aethenar", %multiuserquests);
	BNet::Utils::preprint ($count, '43592', "Leyline Feed: Falanaar Arcway", %multiuserquests);
	BNet::Utils::preprint ($count, '43593', "Leyline Feed: Falanaar Depths", %multiuserquests);
	BNet::Utils::preprint ($count, '43594', "Leyline Feed: Halls of the Eclipse", %multiuserquests);
	BNet::Utils::preprint ($count, '44492', "Leyline Apprentice", %multiuserquests);
	BNet::Utils::preprint ($count, '44493', "Leyline Proficiency", %multiuserquests);
	BNet::Utils::preprint ($count, '44495', "Leyline Master", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Teleporters");
	BNet::Utils::preprint ($count, '43808', "Moon Guard Teleporter Online!", %multiuserquests);
	BNet::Utils::preprint ($count, '43809', "Tel'anor'eporter Online!", %multiuserquests);
	BNet::Utils::preprint ($count, '43811', "Lunastre Estate Teleporter Online!", %multiuserquests);
	BNet::Utils::preprint ($count, '43813', "Sanctum of Order Teleporter Online!", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Breaking the Lightbreaker");
	BNet::Utils::preprint ($count, '40297', "Lyana Darksorrow", %multiuserquests);
	BNet::Utils::preprint ($count, '44489', "Lyana Darksorrow (Demon Hunter)", %multiuserquests);
	BNet::Utils::preprint ($count, '40307', "Glaive Circumstances", %multiuserquests);
	BNet::Utils::preprint ($count, '40898', "Fresh Meat", %multiuserquests);
	BNet::Utils::preprint ($count, '40901', "Grimwing the Devourer", %multiuserquests);
	BNet::Utils::preprint ($count, '44490', "Grimwing the Devourer (Demon Hunter)", %multiuserquests);
	BNet::Utils::preprint ($count, '40328', "A Fate Worse Than Dying", %multiuserquests);
	BNet::Utils::preprint ($count, '40929', "Symbols of Power", %multiuserquests);
	BNet::Utils::preprint ($count, '41097', "Shard of Vorgos", %multiuserquests);
	BNet::Utils::preprint ($count, '41098', "Shard of Kozak", %multiuserquests);
	BNet::Utils::preprint ($count, '40412', "Azoran Must Die", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Moon Guard Stronghold");
	BNet::Utils::preprint ($count, '40883', "Fate of the Guard", %multiuserquests);
	BNet::Utils::preprint ($count, '40949', "Not Their Last Stand", %multiuserquests);
	BNet::Utils::preprint ($count, '41030', "Sigil Reclamation", %multiuserquests);
	BNet::Utils::preprint ($count, '40963', "Take Them in Claw", %multiuserquests);
	BNet::Utils::preprint ($count, '40968', "Recovering Stolen Power", %multiuserquests);
	BNet::Utils::preprint ($count, '41109', "Waiting for Revenge", %multiuserquests);
	BNet::Utils::preprint ($count, '41108', "Rain Death Upon Them", %multiuserquests);
	BNet::Utils::preprint ($count, '40964', "The Rift Between", %multiuserquests);
	BNet::Utils::preprint ($count, '40967', "Precious Little Left", %multiuserquests);
	BNet::Utils::preprint ($count, '41032', "Stop the Spell Seekers", %multiuserquests);
	BNet::Utils::preprint ($count, '40965', "Lay Waste, Lay Mines", %multiuserquests);
	BNet::Utils::preprint ($count, '40969', "Starweaver's Fate", %multiuserquests);
	BNet::Utils::preprint ($count, '40970', "The Orchestrator of Our Demise", %multiuserquests);
	BNet::Utils::preprint ($count, '40971', "Overwhelming Distraction", %multiuserquests);
	BNet::Utils::preprint ($count, '40972', "Last Stand of the Moon Guard", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Tidying Tel'anor");
	BNet::Utils::preprint ($count, '40266', "The Lost Advisor", %multiuserquests);
	BNet::Utils::preprint ($count, '40744', "An Ancient Recipe", %multiuserquests);
	BNet::Utils::preprint ($count, '40227', "Bad Intentions", %multiuserquests);
	BNet::Utils::preprint ($count, '40300', "Tools of the Trade", %multiuserquests);
	BNet::Utils::preprint ($count, '40306', "The Last Chapter", %multiuserquests);
	BNet::Utils::preprint ($count, '40578', "Paying Respects", %multiuserquests);
	BNet::Utils::preprint ($count, '40315', "End of the Line", %multiuserquests);
	BNet::Utils::preprint ($count, '40319', "The Final Ingredient", %multiuserquests);
	BNet::Utils::preprint ($count, '40321', "Feathersong's Redemption", %multiuserquests);
	BNet::Utils::preprint ($count, '40308', "Fragments of Memory", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Eminent Grow-main");
	BNet::Utils::preprint ($count, '41452', "Feline Frantic", %multiuserquests);
	BNet::Utils::preprint ($count, '41453', "Homeward Bounding", %multiuserquests);
	BNet::Utils::preprint ($count, '41462', "Trouble Has Huge Feet", %multiuserquests);
	BNet::Utils::preprint ($count, '41197', "You've Got to Be Kitten Me Right Meow", %multiuserquests);
	BNet::Utils::preprint ($count, '41463', "Missing Along the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '41464', "Not Here, Not Now, Not Ever", %multiuserquests);
	BNet::Utils::preprint ($count, '41467', "The Only Choice We Can Make", %multiuserquests);
	BNet::Utils::preprint ($count, '41473', "Redhoof the Ancient", %multiuserquests);
	BNet::Utils::preprint ($count, '41474', "Fertilizing the Future", %multiuserquests);
	BNet::Utils::preprint ($count, '41475', "Prongs and Fangs", %multiuserquests);
	BNet::Utils::preprint ($count, '41478', "The Final Blessing", %multiuserquests);
	BNet::Utils::preprint ($count, '41479', "Natural Adversaries", %multiuserquests);
	BNet::Utils::preprint ($count, '41485', "Moonwhisper Rescue", %multiuserquests);
	BNet::Utils::preprint ($count, '41480', "Managazer", %multiuserquests);
	BNet::Utils::preprint ($count, '41469', "Return to Irongrove Retreat", %multiuserquests);
	BNet::Utils::preprint ($count, '41494', "Eminent Grow-main", %multiuserquests);
	BNet::Utils::preprint ($count, '42223', "Scouting the Crimson Thicket", %multiuserquests);
	BNet::Utils::preprint ($count, '40617', "Turn Around, Nighteyes", %multiuserquests);
	BNet::Utils::preprint ($count, '41230', "Trapping Evolved", %multiuserquests);
	BNet::Utils::preprint ($count, '41215', "They Become The Hunted", %multiuserquests);
	BNet::Utils::preprint ($count, '41231', "Apex Predator", %multiuserquests);
	BNet::Utils::preprint ($count, '43582', "Shalassic Park", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Good Suramaritan: Jandvik's Jarl");
	BNet::Utils::preprint ($count, '40907', "Removing Obstacles", %multiuserquests);
	BNet::Utils::preprint ($count, '40908', "Jarl Come Back Now", %multiuserquests);
	BNet::Utils::preprint ($count, '40332', "Beach Bonfire", %multiuserquests);
	BNet::Utils::preprint ($count, '40320', "Band of Blood Brothers", %multiuserquests);
	BNet::Utils::preprint ($count, '40331', "Bite of the Sashj'tar", %multiuserquests);
	BNet::Utils::preprint ($count, '40334', "Fisherman's Tonic", %multiuserquests);
	BNet::Utils::preprint ($count, '41034', "Testing the Waters", %multiuserquests);
	BNet::Utils::preprint ($count, '40927', "Jandvik's Last Hope", %multiuserquests);
	BNet::Utils::preprint ($count, '41426', "Against Their Will", %multiuserquests);
	BNet::Utils::preprint ($count, '41709', "Breaking Down the Big Guns", %multiuserquests);
	BNet::Utils::preprint ($count, '41410', "Dry Powder", %multiuserquests);
	BNet::Utils::preprint ($count, '41409', "Timing Is Everything", %multiuserquests);
	BNet::Utils::preprint ($count, '41606', "Finding Brytag", %multiuserquests);
	BNet::Utils::preprint ($count, '40364', "Bubble Trouble", %multiuserquests);
	BNet::Utils::preprint ($count, '41618', "The Seawarden", %multiuserquests);
	BNet::Utils::preprint ($count, '41425', "Sunken Foes", %multiuserquests);
	BNet::Utils::preprint ($count, '41001', "Shatter the Sashj'tar", %multiuserquests);
	BNet::Utils::preprint ($count, '41499', "Squid Out of Water", %multiuserquests);
	BNet::Utils::preprint ($count, '40336', "Turning the Tidemistress", %multiuserquests);
	BNet::Utils::preprint ($count, '41137', "Fall of the King", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Lespin Silverleaf");
	BNet::Utils::preprint ($count, '41123', "An Artisan's Mark", %multiuserquests);
	BNet::Utils::preprint ($count, '41307', "All That Glitters", %multiuserquests);
	BNet::Utils::preprint ($count, '41466', "Estate Jewelry: Haute Claw-ture", %multiuserquests);
	BNet::Utils::preprint ($count, '41320', "Pry It From Their Cold, Feral Claws", %multiuserquests);
	BNet::Utils::preprint ($count, '41465', "Estate Jewelry: A Braggart's Brooch", %multiuserquests);
	BNet::Utils::preprint ($count, '41146', "Elegant Design", %multiuserquests);
	BNet::Utils::preprint ($count, '41915', "The Master's Legacy", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Kyrtos");
	BNet::Utils::preprint ($count, '40694', "One Small Step for Magic", %multiuserquests);
	BNet::Utils::preprint ($count, '40625', "A Different Source", %multiuserquests);
	BNet::Utils::preprint ($count, '40657', "The Road to Fel", %multiuserquests);
	BNet::Utils::preprint ($count, '40683', "Discovery Requires Experimentation", %multiuserquests);
	BNet::Utils::preprint ($count, '40919', "Fel Bent for Leather", %multiuserquests);
	BNet::Utils::preprint ($count, '40713', "The Black Tome", %multiuserquests);
	BNet::Utils::preprint ($count, '40642', "Power! Get The Power!", %multiuserquests);
	BNet::Utils::preprint ($count, '42366', "The Bigger They Are, The Harder They Fel", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Iadreth");
	BNet::Utils::preprint ($count, '40401', "A Way Back In", %multiuserquests);
	BNet::Utils::preprint ($count, '40469', "Final Preparations", %multiuserquests);
	BNet::Utils::preprint ($count, '40424', "A Desperate Journey", %multiuserquests);
	BNet::Utils::preprint ($count, '40470', "Quality of Life", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Absolon");
	BNet::Utils::preprint ($count, '40796', "Lingering on the Edge", %multiuserquests);
	BNet::Utils::preprint ($count, '40798', "Cling to Hope", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Morhun Rivertamer");
	BNet::Utils::preprint ($count, '40368', "Turtle Powered", %multiuserquests);
	BNet::Utils::preprint ($count, '40348', "Something in the Water", %multiuserquests);
	BNet::Utils::preprint ($count, '40370', "Purge the Unclean", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Shal'aran Banking Chest");
	BNet::Utils::preprint ($count, '44176', "The Conveniences of Home", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part One: Lockdown");
	BNet::Utils::preprint ($count, '45260', "One Day at a Time", %multiuserquests);
	BNet::Utils::preprint ($count, '38649', "Silence in the City", %multiuserquests);
	BNet::Utils::preprint ($count, '38695', "Crackdown", %multiuserquests);
	BNet::Utils::preprint ($count, '38692', "Answering Aggression", %multiuserquests);
	BNet::Utils::preprint ($count, '38720', "No Reason to Stay", %multiuserquests);
	BNet::Utils::preprint ($count, '38694', "Regroup", %multiuserquests);
	BNet::Utils::preprint ($count, '42889', "The Way Back Home", %multiuserquests);
	BNet::Utils::preprint ($count, '44955', "Visitor in Shal'Aran", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Two: Missing Persons");
	BNet::Utils::preprint ($count, '45261', "Continuing the Cure", %multiuserquests);
	BNet::Utils::preprint ($count, '44722', "Disillusioned Defector", %multiuserquests);
	BNet::Utils::preprint ($count, '44724', "Missing Persons", %multiuserquests);
	BNet::Utils::preprint ($count, '44723', "More Like Me", %multiuserquests);
	BNet::Utils::preprint ($count, '44725', "Hostage Situation", %multiuserquests);
	BNet::Utils::preprint ($count, '44726', "In the Business of Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '44727', "Smuggled!", %multiuserquests);
	BNet::Utils::preprint ($count, '44814', "Waning Refuge", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Three: Waxing Crescent");
	BNet::Utils::preprint ($count, '45262', "A Message from Ly'leth", %multiuserquests);
	BNet::Utils::preprint ($count, '44742', "Tavernkeeper's Fate", %multiuserquests);
	BNet::Utils::preprint ($count, '44752', "Essence Triangulation", %multiuserquests);
	BNet::Utils::preprint ($count, '44753', "On Public Display", %multiuserquests);
	BNet::Utils::preprint ($count, '44754', "Waxing Crescent", %multiuserquests);
	BNet::Utils::preprint ($count, '44756', "Sign of the Dusk Lily", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Four: An Elven Problem");
	BNet::Utils::preprint ($count, '45316', "Stabilizing Suramar", %multiuserquests);
	BNet::Utils::preprint ($count, '45263', "Eating Before the Meeting", %multiuserquests);
	BNet::Utils::preprint ($count, '40391', "Take Me To Your Leader", %multiuserquests);
	BNet::Utils::preprint ($count, '43810', "Down to Business <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '43812', "Down to Business <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44831', "Taking a Promenade <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '41607', "Taking a Promenade <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '41916', "A Better Future", %multiuserquests);
	BNet::Utils::preprint ($count, '44834', "Nullified", %multiuserquests);
	BNet::Utils::preprint ($count, '44843', "Crystal Clearing", %multiuserquests);
	BNet::Utils::preprint ($count, '44844', "Powering Down the Portal", %multiuserquests);
	BNet::Utils::preprint ($count, '44842', "Shield, Meet Spell", %multiuserquests);
	BNet::Utils::preprint ($count, '44845', "Break an Arm", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Five: Crafting War");
	BNet::Utils::preprint ($count, '45265', "Feeding the Rebellion", %multiuserquests);
	BNet::Utils::preprint ($count, '44743', "Tyrande's Command <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44859', "Liadrin's Command <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44870', "Mouths to Feed", %multiuserquests);
	BNet::Utils::preprint ($count, '44873', "Oculeth Ex Machina", %multiuserquests);
	BNet::Utils::preprint ($count, '44858', "Trolling Them <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44860', "Trolling Them <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44928', "Something's Not Quite Right...", %multiuserquests);
	BNet::Utils::preprint ($count, '44861', "Arming the Rebels <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44862', "Arming the Rebels <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44827', "Citizens' Army", %multiuserquests);
	BNet::Utils::preprint ($count, '44829', "We Need Weapons", %multiuserquests);
	BNet::Utils::preprint ($count, '44830', "Learning From the Dead", %multiuserquests);
	BNet::Utils::preprint ($count, '44790', "Trial by Demonfire", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Six: March on Suramar");
	BNet::Utils::preprint ($count, '45266', "A United Front", %multiuserquests);
	BNet::Utils::preprint ($count, '44739', "Ready for Battle", %multiuserquests);
	BNet::Utils::preprint ($count, '44738', "Full Might of the Elves", %multiuserquests);
	BNet::Utils::preprint ($count, '44740', "Staging Point", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Seven: Elisande's Retort");
	BNet::Utils::preprint ($count, '45317', "Fighting on All Fronts", %multiuserquests);
	BNet::Utils::preprint ($count, '45267', "Before the Siege", %multiuserquests);
	BNet::Utils::preprint ($count, '44736', "Gates of the Nighthold", %multiuserquests);
	BNet::Utils::preprint ($count, '44822', "Temporal Investigations", %multiuserquests);
	BNet::Utils::preprint ($count, '45209', "Those Scrying Eyes", %multiuserquests);
	BNet::Utils::preprint ($count, '44832', "Scouting the Breach", %multiuserquests);
	BNet::Utils::preprint ($count, '44833', "The Seal's Power", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Eight: As Strong as Our Will");
	BNet::Utils::preprint ($count, '45268', "The Advisor and the Arcanist", %multiuserquests);
	BNet::Utils::preprint ($count, '44918', "A Message From Our Enemies", %multiuserquests);
	BNet::Utils::preprint ($count, '44919', "A Challenge From Our Enemies", %multiuserquests);
	BNet::Utils::preprint ($count, '45063', "The Felsoul Experiments", %multiuserquests);
	BNet::Utils::preprint ($count, '45067', "Telemantic Expanse", %multiuserquests);
	BNet::Utils::preprint ($count, '45062', "Resisting Arrest", %multiuserquests);
	BNet::Utils::preprint ($count, '45065', "Survey the City", %multiuserquests);
	BNet::Utils::preprint ($count, '45066', "Experimental Instability", %multiuserquests);
	BNet::Utils::preprint ($count, '45064', "Felborne No More", %multiuserquests);
	BNet::Utils::groupheader ("Suramar: Insurrection: Part Nine: Breaking the Nighthold");
	BNet::Utils::preprint ($count, '45269', "A Taste of Freedom", %multiuserquests);
	BNet::Utils::preprint ($count, '44964', "I'll Just Leave This Here", %multiuserquests);
	BNet::Utils::preprint ($count, '44719', "Breaching the Sanctum", %multiuserquests);
	BNet::Utils::preprint ($count, '45417', "The Nighthold: Lord of the Shadow Council", %multiuserquests);
	BNet::Utils::preprint ($count, '45372', "Fate of the Nightborne", %multiuserquests);



}

sub z_110_legion_fall ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Broken Shore");
	BNet::Utils::preprint ($count, '46730', "Armies of Legionfall", %multiuserquests);
	BNet::Utils::preprint ($count, '46734', "Assault on Broken Shore", %multiuserquests);
	BNet::Utils::preprint ($count, '46245', "Begin Construction", %multiuserquests);
	BNet::Utils::preprint ($count, '46832', "Aalgen Point", %multiuserquests);
	BNet::Utils::preprint ($count, '46845', "Vengeance Point", %multiuserquests);
	BNet::Utils::preprint ($count, '46247', "Defending Broken Isles", %multiuserquests);
	BNet::Utils::preprint ($count, '47137', "Champions of Legionfall", %multiuserquests);
	BNet::Utils::preprint ($count, '46251', "Shard Times", %multiuserquests);
	BNet::Utils::preprint ($count, '47139', "Mark of the Sentinax", %multiuserquests);
	BNet::Utils::preprint ($count, '46248', "Self-Fulfilling Prophecy", %multiuserquests);
	BNet::Utils::preprint ($count, '46252', "Intolerable Infestation", %multiuserquests);
	BNet::Utils::preprint ($count, '46769', "Relieved of Their Valuables", %multiuserquests);
	BNet::Utils::preprint ($count, '46250', "Take Out the Head...", %multiuserquests);
	BNet::Utils::preprint ($count, '46249', "Championing Our Cause", %multiuserquests);
	BNet::Utils::preprint ($count, '46246', "Strike Them Down", %multiuserquests);
	BNet::Utils::groupheader ("Broken Shore: Dungeon/Raid Quests");
	BNet::Utils::preprint ($count, '46244', "Altar of the Aegis", %multiuserquests);
	BNet::Utils::preprint ($count, '46253', "Pillars of Creation", %multiuserquests);
	BNet::Utils::preprint ($count, '46805', "The Deceiver's Downfall", %multiuserquests);

}

sub artifact_improvingonhistory ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Improving on History");
	BNet::Utils::preprint ($count, '43496', "The Power Within", %multiuserquests);
	BNet::Utils::preprint ($count, '40668', "Eye of Azshara: The Heart of Zin-Azshari (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '43517', "Darkheart Thicket: Fallen Power (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '43514', "Vainglorious Past", %multiuserquests);
	BNet::Utils::preprint ($count, '43518', "Tempering Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '43519', "Lucid Strength ", %multiuserquests);
	BNet::Utils::preprint ($count, '43520', "The Emerald Nightmare: In Nightmares", %multiuserquests);
	BNet::Utils::preprint ($count, '43521', "Essence of Power", %multiuserquests);
	BNet::Utils::preprint ($count, '43522', "Essential Consumption", %multiuserquests);
	BNet::Utils::preprint ($count, '43527', "Saving the Guard", %multiuserquests);
	BNet::Utils::preprint ($count, '43523', "Repaid Debt", %multiuserquests);
	BNet::Utils::preprint ($count, '40673', "Lost Knowledge", %multiuserquests);
	BNet::Utils::preprint ($count, '43525', "Vault of the Wardens: Borrowing Without Asking (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '40675', "The Arcway: Rite of the Captain (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '43524', "Court of Stars: Literary Perfection (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '40678', "Twisted Power", %multiuserquests);
	BNet::Utils::preprint ($count, '43526', "A True Test", %multiuserquests);
	BNet::Utils::preprint ($count, '40603', "Seeking the Valkyra", %multiuserquests);
	BNet::Utils::preprint ($count, '40608', "The Mark", %multiuserquests);
	BNet::Utils::preprint ($count, '40613', "Maw of Souls: Retrieving the Svalnguard (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '40614', "A Feast Fit for Odyn", %multiuserquests);
	BNet::Utils::preprint ($count, '40672', "Neltharion's Lair: Presentation is Key (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '40615', "Halls of Valor: Odyn's Blessing (Mythic)", %multiuserquests);
	BNet::Utils::preprint ($count, '43528', "Planning the Assault", %multiuserquests);
	BNet::Utils::preprint ($count, '43898', "Preparing to Move", %multiuserquests);
	BNet::Utils::preprint ($count, '43531', "Into the Nighthold", %multiuserquests);
	BNet::Utils::preprint ($count, '43530', "The Nighthold: Delusions of Grandeur", %multiuserquests);
	BNet::Utils::preprint ($count, '43532', "The Nighthold: Darkness Calls", %multiuserquests);
	BNet::Utils::preprint ($count, '43533', "Balance of Power", %multiuserquests);


}

sub empoweredartifacts ($%) {
	my ($count, %multiuserquests) = @_;
	BNet::Utils::groupheader ("Empowering Artifacts");
	BNet::Utils::preprint ($count, '46744', "Greater Power for Greater Threats", %multiuserquests);
	BNet::Utils::preprint ($count, '46765', "The Broken Shore: Investigating the Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '47000', "The Council's Call", %multiuserquests);
	BNet::Utils::preprint ($count, '44782', "Away From Prying Eyes", %multiuserquests);
	BNet::Utils::preprint ($count, '44821', "In Dire Need", %multiuserquests);
	BNet::Utils::groupheader ("DPS: Archmage Xylem<div>Survival Hunter, Subtlety Rogue, Havoc Demon Hunter, Frost Death Knight, Arms Warrior</div>");
	BNet::Utils::preprint ($count, '47046', "Frost: The Thieving Apprentice <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_deathknight.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47043', "Havoc: The Thieving Apprentice <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_demonhunter.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47047', "Survival: The Thieving Apprentice <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_hunter.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47048', "Subtlety: The Thieving Apprentice <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_rogue.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44914', "Arms: The Thieving Apprentice <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warrior.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '44915', "Professionally Good Looking", %multiuserquests);
	BNet::Utils::preprint ($count, '44920', "Order of Incantations", %multiuserquests);
	BNet::Utils::preprint ($count, '44924', "The Archmage Accosted", %multiuserquests);
	BNet::Utils::preprint ($count, '46177', "A Portal Away", %multiuserquests);
	BNet::Utils::preprint ($count, '45865', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '44925', "Closing the Eye", %multiuserquests);
	BNet::Utils::preprint ($count, '45570', "In Safer Hands", %multiuserquests);
	BNet::Utils::preprint ($count, '45908', "Xylem's Gift", %multiuserquests);
	BNet::Utils::groupheader ("DPS: Fate of the Tideskorn<div>Arcane Mage, Assassination Rogue, Retribution Paladin, Enhancement Shaman, Demonology Warlock</div>");
	BNet::Utils::preprint ($count, '45482', "Arcane: Fate of the Tideskorn <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_mage.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47052', "Retribution: Fate of the Tideskorn <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_paladin.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47051', "Assassination: Fate of the Tideskorn <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_rogue.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47050', "Enhancement: Fate of the Tideskorn <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_shaman.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47049', "Demonology: Fate of the Tideskorn <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warlock.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45486', "The Reluctant Queen", %multiuserquests);
	BNet::Utils::preprint ($count, '45522', "To Silence the Bonespeakers", %multiuserquests);
	BNet::Utils::preprint ($count, '45523', "To Tame the Drekirjar", %multiuserquests);
	BNet::Utils::preprint ($count, '45524', "The Forgotten Heir", %multiuserquests);
	BNet::Utils::preprint ($count, '45525', "Unanswered Questions", %multiuserquests);
	BNet::Utils::preprint ($count, '46340', "The Gates Are Closed", %multiuserquests);
	BNet::Utils::preprint ($count, '45862', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '45526', "The God-Queen's Fury", %multiuserquests);
	BNet::Utils::preprint ($count, '45527', "Eyir's Forgiveness", %multiuserquests);
	BNet::Utils::preprint ($count, '45904', "The God-Queen's Gift", %multiuserquests);
	BNet::Utils::groupheader ("DPS: Folly of Levia Laurence<div>Feral Druid, Outlaw Rogue, Unholy Death Knight, Fury Warrior, Fire Mage, Elemental Shaman</div>");
	BNet::Utils::preprint ($count, '47057', "Unholy: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_deathknight.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47059', "Feral: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_druid.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47055', "Fire: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_mage.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47058', "Outlaw: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_rogue.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45123', "Elemental: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_shaman.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47056', "Fury: The Folly of Levia Laurence <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warrior.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45916', "The Acolyte Imperiled", %multiuserquests);
	BNet::Utils::preprint ($count, '45917', "Following the Scent", %multiuserquests);
	BNet::Utils::preprint ($count, '45125', "Dabbling in the Demonic", %multiuserquests);
	BNet::Utils::preprint ($count, '45126', "Unlikely Seduction", %multiuserquests);
	BNet::Utils::preprint ($count, '45127', "Fel-Crossed Lovers", %multiuserquests);
	BNet::Utils::preprint ($count, '45861', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '46065', "An Impossible Foe", %multiuserquests);
	BNet::Utils::preprint ($count, '45902', "The Imp Mother's Gift", %multiuserquests);
	BNet::Utils::groupheader ("DPS: Rumbling Near Feltotem<div>Discipline Priest, Windwalker Monk, Beast Mastery Hunter, Destruction Warlock</div>");
	BNet::Utils::preprint ($count, '47018', "Beast Mastery: Rumblings Near Feltotem <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_hunter.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47019', "Windwalker: Rumblings Near Feltotem <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_monk.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47020', "Discipline: Rumblings Near Feltotem <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_priest.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45560', "Destruction: Rumblings Near Feltotem <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warlock.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45564', "The Burning Birds", %multiuserquests);
	BNet::Utils::preprint ($count, '45726', "The Tainted Marsh", %multiuserquests);
	BNet::Utils::preprint ($count, '45575', "Village of the Corruptors", %multiuserquests);
	BNet::Utils::preprint ($count, '45587', "The Feltotem Menace", %multiuserquests);
	BNet::Utils::preprint ($count, '45796', "Destroying the Nest", %multiuserquests);
	BNet::Utils::preprint ($count, '45841', "A Triumphant Report", %multiuserquests);
	BNet::Utils::preprint ($count, '45842', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '45627', "Feltotem's Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '45909', "Navarrogg's Gift", %multiuserquests);
	BNet::Utils::groupheader ("DPS: Twisted Twin<div>Shadow Priest, Affliction Warlock, Marksmanship Hunter, Balance Druid, Frost Mage</div>");
	BNet::Utils::preprint ($count, '47037', "Balance: The Twisted Twin <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_druid.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47039', "Marksmanship: The Twisted Twin <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_hunter.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45182', "Frost: The Twisted Twin <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_mage.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47042', "Shadow: The Twisted Twin <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_priest.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47041', "Affliction: The Twisted Twin <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warlock.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45185', "Message from the Shadows", %multiuserquests);
	BNet::Utils::preprint ($count, '45187', "Secrets in the Underbelly", %multiuserquests);
	BNet::Utils::preprint ($count, '45188', "The Wisdom of the Council", %multiuserquests);
	BNet::Utils::preprint ($count, '45190', "Where it's Thinnest", %multiuserquests);
	BNet::Utils::preprint ($count, '45192', "Runes of Rending", %multiuserquests);
	BNet::Utils::preprint ($count, '45193', "One Step Behind", %multiuserquests);
	BNet::Utils::preprint ($count, '45866', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '46127', "Thwarting the Twins", %multiuserquests);
	BNet::Utils::preprint ($count, '45910', "Raest's Gift", %multiuserquests);
	BNet::Utils::groupheader ("Healing: Bradensbrook Investigation<div>Holy Priest, Holy Paladin, Mistweaver Monk, Restoration Druid, Restoration Shaman</div>");
	BNet::Utils::preprint ($count, '47004', "Restoration: The Bradensbrook Investigation <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_druid.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47005', "Mistweaver: The Bradensbrook Investigation <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_monk.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47006', "Holy: The Bradensbrook Investigation <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_paladin.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '46078', "Holy: The Bradensbrook Investigation <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_priest.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47003', "Restoration: The Bradensbrook Investigation <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_shaman.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '46079', "Aid on the Front Lines", %multiuserquests);
	BNet::Utils::preprint ($count, '46080', "Quieting the Spirits", %multiuserquests);
	BNet::Utils::preprint ($count, '46082', "Shadowsong's Return", %multiuserquests);
	BNet::Utils::preprint ($count, '46106', "Cutting off the Heads", %multiuserquests);
	BNet::Utils::preprint ($count, '46107', "Source of the Corruption", %multiuserquests);
	BNet::Utils::preprint ($count, '46200', "The Matter Resolved... For Now...", %multiuserquests);
	BNet::Utils::preprint ($count, '45864', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '46035', "End of the Risen Threat", %multiuserquests);
	BNet::Utils::preprint ($count, '45906', "Jarod's Gift", %multiuserquests);
	BNet::Utils::groupheader ("Tank: Aid of the Illidari<div>Blood Death Knight, Vengeance Demon Hunter, Guardian Druid, Brewmaster Monk, Protection Paladin, Protection Warrior</div>");
	BNet::Utils::preprint ($count, '47025', "Blood: Aid of the Illidari <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_deathknight.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '46314', "Vengeance: Seeking Kor'vas <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_demonhunter.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47023', "Guardian: Aid of the Illidari <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_druid.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47024', "Brewmaster: Aid of the Illidari <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_monk.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47022', "Protection: Aid of the Illidari <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_paladin.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45412', "Protection: Aid of the Illidari <img align=\"right\" src=\"https://wow.zamimg.com/images/wow/icons/small/class_warrior.jpg\">", %multiuserquests);
	BNet::Utils::preprint ($count, '45413', "Gathering Information", %multiuserquests);
	BNet::Utils::preprint ($count, '45414', "Confirming Suspicions", %multiuserquests);
	BNet::Utils::preprint ($count, '45415', "Between Worlds", %multiuserquests);
	BNet::Utils::preprint ($count, '45843', "Dark Omens", %multiuserquests);
	BNet::Utils::preprint ($count, '45863', "A Gift From the Six", %multiuserquests);
	BNet::Utils::preprint ($count, '45416', "The Highlord's Return", %multiuserquests);
	BNet::Utils::preprint ($count, '45905', "Krull's Gift", %multiuserquests);
}

sub z_110_Argus ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("110: Argus: The Assault Begins");
	BNet::Utils::preprint ($count, '47221', "The Hand of Fate <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47835', "The Hand of Fate <img src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47222', "Two If By Sea <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47867', "Two If By Sea <img src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '47223', "Light's Exodus", %multiuserquests);
	BNet::Utils::preprint ($count, '47224', "The Vindicaar", %multiuserquests);
	BNet::Utils::preprint ($count, '48440', "Into the Night", %multiuserquests);
	BNet::Utils::preprint ($count, '46938', "Alone in the Abyss", %multiuserquests);
	BNet::Utils::preprint ($count, '47589', "Righteous Fury", %multiuserquests);
	BNet::Utils::preprint ($count, '46297', "Overwhelming Power", %multiuserquests);
	BNet::Utils::preprint ($count, '48483', "A Stranger's Plea", %multiuserquests);
	BNet::Utils::preprint ($count, '47627', "Vengeance", %multiuserquests);
	BNet::Utils::preprint ($count, '47641', "Sign of Resistance", %multiuserquests);
	BNet::Utils::preprint ($count, '46732', "The Prophet's Gambit", %multiuserquests);
	BNet::Utils::preprint ($count, '46816', "Rendezvous", %multiuserquests);
	BNet::Utils::preprint ($count, '46839', "From Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '46840', "Prisoners No More", %multiuserquests);
	BNet::Utils::preprint ($count, '46841', "Threat Reduction", %multiuserquests);
	BNet::Utils::preprint ($count, '46842', "A Strike at the Heart", %multiuserquests);
	BNet::Utils::preprint ($count, '46843', "Return to the Vindicaar", %multiuserquests);
	BNet::Utils::preprint ($count, '48500', "A Moment of Respite", %multiuserquests);
	BNet::Utils::preprint ($count, '47431', "Gathering Light", %multiuserquests);
	BNet::Utils::preprint ($count, '46213', "Crystals Not Included", %multiuserquests);
	BNet::Utils::preprint ($count, '40238', "A Grim Equation", %multiuserquests);
	BNet::Utils::preprint ($count, '47541', "The Best Prevention", %multiuserquests);
	BNet::Utils::preprint ($count, '47508', "Fire at Will", %multiuserquests);
	BNet::Utils::preprint ($count, '47771', "Locating the Longshot", %multiuserquests);
	BNet::Utils::preprint ($count, '47526', "Bringing the Big Guns", %multiuserquests);
	BNet::Utils::preprint ($count, '47754', "Lightly Roasted", %multiuserquests);
	BNet::Utils::preprint ($count, '47653', "Light's Return", %multiuserquests);
	BNet::Utils::preprint ($count, '47743', "The Child of Light and Shadow", %multiuserquests);
	BNet::Utils::preprint ($count, '49143', "Essence of the Light Mother", %multiuserquests);
	BNet::Utils::preprint ($count, '47287', "The Vindicaar Matrix Core", %multiuserquests);
	BNet::Utils::preprint ($count, '48559', "An Offering of Light", %multiuserquests);
	BNet::Utils::preprint ($count, '48199', "The Burning Heart", %multiuserquests);
	BNet::Utils::preprint ($count, '48200', "Securing a Foothold", %multiuserquests);
	BNet::Utils::preprint ($count, '48201', "Reinforce Light's Purchase", %multiuserquests);
	BNet::Utils::preprint ($count, '48202', "Reinforce the Veiled Den", %multiuserquests);
	BNet::Utils::preprint ($count, '47473', "Sizing Up The Opposition", %multiuserquests);

	BNet::Utils::groupheader ("110: Argus: Dark Awakenings");
	BNet::Utils::preprint ($count, '47889', "The Speaker Calls", %multiuserquests);
	BNet::Utils::preprint ($count, '47890', "Visions of Torment", %multiuserquests);
	BNet::Utils::preprint ($count, '47891', "Dire News", %multiuserquests);
	BNet::Utils::preprint ($count, '47892', "Storming the Citadel", %multiuserquests);
	BNet::Utils::preprint ($count, '47986', "Scars of the Past", %multiuserquests);
	BNet::Utils::preprint ($count, '47987', "Preventive Measures", %multiuserquests);
	BNet::Utils::preprint ($count, '47988', "Chaos Theory", %multiuserquests);
	BNet::Utils::preprint ($count, '47991', "Dark Machinations", %multiuserquests);
	BNet::Utils::preprint ($count, '47990', "A Touch of Fel", %multiuserquests);
	BNet::Utils::preprint ($count, '47989', "Heralds of Apocalypse", %multiuserquests);
	BNet::Utils::preprint ($count, '47992', "Dawn of Justice", %multiuserquests);
	BNet::Utils::preprint ($count, '47993', "Lord of the Spire", %multiuserquests);
	BNet::Utils::preprint ($count, '47994', "Forming a Bond", %multiuserquests);
	BNet::Utils::preprint ($count, '48081', "A Floating Ruin", %multiuserquests);
	BNet::Utils::preprint ($count, '46815', "Mac'Aree, Jewel of Argus", %multiuserquests);
	BNet::Utils::preprint ($count, '46818', "Defenseless and Afraid", %multiuserquests);
	BNet::Utils::preprint ($count, '46834', "Khazaduum, First of His Name", %multiuserquests);
	BNet::Utils::preprint ($count, '47066', "Consecrating Ground", %multiuserquests);
	BNet::Utils::preprint ($count, '46941', "The Path Forward", %multiuserquests);
	BNet::Utils::preprint ($count, '47686', "Not-So-Humble Beginnings", %multiuserquests);
	BNet::Utils::preprint ($count, '47882', "Conservation of Magic", %multiuserquests);
	BNet::Utils::preprint ($count, '47688', "Invasive Species", %multiuserquests);
	BNet::Utils::preprint ($count, '47883', "The Longest Vigil", %multiuserquests);
	BNet::Utils::preprint ($count, '47689', "Gatekeeper's Challenge: Tenacity", %multiuserquests);
	BNet::Utils::preprint ($count, '47685', "Gatekeeper's Challenge: Cunning", %multiuserquests);
	BNet::Utils::preprint ($count, '47687', "Gatekeeper's Challenge: Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '47690', "The Defiler's Legacy", %multiuserquests);
	BNet::Utils::preprint ($count, '48107', "The Sigil of Awakening", %multiuserquests);

	BNet::Utils::groupheader ("110: Argus: War of Light and Shadow");
	BNet::Utils::preprint ($count, '48461', "Where They Least Expect It", %multiuserquests);
	BNet::Utils::preprint ($count, '48344', "We Have a Problem", %multiuserquests);
	BNet::Utils::preprint ($count, '47691', "A Non-Prophet Organization", %multiuserquests);
	BNet::Utils::preprint ($count, '47854', "Wrath of the Hight Exarch", %multiuserquests);
	BNet::Utils::preprint ($count, '47995', "Overt Ops", %multiuserquests);
	BNet::Utils::preprint ($count, '47853', "Flanking Maneuvers", %multiuserquests);
	BNet::Utils::preprint ($count, '48345', "Talgath's Forces", %multiuserquests);
	BNet::Utils::preprint ($count, '47855', "What Might Have Been", %multiuserquests);
	BNet::Utils::preprint ($count, '47856', "Across the Universe", %multiuserquests);
	BNet::Utils::preprint ($count, '47416', "Shadow of the Triumvirate", %multiuserquests);
	BNet::Utils::preprint ($count, '47238', "The Seat of the Triumvirate", %multiuserquests);
	BNet::Utils::preprint ($count, '40761', "Whispers from Oronaar", %multiuserquests);
	BNet::Utils::preprint ($count, '47101', "Arkhaan's Prayers", %multiuserquests);
	BNet::Utils::preprint ($count, '47180', "The Pulsing Madness", %multiuserquests);
	BNet::Utils::preprint ($count, '47100', "Arkhaan's Pain", %multiuserquests);
	BNet::Utils::preprint ($count, '47183', "Arkhaan's Plan", %multiuserquests);
	BNet::Utils::preprint ($count, '47184', "Arkhaan's Peril", %multiuserquests);
	BNet::Utils::preprint ($count, '47203', "Throwing Shade", %multiuserquests);
	BNet::Utils::preprint ($count, '47217', "Sources of Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '47218', "The Shadowguard Incursion", %multiuserquests);
	BNet::Utils::preprint ($count, '47219', "A Vessel Made Ready", %multiuserquests);
	BNet::Utils::preprint ($count, '47220', "A Beacon in the Dark", %multiuserquests);
	BNet::Utils::preprint ($count, '48560', "An Offering of Shadow", %multiuserquests);
	BNet::Utils::preprint ($count, '47654', "Seat of the Triumvirate: The Crest of Knowledge", %multiuserquests);

	BNet::Utils::groupheader ("110: Argus: Side Chain: Class Hall");
	BNet::Utils::preprint ($count, '48460', "The Wranglers", %multiuserquests);
	BNet::Utils::preprint ($count, '47967', "An Argus Roper", %multiuserquests);
	BNet::Utils::preprint ($count, '48455', "Duskcloak Problem", %multiuserquests);
	BNet::Utils::preprint ($count, '48453', "Strike Back", %multiuserquests);
	BNet::Utils::preprint ($count, '48544', "Woah, Nelly!", %multiuserquests);
	BNet::Utils::preprint ($count, '48441', "Remnants of Darkfall Ridge", %multiuserquests);
	BNet::Utils::preprint ($count, '48442', "Nath'raxas Hold: Preparations", %multiuserquests);
	BNet::Utils::preprint ($count, '48443', "Nath'raxas Hold: Rescue Mission", %multiuserquests);
	BNet::Utils::preprint ($count, '48445', "The Ruins of Oronaar", %multiuserquests);
	BNet::Utils::preprint ($count, '48446', "Relics of the Ancient Eredar", %multiuserquests);
	BNet::Utils::preprint ($count, '48654', "Beneath Oronaar", %multiuserquests);
	BNet::Utils::preprint ($count, '48447', "Shadowguard Dispersion", %multiuserquests);
	BNet::Utils::preprint ($count, '48911', "Void Inoculation", %multiuserquests);
	BNet::Utils::preprint ($count, '48448', "Hindering the Legion War Machine", %multiuserquests);
	BNet::Utils::preprint ($count, '48600', "Take the Edge Off", %multiuserquests);
	BNet::Utils::preprint ($count, '48912', "Supplying the Antoran Campaign", %multiuserquests);
	BNet::Utils::preprint ($count, '48601', "Felfire Shattering", %multiuserquests);

	BNet::Utils::groupheader ("110: Argus: Side Chain: Invasion Points");
	BNet::Utils::preprint ($count, '48461', "Where They Least Expect It", %multiuserquests);
	BNet::Utils::preprint ($count, '48513', "Invasion Point Offensive", %multiuserquests);
	BNet::Utils::preprint ($count, '48605', "Commander's Downfall", %multiuserquests);

	BNet::Utils::groupheader ("110: Argus: Side Chain: The Fel Heart of Argus");
	BNet::Utils::preprint ($count, '47102', "The Mysterious Missive", %multiuserquests);
	BNet::Utils::preprint ($count, '47554', "Intercepting the Legion's Plans", %multiuserquests);
	BNet::Utils::preprint ($count, '47104', "Imprisoned Inquisitor", %multiuserquests);
	BNet::Utils::preprint ($count, '47134', "Foiling the Legion's Jailbreak", %multiuserquests);
	BNet::Utils::preprint ($count, '47182', "Long Overdue", %multiuserquests);

}

1;
