package BNet::Quests_EK;

use strict;
use warnings;




sub sz_1_10_belf_eversong ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Eversong Woods/Blood Elf");
	BNet::Utils::preprint ($count, '8325', "Reclaiming Sunstrider Isle", %multiuserquests);
	BNet::Utils::preprint ($count, '8326', "Unfortunate Measures", %multiuserquests);
	BNet::Utils::preprint ($count, '8327', "Report to Lanthan Perilon", %multiuserquests);
	BNet::Utils::preprint ($count, '8345', "The Shrine of Dath\'Remar", %multiuserquests);
	BNet::Utils::preprint ($count, '8346', "Thirst Unending", %multiuserquests);
	BNet::Utils::preprint ($count, '8336', "A Fistful of Slivers", %multiuserquests);
	BNet::Utils::preprint ($count, '8330', "Solanian\'s Belongings", %multiuserquests);
	BNet::Utils::preprint ($count, '8334', "Aggression", %multiuserquests);
	BNet::Utils::preprint ($count, '8335', "Felendren the Banished", %multiuserquests);
	BNet::Utils::preprint ($count, '8338', "Tainted Arcane Sliver", %multiuserquests);
	BNet::Utils::preprint ($count, '8347', "Aiding the Outrunners", %multiuserquests);
	BNet::Utils::preprint ($count, '9704', "Slain by the Wretched", %multiuserquests);
	BNet::Utils::preprint ($count, '9705', "Package Recovery", %multiuserquests);
	BNet::Utils::preprint ($count, '8350', "Completing the Delivery", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Falconwing Square");
	BNet::Utils::preprint ($count, '8463', "Unstable Mana Crystals", %multiuserquests);
	BNet::Utils::preprint ($count, '8468', "Wanted: Thaelis the Hungerer", %multiuserquests);
	BNet::Utils::preprint ($count, '9352', "Darnassian Intrusions", %multiuserquests);
	BNet::Utils::preprint ($count, '8482', "Incriminating Documents", %multiuserquests);
	BNet::Utils::preprint ($count, '8483', "The Dwarven Spy", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: West Sanctum");
	BNet::Utils::preprint ($count, '8472', "Major Malfunction", %multiuserquests);
	BNet::Utils::preprint ($count, '8895', "Delivery to the North Sanctum", %multiuserquests);
	BNet::Utils::preprint ($count, '9119', "Malfunction at the West Sanctum", %multiuserquests);
	BNet::Utils::preprint ($count, '8486', "Arcane Instability", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Roadside Ambush");
	BNet::Utils::preprint ($count, '9035', "Roadside Ambush", %multiuserquests);
	BNet::Utils::preprint ($count, '9062', "Soaked Pages", %multiuserquests);
	BNet::Utils::preprint ($count, '9064', "Taking the Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '9066', "Swift Discipline", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Breadcrumb to Fairbreeze Village");
	BNet::Utils::preprint ($count, '9256', "Fairbreeze Village", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Fairbreeze Village");
	BNet::Utils::preprint ($count, '8491', "Pelt Collection", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Flight Points");
	BNet::Utils::preprint ($count, '9130', "Goods from Silvermoon City", %multiuserquests);
	BNet::Utils::preprint ($count, '9133', "Fly to Silvermoon City", %multiuserquests);
	BNet::Utils::preprint ($count, '8475', "The Dead Scar", %multiuserquests);
	BNet::Utils::preprint ($count, '9134', "Skymistress Gloaming", %multiuserquests);
	BNet::Utils::preprint ($count, '9135', "Return to Sathiel", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Sunsail Anchorage");
	BNet::Utils::preprint ($count, '8892', "Situation at Sunsail Anchorage", %multiuserquests);
	BNet::Utils::preprint ($count, '8886', "Grimscale Pirates!", %multiuserquests);
	BNet::Utils::preprint ($count, '8480', "Lost Armaments", %multiuserquests);
	BNet::Utils::preprint ($count, '9076', "Wretched Ringleader", %multiuserquests);
	BNet::Utils::preprint ($count, '8887', "Captain Kelisendra\'s Lost Rutters", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Murlocs");
	BNet::Utils::preprint ($count, '8884', "Fish Heads, Fish Heads...", %multiuserquests);
	BNet::Utils::preprint ($count, '8885', "The Ring of Mmmrrrggglll", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Saltheril\'s Haven");
	BNet::Utils::preprint ($count, '9395', "Saltheril\'s Haven", %multiuserquests);
	BNet::Utils::preprint ($count, '9067', "The Party Never Ends", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Defending Fairbreeze Village");
	BNet::Utils::preprint ($count, '9358', "Ranger Sareyn", %multiuserquests);
	BNet::Utils::preprint ($count, '9252', "Defending Fairbreeze Village", %multiuserquests);
	BNet::Utils::preprint ($count, '9253', "Runewarden Deryan", %multiuserquests);
	BNet::Utils::preprint ($count, '8490', "Powering our Defenses", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: East Sanctum");
	BNet::Utils::preprint ($count, '9254', "The Wayward Apprentice", %multiuserquests);
	BNet::Utils::preprint ($count, '8487', "Corrupted Soil", %multiuserquests);
	BNet::Utils::preprint ($count, '8488', "Unexpected Results", %multiuserquests);
	BNet::Utils::preprint ($count, '9255', "Research Notes", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Scorched Grove");
	BNet::Utils::preprint ($count, '9258', "The Scorched Grove", %multiuserquests);
	BNet::Utils::preprint ($count, '8473', "A Somber Task", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Farstrider Retreat");
	BNet::Utils::preprint ($count, '9359', "Farstrider Retreat", %multiuserquests);
	BNet::Utils::preprint ($count, '8476', "Amani Encroachment", %multiuserquests);
	BNet::Utils::preprint ($count, '8477', "The Spearcrafter's Hammer", %multiuserquests);
	BNet::Utils::preprint ($count, '8479', "Zul\'Marosh", %multiuserquests);
	BNet::Utils::preprint ($count, '9360', "Amani Invasion", %multiuserquests);
	BNet::Utils::preprint ($count, '9363', "Warning Fairbreeze Village", %multiuserquests);
	BNet::Utils::groupheader ("Eversong Woods: Duskwither Spire");
	BNet::Utils::preprint ($count, '8888', "The Magister\'s Apprentice", %multiuserquests);
	BNet::Utils::preprint ($count, '8889', "Deactivating the Spire", %multiuserquests);
	BNet::Utils::preprint ($count, '9394', "Where's Wyllithen?", %multiuserquests);
	BNet::Utils::preprint ($count, '8894', "Cleaning up the Grounds", %multiuserquests);
	BNet::Utils::preprint ($count, '8891', "Abandoned Investigations", %multiuserquests);
	BNet::Utils::preprint ($count, '8890', "Word from the Spire", %multiuserquests);
}


sub z_10_ghostlands ($%) {
	my ($count, %multiuserquests) = @_;


	BNet::Utils::groupheader ("Ghostlands: To the Ghostlands");
	BNet::Utils::preprint ($count, '28560', "Warchief's Command: Ghostlands!", %multiuserquests);
	BNet::Utils::preprint ($count, '9144', "Missing in the Ghostlands", %multiuserquests);
	BNet::Utils::preprint ($count, '9147', "The Fallen Courier", %multiuserquests);
	BNet::Utils::preprint ($count, '9148', "Delivery to Tranquillien", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Tranquillen");
	BNet::Utils::preprint ($count, '9327', "The Forsaken", %multiuserquests);
	BNet::Utils::preprint ($count, '9329', "The Forsaken", %multiuserquests);
	BNet::Utils::preprint ($count, '9758', "Return to Arcanist Vandril", %multiuserquests);
	BNet::Utils::preprint ($count, '9138', "Suncrown Village", %multiuserquests);
	BNet::Utils::preprint ($count, '9139', "Goldenmist Village", %multiuserquests);
	BNet::Utils::preprint ($count, '9140', "Windrunner Village", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Night Elf Interferance");
	BNet::Utils::preprint ($count, '9160', "Investigate An\'daroth", %multiuserquests);
	BNet::Utils::preprint ($count, '9163', "Into Occupied Territory", %multiuserquests);
	BNet::Utils::preprint ($count, '9166', "Deliver the Plans to An\'telas", %multiuserquests);
	BNet::Utils::preprint ($count, '9169', "Deactivate An\'owyn", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Suncrown Village");
	BNet::Utils::preprint ($count, '9315', "Anok\'suten", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Farstriders");
	BNet::Utils::preprint ($count, '9145', "Help Ranger Valanna!", %multiuserquests);
	BNet::Utils::preprint ($count, '9143', "Dealing with Zeb\'Sora", %multiuserquests);
	BNet::Utils::preprint ($count, '9146', "Report to Captain Helios", %multiuserquests);
	BNet::Utils::preprint ($count, '9158', "Bearers of the Plague", %multiuserquests);
	BNet::Utils::preprint ($count, '9276', "Attack on Zeb\'Tela", %multiuserquests);
	BNet::Utils::preprint ($count, '9214', "Shadowpine Weaponry", %multiuserquests);
	BNet::Utils::preprint ($count, '9157', "Forgotten Rituals", %multiuserquests);
	BNet::Utils::preprint ($count, '9215', "Bring Me Kel\'gash\'s Head!", %multiuserquests);
	BNet::Utils::preprint ($count, '9174', "Vanquishing Aquantion", %multiuserquests);
	BNet::Utils::preprint ($count, '9274', "Spirits of the Drowned", %multiuserquests);
	BNet::Utils::preprint ($count, '9159', "Curbing the Plague", %multiuserquests);
	BNet::Utils::preprint ($count, '9275', "A Little Dash of Seasoning", %multiuserquests);
	BNet::Utils::preprint ($count, '9277', "Assault on Zeb\'Nowa", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Amani Catacombs");
	BNet::Utils::preprint ($count, '9193', "Investigate the Amani Catacombs", %multiuserquests);
	BNet::Utils::preprint ($count, '9199', "Troll Juju", %multiuserquests);
	BNet::Utils::preprint ($count, '9212', "Escape from the Catacombs", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Windrunner Village");
	BNet::Utils::preprint ($count, '9173', "Retaking Windrunner Spire", %multiuserquests);
	BNet::Utils::preprint ($count, '9175', "The Lady\'s Necklace", %multiuserquests);
	BNet::Utils::preprint ($count, '9180', "Journey to Undercity", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Dead Scar");
	BNet::Utils::preprint ($count, '9155', "Down the Dead Scar", %multiuserquests);
	BNet::Utils::preprint ($count, '9216', "Rotting Hearts", %multiuserquests);
	BNet::Utils::preprint ($count, '9218', "Spinal Dust", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Deatholme");
	BNet::Utils::preprint ($count, '9282', "The Farstrider Enclave", %multiuserquests);
	BNet::Utils::preprint ($count, '9161', "The Traitor\'s Shadow", %multiuserquests);
	BNet::Utils::preprint ($count, '9162', "Hints of the Past", %multiuserquests);
	BNet::Utils::preprint ($count, '9172', "Report to Magister Kaendris", %multiuserquests);
	BNet::Utils::preprint ($count, '9281', "Clearing the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '9151', "The Sanctum of the Sun", %multiuserquests);
	BNet::Utils::preprint ($count, '9220', "War on Deatholme", %multiuserquests);
	BNet::Utils::preprint ($count, '9170', "Dar\'Khan\'s Lieutenants", %multiuserquests);
	BNet::Utils::preprint ($count, '9176', "The Twin Ziggurats", %multiuserquests);
	BNet::Utils::preprint ($count, '9877', "A Restorative Draught", %multiuserquests);
	BNet::Utils::preprint ($count, '9164', "Captives at Deatholme", %multiuserquests);
	BNet::Utils::preprint ($count, '9167', "The Traitor\'s Destruction", %multiuserquests);
	BNet::Utils::preprint ($count, '9328', "Hero of the Sin'dorei", %multiuserquests);
	BNet::Utils::preprint ($count, '9811', "Friend of the Sin'dorei", %multiuserquests);
	BNet::Utils::preprint ($count, '9621', "Envoy to the Horde", %multiuserquests);
	BNet::Utils::preprint ($count, '9812', "Envoy to the Horde", %multiuserquests);
	BNet::Utils::preprint ($count, '9626', "Meeting the Orcs", %multiuserquests);
	BNet::Utils::preprint ($count, '9813', "Meeting the Orcs", %multiuserquests);
	BNet::Utils::groupheader ("Ghostlands: Miscellaneous");
	BNet::Utils::preprint ($count, '9150', "Salvaging the Past", %multiuserquests);
	BNet::Utils::preprint ($count, '9156', "Wanted: Knucklerot and Luzran", %multiuserquests);
	BNet::Utils::preprint ($count, '9171', "Culinary Crunch", %multiuserquests);
	BNet::Utils::preprint ($count, '9192', "Trouble at the Underlight Mines", %multiuserquests);
	BNet::Utils::preprint ($count, '9207', "Underlight Ore Samples", %multiuserquests);
	BNet::Utils::preprint ($count, '9149', "The Plagued Coast", %multiuserquests);
	BNet::Utils::preprint ($count, '9152', "Tomber's Supplies", %multiuserquests);


}


sub z_30_35_Hinterlands ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("30: Arathi Highlands: <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '26139', "Into Arathi", %multiuserquests);
	BNet::Utils::preprint ($count, '28573', "Hero's Call: Arathi Highlands!", %multiuserquests);
	BNet::Utils::preprint ($count, '26943', "Home Sweet Gnome", %multiuserquests);
	BNet::Utils::preprint ($count, '26024', "Wanted! Marez Cowl", %multiuserquests);
	BNet::Utils::preprint ($count, '26079', "Wanted! Otto and Falconcrest", %multiuserquests);
	BNet::Utils::preprint ($count, '26093', "Northfold Manor", %multiuserquests);
	BNet::Utils::preprint ($count, '26095', "Stromgarde Badges", %multiuserquests);
	BNet::Utils::groupheader ("Wand Over Fist <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '26035', "Worth Its Weight in Gold", %multiuserquests);
	BNet::Utils::preprint ($count, '26036', "Wand over Fist", %multiuserquests);
	BNet::Utils::preprint ($count, '26037', "Trelane's Defenses", %multiuserquests);
	BNet::Utils::preprint ($count, '26038', "Attack on the Tower", %multiuserquests);
	BNet::Utils::groupheader ("Quae and Kinelory <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '26113', "Quae and Kinelory", %multiuserquests);
	BNet::Utils::preprint ($count, '26110', "Just Like Old Times", %multiuserquests);
	BNet::Utils::preprint ($count, '26114', "Quae Trusts You", %multiuserquests);
	BNet::Utils::preprint ($count, '26116', "Kinelory Strikes", %multiuserquests);
	BNet::Utils::preprint ($count, '26117', "For Southshore", %multiuserquests);
	BNet::Utils::groupheader ("Pirates of Blackwater <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '26336', "Shakes O'Breen", %multiuserquests);
	BNet::Utils::preprint ($count, '26050', "Goggle Boggle", %multiuserquests);
	BNet::Utils::preprint ($count, '26055', "Drowned Sorrows", %multiuserquests);
	BNet::Utils::preprint ($count, '26051', "Sunken Treasure", %multiuserquests);
	BNet::Utils::preprint ($count, '26052', "Speak to Shakes", %multiuserquests);
	BNet::Utils::preprint ($count, '26628', "Death From Below", %multiuserquests);
	BNet::Utils::groupheader ("The Princess Trapped <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '26341', "The Stone Shards", %multiuserquests);
	BNet::Utils::preprint ($count, '26039', "The Princess Trapped", %multiuserquests);
	BNet::Utils::preprint ($count, '26041', "Stones of Binding", %multiuserquests);
	BNet::Utils::preprint ($count, '26042', "Breaking the Keystone", %multiuserquests);
	BNet::Utils::preprint ($count, '26346', "Myzrael's Tale", %multiuserquests);
	BNet::Utils::preprint ($count, '26049', "The Princess Unleashed", %multiuserquests);
	BNet::Utils::groupheader ("30: Arathi Highlands: <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '28572', "Warchief's Command: Arathi Highlands!", %multiuserquests);
	BNet::Utils::preprint ($count, '28619', "Warchief's Command: Arathi Highlands!", %multiuserquests);
	BNet::Utils::preprint ($count, '26428', "To Steal From Thieves", %multiuserquests);
	BNet::Utils::preprint ($count, '26053', "Clearing the Highlands", %multiuserquests);
	BNet::Utils::preprint ($count, '26027', "Call to Arms", %multiuserquests);
	BNet::Utils::preprint ($count, '26029', "The Real Threat", %multiuserquests);
	BNet::Utils::preprint ($count, '26022', "First Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '26023', "The Forsaken Trollbane", %multiuserquests);
	BNet::Utils::preprint ($count, '26030', "Sigil of Strom", %multiuserquests);
	BNet::Utils::preprint ($count, '26025', "The Traitor Orc", %multiuserquests);
	BNet::Utils::preprint ($count, '26031', "Sigil of Thoradin", %multiuserquests);
	BNet::Utils::preprint ($count, '26032', "Sigil of Arathor", %multiuserquests);
	BNet::Utils::preprint ($count, '26033', "Trol'kalar", %multiuserquests);
	BNet::Utils::preprint ($count, '26081', "Alina's Reward", %multiuserquests);
	BNet::Utils::preprint ($count, '26084', "Hammerfall", %multiuserquests);
	BNet::Utils::groupheader ("Hammerfall");
	BNet::Utils::preprint ($count, '26107', "Raising Spirits", %multiuserquests);
	BNet::Utils::preprint ($count, '26108', "Guile of the Raptor", %multiuserquests);
	BNet::Utils::preprint ($count, '26429', "Crush the Witherbark", %multiuserquests);
	BNet::Utils::groupheader ("Pirates of Blackwater <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '26083', "Hello Lolo", %multiuserquests);
	BNet::Utils::preprint ($count, '26050', "Goggle Boggle", %multiuserquests);
	BNet::Utils::preprint ($count, '26055', "Drowned Sorrows", %multiuserquests);
	BNet::Utils::preprint ($count, '26051', "Sunken Treasure", %multiuserquests);
	BNet::Utils::preprint ($count, '26052', "Speak to Shakes", %multiuserquests);
	BNet::Utils::preprint ($count, '26628', "Death From Below", %multiuserquests);
	BNet::Utils::groupheader ("The Princess Trapped <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '26909', "The Stone Shards", %multiuserquests);
	BNet::Utils::preprint ($count, '26039', "The Princess Trapped", %multiuserquests);
	BNet::Utils::preprint ($count, '26041', "Stones of Binding", %multiuserquests);
	BNet::Utils::preprint ($count, '26042', "Breaking the Keystone", %multiuserquests);
	BNet::Utils::preprint ($count, '26911', "Myzrael's Tale", %multiuserquests);
	BNet::Utils::preprint ($count, '26912', "The Princess Unleashed", %multiuserquests);
}

1;
