package BNet::Quests_BC;

use strict;
use warnings;

sub z_58_63_hellfire_peninsula ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("58: Hellfire Peninsula <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '28705', "Warchief's Command: Outland!", %multiuserquests);
	BNet::Utils::preprint ($count, '9407', "Through the Dark Portal", %multiuserquests);
	BNet::Utils::preprint ($count, '10120', "Arrival in Outland", %multiuserquests);
	BNet::Utils::preprint ($count, '10289', "Journey to Thrallmar", %multiuserquests);
	BNet::Utils::preprint ($count, '10291', "Report to Nazgrel", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar: Initial <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10121', "Eradicate the Burning Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '10123', "Felspark Ravine", %multiuserquests);
	BNet::Utils::preprint ($count, '10124', "Forward Base: Reaver's Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '10208', "Disrupt Their Reinforcements", %multiuserquests);
	BNet::Utils::preprint ($count, '10129', "Mission: Gateways Murketh and Shaadraz", %multiuserquests);
	BNet::Utils::preprint ($count, '10162', "Mission: The Abyssal Shelf", %multiuserquests);
	BNet::Utils::preprint ($count, '10388', "Return to Thrallmar", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10086', "I Work... For the Horde!", %multiuserquests);
	BNet::Utils::preprint ($count, '10087', "Burn It Up... For the Horde!", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Thrallmar PvP <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10349', "Hellfire Fortifications", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Mag'har <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9400', "The Assassin", %multiuserquests);
	BNet::Utils::preprint ($count, '9401', "A Strange Weapon", %multiuserquests);
	BNet::Utils::preprint ($count, '9405', "The Warchief's Mandate", %multiuserquests);
	BNet::Utils::preprint ($count, '9410', "A Spirit Guide", %multiuserquests);
	BNet::Utils::preprint ($count, '9406', "The Mag'har", %multiuserquests);
	BNet::Utils::preprint ($count, '9442', "A Debilitating Sickness (Obsolete)", %multiuserquests);
	BNet::Utils::preprint ($count, '9447', "Administering the Salve (Obsolete)", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Fel Orc Blood <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10450', "Bonechewer Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '10449', "Apothecary Zelana", %multiuserquests);
	BNet::Utils::preprint ($count, '10242', "Spinebreaker Post", %multiuserquests);
	BNet::Utils::preprint ($count, '10538', "Boiling Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '10835', "Apothecary Antonivich", %multiuserquests);
	BNet::Utils::preprint ($count, '10864', "A Burden of Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '10838', "The Demoniac Scryer", %multiuserquests);
	BNet::Utils::preprint ($count, '10875', "Report to Nazgrel", %multiuserquests);
	BNet::Utils::preprint ($count, '10876', "The Foot of the Citadel", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Forge Camp: Mageddon <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10390', "Forge Camp: Mageddon", %multiuserquests);
	BNet::Utils::preprint ($count, '10391', "Cannons of Rage", %multiuserquests);
	BNet::Utils::preprint ($count, '10392', "Doorway to the Abyss", %multiuserquests);
	BNet::Utils::preprint ($count, '10389', "The Agony and the Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '10136', "Cruel's Intentions", %multiuserquests);
	BNet::Utils::preprint ($count, '10393', "Vile Plans", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Honor the Fallen <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10220', "Make Them Listen", %multiuserquests);
	BNet::Utils::preprint ($count, '10229', "Decipher the Tome", %multiuserquests);
	BNet::Utils::preprint ($count, '10230', "The Battle Horn", %multiuserquests);
	BNet::Utils::preprint ($count, '10250', "Bloody Vengeance", %multiuserquests);
	BNet::Utils::preprint ($count, '10258', "Honor the Fallen", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Ogath the Mad <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10278', "The Warp Rifts", %multiuserquests);
	BNet::Utils::preprint ($count, '10294', "Void Ridge", %multiuserquests);
	BNet::Utils::preprint ($count, '10295', "From the Abyss", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Spinebreaker Post: Zeth'gor <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10792', "Zeth'Gor Must Burn!", %multiuserquests);
	BNet::Utils::preprint ($count, '10809', "Wanted: Worg Master Kruush", %multiuserquests);
	BNet::Utils::preprint ($count, '10813', "The Eyes of Grillok", %multiuserquests);
	BNet::Utils::preprint ($count, '10834', "Grillok \"Darkeye\"", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Zeppelin <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9345', "Preparing the Salve", %multiuserquests);
	BNet::Utils::preprint ($count, '10213', "Investigate the Crash", %multiuserquests);
	BNet::Utils::preprint ($count, '10161', "In Case of Emergency...", %multiuserquests);
	BNet::Utils::preprint ($count, '9351', "Voidwalkers Gone Wild", %multiuserquests);
	BNet::Utils::preprint ($count, '9349', "Ravager Egg Roundup", %multiuserquests);
	BNet::Utils::preprint ($count, '9361', "Helboar, the Other White Meat", %multiuserquests);
	BNet::Utils::preprint ($count, '9356', "Smooth as Butter", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9375', "The Road to Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9498', "Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9499', "Falcon Watch", %multiuserquests);
	BNet::Utils::preprint ($count, '9340', "The Great Fissure", %multiuserquests);
	BNet::Utils::preprint ($count, '9391', "Marking the Path", %multiuserquests);
	BNet::Utils::preprint ($count, '9376', "A Pilgrim's Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '9381', "Trueflight Arrows", %multiuserquests);
	BNet::Utils::preprint ($count, '9466', "Wanted: Blacktalon the Savage", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch: Arelion's Mistress <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '9374', "Arelion's Journal", %multiuserquests);
	BNet::Utils::preprint ($count, '10286', "Arelion's Secret", %multiuserquests);
	BNet::Utils::preprint ($count, '10287', "The Mistress Revealed", %multiuserquests);
	BNet::Utils::preprint ($count, '9483', "Life's Finer Pleasures", %multiuserquests);
	BNet::Utils::preprint ($count, '9472', "Arelion's Mistress", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Falcon Watch: Miscellaneou <img src=\"http://wow.zamimg.com/images/icons/horde.png\">s");
	BNet::Utils::preprint ($count, '9397', "Birds of a Feather", %multiuserquests);
	BNet::Utils::preprint ($count, '9366', "In Need of Felblood", %multiuserquests);
	BNet::Utils::preprint ($count, '9370', "The Cleansing Must Be Stopped", %multiuserquests);
	BNet::Utils::preprint ($count, '9387', "Source of the Corruption", %multiuserquests);
	BNet::Utils::preprint ($count, '9396', "Magic of the Arakkoa", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Cenarion Post <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10442', "Helping the Cenarion Post", %multiuserquests);
	BNet::Utils::preprint ($count, '9373', "Missing Missive", %multiuserquests);
	BNet::Utils::preprint ($count, '9372', "Demonic Contamination", %multiuserquests);
	BNet::Utils::preprint ($count, '10255', "Testing the Antidote", %multiuserquests);
	BNet::Utils::preprint ($count, '10159', "Keep Thornfang Hill Clear!", %multiuserquests);
	BNet::Utils::preprint ($count, '10132', "Colossal Menace", %multiuserquests);
	BNet::Utils::preprint ($count, '10134', "Crimson Crystal Clue", %multiuserquests);
	BNet::Utils::preprint ($count, '10349', "The Earthbinder", %multiuserquests);
	BNet::Utils::preprint ($count, '10351', "Natural Remedies", %multiuserquests);
	BNet::Utils::preprint ($count, '9912', "The Cenarion Expedition", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Neutral quest chains");
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Outland Sucks!");
	BNet::Utils::preprint ($count, '10236', "Outland Sucks!", %multiuserquests);
	BNet::Utils::preprint ($count, '10238', "How to Serve Goblins", %multiuserquests);
	BNet::Utils::preprint ($count, '10629', "Shizz Work", %multiuserquests);
	BNet::Utils::preprint ($count, '10630', "Beneath Thrallmar", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Dreghood");
	BNet::Utils::preprint ($count, '10403', "Naladu", %multiuserquests);
	BNet::Utils::preprint ($count, '10367', "A Traitor Among Us", %multiuserquests);
	BNet::Utils::preprint ($count, '10368', "The Dreghood Elders", %multiuserquests);
	BNet::Utils::preprint ($count, '10369', "Arzeth's Demise", %multiuserquests);
	BNet::Utils::groupheader ("58: Hellfire Peninsula: Miscellaneous");
	BNet::Utils::preprint ($count, '9418', "Avruu's Orb", %multiuserquests);

}

sub z_60_64_zangarmarsh ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Zangarmarsh: Cenarion Refuge");
	BNet::Utils::preprint ($count, '9912', "The Cenarion Expedition", %multiuserquests);
	BNet::Utils::preprint ($count, '39180', "Warchief's Command: Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9895', "The Dying Balance", %multiuserquests);
	BNet::Utils::preprint ($count, '9747', "The Umbrafen Tribe", %multiuserquests);
	BNet::Utils::preprint ($count, '9788', "A Damp, Dark Place", %multiuserquests);
	BNet::Utils::preprint ($count, '10096', "Saving the Sporeloks", %multiuserquests);
	BNet::Utils::preprint ($count, '9894', "Safeguarding the Watchers", %multiuserquests);
	BNet::Utils::preprint ($count, '9716', "Disturbance at Umbrafen Lake", %multiuserquests);
	BNet::Utils::preprint ($count, '9718', "As the Crow Flies", %multiuserquests);
	BNet::Utils::preprint ($count, '9720', "Balance Must Be Preserved", %multiuserquests);
	BNet::Utils::preprint ($count, '9731', "Drain Schematics", %multiuserquests);
	BNet::Utils::preprint ($count, '9724', "Warning the Cenarion Circle", %multiuserquests);
	BNet::Utils::preprint ($count, '9732', "Return to the Marsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9876', "Failed Incursion (Obsolete)", %multiuserquests);
	BNet::Utils::preprint ($count, '9817', "Leader of the Bloodscale", %multiuserquests);
	BNet::Utils::preprint ($count, '9802', "Plants of Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9697', "Watcher Leesa'oh", %multiuserquests);
	BNet::Utils::preprint ($count, '9957', "What's Wrong at Cenarion Thicket?", %multiuserquests);
	BNet::Utils::preprint ($count, '9785', "Blessings of the Ancients", %multiuserquests);
	BNet::Utils::preprint ($count, '9730', "Leader of the Darkcrest", %multiuserquests);
	BNet::Utils::preprint ($count, '9778', "Warden Hamoot", %multiuserquests);
	BNet::Utils::preprint ($count, '9728', "A Warm Welcome", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Cenarion Watchpost");
	BNet::Utils::preprint ($count, '9701', "Observing the Sporelings", %multiuserquests);
	BNet::Utils::preprint ($count, '9702', "A Question of Gluttony", %multiuserquests);
	BNet::Utils::preprint ($count, '9708', "Familiar Fungi", %multiuserquests);
	BNet::Utils::preprint ($count, '9709', "Stealing Back the Mushrooms", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Sporeggar");
	BNet::Utils::preprint ($count, '9806', "Fertile Spores", %multiuserquests);
	BNet::Utils::preprint ($count, '9808', "Glowcap Mushrooms", %multiuserquests);
	BNet::Utils::preprint ($count, '9726', "Now That We're Friends...", %multiuserquests);
	BNet::Utils::preprint ($count, '9729', "Fhwoor Smash!", %multiuserquests);
	BNet::Utils::preprint ($count, '9739', "The Sporelings' Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '9743', "Natural Enemies", %multiuserquests);
	BNet::Utils::preprint ($count, '9919', "Sporeggar", %multiuserquests);
	BNet::Utils::preprint ($count, '9911', "The Count of the Marshes", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Swamprat Post (Horde)");
	BNet::Utils::preprint ($count, '9899', "A Job Undone", %multiuserquests);
	BNet::Utils::preprint ($count, '9773', "No More Mushrooms!", %multiuserquests);
	BNet::Utils::preprint ($count, '9770', "Menacing Marshfangs", %multiuserquests);
	BNet::Utils::preprint ($count, '9898', "Nothin' Says Lovin' Like a Big Stinger", %multiuserquests);
	BNet::Utils::preprint ($count, '9796', "News from Zangarmarsh", %multiuserquests);
	BNet::Utils::preprint ($count, '9775', "Report to Shadow Hunter Denjai", %multiuserquests);
	BNet::Utils::preprint ($count, '9769', "There's No Explanation for Fashion", %multiuserquests);
	BNet::Utils::preprint ($count, '9774', "Thick Hydra Scales", %multiuserquests);
	BNet::Utils::preprint ($count, '9771', "Searching for Scout Jyoba", %multiuserquests);
	BNet::Utils::preprint ($count, '9772', "Jyoba's Report", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Zabra'jin (Horde)");
	BNet::Utils::preprint ($count, '10105', "News for Rakoria", %multiuserquests);
	BNet::Utils::preprint ($count, '9846', "Spirits of the Feralfen", %multiuserquests);
	BNet::Utils::preprint ($count, '9847', "A Spirit Ally?", %multiuserquests);
	BNet::Utils::preprint ($count, '9845', "Angling to Beat the Competition", %multiuserquests);
	BNet::Utils::preprint ($count, '9904', "Pursuing Terrorclaw", %multiuserquests);
	BNet::Utils::preprint ($count, '9903', "The Biggest of Them All", %multiuserquests);
	BNet::Utils::preprint ($count, '9814', "Burstcap Mushrooms, Mon!", %multiuserquests);
	BNet::Utils::preprint ($count, '9816', "Have You Ever Seen One of These?", %multiuserquests);
	BNet::Utils::preprint ($count, '9797', "Reinforcements for Garadar", %multiuserquests);
	BNet::Utils::preprint ($count, '9795', "The Ogre Threat", %multiuserquests);
	BNet::Utils::preprint ($count, '9841', "Stinging the Stingers", %multiuserquests);
	BNet::Utils::preprint ($count, '9842', "The Sharpest Blades", %multiuserquests);
	BNet::Utils::preprint ($count, '9820', "WANTED: Boss Grog'ak", %multiuserquests);
	BNet::Utils::preprint ($count, '9822', "Impending Attack", %multiuserquests);
	BNet::Utils::preprint ($count, '9823', "Us or Them", %multiuserquests);
	BNet::Utils::preprint ($count, '10117', "Wanted: Chieftain Mummaki", %multiuserquests);
	BNet::Utils::preprint ($count, '10118', "Message to the Daggerfen", %multiuserquests);
	BNet::Utils::preprint ($count, '9828', "Withered Basidium", %multiuserquests);
	BNet::Utils::groupheader ("Zangarmarsh: Umbrafen Village");
	BNet::Utils::preprint ($count, '9752', "Escape from Umbrafen", %multiuserquests);
}


sub z_62_65_terokkar_forest ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("62: Terrokar Forest");
	BNet::Utils::preprint ($count, '39188', "Hero's Call: Terokkar Forest <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '39182', "Warchief's Command: Terokkar Forest <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Shattrath");
	BNet::Utils::preprint ($count, '10210', "A'dal", %multiuserquests);
	BNet::Utils::preprint ($count, '10211', "City of Light", %multiuserquests);
	BNet::Utils::preprint ($count, '10037', "Rather Be Fishin'", %multiuserquests);
	BNet::Utils::preprint ($count, '10917', "The Outcast's Plight", %multiuserquests);
	BNet::Utils::preprint ($count, '10180', "Can't Stay Away", %multiuserquests);
	BNet::Utils::preprint ($count, '10847', "The Eyes of Skettis", %multiuserquests);
	BNet::Utils::preprint ($count, '10849', "Seek Out Kirrik", %multiuserquests);
	BNet::Utils::preprint ($count, '10839', "Veil Skith: Darkstone of Terokk", %multiuserquests);
	BNet::Utils::preprint ($count, '10848', "Veil Rhaze: Unliving Evil", %multiuserquests);
	BNet::Utils::preprint ($count, '10861', "Veil Lithic: Preemptive Strike", %multiuserquests);
	BNet::Utils::preprint ($count, '10874', "Veil Shalas: Signal Fires", %multiuserquests);
	BNet::Utils::preprint ($count, '10889', "Return to Shattrath", %multiuserquests);
	BNet::Utils::preprint ($count, '10879', "The Skettis Offensive", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Cenarian Thicket");
	BNet::Utils::preprint ($count, '9957', "What's Wrong at Cenarion Thicket?", %multiuserquests);
	BNet::Utils::preprint ($count, '9960', "What's Wrong at Cenarion Thicket? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9961', "What's Wrong at Cenarion Thicket? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9968', "Strange Energy", %multiuserquests);
	BNet::Utils::preprint ($count, '9971', "Clues in the Thicket", %multiuserquests);
	BNet::Utils::preprint ($count, '9978', "By Any Means Necessary", %multiuserquests);
	BNet::Utils::preprint ($count, '9979', "Wind Trader Lathrai", %multiuserquests);
	BNet::Utils::preprint ($count, '10112', "A Personal Favor", %multiuserquests);
	BNet::Utils::preprint ($count, '9990', "Investigate Tuurem", %multiuserquests);
	BNet::Utils::preprint ($count, '9951', "It's Watching You!", %multiuserquests);
	BNet::Utils::preprint ($count, '9994', "What Are These Things? <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9995', "What Are These Things? <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10444', "Report to the Allerian Post <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10448', "Report to Stonebreaker Camp <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9996', "Attack on Firewing Point <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9997', "Attack on Firewing Point <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10446', "The Final Code <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10447', "The Final Code <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10005', "Letting Earthbinder Tavgren Know <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10006', "Letting Earthbinder Tavgren Know <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Firewing Point");
	BNet::Utils::preprint ($count, '10051', "Escape from Firewing Point! <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10052', "Escape from Firewing Point! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Bonechewer Ruins");
	BNet::Utils::preprint ($count, '10012', "Fel Orc Plans <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10013', "An Unseen Hand <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Refugee Caravan");
	BNet::Utils::preprint ($count, '10842', "Vengeful Souls", %multiuserquests);
	BNet::Utils::preprint ($count, '10908', "Speak with Rilak the Redeemed", %multiuserquests);
	BNet::Utils::preprint ($count, '10863', "Secrets of the Arakkoa <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10862', "Surrender to the Horde <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10896', "The Infested Protectors", %multiuserquests);
	BNet::Utils::preprint ($count, '10878', "Before Darkness Falls", %multiuserquests);
	BNet::Utils::preprint ($count, '10852', "Missing Friends", %multiuserquests);
	BNet::Utils::preprint ($count, '10840', "The Tomb of Lights", %multiuserquests);
	BNet::Utils::preprint ($count, '10030', "Recover the Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '10031', "Helping the Lost Find Their Way", %multiuserquests);
	BNet::Utils::preprint ($count, '10880', "Cabal Orders", %multiuserquests);
	BNet::Utils::preprint ($count, '10881', "The Shadow Tomb", %multiuserquests);
	BNet::Utils::preprint ($count, '10887', "Escaping the Tomb", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Sha'tari Base Camp");
	BNet::Utils::preprint ($count, '10922', "Digging Through Bones", %multiuserquests);
	BNet::Utils::preprint ($count, '10929', "Fumping", %multiuserquests);
	BNet::Utils::preprint ($count, '10930', "The Big Bone Worm", %multiuserquests);
	BNet::Utils::preprint ($count, '10877', "The Dread Relic", %multiuserquests);
	BNet::Utils::preprint ($count, '10923', "Evil Draws Near", %multiuserquests);
	BNet::Utils::preprint ($count, '10913', "An Improper Burial", %multiuserquests);
	BNet::Utils::preprint ($count, '10914', "A Hero Is Needed", %multiuserquests);
	BNet::Utils::preprint ($count, '10915', "The Fallen Exarch", %multiuserquests);
	BNet::Utils::preprint ($count, '10873', "Taken in the Night", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Netherweb Ridge");
	BNet::Utils::preprint ($count, '10898', "Skywing", %multiuserquests);
	BNet::Utils::preprint ($count, '10920', "For the Fallen", %multiuserquests);
	BNet::Utils::preprint ($count, '10921', "Terokkarantula", %multiuserquests);
	BNet::Utils::preprint ($count, '10926', "Return to Sha'tari Base Camp", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Auchindoun");
	BNet::Utils::preprint ($count, '10227', "I See Dead Draenei", %multiuserquests);
	BNet::Utils::preprint ($count, '10228', "Ezekiel", %multiuserquests);
	BNet::Utils::preprint ($count, '10231', "What Book? I Don't See Any Book.", %multiuserquests);
	BNet::Utils::preprint ($count, '10251', "The Master's Grand Design?", %multiuserquests);
	BNet::Utils::preprint ($count, '10252', "Vision of the Dead", %multiuserquests);
	BNet::Utils::preprint ($count, '10253', "Levixus the Soul Caller", %multiuserquests);
	BNet::Utils::preprint ($count, '29595', "Everything Will Be Alright", %multiuserquests);
	BNet::Utils::preprint ($count, '29596', "The End of the Exarch", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Stonebreaker Hold <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10105', "News for Rakoria", %multiuserquests);
	BNet::Utils::preprint ($count, '9993', "Olemba Seed Oil", %multiuserquests);
	BNet::Utils::preprint ($count, '10201', "And Now, the Moment of Truth", %multiuserquests);
	BNet::Utils::preprint ($count, '9987', "Stymying the Arakkoa", %multiuserquests);
	BNet::Utils::preprint ($count, '10000', "An Unwelcome Presence", %multiuserquests);
	BNet::Utils::preprint ($count, '10003', "The Firewing Liaison", %multiuserquests);
	BNet::Utils::preprint ($count, '10008', "What Happens in Terokkar Stays in Terokkar", %multiuserquests);
	BNet::Utils::preprint ($count, '10027', "Magical Disturbances", %multiuserquests);
	BNet::Utils::preprint ($count, '10039', "Speak with Scout Neftis", %multiuserquests);
	BNet::Utils::preprint ($count, '10041', "Who Are They?", %multiuserquests);
	BNet::Utils::preprint ($count, '10043', "Kill the Shadow Council!", %multiuserquests);
	BNet::Utils::preprint ($count, '10018', "Vestments of the Wolf Spirit", %multiuserquests);
	BNet::Utils::preprint ($count, '10023', "Patriarch Ironjaw", %multiuserquests);
	BNet::Utils::preprint ($count, '10791', "Welcoming the Wolf Spirit", %multiuserquests);
	BNet::Utils::preprint ($count, '10034', "Wanted: Bonelashers Dead!", %multiuserquests);
	BNet::Utils::preprint ($count, '10036', "Torgos!", %multiuserquests);
	BNet::Utils::preprint ($count, '10868', "Arakkoa War Path", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Allerian Hold <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '9992', "Olemba Seeds", %multiuserquests);
	BNet::Utils::preprint ($count, '10028', "Vessels of Power", %multiuserquests);
	BNet::Utils::preprint ($count, '10026', "Magical Disturbances", %multiuserquests);
	BNet::Utils::preprint ($count, '10038', "Speak with Private Weeks", %multiuserquests);
	BNet::Utils::preprint ($count, '10040', "Who Are They?", %multiuserquests);
	BNet::Utils::preprint ($count, '10042', "Kill the Shadow Council!", %multiuserquests);
	BNet::Utils::preprint ($count, '9998', "Unruly Neighbors", %multiuserquests);
	BNet::Utils::preprint ($count, '10007', "Thinning the Ranks", %multiuserquests);
	BNet::Utils::preprint ($count, '9986', "Stymying the Arakkoa", %multiuserquests);
	BNet::Utils::preprint ($count, '10016', "Timber Worg Tails", %multiuserquests);
	BNet::Utils::preprint ($count, '10022', "The Elusive Ironjaw", %multiuserquests);
	BNet::Utils::preprint ($count, '10002', "The Firewing Liaison", %multiuserquests);
	BNet::Utils::preprint ($count, '10869', "Thin the Flock", %multiuserquests);
	BNet::Utils::preprint ($count, '10033', "Wanted: Bonelashers Dead!", %multiuserquests);
	BNet::Utils::preprint ($count, '10035', "Torgos!", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Skettis");
	BNet::Utils::preprint ($count, '11096', "Threat from Above", %multiuserquests);
	BNet::Utils::preprint ($count, '11098', "To Skettis!", %multiuserquests);
	BNet::Utils::preprint ($count, '11093', "Hungry Nether Rays", %multiuserquests);
	BNet::Utils::preprint ($count, '11004', "World of Shadows", %multiuserquests);
	BNet::Utils::preprint ($count, '11005', "Secrets of the Talonpriests", %multiuserquests);
	BNet::Utils::preprint ($count, '11021', "Ishaal's Almanac", %multiuserquests);
	BNet::Utils::preprint ($count, '11024', "An Ally in Lower City", %multiuserquests);
	BNet::Utils::preprint ($count, '11028', "Countdown to Doom", %multiuserquests);
	BNet::Utils::preprint ($count, '11056', "Hazzik's Bargain", %multiuserquests);
	BNet::Utils::preprint ($count, '11029', "A Shabby Disguise", %multiuserquests);
	BNet::Utils::preprint ($count, '11073', "Terokk's Downfall", %multiuserquests);
	BNet::Utils::groupheader ("62: Terrokar Forest: Rep");
	BNet::Utils::preprint ($count, '10551', "Allegiance to the Aldor", %multiuserquests);
	BNet::Utils::preprint ($count, '10554', "Ishanah", %multiuserquests);
	BNet::Utils::preprint ($count, '10021', "Restoring the Light", %multiuserquests);
	BNet::Utils::preprint ($count, '10017', "Strained Supplies", %multiuserquests);
	BNet::Utils::preprint ($count, '10325', "Marks of Kil'jaeden", %multiuserquests);
	BNet::Utils::preprint ($count, '10020', "A Cure for Zahlia", %multiuserquests);
	BNet::Utils::preprint ($count, '10552', "Allegiance to the Scryers", %multiuserquests);
	BNet::Utils::preprint ($count, '10412', "Firewing Signets", %multiuserquests);
	BNet::Utils::preprint ($count, '10553', "Voren'thal the Seer", %multiuserquests);

}

sub z_64_67_nagrand ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("64: Nagrand: Breadcrumbs");
	BNet::Utils::preprint ($count, '39189', "Warchief's Command: Nagrand <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '39197', "Hero's Call: Nagrand <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::groupheader ("64: Nagrand: Garadar <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">");
	BNet::Utils::preprint ($count, '9888', "The Impotent Leader <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9889', "Don't Kill the Fat One <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9890', "Success! <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9891', "Because Kilrath is a Coward <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9906', "Message in a Battle <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9907', "An Audacious Advance <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10107', "Diplomatic Measures <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9910', "Standards and Practices <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9916', "Bleeding Hollow Supply Crates <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9935', "Wanted: Giselda the Crone <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9939', "Wanted: Zorbo the Advisor <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9937', "Wanted: Durn the Hungerer <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9863', "Vile Idolatry <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9944', "Missing Mag\'hari Procession <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9945', "War on the Warmaul <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9946', "Cho\'war the Pillager <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9864', "The Missing War Party <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9865', "Once Were Warriors <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9866', "He Will Walk The Earth... <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10479', "Proving Your Strength <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9867', "Murkblood Leaders... <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9872', "Murkblood Invaders <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Garadar: Finale <img src=\"http://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '10044', "A Visit With the Greatmother <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10045', "Material Components <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10081', "To Meet Mother Kashur <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10082', "The Agitated Ancestors <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10085', "A Visit With The Ancestors <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10101', "When Spirits Speak <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10102', "A Secret Revealed <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10167', "Auchindoun... <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10168', "What the Soul Sees <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10170', "Return to the Greatmother <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10171', "The Inconsolable Chieftain <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10172', "There Is No Hope <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10175', "Thrall, Son of Durotan (Obsolete)  <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10212', "Hero of the Mag\'har <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Throne of the Elements");
	BNet::Utils::preprint ($count, '9869', "The Throne of the Elements <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9870', "The Throne of the Elements <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9861', "The Howling Wind", %multiuserquests);
	BNet::Utils::preprint ($count, '9862', "Murkblood Corrupters", %multiuserquests);
	BNet::Utils::preprint ($count, '9800', "A Rare Bean", %multiuserquests);
	BNet::Utils::preprint ($count, '9804', "Agitated Spirits of Skysong", %multiuserquests);
	BNet::Utils::preprint ($count, '9805', "Blessing of Incineratus", %multiuserquests);
	BNet::Utils::preprint ($count, '9810', "The Spirit Polluted", %multiuserquests);
	BNet::Utils::preprint ($count, '9815', "Muck Diving", %multiuserquests);
	BNet::Utils::preprint ($count, '9818', "The Underneath", %multiuserquests);
	BNet::Utils::preprint ($count, '9819', "The Tortured Earth", %multiuserquests);
	BNet::Utils::preprint ($count, '9821', "Eating Damnation", %multiuserquests);
	BNet::Utils::preprint ($count, '9849', "Shattering the Veil", %multiuserquests);
	BNet::Utils::preprint ($count, '9853', "Gurok the Usurper", %multiuserquests);
	BNet::Utils::preprint ($count, '9852', "The Ultimate Bloodsport", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Mag'hari Procession");
	BNet::Utils::preprint ($count, '9948', "Finding the Survivors <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9879', "The Totem of Kar\'dash <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9868', "The Totem of Kar\'dash <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Nesingwary Safari");
	BNet::Utils::preprint ($count, '10113', "The Nesingwary Safari <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10114', "The Nesingwary Safari <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9897', "I\'m Saved!", %multiuserquests);
	BNet::Utils::preprint ($count, '9857', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9858', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9859', "Talbuk Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9854', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9855', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9856', "Windroc Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9850', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9851', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9789', "Clefthoof Mastery", %multiuserquests);
	BNet::Utils::preprint ($count, '9852', "The Ultimate Bloodsport", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Burning Blade Ruins");
	BNet::Utils::preprint ($count, '9928', "Armaments for Deception", %multiuserquests);
	BNet::Utils::preprint ($count, '9927', "Ruthless Cunning", %multiuserquests);
	BNet::Utils::preprint ($count, '9932', "Body of Evidence", %multiuserquests);
	BNet::Utils::preprint ($count, '9931', "Returning the Favor", %multiuserquests);
	BNet::Utils::preprint ($count, '9933', "Message to Telaar <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9934', "Message to Garadar <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);


	BNet::Utils::groupheader ("64: Nagrand: Telaar <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">");
	BNet::Utils::preprint ($count, '9917', "Do My Eyes Deceive Me <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9918', "Not On My Watch! <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9920', "Mo\'mor the Breaker <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9921', "The Ruins of Burning Blade <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9922', "The Twin Clefts of Nagrand <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10108', "Diplomatic Measures <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9936', "Wanted: Giselda the Crone <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9940', "Wanted: Zorbo the Advisor <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9938', "Wanted: Durn the Hungerer <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9871', "Murkblood Invaders <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '10476', "Fierce Enemies <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9923', "HELP! <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9924', "Corki\'s Gone Missing Again! <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9954', "Corki\'s Ransom <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9955', "Cho\'war the Pillager <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9956', "The Ravaged Caravan <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9874', "Stopping the Spread <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9878', "Solving the Problem <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Ring of Blood");
	BNet::Utils::preprint ($count, '9962', "The Ring of Blood: Brokentoe", %multiuserquests);
	BNet::Utils::preprint ($count, '9967', "The Ring of Blood: The Blue Brothers", %multiuserquests);
	BNet::Utils::preprint ($count, '9970', "The Ring of Blood: Rokdar the Sundered Lord", %multiuserquests);
	BNet::Utils::preprint ($count, '9972', "The Ring of Blood: Skra\'gath", %multiuserquests);
	BNet::Utils::preprint ($count, '9973', "The Ring of Blood: The Warmaul Champion", %multiuserquests);
	BNet::Utils::preprint ($count, '9977', "The Ring of Blood: The Final Challenge", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Aeris Landing");
	BNet::Utils::preprint ($count, '9913', "The Consortium Needs You!", %multiuserquests);
	BNet::Utils::preprint ($count, '9914', "A Head Full of Ivory", %multiuserquests);
	BNet::Utils::preprint ($count, '9925', "Matters of Security", %multiuserquests);
	BNet::Utils::preprint ($count, '9900', "Gava\'xi", %multiuserquests);
	BNet::Utils::preprint ($count, '9882', "Stealing from Thieves", %multiuserquests);
	BNet::Utils::preprint ($count, '9893', "Obsidian Warbeads", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Miscellaneous");
	BNet::Utils::preprint ($count, '10111', "Bring Me The Egg!", %multiuserquests);
	BNet::Utils::preprint ($count, '10109', "I Must Have Them!", %multiuserquests);
	BNet::Utils::preprint ($count, '13799', "Where Are My Keys?", %multiuserquests);
	BNet::Utils::preprint ($count, '13800', "Get My Keys!", %multiuserquests);

	BNet::Utils::groupheader ("64: Nagrand: Altruis the Sufferer");
	BNet::Utils::preprint ($count, '9983', "He Called Himself Altruis... <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9982', "He Called Himself Altruis... <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '9991', "Survey the Land", %multiuserquests);
	BNet::Utils::preprint ($count, '9999', "Buying Time", %multiuserquests);
	BNet::Utils::preprint ($count, '10001', "The Master Planner", %multiuserquests);
	BNet::Utils::preprint ($count, '10004', "Patience and Understanding", %multiuserquests);
	BNet::Utils::preprint ($count, '10009', "Crackin' Some Skulls", %multiuserquests);
	BNet::Utils::preprint ($count, '10010', "It's Just That Easy?", %multiuserquests);
	BNet::Utils::preprint ($count, '10011', "Forge Camp: Annihilated", %multiuserquests);

}

sub z_65_68_blades_edge_mountains ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::preprint ($count, '10984', "Speak with the Ogre", %multiuserquests);
	BNet::Utils::preprint ($count, '10983', "Mog'dorg the Wizened", %multiuserquests);
}

sub z_67_70_netherstorm ($%) {
	my ($count, %multiuserquests) = @_;
	BNet::Utils::groupheader ("67: Netherstorm");
	BNet::Utils::preprint ($count, '11042', "A Mystifying Vision <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11037', "A Strange Vision <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11039', "Report to Spymaster Thalodien", %multiuserquests);
	BNet::Utils::preprint ($count, '11038', "Assist Exarch Orelis", %multiuserquests);

}

sub z_67_70_shadowmoon_valley ($%) {
	my ($count, %multiuserquests) = @_;
	BNet::Utils::groupheader ("67: Shadowmoon Valley");
	BNet::Utils::preprint ($count, '11044', "Visions of Destruction <img src=\"http://wow.zamimg.com/images/wow/icons/small/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11048', "Kroghan\'s Report <img src=\"http://wow.zamimg.com/images/wow/icons/small/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11045', "Zorus the Judicator <img src=\"http://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '11046', "Chief Apothecary Hildagard <img src=\"http://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);

	BNet::Utils::groupheader ("70: Shadowmoon Valley/Nagrand: Altruis the Sufferer");
	BNet::Utils::preprint ($count, '10640', "Altruis (Aldor)", %multiuserquests);
	BNet::Utils::preprint ($count, '10689', "Altruis (Scryers)", %multiuserquests);
	BNet::Utils::preprint ($count, '10641', "Against the Legion", %multiuserquests);
	BNet::Utils::preprint ($count, '10668', "Against the Illidari", %multiuserquests);
	BNet::Utils::preprint ($count, '10669', "Against All Odds", %multiuserquests);
	BNet::Utils::preprint ($count, '10646', "Illidan's Pupil", %multiuserquests);
	BNet::Utils::preprint ($count, '10649', "The Book of Fel Names", %multiuserquests);
	BNet::Utils::preprint ($count, '10650', "Return to the Aldor", %multiuserquests);
	BNet::Utils::preprint ($count, '10691', "Return to the Scryers", %multiuserquests);
	BNet::Utils::preprint ($count, '10651', "Varedis Must Be Stopped (Aldor)", %multiuserquests);
	BNet::Utils::preprint ($count, '10692', "Varedis Must Be Stopped (Scryers)", %multiuserquests);

}

sub z_70_isle_of_queldanas ($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("70: Isle of Quel'Danas");
	BNet::Utils::preprint ($count, '11554', "A Friend in the Frontlines", %multiuserquests);
	BNet::Utils::preprint ($count, '11555', "Honored by Your Allies", %multiuserquests);
	BNet::Utils::preprint ($count, '11556', "Revered in the Field of Battle", %multiuserquests);
	BNet::Utils::preprint ($count, '11557', "Exalted Among All Combatants", %multiuserquests);
	BNet::Utils::preprint ($count, '11549', "A Magnanimous Benefactor", %multiuserquests);

}

1;
