package BNet::Quests_Cata;

use strict;
use warnings;

sub sz_01_05_Gilneas_City($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Gilneas City <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">");

}

sub sz_01_20_Gilneas($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Gilneas <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">");

}

sub sz_10_60_Ruins_of_Gilneas($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Ruins of Gilneas <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">");

}

sub sz_01_05_Kezan($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("01-05: Kezan <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");

}

sub sz_01_10_Lost_Isles($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("01-20:Lost Isles <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");

}

sub z_80_90_Mount_Hyjal($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("80-90: Mount Hyjal: Intro");
	BNet::Utils::preprint ($count, '27726', "Hero's Call: Mount Hyjal! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27721', "Warchief's Command: Mount Hyjal! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25316', "As Hyjal Burns", %multiuserquests);
	BNet::Utils::preprint ($count, '25370', "Inciting the Elements", %multiuserquests);
	BNet::Utils::preprint ($count, '25460', "The Earth Rises", %multiuserquests);
	BNet::Utils::preprint ($count, '25574', "Flames from Above", %multiuserquests);
	BNet::Utils::preprint ($count, '25317', "Protect the World Tree", %multiuserquests);
	BNet::Utils::preprint ($count, '25319', "War on the Twilight's Hammer", %multiuserquests);
	BNet::Utils::preprint ($count, '25323', "Flamebreaker", %multiuserquests);
	BNet::Utils::preprint ($count, '25464', "The Return of Baron Geddon", %multiuserquests);
	BNet::Utils::preprint ($count, '25430', "Emerald Allies", %multiuserquests);
	BNet::Utils::preprint ($count, '25320', "The Captured Scout", %multiuserquests);
	BNet::Utils::preprint ($count, '25321', "Twilight Captivity", %multiuserquests);
	BNet::Utils::preprint ($count, '25424', "Return to Alysra", %multiuserquests);
	BNet::Utils::preprint ($count, '25324', "A Prisoner of Interest", %multiuserquests);
	BNet::Utils::preprint ($count, '25325', "Through the Dream", %multiuserquests);
	BNet::Utils::preprint ($count, '25578', "Return to Nordrassil", %multiuserquests);
	BNet::Utils::groupheader ("80-90: Mount Hyjal: Shrine of Goldrinn");
	BNet::Utils::preprint ($count, '25584', "The Return of the Ancients", %multiuserquests);
	BNet::Utils::preprint ($count, '25233', "End of the Supply Line", %multiuserquests);
	BNet::Utils::preprint ($count, '25234', "In the Rear With the Gear", %multiuserquests);
	BNet::Utils::preprint ($count, '25255', "Harrying the Hunters", %multiuserquests);
	BNet::Utils::preprint ($count, '25268', "The Voice of Goldrinn <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25269', "The Voice of Lo'Gosh <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25271', "Goldrinn's Ferocity <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25270', "Howling Mad <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25273', "Lycanthoth the Corruptor <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25272', "Lycanthoth the Corruptor <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25280', "The Shrine Reclaimed <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25279', "The Shrine Reclaimed <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25278', "Cleaning House <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '25297', "From the Mouth of Madness", %multiuserquests);
	BNet::Utils::preprint ($count, '25298', "Free Your Mind, the Rest Follows", %multiuserquests);
	BNet::Utils::groupheader ("80-90: Mount Hyjal: (Unsorted)");
	BNet::Utils::preprint ($count, '25223', "Trial By Fire", %multiuserquests);
	BNet::Utils::preprint ($count, '25224', "In Bloom", %multiuserquests);
	BNet::Utils::preprint ($count, '25274', "Signed in Blood", %multiuserquests);
	BNet::Utils::preprint ($count, '25276', "Your New Identity", %multiuserquests);
	BNet::Utils::preprint ($count, '25291', "Twilight Training", %multiuserquests);
	BNet::Utils::preprint ($count, '25294', "Walking the Dog", %multiuserquests);
	BNet::Utils::preprint ($count, '25296', "Gather the Intelligence", %multiuserquests);
	BNet::Utils::preprint ($count, '25299', "Mental Training: Speaking the Truth to Power", %multiuserquests);
	BNet::Utils::preprint ($count, '25308', "Seeds of Discord", %multiuserquests);
	BNet::Utils::preprint ($count, '25309', "Spiritual Training: Mercy is for the Weak", %multiuserquests);
	BNet::Utils::preprint ($count, '25310', "The Greater of Two Evils", %multiuserquests);
	BNet::Utils::preprint ($count, '25311', "Twilight Territory", %multiuserquests);
	BNet::Utils::preprint ($count, '25314', "Speech Writing for Dummies", %multiuserquests);
	BNet::Utils::preprint ($count, '25315', "Graduation Speech", %multiuserquests);
	BNet::Utils::preprint ($count, '25330', "Waste of Flesh", %multiuserquests);
	BNet::Utils::preprint ($count, '25372', "Aessina's Miracle", %multiuserquests);
	BNet::Utils::preprint ($count, '25381', "Fighting Fire With ... Anything", %multiuserquests);
	BNet::Utils::preprint ($count, '25382', "Disrupting the Rituals", %multiuserquests);
	BNet::Utils::preprint ($count, '25385', "Save the Wee Animals", %multiuserquests);
	BNet::Utils::preprint ($count, '25392', "Oh, Deer!", %multiuserquests);
	BNet::Utils::preprint ($count, '25404', "If You're Not Against Us...", %multiuserquests);
	BNet::Utils::preprint ($count, '25408', "Seeds of Their Demise", %multiuserquests);
	BNet::Utils::preprint ($count, '25411', "A New Master", %multiuserquests);
	BNet::Utils::preprint ($count, '25412', "The Name Never Spoken", %multiuserquests);
	BNet::Utils::preprint ($count, '25428', "Black Heart of Flame", %multiuserquests);
	BNet::Utils::preprint ($count, '25462', "The Bears Up There", %multiuserquests);
	BNet::Utils::preprint ($count, '25472', "The Flameseer's Staff", %multiuserquests);
	BNet::Utils::preprint ($count, '25490', "Smashing Through Ashes", %multiuserquests);
	BNet::Utils::preprint ($count, '25491', "Durable Seeds", %multiuserquests);
	BNet::Utils::preprint ($count, '25492', "Firebreak", %multiuserquests);
	BNet::Utils::preprint ($count, '25493', "Fresh Bait", %multiuserquests);
	BNet::Utils::preprint ($count, '25494', "A Champion's Collar", %multiuserquests);
	BNet::Utils::preprint ($count, '25496', "Grudge Match", %multiuserquests);
	BNet::Utils::preprint ($count, '25499', "Agility Training: Run Like Hell!", %multiuserquests);
	BNet::Utils::preprint ($count, '25502', "Prepping the Soil", %multiuserquests);
	BNet::Utils::preprint ($count, '25507', "Hell's Shells", %multiuserquests);
	BNet::Utils::preprint ($count, '25509', "Physical Training: Forced Labor", %multiuserquests);
	BNet::Utils::preprint ($count, '25510', "Tortolla Speaks", %multiuserquests);
	BNet::Utils::preprint ($count, '25514', "Breaking the Bonds", %multiuserquests);
	BNet::Utils::preprint ($count, '25519', "Children of Tortolla", %multiuserquests);
	BNet::Utils::preprint ($count, '25520', "An Ancient Awakens", %multiuserquests);
	BNet::Utils::preprint ($count, '25523', "Flight in the Firelands", %multiuserquests);
	BNet::Utils::preprint ($count, '25525', "Wave One", %multiuserquests);
	BNet::Utils::preprint ($count, '25531', "Twilight Riot", %multiuserquests);
	BNet::Utils::preprint ($count, '25544', "Wave Two", %multiuserquests);
	BNet::Utils::preprint ($count, '25548', "Might of the Firelord", %multiuserquests);
	BNet::Utils::preprint ($count, '25549', "The Sanctum of the Prophets", %multiuserquests);
	BNet::Utils::preprint ($count, '25554', "Secrets of the Flame", %multiuserquests);
	BNet::Utils::preprint ($count, '25560', "Egg Wave", %multiuserquests);
	BNet::Utils::preprint ($count, '25597', "Commander Jarod Shadowsong", %multiuserquests);
	BNet::Utils::preprint ($count, '25601', "Head of the Class", %multiuserquests);
	BNet::Utils::preprint ($count, '25608', "Slash and Burn", %multiuserquests);
	BNet::Utils::preprint ($count, '25653', "The Ancients are With Us", %multiuserquests);
	BNet::Utils::preprint ($count, '25655', "The Wormwing Problem", %multiuserquests);
	BNet::Utils::preprint ($count, '25656', "Scrambling for Eggs", %multiuserquests);
	BNet::Utils::preprint ($count, '25663', "An Offering for Aviana", %multiuserquests);
	BNet::Utils::preprint ($count, '25664', "A Prayer and a Wing", %multiuserquests);
	BNet::Utils::preprint ($count, '25665', "A Plea From Beyond", %multiuserquests);
	BNet::Utils::preprint ($count, '25731', "A Bird in Hand", %multiuserquests);
	BNet::Utils::preprint ($count, '25740', "Fact-Finding Mission", %multiuserquests);
	BNet::Utils::preprint ($count, '25746', "Sethria's Brood", %multiuserquests);
	BNet::Utils::preprint ($count, '25758', "A Gap in Their Armor", %multiuserquests);
	BNet::Utils::preprint ($count, '25761', "Disassembly", %multiuserquests);
	BNet::Utils::preprint ($count, '25763', "The Codex of Shadows", %multiuserquests);
	BNet::Utils::preprint ($count, '25764', "Egg Hunt", %multiuserquests);
	BNet::Utils::preprint ($count, '25776', "Sethria's Demise", %multiuserquests);
	BNet::Utils::preprint ($count, '25795', "Return to the Shrine", %multiuserquests);
	BNet::Utils::preprint ($count, '25807', "An Ancient Reborn", %multiuserquests);
	BNet::Utils::preprint ($count, '25810', "The Hatchery Must Burn", %multiuserquests);
	BNet::Utils::preprint ($count, '25830', "The Last Living Lorekeeper", %multiuserquests);
	BNet::Utils::preprint ($count, '25832', "Return to Aviana", %multiuserquests);
	BNet::Utils::preprint ($count, '25842', "Firefight", %multiuserquests);
	BNet::Utils::preprint ($count, '25843', "Tortolla's Revenge", %multiuserquests);
	BNet::Utils::preprint ($count, '25881', "Lost Wardens", %multiuserquests);
	BNet::Utils::preprint ($count, '25886', "Pressing the Advantage", %multiuserquests);
	BNet::Utils::preprint ($count, '25899', "Breakthrough", %multiuserquests);
	BNet::Utils::preprint ($count, '25901', "Hyjal Recycling Program", %multiuserquests);
	BNet::Utils::preprint ($count, '25904', "The Hammer and the Key", %multiuserquests);
	BNet::Utils::preprint ($count, '25906', "The Third Flamegate", %multiuserquests);
	BNet::Utils::preprint ($count, '25910', "The Time for Mercy has Passed", %multiuserquests);
	BNet::Utils::preprint ($count, '25915', "The Strength of Tortolla", %multiuserquests);
	BNet::Utils::preprint ($count, '25923', "Finish Nemesis", %multiuserquests);
	BNet::Utils::preprint ($count, '25928', "Tortolla's Triumph", %multiuserquests);
	BNet::Utils::preprint ($count, '25940', "Last Stand at Whistling Grove", %multiuserquests);
	BNet::Utils::preprint ($count, '25985', "Wings Over Mount Hyjal", %multiuserquests);
	BNet::Utils::preprint ($count, '27874', "Aviana's Legacy", %multiuserquests);
	BNet::Utils::preprint ($count, '29066', "Good News... and Bad News", %multiuserquests);
	BNet::Utils::preprint ($count, '25550', "Magma Monarch", %multiuserquests);
	BNet::Utils::preprint ($count, '25551', "The Firelord", %multiuserquests);
	BNet::Utils::preprint ($count, '25552', "Brood of Evil", %multiuserquests);
	BNet::Utils::preprint ($count, '25553', "Death to the Broodmother", %multiuserquests);
	BNet::Utils::preprint ($count, '25555', "The Gatekeeper", %multiuserquests);
	BNet::Utils::preprint ($count, '25644', "The Twilight Egg", %multiuserquests);
	BNet::Utils::preprint ($count, '29234', "Delegation", %multiuserquests);
	BNet::Utils::preprint ($count, '29437', "The Fallen Guardian", %multiuserquests);

}

sub z_80_90_Vashjir($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("Vash'jir");

}

sub z_82_90_Deepholm($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("82-90: Deepholm: Intro");
	BNet::Utils::preprint ($count, '27722', "Warchief's Command: Deepholm! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27722', "Hero's Call: Deepholm! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27203', "The Maelstrom", %multiuserquests);
	BNet::Utils::preprint ($count, '27123', "Deepholm, Realm of Earth", %multiuserquests);
	BNet::Utils::groupheader ("82-90: Deepholm: Upper World Pillar Fragment");
	BNet::Utils::preprint ($count, '26245', "Gunship Down", %multiuserquests);
	BNet::Utils::preprint ($count, '26246', "Captain's Log", %multiuserquests);
	BNet::Utils::preprint ($count, '27136', "Elemental Energy", %multiuserquests);
	BNet::Utils::preprint ($count, '26244', "The Earth Claims All", %multiuserquests);
	BNet::Utils::preprint ($count, '26247', "Diplomacy First", %multiuserquests);
	BNet::Utils::preprint ($count, '26248', "All Our Friends Are Dead", %multiuserquests);
	BNet::Utils::preprint ($count, '26249', "The Admiral's Cabin", %multiuserquests);
	BNet::Utils::preprint ($count, '26427', "Without a Captain or Crew", %multiuserquests);
	BNet::Utils::preprint ($count, '26251', "Take No Prisoners", %multiuserquests);
	BNet::Utils::preprint ($count, '26250', "On Second Thought, Take One Prisoner", %multiuserquests);
	BNet::Utils::preprint ($count, '26254', "Some Spraining to Do", %multiuserquests);
	BNet::Utils::preprint ($count, '26255', "Return to the Temple of Earth", %multiuserquests);
	BNet::Utils::preprint ($count, '26258', "Deathwing's Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '26259', "Blood of the Earthwarder", %multiuserquests);
	BNet::Utils::preprint ($count, '26256', "Bleed the Bloodshaper", %multiuserquests);
	BNet::Utils::preprint ($count, '26261', "Question the Slaves", %multiuserquests);
	BNet::Utils::preprint ($count, '26260', "The Forgemaster's Log", %multiuserquests);
	BNet::Utils::preprint ($count, '27007', "Silvermarsh Rendezvous", %multiuserquests);
	BNet::Utils::preprint ($count, '27010', "Quicksilver Submersion", %multiuserquests);
	BNet::Utils::preprint ($count, '27100', "Twilight Research", %multiuserquests);
	BNet::Utils::preprint ($count, '27101', "Maziel's Revelation", %multiuserquests);
	BNet::Utils::preprint ($count, '27102', "Maziel's Ascendancy", %multiuserquests);
	BNet::Utils::preprint ($count, '27061', "The Twilight Overlook", %multiuserquests);
	BNet::Utils::preprint ($count, '26766', "Big Game, Big Bait", %multiuserquests);
	BNet::Utils::preprint ($count, '26768', "To Catch a Dragon", %multiuserquests);
	BNet::Utils::preprint ($count, '26771', "Testing the Trap", %multiuserquests);
	BNet::Utils::preprint ($count, '26857', "Abyssion's Minions", %multiuserquests);
	BNet::Utils::preprint ($count, '26861', "Block the Gates", %multiuserquests);
	BNet::Utils::preprint ($count, '26876', "The World Pillar Fragment", %multiuserquests);
	BNet::Utils::groupheader ("82-90: Deepholm: Middle World Pillar Fragment");
	BNet::Utils::preprint ($count, '26409', "Where's Goldmine?", %multiuserquests);
	BNet::Utils::preprint ($count, '26410', "Explosive Bonding Compound", %multiuserquests);
	BNet::Utils::preprint ($count, '27135', "Something that Burns", %multiuserquests);
	BNet::Utils::preprint ($count, '26411', "Apply and Flash Dry", %multiuserquests);
	BNet::Utils::preprint ($count, '26413', "Take Him to the Earthcaller", %multiuserquests);
	BNet::Utils::preprint ($count, '26484', "To Stonehearth's Aid", %multiuserquests);
	BNet::Utils::preprint ($count, '27931', "The Quaking Fields", %multiuserquests);
	BNet::Utils::preprint ($count, '27932', "The Axe of Earthly Sundering", %multiuserquests);
	BNet::Utils::preprint ($count, '27933', "Elemental Ore", %multiuserquests);
	BNet::Utils::preprint ($count, '27934', "One With the Ground", %multiuserquests);
	BNet::Utils::preprint ($count, '27935', "Bring Down the Avalanche", %multiuserquests);
	BNet::Utils::preprint ($count, '26499', "Stonefather's Boon", %multiuserquests);
	BNet::Utils::preprint ($count, '26501', "Sealing the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '26500', "We're Surrounded", %multiuserquests);
	BNet::Utils::preprint ($count, '26502', "Thunder Stones", %multiuserquests);
	BNet::Utils::preprint ($count, '26537', "Shatter Them!", %multiuserquests);
	BNet::Utils::preprint ($count, '26564', "Fixer Upper", %multiuserquests);
	BNet::Utils::preprint ($count, '26591', "Battlefront Triage", %multiuserquests);
	BNet::Utils::preprint ($count, '26625', "Troggzor the Earthinator", %multiuserquests);
	BNet::Utils::preprint ($count, '27126', "Rush Delivery", %multiuserquests);
	BNet::Utils::preprint ($count, '26632', "Close Escort", %multiuserquests);
	BNet::Utils::preprint ($count, '26755', "Keep Them off the Front", %multiuserquests);
	BNet::Utils::preprint ($count, '26762', "Reactivate the Constructs", %multiuserquests);
	BNet::Utils::preprint ($count, '26770', "Mystic Masters", %multiuserquests);
	BNet::Utils::preprint ($count, '26834', "Down Into the Chasm", %multiuserquests);
	BNet::Utils::preprint ($count, '26791', "Sprout No More", %multiuserquests);
	BNet::Utils::preprint ($count, '26792', "Fungal Monstrosities", %multiuserquests);
	BNet::Utils::preprint ($count, '26835', "A Slight Problem", %multiuserquests);
	BNet::Utils::preprint ($count, '26836', "Rescue the Stonefather... and Flint", %multiuserquests);
	BNet::Utils::preprint ($count, '27937', "The Hero Returns", %multiuserquests);
	BNet::Utils::preprint ($count, '27938', "The Middle Fragment", %multiuserquests);
	BNet::Utils::groupheader ("82-90: Deepholm: Lower World Pillar Fragment");
	BNet::Utils::preprint ($count, '26326', "The Very Earth Beneath Our Feet", %multiuserquests);
	BNet::Utils::preprint ($count, '26312', "Crumbling Defenses", %multiuserquests);
	BNet::Utils::preprint ($count, '26313', "Core of Our Troubles", %multiuserquests);
	BNet::Utils::preprint ($count, '26314', "On Even Ground", %multiuserquests);
	BNet::Utils::preprint ($count, '26315', "Imposing Confrontation", %multiuserquests);
	BNet::Utils::preprint ($count, '26328', "Rocky Relations", %multiuserquests);
	BNet::Utils::preprint ($count, '26375', "Loose Stones", %multiuserquests);
	BNet::Utils::preprint ($count, '26376', "Hatred Runs Deep", %multiuserquests);
	BNet::Utils::preprint ($count, '26377', "Unsolid Ground", %multiuserquests);
	BNet::Utils::preprint ($count, '26426', "Violent Gale", %multiuserquests);
	BNet::Utils::preprint ($count, '26869', "Depth of the Depths", %multiuserquests);
	BNet::Utils::preprint ($count, '26871', "A Rock Amongst Many", %multiuserquests);
	BNet::Utils::preprint ($count, '26436', "Entrenched", %multiuserquests);
	BNet::Utils::preprint ($count, '26437', "Making Things Crystal Clear", %multiuserquests);
	BNet::Utils::preprint ($count, '26438', "Intervention", %multiuserquests);
	BNet::Utils::preprint ($count, '26439', "Putting the Pieces Together", %multiuserquests);
	BNet::Utils::preprint ($count, '28869', "Pebble", %multiuserquests);
	BNet::Utils::preprint ($count, '26440', "Clingy", %multiuserquests);
	BNet::Utils::preprint ($count, '26441', "So Big, So Round...", %multiuserquests);
	BNet::Utils::preprint ($count, '26575', "Rock Bottom", %multiuserquests);
	BNet::Utils::preprint ($count, '26507', "Petrified Delicacies", %multiuserquests);
	BNet::Utils::preprint ($count, '26576', "Steady Hand", %multiuserquests);
	BNet::Utils::preprint ($count, '26656', "Don't. Stop. Moving.", %multiuserquests);
	BNet::Utils::preprint ($count, '26657', "Hard Falls", %multiuserquests);
	BNet::Utils::preprint ($count, '26658', "Fragile Values", %multiuserquests);
	BNet::Utils::preprint ($count, '26659', "Resonating Blow", %multiuserquests);
	BNet::Utils::preprint ($count, '26577', "Rocky Upheaval", %multiuserquests);
	BNet::Utils::preprint ($count, '26578', "Doomshrooms", %multiuserquests);
	BNet::Utils::preprint ($count, '26579', "Gone Soft", %multiuserquests);
	BNet::Utils::preprint ($count, '26580', "Familiar Intruders", %multiuserquests);
	BNet::Utils::preprint ($count, '26581', "A Head Full of Wind", %multiuserquests);
	BNet::Utils::preprint ($count, '26582', "Unnatural Causes", %multiuserquests);
	BNet::Utils::preprint ($count, '26583', "Wrath of the Fungalmancer", %multiuserquests);
	BNet::Utils::preprint ($count, '26584', "Shaken and Stirred", %multiuserquests);
	BNet::Utils::preprint ($count, '26585', "Corruption Destruction", %multiuserquests);
	BNet::Utils::preprint ($count, '26750', "At the Stonemother's Call", %multiuserquests);
	BNet::Utils::preprint ($count, '26752', "Audience with the Stonemother", %multiuserquests);
	BNet::Utils::preprint ($count, '26827', "Rallying the Earthen Ring", %multiuserquests);
	BNet::Utils::preprint ($count, '26828', "Our Part of the Bargain", %multiuserquests);
	BNet::Utils::preprint ($count, '26829', "The Stone March", %multiuserquests);
	BNet::Utils::preprint ($count, '26832', "Therazane's Mercy", %multiuserquests);
	BNet::Utils::preprint ($count, '26831', "The Twilight Flight", %multiuserquests);
	BNet::Utils::preprint ($count, '26833', "Word In Stone", %multiuserquests);
	BNet::Utils::preprint ($count, '26875', "Undying Twilight", %multiuserquests);
	BNet::Utils::preprint ($count, '26971', "The Binding", %multiuserquests);
	BNet::Utils::preprint ($count, '26709', "The Stone Throne", %multiuserquests);
	BNet::Utils::groupheader ("82-90: Deepholm: To Uldum <img src=\"https://wow.zamimg.com/images/icons/alliance.png\">");
	BNet::Utils::preprint ($count, '27952', "The Explorers", %multiuserquests);
	BNet::Utils::preprint ($count, '27004', "The Twilight Plot", %multiuserquests);
	BNet::Utils::preprint ($count, '27006', "Fly Over", %multiuserquests);
	BNet::Utils::preprint ($count, '27040', "Decryption Made Easy", %multiuserquests);
	BNet::Utils::preprint ($count, '27042', "Fight Fire and Water and Air with...", %multiuserquests);
	BNet::Utils::preprint ($count, '27058', "The Wrong Sequence", %multiuserquests);
	BNet::Utils::preprint ($count, '28292', "That's No Pyramid!", %multiuserquests);
	BNet::Utils::groupheader ("82-90: Deepholm: To Uldum <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '27953', "The Reliquary", %multiuserquests);
	BNet::Utils::preprint ($count, '27005', "The Twilight Plot", %multiuserquests);
	BNet::Utils::preprint ($count, '27008', "Fly Over", %multiuserquests);
	BNet::Utils::preprint ($count, '27041', "Decryption Made Easy", %multiuserquests);
	BNet::Utils::preprint ($count, '27043', "Fight Fire and Water and Air with...", %multiuserquests);
	BNet::Utils::preprint ($count, '27059', "The Wrong Sequence", %multiuserquests);
	BNet::Utils::preprint ($count, '28293', "That's No Pyramid!", %multiuserquests);

}

sub z_83_90_Uldum($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("83-90: Uldum (Unsorted)");
	BNet::Utils::preprint ($count, '27003', "Easy Money", %multiuserquests);
	BNet::Utils::preprint ($count, '27141', "Premature Explosionation", %multiuserquests);
	BNet::Utils::preprint ($count, '27176', "Just the Tip", %multiuserquests);
	BNet::Utils::preprint ($count, '27179', "Field Work", %multiuserquests);
	BNet::Utils::preprint ($count, '27187', "Do the World a Favor", %multiuserquests);
	BNet::Utils::preprint ($count, '27196', "On to Something", %multiuserquests);
	BNet::Utils::preprint ($count, '27431', "Tipping the Balance", %multiuserquests);
	BNet::Utils::preprint ($count, '27511', "The Thrill of Discovery", %multiuserquests);
	BNet::Utils::preprint ($count, '27517', "Be Prepared", %multiuserquests);
	BNet::Utils::preprint ($count, '27519', "Under the Choking Sands", %multiuserquests);
	BNet::Utils::preprint ($count, '27520', "Minions of Al'Akir", %multiuserquests);
	BNet::Utils::preprint ($count, '27541', "Lessons From the Past", %multiuserquests);
	BNet::Utils::preprint ($count, '27549', "By the Light of the Stars", %multiuserquests);
	BNet::Utils::preprint ($count, '27595', "The Prophet Hadassi", %multiuserquests);
	BNet::Utils::preprint ($count, '27602', "The Prophet's Dying Words", %multiuserquests);
	BNet::Utils::preprint ($count, '27623', "Colossal Guardians", %multiuserquests);
	BNet::Utils::preprint ($count, '27624', "After the Fall", %multiuserquests);
	BNet::Utils::preprint ($count, '27627', "Just a Fancy Cockroach", %multiuserquests);
	BNet::Utils::preprint ($count, '27628', "Send Word to Phaoris", %multiuserquests);
	BNet::Utils::preprint ($count, '27630', "The High Priest's Vote", %multiuserquests);
	BNet::Utils::preprint ($count, '27631', "The High Commander's Vote", %multiuserquests);
	BNet::Utils::preprint ($count, '27632', "Tanotep's Son", %multiuserquests);
	BNet::Utils::preprint ($count, '27669', "Do the Honors", %multiuserquests);
	BNet::Utils::preprint ($count, '27706', "The Scepter of Orsis", %multiuserquests);
	BNet::Utils::preprint ($count, '27707', "Neferset Prison", %multiuserquests);
	BNet::Utils::preprint ($count, '27738', "The Pit of Scales", %multiuserquests);
	BNet::Utils::preprint ($count, '27748', "Fortune and Glory", %multiuserquests);
	BNet::Utils::preprint ($count, '27755', "The Curse of the Tombs", %multiuserquests);
	BNet::Utils::preprint ($count, '27760', "Artificial Intelligence", %multiuserquests);
	BNet::Utils::preprint ($count, '27761', "A Disarming Distraction", %multiuserquests);
	BNet::Utils::preprint ($count, '27777', "Core Access Codes", %multiuserquests);
	BNet::Utils::preprint ($count, '27778', "Hacking the Wibson", %multiuserquests);
	BNet::Utils::preprint ($count, '27779', "Gnomebliteration", %multiuserquests);
	BNet::Utils::preprint ($count, '27836', "Stopping the Spread", %multiuserquests);
	BNet::Utils::preprint ($count, '27837', "Trespassers in the Water", %multiuserquests);
	BNet::Utils::preprint ($count, '27838', "The Root of the Corruption", %multiuserquests);
	BNet::Utils::preprint ($count, '27839', "Ancient Weapons", %multiuserquests);
	BNet::Utils::preprint ($count, '27899', "That Gleam in his Eye", %multiuserquests);
	BNet::Utils::preprint ($count, '27900', "I've Got This Guy", %multiuserquests);
	BNet::Utils::preprint ($count, '27901', "They Don't Know What They've Got Here", %multiuserquests);
	BNet::Utils::preprint ($count, '27903', "Ignition", %multiuserquests);
	BNet::Utils::preprint ($count, '27905', "Tailgunner!", %multiuserquests);
	BNet::Utils::preprint ($count, '27922', "Traitors!", %multiuserquests);
	BNet::Utils::preprint ($count, '27923', "Smoke in Their Eyes", %multiuserquests);
	BNet::Utils::preprint ($count, '27924', "Budd's Plan", %multiuserquests);
	BNet::Utils::preprint ($count, '27926', "Eastern Hospitality", %multiuserquests);
	BNet::Utils::preprint ($count, '27928', "A Favor for the Furrier", %multiuserquests);
	BNet::Utils::preprint ($count, '27939', "The Desert Fox", %multiuserquests);
	BNet::Utils::preprint ($count, '27941', "Fashionism", %multiuserquests);
	BNet::Utils::preprint ($count, '27942', "Idolatry", %multiuserquests);
	BNet::Utils::preprint ($count, '27943', "Angered Spirits", %multiuserquests);
	BNet::Utils::preprint ($count, '27950', "Gobbles!", %multiuserquests);
	BNet::Utils::preprint ($count, '27969', "Make Yourself Useful", %multiuserquests);
	BNet::Utils::preprint ($count, '27990', "Battlezone", %multiuserquests);
	BNet::Utils::preprint ($count, '27993', "Take it to 'Em!", %multiuserquests);
	BNet::Utils::preprint ($count, '28002', "Crisis Management", %multiuserquests);
	BNet::Utils::preprint ($count, '28105', "Kavem the Callous", %multiuserquests);
	BNet::Utils::preprint ($count, '28112', "Escape From the Lost City", %multiuserquests);
	BNet::Utils::preprint ($count, '28132', "Efficient Excavations", %multiuserquests);
	BNet::Utils::preprint ($count, '28134', "Impending Retribution", %multiuserquests);
	BNet::Utils::preprint ($count, '28135', "Al'Akir's Vengeance", %multiuserquests);
	BNet::Utils::preprint ($count, '28141', "Relics of the Sun King", %multiuserquests);
	BNet::Utils::preprint ($count, '28145', "Venomblood Antidote", %multiuserquests);
	BNet::Utils::preprint ($count, '28187', "Missed Me By Zhat Much!", %multiuserquests);
	BNet::Utils::preprint ($count, '28193', "Lockdown!", %multiuserquests);
	BNet::Utils::preprint ($count, '28194', "The Great Escape", %multiuserquests);
	BNet::Utils::preprint ($count, '28195', "Sending a Message", %multiuserquests);
	BNet::Utils::preprint ($count, '28198', "The Weakest Link", %multiuserquests);
	BNet::Utils::preprint ($count, '28200', "The Element of Supplies", %multiuserquests);
	BNet::Utils::preprint ($count, '28201', "Ploughshares to Swords", %multiuserquests);
	BNet::Utils::preprint ($count, '28210', "Shaping Up", %multiuserquests);
	BNet::Utils::preprint ($count, '28267', "Firing Squad", %multiuserquests);
	BNet::Utils::preprint ($count, '28269', "Meet Me In Vir'sar", %multiuserquests);
	BNet::Utils::preprint ($count, '28271', "Reduced Productivity", %multiuserquests);
	BNet::Utils::preprint ($count, '28272', "Missing Pieces", %multiuserquests);
	BNet::Utils::preprint ($count, '28273', "Friend of a Friend", %multiuserquests);
	BNet::Utils::preprint ($count, '28274', "Two Tents", %multiuserquests);
	BNet::Utils::preprint ($count, '28276', "Salhet's Secret", %multiuserquests);
	BNet::Utils::preprint ($count, '28277', "Salhet the Tactician", %multiuserquests);
	BNet::Utils::preprint ($count, '28291', "Return to Camp", %multiuserquests);
	BNet::Utils::preprint ($count, '28350', "Master Trapper", %multiuserquests);
	BNet::Utils::preprint ($count, '28351', "Unlimited Potential", %multiuserquests);
	BNet::Utils::preprint ($count, '28352', "Camel Tow", %multiuserquests);
	BNet::Utils::preprint ($count, '28353', "Jonesy Sent For You", %multiuserquests);
	BNet::Utils::preprint ($count, '28363', "Stirred the Hornet's Nest", %multiuserquests);
	BNet::Utils::preprint ($count, '28367', "Shroud of the Makers", %multiuserquests);
	BNet::Utils::preprint ($count, '28376', "Myzerian's Head", %multiuserquests);
	BNet::Utils::preprint ($count, '28402', "Schnottz So Fast", %multiuserquests);
	BNet::Utils::preprint ($count, '28403', "Bad Datas", %multiuserquests);
	BNet::Utils::preprint ($count, '28404', "I'll Do It By Hand", %multiuserquests);
	BNet::Utils::preprint ($count, '28482', "Sullah's Gift", %multiuserquests);
	BNet::Utils::preprint ($count, '28497', "Fire From the Sky", %multiuserquests);
	BNet::Utils::preprint ($count, '28602', "Be Prepared", %multiuserquests);
	BNet::Utils::preprint ($count, '28621', "Put That Baby in the Cradle!", %multiuserquests);
	BNet::Utils::preprint ($count, '28622', "Three if by Air", %multiuserquests);
	BNet::Utils::preprint ($count, '28633', "The Coffer of Promise", %multiuserquests);
	BNet::Utils::preprint ($count, '27629', "The Vizier's Vote", %multiuserquests);
	BNet::Utils::preprint ($count, '28480', "Lieutenants of Darkness", %multiuserquests);
	BNet::Utils::preprint ($count, '28483', "Bleeding the Enemy", %multiuserquests);
	BNet::Utils::preprint ($count, '28486', "Salhet's Gambit", %multiuserquests);
	BNet::Utils::preprint ($count, '28498', "The Secret of Nahom", %multiuserquests);
	BNet::Utils::preprint ($count, '28499', "Punish the Trespassers", %multiuserquests);
	BNet::Utils::preprint ($count, '28500', "The Cypher of Keset", %multiuserquests);
	BNet::Utils::preprint ($count, '28501', "The Defense of Nahom", %multiuserquests);
	BNet::Utils::preprint ($count, '28502', "The Bandit Warlord", %multiuserquests);
	BNet::Utils::preprint ($count, '28520', "The Fall of Neferset City", %multiuserquests);
	BNet::Utils::preprint ($count, '28533', "The High Council's Decision", %multiuserquests);
	BNet::Utils::preprint ($count, '28561', "Nahom Must Hold", %multiuserquests);
	BNet::Utils::preprint ($count, '28611', "The Defilers' Ritual", %multiuserquests);
	BNet::Utils::preprint ($count, '28623', "The Push Westward", %multiuserquests);

}

sub z_84_90_Twilight_Highlands($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("84-90: Twilight Highlands: Intro <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '28909', "Sauranok Will Point the Way", %multiuserquests);
	BNet::Utils::preprint ($count, '26311', "Unfamiliar Waters", %multiuserquests);
	BNet::Utils::preprint ($count, '28717', "Warchief's Command: Twilight Highlands!", %multiuserquests);
	BNet::Utils::preprint ($count, '26293', "Machines of War", %multiuserquests);
	BNet::Utils::preprint ($count, '26294', "Weapons of Mass Dysfunction", %multiuserquests);
	BNet::Utils::preprint ($count, '26324', "Where Is My Warfleet?", %multiuserquests);
	BNet::Utils::preprint ($count, '26374', "Ready the Ground Troops", %multiuserquests);
	BNet::Utils::preprint ($count, '26335', "Ready the Navy", %multiuserquests);
	BNet::Utils::preprint ($count, '26337', "Beating the Market", %multiuserquests);
	BNet::Utils::preprint ($count, '26358', "Ready the Air Force", %multiuserquests);
	BNet::Utils::preprint ($count, '26361', "Smoot's Samophlange", %multiuserquests);
	BNet::Utils::preprint ($count, '26372', "Pre-Flight Checklist", %multiuserquests);
	BNet::Utils::preprint ($count, '28849', "Twilight Skies", %multiuserquests);
	BNet::Utils::preprint ($count, '26388', "Twilight Skies", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: The Dragonmaw Clan and the Horde <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '26539', "Stalled Negotiations", %multiuserquests);
	BNet::Utils::preprint ($count, '26539', "Stalled Negotiations", %multiuserquests);
	BNet::Utils::preprint ($count, '26549', "Madness", %multiuserquests);
	BNet::Utils::preprint ($count, '26608', "Negotiations Terminated", %multiuserquests);
	BNet::Utils::preprint ($count, '26538', "Emergency Aid", %multiuserquests);
	BNet::Utils::preprint ($count, '26540', "Dangerous Compassion", %multiuserquests);
	BNet::Utils::preprint ($count, '26619', "You Say You Want a Revolution", %multiuserquests);
	BNet::Utils::preprint ($count, '26621', "Insurrection", %multiuserquests);
	BNet::Utils::preprint ($count, '26622', "Death to Mor'ghor", %multiuserquests);
	BNet::Utils::preprint ($count, '26786', "Securing the Beach Head", %multiuserquests);
	BNet::Utils::preprint ($count, '26784', "Muddied Waters", %multiuserquests);
	BNet::Utils::preprint ($count, '26788', "Cementing Our Victory", %multiuserquests);
	BNet::Utils::preprint ($count, '26798', "Saurfang Will be Pleased", %multiuserquests);
	BNet::Utils::preprint ($count, '26830', "Traitor's Bait", %multiuserquests);
	BNet::Utils::preprint ($count, '26840', "Return to the Highlands", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: The Southern Flank <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '27607', "The Southern Flank", %multiuserquests);
	BNet::Utils::preprint ($count, '27610', "Scouting the Shore", %multiuserquests);
	BNet::Utils::preprint ($count, '27611', "Blood on the Sand", %multiuserquests);
	BNet::Utils::preprint ($count, '27622', "Mo' Better Shredder", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: Krazzworks <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '28583', "Krazzworks", %multiuserquests);
	BNet::Utils::preprint ($count, '28584', "Quality Construction", %multiuserquests);
	BNet::Utils::preprint ($count, '28586', "Pool Pony Rescue", %multiuserquests);
	BNet::Utils::preprint ($count, '28588', "Wildhammer Infestation", %multiuserquests);
	BNet::Utils::preprint ($count, '28589', "Everything But the Kitchen Sink", %multiuserquests);
	BNet::Utils::preprint ($count, '28590', "Reprisal", %multiuserquests);
	BNet::Utils::preprint ($count, '28591', "Off The Wall", %multiuserquests);
	BNet::Utils::preprint ($count, '28592', "Parting Packages", %multiuserquests);
	BNet::Utils::preprint ($count, '28593', "Of Utmost Importance", %multiuserquests);
	BNet::Utils::preprint ($count, '28594', "Highbank, Crybank", %multiuserquests);
	BNet::Utils::preprint ($count, '28595', "Krazz Works!", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: The Northern Flank <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '27583', "The Northern Flank", %multiuserquests);
	BNet::Utils::preprint ($count, '27584', "Blood in the Surf", %multiuserquests);
	BNet::Utils::preprint ($count, '27586', "Shells on the Sea Shore", %multiuserquests);
	BNet::Utils::preprint ($count, '27606', "Blast Him!", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: Bloodgulch <img src=\"https://wow.zamimg.com/images/icons/horde.png\">");
	BNet::Utils::preprint ($count, '27690', "Narkrall, the Drake-Tamer", %multiuserquests);
	BNet::Utils::preprint ($count, '27751', "Crushing the Wildhammer", %multiuserquests);
	BNet::Utils::preprint ($count, '27929', "Drag 'em Down", %multiuserquests);
	BNet::Utils::preprint ($count, '27747', "Total War", %multiuserquests);
	BNet::Utils::preprint ($count, '27750', "War Forage", %multiuserquests);
	BNet::Utils::preprint ($count, '27947', "A Vision of Twilight", %multiuserquests);
	BNet::Utils::preprint ($count, '27951', "We All Must Sacrifice", %multiuserquests);
	BNet::Utils::preprint ($count, '27954', "The Eyes Have It", %multiuserquests);
	BNet::Utils::preprint ($count, '27955', "Eye Spy", %multiuserquests);
	BNet::Utils::preprint ($count, '28041', "Bait and Throttle", %multiuserquests);
	BNet::Utils::preprint ($count, '28043', "How to Maim Your Dragon", %multiuserquests);
	BNet::Utils::preprint ($count, '28123', "The Demon Chain", %multiuserquests);
	BNet::Utils::preprint ($count, '28133', "Fury Unbound", %multiuserquests);
	BNet::Utils::preprint ($count, '28147', "Purple is Your Color", %multiuserquests);
	BNet::Utils::preprint ($count, '28151', "Dressed to Kill", %multiuserquests);
	BNet::Utils::preprint ($count, '28149', "Whispers in the Wind", %multiuserquests);
	BNet::Utils::preprint ($count, '28166', "Thog's Nightlight", %multiuserquests);
	BNet::Utils::preprint ($count, '28170', "Night Terrors", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: The Maw of Madness");
	BNet::Utils::preprint ($count, '27945', "Paint it Black <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27375', "The Weeping Wound <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27374', "The Maw of Madness <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27299', "Torn Ground", %multiuserquests);
	BNet::Utils::preprint ($count, '27300', "Pushing Back", %multiuserquests);
	BNet::Utils::preprint ($count, '27302', "Simple Solutions", %multiuserquests);
	BNet::Utils::preprint ($count, '27301', "Unbroken", %multiuserquests);
	BNet::Utils::preprint ($count, '27303', "Mercy for the Bound", %multiuserquests);
	BNet::Utils::preprint ($count, '27376', "The Maw of Iso'rath", %multiuserquests);
	BNet::Utils::preprint ($count, '27377', "Devoured", %multiuserquests);
	BNet::Utils::preprint ($count, '27378', "The Worldbreaker", %multiuserquests);
	BNet::Utils::preprint ($count, '27379', "The Terrors of Iso'rath", %multiuserquests);
	BNet::Utils::preprint ($count, '27380', "Nightmare", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: Vermillion Redoubt");
	BNet::Utils::preprint ($count, '27485', "Warm Welcome <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27486', "Warm Welcome <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27504', "Even Dragons Bleed", %multiuserquests);
	BNet::Utils::preprint ($count, '27505', "Draconic Mending", %multiuserquests);
	BNet::Utils::preprint ($count, '27506', "Life from Death", %multiuserquests);
	BNet::Utils::preprint ($count, '27564', "In Defense of the Redoubt", %multiuserquests);
	BNet::Utils::preprint ($count, '27507', "Encroaching Twilight", %multiuserquests);
	BNet::Utils::preprint ($count, '27508', "Far from the Nest", %multiuserquests);
	BNet::Utils::preprint ($count, '27509', "Breach in the Defenses", %multiuserquests);
	BNet::Utils::preprint ($count, '28101', "Mathias' Command <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27576', "Patchwork Command", %multiuserquests);
	BNet::Utils::preprint ($count, '28091', "Easy Pickings <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28103', "Easy Pickings <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28090', "Precious Goods <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28104', "Precious Goods <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28097', "The Gates of Grim Batol <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28108', "If The Key Fits <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28092', "If The Key Fits <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28107', "Paving the Way <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28094', "Paving the Way <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28109', "Pressing Forward <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28093', "Pressing Forward <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28712', "Enter the Dragon Queen", %multiuserquests);
	BNet::Utils::preprint ($count, '28758', "Battle of Life and Death", %multiuserquests);
	BNet::Utils::preprint ($count, '28171', "And the Sky Streaked Red", %multiuserquests);
	BNet::Utils::preprint ($count, '28191', "A Fitting End", %multiuserquests);
	BNet::Utils::preprint ($count, '28173', "Blackout", %multiuserquests);
	BNet::Utils::preprint ($count, '28175', "Shining Through the Dark", %multiuserquests);
	BNet::Utils::preprint ($count, '28176', "Following the Young Home", %multiuserquests);
	BNet::Utils::preprint ($count, '28247', "Last of Her Kind", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: Twilight Rising");
	BNet::Utils::preprint ($count, '28248', "Victors' Point <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28249', "Crushblow <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27492', "Ogres & Ettins <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27493', "Ogres & Ettins <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27496', "Call in the Artillery <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27497', "Call in the Artillery <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27490', "SI:7 Drop <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27491', "Kor'kron Drop <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27494', "Move the Mountain <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27495', "Move the Mountain <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27498', "Signal the Attack", %multiuserquests);
	BNet::Utils::preprint ($count, '27499', "Signal the Attack", %multiuserquests);
	BNet::Utils::preprint ($count, '27500', "Four Heads are Better than None <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27501', "Four Heads are Better than None <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27502', "Up to the Citadel <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27503', "Up to the Citadel <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27636', "Just You and Mathias <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27638', "Just You and Garona <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27652', "Dark Assassins <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27653', "Dark Assassins <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27654', "Bring the Hammer Down <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27655', "Bring the Hammer Down <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27688', "Distract Them for Me <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27689', "Distract Them for Me <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27695', "The Elementium Axe <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27696', "The Elementium Axe <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27700', "Dragon, Unchained <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27701', "Dragon, Unchained <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27702', "Coup de Grace <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27703', "Coup de Grace <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27657', "Help from the Earthcaller <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27658', "Help from the Earthcaller <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27660', "Spirit of the Loch", %multiuserquests);
	BNet::Utils::preprint ($count, '27659', "Portal Overload", %multiuserquests);
	BNet::Utils::preprint ($count, '27662', "Unbinding", %multiuserquests);
	BNet::Utils::preprint ($count, '27661', "Fire the Cannon", %multiuserquests);
	BNet::Utils::preprint ($count, '27719', "Water of Life <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27798', "Water of Life <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27711', "Back to the Elementium Depths <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27712', "Back to the Elementium Depths <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27720', "Mr. Goldmine's Wild Ride <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '28885', "Mr. Goldmine's Wild Ride <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27742', "A Little on the Side", %multiuserquests);
	BNet::Utils::preprint ($count, '27743', "While We're Here", %multiuserquests);
	BNet::Utils::preprint ($count, '27744', "Rune Ruination", %multiuserquests);
	BNet::Utils::preprint ($count, '27745', "A Fiery Reunion", %multiuserquests);
	BNet::Utils::preprint ($count, '27782', "Mathias Needs You", %multiuserquests);
	BNet::Utils::preprint ($count, '27783', "Garona Needs You", %multiuserquests);
	BNet::Utils::preprint ($count, '27784', "The Hammer of Twilight <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27786', "The Hammer of Twilight <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27787', "Skullcrusher the Mountain <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27788', "Skullcrusher the Mountain <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::groupheader ("84-90: Twilight Highlands: The Crucible of Carnage");
	BNet::Utils::preprint ($count, '28038', "Blood in the Highlands", %multiuserquests);
	BNet::Utils::preprint ($count, '27861', "The Crucible of Carnage: The Bloodeye Bruiser!", %multiuserquests);
	BNet::Utils::preprint ($count, '27862', "The Crucible of Carnage: The Bloodeye Bruiser!", %multiuserquests);
	BNet::Utils::preprint ($count, '27863', "The Crucible of Carnage: The Bloodeye Bruiser!", %multiuserquests);
	BNet::Utils::preprint ($count, '27864', "The Crucible of Carnage: The Deadly Dragonmaw! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27865', "The Crucible of Carnage: The Wayward Wildhammer! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '27866', "The Crucible of Carnage: Calder's Creation!", %multiuserquests);
	BNet::Utils::preprint ($count, '27867', "The Crucible of Carnage: The Earl of Evisceration!", %multiuserquests);
	BNet::Utils::preprint ($count, '27868', "The Crucible of Carnage: The Twilight Terror!", %multiuserquests);

}

sub z_85_Molten_Front($%) {
	my ($count, %multiuserquests) = @_;

	BNet::Utils::groupheader ("85: Molten Front: The Invasion");
	BNet::Utils::preprint ($count, '29391', "Guardians of Hyjal: Call of the Ancients <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '29390', "Guardians of Hyjal: Call of the Ancients <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '29387', "Guardians of Hyjal: Firelands Invasion! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/alliance.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '29388', "Guardians of Hyjal: Firelands Invasion! <img align=\"right\" src=\"https://wow.zamimg.com/images/icons/horde.png\">", %multiuserquests);
	BNet::Utils::preprint ($count, '29145', "Opening the Door", %multiuserquests);
	BNet::Utils::preprint ($count, '29195', "A Ritual of Flame", %multiuserquests);
	BNet::Utils::preprint ($count, '29196', "To the Sanctuary!", %multiuserquests);
	BNet::Utils::preprint ($count, '29197', "Caught Unawares", %multiuserquests);
	BNet::Utils::preprint ($count, '29198', "The Sanctuary Must Not Fall", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: The Sanctuary of Malorn");
	BNet::Utils::preprint ($count, '29199', "Calling for Reinforcements", %multiuserquests);
	BNet::Utils::preprint ($count, '29200', "Leyara", %multiuserquests);
	BNet::Utils::preprint ($count, '29201', "Through the Gates of Hell", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: Druids of the Talon");
	BNet::Utils::preprint ($count, '29181', "Druids of the Talon", %multiuserquests);
	BNet::Utils::preprint ($count, '29182', "Flight of the Storm Crows", %multiuserquests);
	BNet::Utils::preprint ($count, '29272', "Need... Water... Badly...", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: The Shadow Wardens");
	BNet::Utils::preprint ($count, '29214', "The Shadow Wardens", %multiuserquests);
	BNet::Utils::preprint ($count, '29215', "The Hunt Begins", %multiuserquests);
	BNet::Utils::preprint ($count, '29245', "The Mysterious Seed", %multiuserquests);
	BNet::Utils::preprint ($count, '29249', "Planting Season", %multiuserquests);
	BNet::Utils::preprint ($count, '29254', "Little Lasher", %multiuserquests);
	BNet::Utils::preprint ($count, '29204', "The Warden's Charge", %multiuserquests);
	BNet::Utils::preprint ($count, '29204', "The Forlorn Spire", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: Additional Armaments");
	BNet::Utils::preprint ($count, '29281', "Additional Armaments", %multiuserquests);
	BNet::Utils::preprint ($count, '29282', "Well Armed", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: Calling the Ancients");
	BNet::Utils::preprint ($count, '29283', "Calling the Ancients", %multiuserquests);
	BNet::Utils::preprint ($count, '29284', "Aid of the Ancients", %multiuserquests);
	BNet::Utils::groupheader ("85: Molten Front: Filling the Moonwell");
	BNet::Utils::preprint ($count, '29279', "Filling the Moonwell", %multiuserquests);
	BNet::Utils::preprint ($count, '29280', "Nourishing Waters", %multiuserquests);
	BNet::Utils::preprint ($count, '29203', "Into the Depths", %multiuserquests);
	BNet::Utils::preprint ($count, '29298', "A Smoke-Stained Locket", %multiuserquests);
	BNet::Utils::preprint ($count, '29302', "Unlocking the Secrets Within", %multiuserquests);
	BNet::Utils::preprint ($count, '29303', "Tragedy and Family", %multiuserquests);
	BNet::Utils::preprint ($count, '29310', "The Tipping Point", %multiuserquests);
	BNet::Utils::preprint ($count, '29311', "The Rest is History", %multiuserquests);
	BNet::Utils::preprint ($count, '29243', "Strike at the Heart", %multiuserquests);

}


1;

